### ISSUE TITLE
Hooking into the Publish target is counterintuitive

### ISSUE THREAD

**Issue by tuespetre** [dotnet/sdk#1039]
It seems natural to define a target to run before `Publish` with something like `<Target Name="MyTarget" BeforeTargets="Publish">`, but this does not work as expected because `BeforeTargets` always run after `DependsOnTargets` and the `Publish` target is using `DependsOnTargets` to 'run all its stuff', so by the time `MyTarget` is run, the publish has actually completed. 😕 

My thought is that the `Publish` target could be slightly rewritten like this:

```
<Target Name="Publish" DependsOnTargets="Build; PrepareForPublish">
    <CallTarget Targets="ComputeAndCopyFilesToPublishDirectory;
                         GeneratePublishDependencyFile;
                         GeneratePublishRuntimeConfigurationFile" />
</Target>
```

This would result in the following expectations all being met:

- The project is built before `MyTarget` is called
- The publish output folder is created before `MyTarget` is called
- `MyTarget` is called before any of the 'actual' publishing work is done

**Comment by tuespetre** [comment]
@rainersigwald any thoughts on this? Considering other discussions like https://github.com/dotnet/sdk/issues/841 I'm fine with leaving the 'magic' `BeforePublish` and `AfterPublish` target names in the past, but it just seems wrong to have to use `BeforeTargets="PrepareForPublish"` or `BeforeTargets="BeforePublish"` (before-before-publish? 😛) especially when we a simple `AfterTargets="Publish"` works 100% as expected.

**Comment by rainersigwald** [comment]
Unfortunately, the target naming conventions (`Target Name="X" DependsOnTargets="$(XDependsOn)"` which is `BeforeX;CoreX;AfterX` or similar) were defined before `BeforeTargets` and `AfterTargets` were, when you could only hook onto the end of a target. In that context, they make more sense.

Today, I'd probably try to form a different naming convention. But I think we're stuck with this one after years of its use. I can't see a) a better way and b) an easy glide path from here to there.

Your proposal is interesting but I prefer to avoid `CallTarget` whenever possible, because it makes understanding the target "dependency graph" and execution order really confusing.

I think the best thing to do is go with the convention that `BeforeX` is the first part of X so `BeforeTargets="BeforeX"` is the way to hook into it. I've certainly written my share of `BeforeTargets="BeforeBuild"` extensions . . .

**Comment by tuespetre** [comment]
@rainersigwald thanks! ✌️
