### ISSUE TITLE
error MSB4019 v14.0/DNX/Microsoft.DNX.Props (MacOS)

### ISSUE THREAD

**Issue by beckmx** [dotnet/sdk#1058]
Hello guys, I installed a fresh version of runtime dotnet core 1.1.1 and SDK 1.0.1, but this error pops up whenever I want to restore or run a project:

`/Users/andressantos/ng2boilerplate/src/dotnetstarter/dotnetstarter.xproj(7,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/1.0.1/Microsoft/VisualStudio/v14.0/DNX/Microsoft.DNX.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
`

Do you have any recommendations on how to make it run again on macos?

**Comment by jmoody** [comment]
I have the same problem.

**Comment by livarcocc** [comment]
This is happening because you have not migrated your projects from project.json/xproj to csproj. Which you can do by using the dotnet migrate from the command line or by opening a solution containing your projects in VS2017.

The new CLI (1.0.1) no longer supports project.json. Because we always roll forward on the CLI version, that version of the CLI is being picked up when you execute dotnet. If you don't want to migrate your project, you can create a global.json file in your repo root and use it to pin the version of the CLI to a version that supports project.json. More information on this here: https://github.com/dotnet/cli/blob/master/Documentation/ProjectJsonToCSProj.md
