### ISSUE TITLE
<Library>.runtimeconfig.json is not copied from nuget lib to output 

### ISSUE THREAD

**Issue by Lonli-Lokli** [dotnet/sdk#10693]
Background: I would like to use dotnet tool as library but I need runtimeconfig.json for this to run dotnet.

So I have several issues: 
1) Referenced assembly dotnet-swagger.dll is not copied to output on dotnet build without `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`
2) Even with <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> only dotnet-swagger.dll is copied, dotnet-swagger.runtimeconfig.json is not copied as assets from nuget to output folder.
3) It is not possible to filter out unnessesary libs from copying with previous solution
<Target Name="FilterCopyLocalItems" AfterTargets="ResolveLockFileCopyLocalProjectDeps">
  <ItemGroup>
    <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="'%(Filename)' == 'dotnet-swagger'" />
  </ItemGroup>
</Target>
[RuntimeConfigNugetIssue.zip](https://github.com/dotnet/sdk/files/4234748/RuntimeConfigNugetIssue.zip)

**Comment by brcaswell** [comment]
It's an interesting expectation to have; I'm not sure it's one you should have though.

Also, I'm not entirely sure how this issue relates to dotnet sdk; it seems like you're basically asking for those runtimeconfig.json files (presuming they exist) to be included as contentfiles\assets in those package references so your post build operation will work because the package would include the file in the output.  

But those sort of inquiries should potentially be to the package authors, right? (check the ProjectUrl associated to the NuGet Packages)

---
Apart from that, in regards to the runtimeconfig.json files themselves though, I think the idea there is supposed to be that you define them in your project (that they are not inherited by projects that consume the package) when\where warranted.  

Certainly you can just include the file in your project.

**dotnet-swagger.runtimeconfig.json**
``` json
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "frameworks": [
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "2.1.1"
      }
    ]
  }
}
```

and the AfterBuild task will create a "swagger.json" file.

**Comment by Lonli-Lokli** [comment]
@brcaswell thanks for the reply.
1) _Also, I'm not entirely sure how this issue relates to dotnet sdk_
From my point of view this file as part of dotnet tool should be available for fetch and it's the task for sdk part. Am I wrong?

2) I copied this file from nuget package, it has  "version": "2.0.0" and yes it works.

3) May I then ask why this target do not filter all assemblies except for the dotnet-swagger?

```
  <Target Name="FilterCopyLocalItems" AfterTargets="ResolveLockFileCopyLocalProjectDeps">
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" Condition="'%(Filename)' != 'dotnet-swagger'" />
    </ItemGroup>
  </Target>
```

**Comment by Lonli-Lokli** [comment]
Anyway thanks for explaining
