### ISSUE TITLE
exe no longer created on macOS

### ISSUE THREAD

**Issue by bentoi** [dotnet/sdk#10780]
On macOS Catalina, like on Linux, the dotnet build used to create a small exe file to run the console application, this exe is no longer created:
```
MacBookPro:~/Devel/GitHub/tmp$ dotnet new console
...
MacBookPro:~/Devel/GitHub/tmp$ dotnet run
Hello World!
MacBookPro:~/Devel/GitHub/tmp$ ls bin/Debug/netcoreapp3.1/
tmp.deps.json			tmp.runtimeconfig.dev.json
tmp.dll				tmp.runtimeconfig.json
tmp.pdb
```
No `tmp` executable in the `bin/Debug/netcoreapp3.1` directory above. When I run these same commands on Linux and Windows, the exe is created.

**Comment by am11** [comment]
This is by design for Catalina and above, due to macOS' new notarization requirements: https://docs.microsoft.com/en-us/dotnet/core/install/macos-notarization-issues#apphost-is-disabled-by-default

We can change the build command as below:

```diff
- dotnet build /path/to/project
+ dotnet build /p:UseAppHost /path/to/project
```

see it in action: https://cirrus-ci.com/task/5728984990220288 (with this [ci script](https://github.com/am11/sdk/commit/5ed4711cd85984eeea8812bb4c6c180f42f23ce7)).

note: we cannot pass MSBuild properties (`/p:..` argument) to dotnet-run command (yet; see #8520), so we need to either add the property in csproj:

```xml
<UseAppHost>true</UseAppHost>
```
or run `dotnet build /p:UseAppHost=true` followed by `dotnet run --no-build`, to avoid re-invoking build from dotnet-run without `UseAppHost` property.

**Comment by bentoi** [comment]
Thanks, I missed this information!
