### ISSUE TITLE
After conflict resolution, remove libraries from the deps file that no longer include any assets

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#1109]
When the conflict resolution removes an asset from the deps.json file, there can be a library entry in the file with no assets.  Especially when the .NET Standard 1.x package graph is brought into a .NET Core 2.0 project, this results in a lot of libraries in the deps file that don't have any useful data in them.  So when we're trimming out assets, we should also trim out the entire library entry if it doesn't have any assets.

See the discussion [here](https://github.com/dotnet/sdk/pull/1052#discussion_r110253842)

**Comment by nguerrera** [comment]
Load balancing this over to @wli3

**Comment by wli3** [comment]
We cannot trim these libraries solely on no assets. If there is an dependency that has an asset, it should be kept, for example, [MVC](https://github.com/aspnet/Mvc/blob/c8a1bb69142792d1046044bde7082b4e3ac8ac27/src/Microsoft.AspNetCore.Mvc.Core/Internal/DefaultAssemblyPartDiscoveryProvider.cs) , MVC will walk all the dependencies looking for assemblies that eventually depend on an MVC assembly. In order to do so, we need to add an extra step to walk the tree just to trim dep.json. It is complex and will make build performance worse.

Dep.json will be used in runtime. So it will be the trade of runtime and build time. However, so far there is no complain of dep.json being too long. Also, due to libraries have serval dependencies and any one of them may end up has an assert, I don't know if trim can actually help. Close it for now
