### ISSUE TITLE
SDK changes name of EmbeddedResource elements

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1120]
One of the projects I've converted to the new SDK has a number of [EmbeddedResource elements](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Test/Resources/Core/CompilerTestResources.csproj#L26). 

``` xml 
<EmbeddedResource Include="Analyzers\FaultyAnalyzer.dll" />
```

When compiled as a PCL the name of the resource in the assembly would be "Analyzers.FaultyAnalyzer.dll".  After converting to the new SDK the name instead is "CompilerTestResources.Analyzers.FaultyAnalyzer.dll".  

It seems the name is getting prepending with the string `$(MSBuildThisFileName)`.  That's breaking a number of our suites which can't find resources anymore.  

Is this a known issue?  If so is there a work around we can use?

**Comment by tannergooding** [comment]
I looked into this and it appears to be because the legacy targets had no concept of a "default RootNamespace".

The project in question does not have a `<RootNamespace>` declaration, so under the legacy targets, the final value is nothing.

However, under the SDK, a default RootNamespace is provided if none has been set, thus the final value is different and causes embedded resources to be evaluated differently.

@jaredpar could likely provide more details on how widespread this back-compat break impacted Roslyn (I believe he mentioned that it broke 100% of VB projects).

**Comment by jaredpar** [comment]
Thanks for looking into this.  It does seem likely that the change in behavior around `$(RootNamespace)` is the cause here.  I'm still trying to 100% verify this (having a machine issue ATM). 

If so I really have to question why the SDK changed the behavior here.  This has caused me tremendous pain in porting the Roslyn code base to the new SDK

1. Broke 100% of our VB projects.  It's very common for VB projects to have an empty root namespace.  The SDK interprets this as unset and assigns a default.  That broke compilation for all of our projects because it ended up changing the full namespace of many of the types. 
1. Broke about 70% of our test assemblies.  All resource lookup in our tests seem to be impacted by this bug and as a consequence the assembly fails.

Additionally this is a breaking change for which I can't find any documentation.  Hence I'm spending hours digging through MSBuild logs and debugging test failures trying to figure out what is going on here.

**Comment by tannergooding** [comment]
FYI. @srivatsn, @dotnet/project-system as well

**Comment by nguerrera** [comment]
The rationale for the default is like many others in the SDK: to reduce boilerplate by transforming what you get from the new project templates in to defaults supplied by props and targets.

Now if VB File -> New hasn't had a different RootNamespace convention, we should change the SDK default accordingly. (It would be truly breaking to change the default for C# now (because SDK project behavior would change without any user changes, whereas the "breaking" here occurs only after you opt in to using the SDK.)

This is what to add to a project file to get an empty root namespace:

``` XML
<PropertyGroup>
  <RootNamespace />
</PropertyGroup>
```

There is not (and, IMHO, should not be) a design goal that you can just import the SDK, make no other project changes and get exactly the same behavior. Achieving that would severely compromise the project file simplification goal. 

I do appreciate that this issue is more subtle than some of the others (e.g. duplicate items or assembly info) to detect and the fix isn't obvious. :( Still, I think there are better ways to address migration pain than to reverse course on the defaults:

1. Automated migration to SDK that ensures your settings are preserved.
2. Allow non-SDK projects to load in CPS and get its nice features without modifying the project file *at all*.

I'm told that (2) is planned. 

@srivatsn has a tool that compares msbuild evaluations that could be used as the basis for (1) though I bet demand for that would be significantly lower if we had (2) already.

**Comment by jaredpar** [comment]
> There is not (and, IMHO, should not be) a design goal that you can just import the SDK, make no other project changes and get exactly the same behavior.

I agree. 

> Still, I think there are better ways to address migration pain than to reverse course on the defaults:

The SDK could also document the breaks in behavior.  Knowing this was a break is better than spending a few hours to discover it's a break.

**Comment by livarcocc** [comment]
From reading the thread, it seems like there is nothing that we can/should be doing here. Besides maybe adding some documentation.

Given that, I am going to go ahead and close this issue.

As for the documentation, maybe we should file an issue under microsoft/docs, if there isn't one already, to document these breaking changes as a whole and not just this one.
