### ISSUE TITLE
Could not load file or assembly  'system.runtime, version =4.2.2.0'

### ISSUE THREAD

**Issue by Aowek** [dotnet/sdk#11263]
I just created a new project following a course on c# fundamentals. I did the following 
dotnet new console 
dotnet build
whenever i try to run it from visual studio i get this error. Anyone had a simillar issue i lost 5 days trying to solve this on my own.

![image](https://user-images.githubusercontent.com/33379609/79077954-48ecac00-7d05-11ea-8aef-469c2a46a677.png) 
this is my folder structure inside visual studio.

**Comment by sfoslund** [comment]
Based on the screenshot it looks like you opened the directory in Visual Studio instead of the project file. Try opening Visual Studio by clicking on the `GradeBook.csproj` file instead of a folder. For more information on project files, see [the docs](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019).
