### ISSUE TITLE
dotnet build standard error redirection data always remains empty (even if builds fail)

### ISSUE THREAD

**Issue by udeeshagautam** [dotnet/sdk#11273]
SDK version 3.1.200

I am trying to use "dotnet build" command through C# code initiating a Process.Start() with redirection of standard error and output. The output data comes correctly for successful and failed builds but redirected error data is always empty - even if the build failed. Is that expected?

```
            process.OutputDataReceived += (sender, e) =>
                {
                    if (e.Data != null)
                    {
                        Console.WriteLine(e.Data) //gets data in failed or passed builds
                    }
                };

              process.ErrorDataReceived += (sender, e) =>
                {
                    if (e.Data != null)
                    {
                        Console.WriteLine(e.Data) //doesn't get data even when build failed
                    }
                };
```

Also, would you suggest any preferred alternative way to call dotnet build's equivalent form code that doesn't need separate process (as in through API) - and will let the code handle error and success conditions better?

**Comment by wli3** [comment]
@rainersigwald do we have a better documentation for MSBuild C# API. The best I find is just [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.msbuild?view=netframework-4.8).

**Comment by rainersigwald** [comment]
It is intentional that MSBuild emits only to stdout and not stderr. This is a questionable design but unchangeable now.

@udeeshagautam, consider using the [MSBuild API](https://docs.microsoft.com/visualstudio/msbuild/msbuild-api?view=vs-2019) rather than shelling out to `dotnet build`. Your application should use [MSBuildLocator](https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2019) to ensure that it's loading the correct version of the toolchain.

As @wli3 hinted, the docs on the API are stale, but they should get you going pretty well. Feel free to ask questions at https://github.com/microsoft/msbuild/ if something needs clarification.
