### ISSUE TITLE
dotnetfeed.blob.core.windows.net very slow (300KB/s in Amsterdam, NL)

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/sdk#11283]
There are some big packages on this feed like the compilers for CoreRT (60+ MB) which together with 300KB/s download speeds create the illusion dotnet restore isn't functioning at all, dotnet restore doesn't have any progress indication in any case.

Increasing dotnetfeed.blob.core.windows.net perf would be helpful but generally having a progress bar for 1MB+ package downloads would also help.

**Comment by Chrisboh** [comment]
@dotnet/dnceng could you take a look and see if there is something going on with these feeds?

**Comment by mmitche** [comment]
This is just a storage account, so we don't have really any control over the perf. I tried a random file download and got about 250MBps.

**Comment by dagood** [comment]
Over at https://github.com/NuGet/Home/issues/4346 there's some feedback about adding feedback to long dotnet restores. I agree this would be nice.

Can't we choose to add geolocal mirroring to the storage account for faster non-US (non-Redmond) perf?

**Comment by NinoFloris** [comment]
>Over at NuGet/Home#4346 there's some feedback about adding feedback to long dotnet restores. I agree this would be nice.

Oh that's only open since 2017 ;)

If possible, global cdn would definitely help :) AMS-IX is a big hub so I really shouldn't get speeds like this, but people in over-leveraged internet areas like India and Australia probably have more use for a progress bar in general.

**Comment by mmitche** [comment]
> Can't we choose to add geolocal mirroring to the storage account for faster non-US (non-Redmond) perf?

We could do that, would be fine. 

FYI the dotnet-core feed has been removed from the .NET 5 master builds, and so usage of this for forward looking work should go down.

**Comment by mmitche** [comment]
a CDN isn't really possible without rewriting the entire feed (which is infeasible at this point due to the size of the feed). The reason is that this package feed is not a 'real' package feed. It's a blob storage setup which acts a bit like a real feed. So what happens is that nuget will use the various json files in the feed to find packages. These json files have internal references to other locations within the feed.

So while you could add a CDN and alter your initial reference to the feed to point to the CDN, all of the internal references will would still point to the non-CDN locations. Rewriting these feeds is prohibitive. The feed is gigantic, and write operations are exclusive.

This is one reason we're not using these kinds of feeds going forward. They are more reliable than some other nuget services we had in the past, but suffer serious drawbacks in many areas:
- Exclusive write operations
- Poor browseability
- Very poor push performance

This is why the master branches of 5.0 have switched away from these feeds in the last few weeks, in preparation for all new 5.0 builds to no longer publish to them.

**Comment by NinoFloris** [comment]
I see, so no way to transparently upgrade the blob storage, not even to replicate across regions?

Very understandable you're moving away from them in that case and for the reasons stated :)

**Comment by mmitche** [comment]
I think we can replicate it...let me go poke at some settings.

**Comment by wli3** [comment]
Issue moved to [dotnet/arcade #5294](https://github.com/dotnet/arcade/issues/5294) via [**ZenHub**](https://www.zenhub.com/)
