### ISSUE TITLE
Duplicated References with implicit references from NETStandard.Libraray[.NETFramework]

### ISSUE THREAD

**Issue by weshaggard** [dotnet/sdk#1129]
MusicStore application is hitting an issue where we end up with 2 System.Net.Http reference (see https://github.com/aspnet/MusicStore/pull/775).

This is an issue because of the way we are adding References in our NETStandard.Library[.NETFramework] targets (See https://github.com/dotnet/corefx/blob/master/pkg/NETStandard.Library.NETFramework/targets/NETStandard.Library.NETFramework.targets#L3) and how the SDK removes simple name references that come from nuget packages which is https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.PackageDependencyResolution.targets#L375. 

The reason NETStandard.Library packages is adding references in a targets file is to enable playing nicely with packages.config projects.

We need to come up with a solution eliminate the simple name duplication to avoid these conflicts.

cc @dsplaisted @ericstj

**Comment by ericstj** [comment]
We just need to decide the best way to hook into the SDK's ResolveLockFileReferences target.

This package will install downlevel in packages.config based projects so it must use Reference and ReferencePath items.

Ideally the SDK would consider these as well, perhaps conditionally based on metadata on the item.

Otherwise we'll need to fork our targets for PackageReference vs packages.config/project.json.

/cc @natidea who made the change: https://github.com/dotnet/sdk/commit/03f6a2a6e379eb9d699644bd529e6903b8576833

**Comment by nguerrera** [comment]
Is this still an issue with the targets that are integrated in to this repo and not in the NetStandard.Library package?

**Comment by weshaggard** [comment]
I suspect https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L70 fixes this issue, but we would need to try it. 

@kichalla is asp.net still interested in trying to make the MusicStore application target net461?

**Comment by livarcocc** [comment]
Closing.
