### ISSUE TITLE
dotnet-install fails to xcopy run-time & SDK

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/sdk#11320]
**impact**
- blocking the development rhythm of dotnet/runtime repository ~15% builds fail (Jared's team)
- ~100 failed builds / week 

need:
1. What are the distinct download requests failing?  (distinct = unique set of request parameters)
1. What are the specific errors per distinct failing requests?
1. Are the relevant distinct requests absolutely failing (100% cases)?
1. What is the load on the web server(s) during failures?  (would it help if we added more web servers behind the URL?)
1. Can we reproduce each distinct failing request locally?
1. What are the distinct failures & their proportions?

**Comment by grinrag** [comment]
I have tried to reproduce the bug locally and also in the Docker, using the image provided by `dotnet/runtime` team. No luck so far.

Our `dotnet-install` script using curl/wget under the hood. I see that in the image, curl is linked with OpenSSL instead of GNU TLS (https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/ubuntu/16.04/crossdeps/Dockerfile).

Initially, we believed that the problem in the GNU TLS itself, but the problem remain after update to OpenSSL (https://github.com/dotnet/runtime/issues/34015#issuecomment-614298651)


Also, I see many other network-related problems during official runtime builds, e.g.:

- [failed to download nupkg ](https://dev.azure.com/dnceng/public/_build/results?buildId=603910&view=logs&j=859e6d19-a509-50b0-9995-9c345fa3eb18&t=faa98da6-63b4-55bd-3c7c-db50ced2583a)  The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.debug/4.3.0/system.diagnostics.debug.4.3.0.nupkg' has timed out after 100000ms.
This fails for `tvOS x64`

- [failed to download nupkg](https://dev.azure.com/dnceng/public/_build/results?buildId=603910&view=logs&j=859e6d19-a509-50b0-9995-9c345fa3eb18&t=faa98da6-63b4-55bd-3c7c-db50ced2583a), as a result of executing `msbuild.sh` on `OSX,   x64`

- [failed send to Helix](https://dev.azure.com/dnceng/public/_build/results?buildId=604116&view=logs&j=b4344b0d-0f92-5d69-ccaf-e0b24fbf14a2&t=555ea487-e6f6-5e9e-ac96-b1fa34f2540d), also could be related, not sure

- [Failed to retrieve information from remote source](https://dev.azure.com/dnceng/public/_build/results?buildId=603962&view=logs&j=e172a4e5-28c0-5ec6-8195-6e0c452a9b1b&t=f7a36d28-92f8-5b43-2625-9232d8473e45), MSBuild execution failed on `OSX x64`

**Comment by donJoseLuis** [comment]
We sent notification to Jared's team about closing this issue due to a drop in communications on the topic.  If there remains anything actionable for us, we'll jump in and fix it :)
