### ISSUE TITLE
Fedora 32: No SDKs were found

### ISSUE THREAD

**Issue by wes-novack** [dotnet/sdk#11533]
Hello! I followed the instructions here: https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-fedora32

For installing dotnet core SDK and runtime using the Fedora package manager, using the commands:
```
sudo dnf install dotnet-sdk-3.1
sudo dnf install aspnetcore-runtime-3.1
sudo dnf install dotnet-runtime-3.1
```

Note that the 2nd and 3rd command above did nothing, because the first command for the sdk installed everything.

After successfully installing, I can see that I have all the packages:
```
$ sudo dnf list installed 'dotnet*'
Installed Packages
dotnet-apphost-pack-3.1.x86_64                              3.1.3-1.fc32                             @updates                    
dotnet-host.x86_64                                          3.1.3-1.fc32                             @updates                    
dotnet-hostfxr-3.1.x86_64                                   3.1.3-1.fc32                             @updates                    
dotnet-runtime-3.1.x86_64                                   3.1.3-1.fc32                             @updates                    
dotnet-sdk-3.1.x86_64                                       3.1.201-1                                @packages-microsoft-com-prod
dotnet-targeting-pack-3.1.x86_64                            3.1.3-1.fc32                             @updates                    
```

The problem is, however, that no SDK's are detected
```
$ dotnet --info
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

System info
```
$ cat /etc/*release
Fedora release 32 (Thirty Two)
NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 32 (Thirty Two)
Fedora release 32 (Thirty Two)
```
If I check my path for my non-root user, the only dotnet related entry is `/home/wes/.dotnet/tools`.

I've tried uninstalling and reinstalling this half a dozen times and I can't get it to recognize the SDK. What can I do to get this working?

**Comment by wes-novack** [comment]
I resolved this issue by running: `sudo dnf install dotnet-sdk-3.1` 

And then following most of the instructions here:  https://stackoverflow.com/a/59201350

I did not use the wget or rpm commands, as they aren't necessary in Fedora 32 because dotnet appears to be included in the OS repos now.

The commentary on that post suggests that the `sudo dnf clean all` might have been the thing that solves the problem.

**Comment by giuliohome** [comment]
I've tried to follow the above solution and this is my issue:

https://ask.fedoraproject.org/t/package-libreoffice-core-1-6-4-6-2-2-fc32-x86-64-does-not-verify-payload-sha256-digest-bad/9158

I think this should be re-opened and solved in a safer and better way.

**Comment by tor-jorgen** [comment]
I ended up downloading the x64 binary distribution from here: https://dotnet.microsoft.com/download/dotnet-core/3.1, unpacking it to `/opt`, and adding the `/opt/dotnet-sdk-xxx` folder to the path. Using `dnf` did not work for me.

**Comment by gavincampbell** [comment]
So this happened to me after I enabled the microsoft-prod repo in order to install the mssql-tools package.
Solution in my case was:

 * `dnf remove` the existing `dotnet-sdk-3.1` package, 
* Set the repo priorities in `yum.repos.d` so that `fedora` was higher priority than `microsoft-prod-repo` *
* `dnf install` the `dotnet-sdk-3.1` package

I suspect the reason the microsoft repo is normally preferred to the fedora one is that the version of the package will be newer.

\*  https://dnf.readthedocs.io/en/latest/conf_ref.html

**Comment by RheaAyase** [comment]
@gavincampbell good idea with the priorities as well. The packages in it get installed because Microsoft provides feature versions that are not "source-built" and have a higher.

I'll re-iterate the solution with bold text if someone else looks this up again.

# Correct Solution

We package dotnet directly in Fedora proper, if you add an extra Microsoft repo providing them as well, you will have conflicts.

* Remove all Microsoft provided packages
* Remove Microsoft provided repositories (or set `fedora` repositories to a higher priority than the Microsoft one if you need it for other packages.)
* `dnf install dotnet-sdk-x.y` (where `x.y` is the desired version - 3.1 or higher.)

**Comment by jebediah47** [comment]
> I resolved this issue by running: `sudo dnf remove dotnet-sdk-3.1`
> 
> And then following most of the instructions here: https://stackoverflow.com/a/59201350
> 
> ```
> sudo rm -rf /usr/share/dotnet
> sudo rm -rf /usr/bin/dotnet
> sudo rm -rf /etc/yum.repos.d/microsoft-prod.repo
> sudo dnf clean all
> sudo dnf upgrade
> sudo init 6 #reboots the machine
> ```
> 
> Then `sudo dnf install dotnet-sdk-3.1`
> 
> I did not use the wget or rpm commands suggested in the stackoverflow post, as they aren't necessary in Fedora 32 because dotnet appears to be included in the OS repos now.
> 
> The commentary on that post suggests that the `sudo dnf clean all` might have been the thing that solves the problem.

THANK YOU MAN YOU HELPED ME A LOOOOOT! THANKS!

**Comment by mehs2690** [comment]
Hi everyone!

In my case, I resolved this issue with the following steps:

1. `sudo rm -rf /etc/yum.repos.d/microsoft-prod.repo`
2. `sudo dnf clean all`
3. `sudo dnf remove dotnet*` ==> this is important
4. `sudo dnf install dotnet-sdk-3.1`

I am using Fedora 34
I hope that this solution is support to you

**Comment by bill-redcloudsolutions** [comment]
The issue is likely due to the differences in the Fedora repos vs. the Microsoft repos.  Microsoft's repo installs the runtime into /usr/share/dotnet, which is where the CLI will look if it comes from a Microsoft-installed package.  Fedora installs dotnet-* to /usr/lib64/dotnet and looks for the installed SDKs and runtimes there instead.

Try this to fix your issue (worked for me with Fedora 34):
1. Remove anything your have installed for .NET:  `$ sudo dnf remove dotnet-*`
2. Re-install by disabling the Fedora repos and enabling Microsoft's:  `$ sudo dnf install --enablerepo=packages-microsoft-com-prod --disablerepo=updates --disablerepo=fedora dotnet-sdk-5.0`

After I did this, the SDK was found:
`$ dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     fedora
 OS Version:  33
 OS Platform: Linux
 RID:         fedora.33-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.302/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  5.0.302 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by YunusOzdemirr** [comment]
> I resolved this issue by running: `sudo dnf remove dotnet-sdk-3.1`
> 
> And then following most of the instructions here: https://stackoverflow.com/a/59201350
> 
> ```
> sudo rm -rf /usr/share/dotnet
> sudo rm -rf /usr/bin/dotnet
> sudo rm -rf /etc/yum.repos.d/microsoft-prod.repo
> sudo dnf clean all
> sudo dnf upgrade
> sudo init 6 #reboots the machine
> ```
> 
> Then `sudo dnf install dotnet-sdk-3.1`
> 
> I did not use the wget or rpm commands suggested in the stackoverflow post, as they aren't necessary in Fedora 32 because dotnet appears to be included in the OS repos now.
> 
> The commentary on that post suggests that the `sudo dnf clean all` might have been the thing that solves the problem.

Thanks this is solved my problem

**Comment by salsitu** [comment]
> The issue is likely due to the differences in the Fedora repos vs. the Microsoft repos. Microsoft's repo installs the runtime into /usr/share/dotnet, which is where the CLI will look if it comes from a Microsoft-installed package. Fedora installs dotnet-* to /usr/lib64/dotnet and looks for the installed SDKs and runtimes there instead.
> 
> Try this to fix your issue (worked for me with Fedora 34):
> 
>     1. Remove anything your have installed for .NET:  `$ sudo dnf remove dotnet-*`
> 
>     2. Re-install by disabling the Fedora repos and enabling Microsoft's:  `$ sudo dnf install --enablerepo=packages-microsoft-com-prod --disablerepo=updates --disablerepo=fedora dotnet-sdk-5.0`
> 
> 
> After I did this, the SDK was found:
> `$ dotnet --info`
> .NET SDK (reflecting any global.json):
> Version: 5.0.302
> Commit: c005824e35
> 
> Runtime Environment:
> OS Name: fedora
> OS Version: 33
> OS Platform: Linux
> RID: fedora.33-x64
> Base Path: /usr/share/dotnet/sdk/5.0.302/
> 
> Host (useful for support):
> Version: 5.0.8
> Commit: 35964c9215
> 
> .NET SDKs installed:
> 5.0.302 [/usr/share/dotnet/sdk]
> 
> .NET runtimes installed:
> Microsoft.AspNetCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET runtimes or SDKs:
> https://aka.ms/dotnet-download

This worked perfectly for me! Btw, if you want `dnf` to permanently prioritize updates from Microsoft repos, then make the priority of the Fedora repo lower than the Microsoft repo.

**Comment by RheaAyase** [comment]
That's the exactly opposite of what one should be doing :D

**Comment by kepchu** [comment]
> I resolved this issue by running: `sudo dnf remove dotnet-sdk-3.1`
> 
> And then following most of the instructions here: https://stackoverflow.com/a/59201350
> 
> ```
> sudo rm -rf /usr/share/dotnet
> sudo rm -rf /usr/bin/dotnet
> sudo rm -rf /etc/yum.repos.d/microsoft-prod.repo
> sudo dnf clean all
> sudo dnf upgrade
> sudo init 6 #reboots the machine
> ```
> 
> Then `sudo dnf install dotnet-sdk-3.1`
> 
> I did not use the wget or rpm commands suggested in the stackoverflow post, as they aren't necessary in Fedora 32 because dotnet appears to be included in the OS repos now.
> 
> The commentary on that post suggests that the `sudo dnf clean all` might have been the thing that solves the problem.

This worked for me for dotnet7.0

**Comment by miermontoto** [comment]
> * Remove anything your have installed for .NET:  `$ sudo dnf remove dotnet-*`
> 
> * Re-install by disabling the Fedora repos and enabling Microsoft's:  `$ sudo dnf install --enablerepo=packages-microsoft-com-prod --disablerepo=updates --disablerepo=fedora dotnet-sdk-5.0`

This worked for me on Fedora 38 and .NET 7.0

**Comment by iloveyouexe** [comment]
> I resolved this issue by running: `sudo dnf remove dotnet-sdk-3.1`
> 
> And then following most of the instructions here: https://stackoverflow.com/a/59201350
> 
> ```
> sudo rm -rf /usr/share/dotnet
> sudo rm -rf /usr/bin/dotnet
> sudo rm -rf /etc/yum.repos.d/microsoft-prod.repo
> sudo dnf clean all
> sudo dnf upgrade
> sudo init 6 #reboots the machine
> ```
> 
> Then `sudo dnf install dotnet-sdk-3.1`
> 
> I did not use the wget or rpm commands suggested in the stackoverflow post, as they aren't necessary in Fedora 32 because dotnet appears to be included in the OS repos now.
> 
> The commentary on that post suggests that the `sudo dnf clean all` might have been the thing that solves the problem.

Worked for me on Linux Nobara 3.9

**Comment by wchesley** [comment]
Same issue here with Fedora 40, though I think this is related to the Microsoft repository listed in `/etc/yum.repos.d` once it was removed dotnet 8.0 sdk installed without a problem.
