### ISSUE TITLE
Provide a way to turn off Diagnostic Tracing in projects

### ISSUE THREAD

**Issue by vatsan-madhavan** [dotnet/sdk#11530]
Today, tracing support is always enabled by default, unless it is overridden externally (to the project), for e.g., at the msbuild command-line. There seems to be no way - at least no easy way - to control this in a project. 

https://github.com/dotnet/sdk/blob/bc5c514a45a1a900b71d39a3541196bc2cf1bb0d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props#L21-L24

This could be made opt-in by supplying a property - for e.g., `EnableDiagnosticTracing` - that's `true` by default for compatibility purposes. 

```xml
  <PropertyGroup>
    <DefineConstants Condition=" '$(DefineConstants)' != '' ">$(DefineConstants);</DefineConstants>
    <DefineConstants Condition="'$(EnableDiagnosticTracing)'!='false'">$(DefineConstants)TRACE</DefineConstants>
  </PropertyGroup>
```

**Comment by shueybubbles** [comment]
Please consider taking this fix. We have to build SqlManagementObjects with tracing disabled for use in SqlClr. The only way I can do this today is to provide my own DefineConstant value that removes all calls to Trace. I can't really provide a DefineConstants value on the command line of our build.

**Comment by marcpopMSFT** [comment]
Moving this out of the props could be breaking if customers were overwriting that value. Something simpler than the regex like the below could be added to a targets file (probably in the [CSHARP.targets](https://github.com/dotnet/sdk/blob/bc5c514a45a1a900b71d39a3541196bc2cf1bb0d/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.targets#L31) file) based on a condition. If you're interested in doing that work, we'd accept the PR.

`$(DefineConstants.Replace('TRACE', ''))`

**Comment by vatsan-madhavan** [comment]
> What would be bad about gating the definition on a constant as @vatsan-madhavan  proposed? Is it that someone would have to set the property before importing the SDK? That seems like a small penalty to pay.
> 

My proposal is non-breaking, and I still think that's the better overall approach. All it does is makes opting-out if `TRACE` a simple `Property`, but otherwise leaves everything the way it is today.

**Comment by vatsan-madhavan** [comment]
On second thoughts, I think @marcpopMSFT's suggestion is worth thinking though carefully - I think updating CSharp.targets is likely the most viable path forward. 

A typical SDK style project would implicitly import CSharp.props very early.:

```xml
<Project Sdk"Microsoft.Net.Sdk"> <!-- CSharp.props imported ~here -->
  <PropertyGroup>
    <EnableDiagnosticTracing>false</EnableDiagnosticTracing> <!-- Doesnt' have any impact -->
  </PropertyGroup>
</Project> <!-- CSharp.targets imported ~here -->
```

I agree that moving the `DefineConstants` for `TRACE` from CSharp.props to CSharp.targets would be a breaking change (even if such a modification would work for this situation well). 

That likely leaves us with the CSharp.targets `string::Replace` approach. I agree that `string::Replace` can be imprecise, but we can be careful, so perhaps something like this could work:

```xml
<!-- CSharpt.targets -->
<PropertyGroup Condition="'$(EnableDiagnosticTracing)' == 'true'">
   <!-- 'TRACE;' with semicolon-suffix is the easy case -->
  <DefineConstants Condition="'$(DefineConstants.Contains('TRACE;'))">$(DefineConstants.Replace('TRACE;', ''))</DefineConstants>
  
  <!-- 'TRACE' - no semicolon suffix. This means the string has to end with 'TRACE' -->
  <DefineConstants Condition="$(DefineConstants.TrimEnd('TRACE'))"></DefineConstants>
</PropertyGroup>
```

**Comment by vatsan-madhavan** [comment]
I've proposed a fix at #22883

**Comment by KalleOlaviNiemitalo** [comment]
Visual Basic uses the DefineTrace property:

<https://github.com/dotnet/sdk/blob/c53c8ac81e1bcb8118c31bc4f5622396c72e9959/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.VisualBasic.props#L26-L32>

<https://github.com/dotnet/msbuild/blob/4adc47707f27d0dce03cee9e4651d599e7ff265f/src/Tasks/Microsoft.VisualBasic.CurrentVersion.targets#L141>

If DefineTrace in Visual Basic controls whether TRACE is added, and EnableDiagnosticTracing in C# controls whether TRACE is removed after having been added, it's good that the properties have different names. Still, it is unfortunate if VB's simpler mechanism cannot be used for C# because of compatibility.

**Comment by vatsan-madhavan** [comment]
I think the better approach here is to use `DefineTrace` instead of a new property (`DisableDiagnosticTracing`). There will be minor differences in semantics, but that may be fine. The idea would be to:

- Initialize `DefineTracing` in CSharp.props; `TRACE` addition into `DefineConstants` would not be changed here.
```xml
  <PropertyGroup>
    <!-- Identical to VisualBasic.props -->
    <DefineTrace Condition=" '$(DefineTrace)' == '' ">true</DefineTrace> 
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants Condition=" '$(DefineConstants)' != '' ">$(DefineConstants);</DefineConstants>

    <!-- Backwards compatible, no change here -->
    <DefineConstants>$(DefineConstants)TRACE</DefineConstants>
  </PropertyGroup>
```
- Then update `DefiniteConstants` in a target in *BeforeCommon.props*, like this:
```xml
  <!-- Remove TRACE when $(DefineTrace) != true -->
  <Target Name="_DisableDiagnosticTracing"
          Condition="'$(DefineTrace)' != 'true'"
          DependsOnTargets="GenerateTargetPlatformDefineConstants;GenerateNETCompatibleDefineConstants;GeneratePlatformCompatibleDefineConstants"
          BeforeTargets="CoreCompile">
    <ItemGroup>
      <_DefineConstantsWithoutTrace Include="$(DefineConstants)" />
      <_DefineConstantsWithoutTrace Remove="TRACE"/>
    </ItemGroup>

    <PropertyGroup>
      <DefineConstants>@(_DefineConstantsWithoutTrace)</DefineConstants>
    </PropertyGroup>
  </Target>
```
This is what I see as differences, which are IMHO minor. 

| Vb                                                                                    | C#                                                                                                                                                         |
|---------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `DefineTrace` defaults to `true`                                                      | `DefineTrace` defaults to `true` in CSharp.props                                                                                                           |
| When `DefineTrace` is not `true` (includes empty string), `TRACE` will not be defined | `TRACE` will be initially defined in *CSharp.props*, but will be undefined in a *Target* defined in *BeforeCommon.props* when `$(DefineTrace)` is not true |
| Typical usage is to do this in vbproj, or in custom props or targets:<br><br>&lt;PropertyGroup&gt;<br>&nbsp;&nbsp;&lt;DefineTrace&gt;false&lt;/DefineTrace&gt;<br> &lt;PropertyGroup&gt; | Typical usage is to do this in csproj, or in custom props or targets:<br><br>&lt;PropertyGroup&gt;<br>&nbsp;&nbsp;&lt;DefineTrace&gt;false&lt;/DefineTrace&gt;<br> &lt;PropertyGroup&gt; |

**Comment by eliasHeyndrickx** [comment]
After looking through lots of documentation, reading many MS webpages and browsing tons of stack overflow posts and reading the source code of .net itself I find myself here without a solution to this problem.

The issue is simple, I have an old .net framework project I am trying to port to .net6. But I can't because of this TRACE issue. Before I had 2 checkboxes which allowed me to enable and disable DEBUG and TRACE. I debug without Trace and Debug constants for my libraries when testing because it's not needed and makes it harder to know what to do when these libraries print extra things. I also DO NOT WANT THIS FOR RELEASES. Why would I ever want this? It makes no sense.

Every other .net project STILL HAS THIS. Visual Basic, ASP, F#. WHY WAS THIS REMOVED? And how ON EARTH do I override this annoying behavior WITHOUT having to resort to console commands for building or some random XML Toggle that I cannot see OR CHANGE from the GUI in Project Props. This is a straight up regression in functionality for seemingly no given reason.

Is there ANY WAY AT ALL to disable all there predefined constants and to manually define them in the props file myself. I'll add them all back in without TRACE and DEBUG. I honestly don't know how to fix this and I can find 0 documentation on this issue except for this GitHub Issue. What do I do? I don't want these constants declared for me.

Any help or solutions where I can do this in the GUI are greatly appreciated. Ideally something to get rid of all or of not most. But mostly TRACE and DEBUG.

**Comment by eliasHeyndrickx** [comment]
Thanks for clarifying, I'll open an issue over there and hope it gets resolved. This is really annoying since TRACE seems to be hardcoded (same with DEBUG) and no option is provided to get get rid of it.

**Comment by drewnoakes** [comment]
I'm looking at https://developercommunity.visualstudio.com/t/Provide-a-way-to-turn-off-TRACE-and-DEBU/10467893 and considering whether we can add UI support to disable trace, as described here.

The linked PR suggests that setting property `DisableDiagnosticTracing` to `true` should do the trick, but that's not my experience:

![image](https://github.com/dotnet/sdk/assets/350947/9c447775-fbbe-451e-a312-4daa744a8431)

Does this property have to be set earlier than the user's project file? If so, we can't add tooling support for it in the UI, and I'm wondering how people are expected to use this feature.

**Comment by drewnoakes** [comment]
I spoke too soon. It does work. The property UI is just showing the value from _before_ the target runs that takes `DisableDiagnosticTracing` into account.

![image](https://github.com/dotnet/sdk/assets/350947/345cf934-5569-4fdc-ab6e-da56b776c2b5)

So that's a problem on our side.
