### ISSUE TITLE
Few checks for Framework projects should look at TargetExt for outputtype instead of looking at OutputType directly

### ISSUE THREAD

**Issue by basoundr** [dotnet/sdk#1174]
The logic to set AutoGenerateBindingRedirects happens [here](https://github.com/dotnet/sdk/blob/af6530cb7b4fffb143a2b5d188606d521b17b775/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.BeforeCommon.targets#L46)

If the output type of project is set to 'Windows Application' instead of 'Console Application', we should still set AutoGenerateBindingRedirects to true.

So the condition could check for OutputType to be either 'Exe' or 'WinExe' or just check for TargetExt to be '.exe' which uses the information from OutputType to get its value.

**Comment by nguerrera** [comment]
I see now that you filed an issue here for the issues other than F5. I'd rather we come up with the right coding pattern and fix them all together. Using $(TargetExt) is problematic because in the netcoreapp case you have OutputType=Exe and TargetExt=.dll. So we can't just switch all OutputType==Exe. I think we need a distinct variable to trigger these behavior, initialize it based on Exe or WinExe by default, and allow it to be overridden.

**Comment by nguerrera** [comment]
This is fixed by #1178
