### ISSUE TITLE
Missing dependencies tags for 2.1.18 builds

### ISSUE THREAD

**Issue by normj** [dotnet/sdk#11812]
I need to build the latest 2.1 patch for our AWS Lambda support at AWS. The cli, core-setup, coreclr, corefx repositories have the 2.1.18 and 2.1.806 tags but are missing the corresponding dependencies tags. For example I expected to find tags v2.1.18-dependencies in coreclr, corefx, core-setup and tag v2.1.806+dependencies in cli. Can those tags be pushed to unblock us getting the latest patch built and published?

**Comment by normj** [comment]
Any chance I can get an update on this? This is blocking us rolling out the update at AWS.

**Comment by normj** [comment]
The dependency tag hasn't been push for either 2.1.19 or 2.1.20. I have been trying to figure out how to manually update the `dependencies.props` file but I would really appreciate if the dependencies tag could be pushed.

**Comment by sfoslund** [comment]
Hi @normj, I think there's some confusion here on our versioning scheme. We have tags for the SDK versions in this repo, for example, for [2.1.808](https://github.com/dotnet/sdk/releases/tag/v2.1.808). However, 2.1.19 and 2.1.20 are runtime versions, which is a different versioning scheme than the one you see in this repo, that's why those tags don't exist here. You can get more information on the difference in versioning [here](https://docs.microsoft.com/en-us/dotnet/core/versions/).

**Comment by normj** [comment]
I see the "dependencies" tags are now pushed and I'm able to build the latest 2.1.20 patch. 

@sfoslund The versioning is confusing but I do understand the difference between the runtime version and sdk version. It was the missing 2.1.20+dependencies tag and 2.1.808+dependencies tag that were missing which version stamps the linkage to the different repositories.
