### ISSUE TITLE
GenerateRuntimeConfigurationFiles is for .Net Core Projects only

### ISSUE THREAD

**Issue by basoundr** [dotnet/sdk#1183]
[Refer here](https://github.com/dotnet/sdk/pull/1178#discussion_r115101389)

**Comment by eerhardt** [comment]
@livarcocc - is this something I can fix for 2.0?  It is "junk" in desktop project's output.  Desktop projects should never have runtimeconfig.json files, since they don't do anything.  The fix is a simple check for .NET Core and add a test.

I can do the work - I just don't want to do the work if it won't be approved for 2.0.

**Comment by srivatsn** [comment]
This is https://github.com/dotnet/sdk/issues/404

**Comment by eerhardt** [comment]
Closing as dupe of #404.
