### ISSUE TITLE
IsTrimmable metadata requirement is not flexible enough

### ISSUE THREAD

**Issue by marek-safar** [dotnet/sdk#11863]
We need to simplify how any of our SDKs can be enabled for true (aggressive) linking and ideally the same approach could be used for component vendors or any other NuGet packages. Nowadays this process is controlled using `IsTrimmable` metadata but there is no easy way to set this within NuGet package or runtime-pack and it can be set only at consuming side.

We could also redo this very restrictive setup and consider making any assembly illinker compatible when it has a certain assembly-level attribute (e.g. `ILLinkCompatibility ("link")`. This attribute could even be automatically generated by our tooling as part of the build when linker does not report any warnings.

@sbomer @vitek-karas

**Comment by sbomer** [comment]
To give some more context:
`IsTrimmable` is an opt-in metadata that can be set on the [framework definitions](https://github.com/dotnet/installer/blob/f1564ea07f85999c3712ac8cbce5d7569a1632a7/src/redist/targets/GenerateBundledVersions.targets#L217), and it flows to the ItemGroups that are input to the linker build logic. Any inputs which are not `IsTrimmable` currently get passed through to the linker as root assemblies, with the action set to "copy" (which is as close as we get to a pass-through mode today, see https://github.com/mono/linker/issues/639).

There are a few asks here:
- Support aggressive trimming. I agree that this needs to be done. I have filed a more specific issue for it at https://github.com/dotnet/sdk/issues/12035.
- Support `IsTrimmable` on runtime-packs. I think the existing behavior with https://github.com/dotnet/installer/blob/f1564ea07f85999c3712ac8cbce5d7569a1632a7/src/redist/targets/GenerateBundledVersions.targets#L217 does what you have asked - if there is more to it, let me know. If there are specific scenarios that need to be enabled, I'm happy to help make sure that they work end-to-end.
- Support `IsTrimmable` on nuget packages. This could be done - there's an open issue for it here: https://github.com/dotnet/sdk/issues/3302.
- Use attributes on the output side - added by the linker, to indicate that it was linked, the action taken, whether it is linker-friendly, etc... There are lots of open questions. https://github.com/mono/linker/issues/1194 is an existing issue for this.
- Use attributes on the input side to determine the linker action. This could provide an alternate way to set the action instead of passing it to the task [metadata](https://github.com/mono/linker/blob/master/src/ILLink.Tasks/LinkTask.cs#L17). It needs more thought. I think we should discuss it at https://github.com/mono/linker/issues/1194 or open a new issue if they are sufficiently different.

I am planning to do https://github.com/dotnet/sdk/issues/12035 for .NET 5. How do we want to prioritize the rest? Are there any other parts to this that I missed?

**Comment by marek-safar** [comment]
> Support IsTrimmable on nuget packages

I don't think that's the same thing. Doing manual edits in projects and set IsTrimmable to true for NuGets which are linker friendly is not great.

> I think we should discuss it at mono/linker#1194 or open a new issue if they are sufficiently different.

I think that's a very different concept and will open another issue then

>How do we want to prioritize the rest?

#12035 is required and we also need a solution for component vendors to make their NuGets to be automatically linked which I think is the second large missing piece today

**Comment by vitek-karas** [comment]
I must admit I'm a bit nervous adding official looking support for more aggressive trimming given that for .NET 5 we won't have the correctness in place. Hopefully in 6 we will be able to revisit this and somehow tie correctness into it as well.

**Comment by sbomer** [comment]
> Doing manual edits in projects and set IsTrimmable to true for NuGets which are linker friendly is not great.

I see - so you are asking for it to be defined by the package itself. I agree that the right place to do this is in the assembly or an extra file, rather than the package manifest for example.

> I'm a bit nervous adding official looking support for more aggressive trimming

I could make it a non-public option for now - I think it makes sense to add even just for linker developers. I have lost count of the number of times I have had to add sizeable msbuild snippets to my project just to get this behavior. :)

**Comment by sbomer** [comment]
I will close this for now - we can discuss in the linked issues, or re-open if there are more missing pieces.
