### ISSUE TITLE
Add SDK Support for new runtime feature switches

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#12217]
We are introducing new runtime options  in dotnet/runtime to allow unnecessary code to be trimmed in size sensitive apps (Blazor, Xamarin).

To complete this experience we should add a `RuntimeHostConfigurationOption` and MSBuild property to set each feature switch. For example:

```xml
    <RuntimeHostConfigurationOption Include="System.Diagnostics.Tracing.EventSource.IsSupported"
                                    Condition="'$(EventSourceSupport)' != ''"
                                    Value="$(EventSourceSupport)"
                                    Trim="true" />
```

Feature switches being added to dotnet/runtime:

* [System.Diagnostics.Tracing.EventSource.IsSupported](https://github.com/dotnet/runtime/pull/38129)
* [System.Resources.UseSystemResourceKeys](https://github.com/dotnet/runtime/pull/38397)
* [System.Diagnostics.Debugger.IsSupported](https://github.com/dotnet/runtime/pull/37288/)
* [System.Text.Encoding.EnableUnsafeUTF7Encoding](https://github.com/dotnet/runtime/pull/37535)

We also should add `Trim='true'` for the `System.Globalization.Invariant` RuntimeHostConfigurationOption so the non-invariant globalization code can be trimmed.

**Comment by GrabYourPitchforks** [comment]
@eerhardt What's the expected behavior if a setting is specified in _both_ the .csproj _and_ the runtimeconfig.json file? From some quick experiments it looks like the build output contains the .csproj's value rather than the .json's value. Just wanted to verify that this met your expectations.

Context: the aspnet core SDK targets file will contain `<EnableBinaryFormatter>false</EnableBinaryFormatter>`. But if a developer wants to re-enable it, this means that they're forced to make a change to the .csproj rather than having the option of making the change to runtimeconfig.json. I'm trying to figure out if this is an acceptable scenario, as there might be some web applications where the .csproj is auto-generated and devs might not be able to modify those entries.

**Comment by eerhardt** [comment]
> @eerhardt What's the expected behavior if a setting is specified in both the .csproj and the runtimeconfig.json file? 

See the comment here:

https://github.com/dotnet/sdk/blob/a5f5bb5183517cb301050288b25c9c727e52e8a6/src/Tasks/Microsoft.NET.Build.Tasks/GenerateRuntimeConfigurationFiles.cs#L163-L166

So yes, the intention is that the settings in the .csproj will always win over a conflicting `runtimeconfig.template.json` setting.
