### ISSUE TITLE
Conditional project references fail when targeting multiple TFMs

### ISSUE THREAD

**Issue by hennys** [dotnet/sdk#1227]
Reproduction steps:
1. Create 3 projects, LibA, LibB & LibC (netstandard1.1)
2. Reference LibA from LibB and LibB from LibC
3. Add a class in LibA and reference it in LibC
4. Confirm successful build
5. Make LibC target another TFM (netcoreapp1.1)
6. Add a project reference to LibA, conditional to the second TFM 
7. Run dotnet build or build in VS2017 
8. Build fails for first TFM (netstandard1.1)

The following error message is provided: 
_Cannot find project info for 'X:\LibA\LibA.csproj'. This can indicate a missing project reference.	LibC	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets	92_

This is LibC.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>    
    <TargetFrameworks>netstandard1.1;netcoreapp1.1</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LibB\LibB.csproj" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.1'">
    <ProjectReference Include="..\LibA\LibA.csproj" />
  </ItemGroup>
</Project>
```

Removing the conditional TFM, e.g. letting LibC only target netstandard1.1 again will result in a successful build even if the conditional reference remains.

**Comment by nguerrera** [comment]
@emgarten I believe this would be because nugets traversal of project references at restore time only considers project references from the outer build context and not per tftm. This error in the SDK triggers when there's no matching information about a project reference in the assets file. Does that sound right? If so, I think we need to move this to nuget.

**Comment by emgarten** [comment]
Restore reads from the inner build, conditional project references have been working in the past.

**Comment by nguerrera** [comment]
Ok. I'll take a deeper look.

**Comment by nguerrera** [comment]
@grokys Yes, I'm not aware of anything that has changed here.

**Comment by grokys** [comment]
Thanks @nguerrera - do you know of any workarounds for now?

**Comment by nguerrera** [comment]
The issue is that we do not look at ProjectFileDependencyGroup.FrameworkName here:

https://github.com/dotnet/sdk/blob/7ee4c2a2f657081262140e7c863641e979bb1c06/src/Tasks/Microsoft.NET.Build.Tasks/LockFileExtensions.cs#L92

We should only be adding the one's that have a FrameworkName matching the target framework of the current of the inner build.

The result for the specific repro steps here, is that we see a direct reference to LibA for all TFMs instead of just for netcoreapp1.1. This causes us to think that we do not need the transitive ref in netstandard2.1.

The workaround is that when you add a direct reference, add it to all the TFMs that you expect to see that ref, even if they would otherwise get it transitively were it not for this bug.

**Comment by nguerrera** [comment]
I moved this out of 3.0 to backlog as the case this covers is actually relatively obscure where you have a direct reference in one tfm, and an indirect in another. 

There's also some risk to making a change to reference resolution at this stage of 3.0.

**Comment by eriawan** [comment]
@nguerrera 
Any update on this issue?

I still experience this on targeting netcoreapp2.1 based on the scenario on the first thread.

**Comment by nguerrera** [comment]
I haven't worked on this project for a long time, so I'm not aware of any updates. Adding @marcpopMSFT @dsplaisted

**Comment by dsplaisted** [comment]
@sfoslund Would you be able to take a look at this?  [Nick's comment](https://github.com/dotnet/sdk/issues/1227#issuecomment-514429455) describes the issue.
