### ISSUE TITLE
dotnet pack with /p:PackageVersion overrides package version of dependecies as well

### ISSUE THREAD

**Issue by andradf** [dotnet/sdk#12322]
This is on  SDK ` 3.1.301`. I haven't tested it  on the 5.0 previews. I have a solution with two .net core class libraries, LibA and LibB. LibB depends on LibA. Each of the csproj sets the package version  for their corresponding library (LibA 2.0.0, LibB 1.0.0).
When I run `dotnet pack` on LibB, the nupkg correctly lists LibA 2.0.0 as a dependecy. However if I run `dotnet pack /p:PackageVersion=1.0.0-ci-20200702.1` on LibB the nupkg lists LibA 1.0.0-ci-20200702.1 as a dependency. The pack tool seems to be overriding the package version of all my project dependencies, not just the project I am building. Is this the intended behavior? I would think that the package version should only apply to the package I am building. Is there a way to tell dotnet pack to only override the version of the csproj on  which it is being invoked and not its project dependencies?

**Comment by sfoslund** [comment]
I don't think this is intended behavior, can you please provide [a binlog](https://github.com/Microsoft/msbuild/blob/master/documentation/wiki/Binary-Log.md) reproducing the error?

**Comment by sfoslund** [comment]
My mistake, this actually is intended behavior. Specifying a property on the command line makes it a global property, which means it applies to all projects that are being built. To use this property for only one project, you can specify it in the project file. Feel free to comment or reopen if you have further questions.

**Comment by binarydad** [comment]
I found this, and unfortunately it's closed, but I'm having the exact same issue. 

I can't set it at the project level because I'm specifying the version, via `-p:PackageVersion=1.2.3.4` when invoking `dotnet pack`. When using nuget.exe to pack (before converting from net48 to standard20), we used to specify `-Version 1.2.3.4` and it only set the version on the package, NOT the dependencies required. 

Seems like really silly behavior to force the dependencies to use the same version name/number/scheme as the main package. I have dependent packages that DON'T need to be the same version. 

How can I get around this behavior and only set the version on the package I'm building, and not the dependency versions? Thanks.

**Comment by baronfel** [comment]
One suggestion would be to use a different property than the already-used-by-the-SDK `PackageVersion` property. If instead you used something like `-p:MyPackageVersion=1.2.3`, then in your project file you could add `<PackageVersion>$(MyPackageVersion)</PackageVersion>` and limit the scope of the property to just that one project.
