### ISSUE TITLE
 Could not copy Error in docker linux container

### ISSUE THREAD

**Issue by aortiz-msft** [dotnet/sdk#12611]
---
**Issue moved from NuGet/Home#9787**
- Please respond to @ZergRushJoe.

---

_From @ZergRushJoe on Monday, July 13, 2020 12:56:23 AM_

## Details about Problem
I keep getting this error from my 'docker build .'. I'm getting the error with this .net core microsoft.analysisservices.adomdclient.netcore.retail.amd64. The Error that comes from it:

/usr/share/dotnet/sdk/3.1.301/Microsoft.Common.CurrentVersion.targets(4360,5): error MSB3021: Unable to copy file "/root/.nuget/packages/microsoft.analysisservices.adomdclient.netcore.retail.amd64/19.4.0.2-preview/lib/netcoreapp3.0/zh-HANS/Microsoft.AnalysisServices.AdomdClient.resources.dll" to "bin/Debug/netcoreapp3.1/zh-HANS/Microsoft.AnalysisServices.AdomdClient.resources.dll". Could not find a part of the path '/app/Processor/bin/Debug/netcoreapp3.1/zh-HANS/Microsoft.AnalysisServices.AdomdClient.resources.dll'

Don't know why it can't find that package. it restores just fine. I know it builds on windows which more then likly means I can never get it to work. The project it is in is an F# project.

Docker File
From node:12 AS web-build

COPY ./Web.UI ./

RUN npm i
RUN npm run test
RUN npm run buildProd

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS backend-build

WORKDIR /app
COPY . ./
COPY --from=web-build /Processor/wwwroot ./Processor/wwwroot
RUN dotnet test
RUN dotnet publish -c Release -o publish

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=backend-build /app/publish .
EXPOSE 80

**Comment by IntoTheNature** [comment]
Ran into the same issue with this preview library. Seems like the issue is in linux being case sensitive to folder names:

`/usr/share/dotnet/sdk/3.1.101/Microsoft.Common.CurrentVersion.targets(4384,5): warning MSB3026: Could not copy "/root/.nuget/packages/microsoft.codeanalysis.common/3.3.1/lib/netstandard2.0/**zh-Hans**/Microsoft.CodeAnalysis.resources.dll" to "bin/Release/netcoreapp3.1/**zh-Hans**/Microsoft.CodeAnalysis.resources.dll". Beginning retry 1 in 1000ms. Could not find a part of the path '/src/MyProject/bin/Release/netcoreapp3.1**/zh-Hans**/Microsoft.CodeAnalysis.resources.dll'.  [/src/Myproject.csproj]`

The folder exists though, but with a different (case-wise) name:
/src/MyProject/bin/Release/netcoreapp3.1/**zh-HANS**/

**Comment by IntoTheNature** [comment]
Created a simple solution for you to reproduce the issue.
https://github.com/IntoTheNature/DR.NetCore.AdomdClient.Bug 
@dsplaisted any chance you will look at it soon?

**Comment by sfoslund** [comment]
You're right, this looks like a casing issue with MSBuild, see [the binlog here](https://github.com/sfoslund/DR.NetCore.AdomdClient.Bug/tree/main/DR.NetCore.AdomdClient.Bug). _CleanGetCurrentAndPriorFileWrites is returning the lower case version of the path when we're publishing seemingly because we're [ignoring case in this comparison](https://github.com/dotnet/msbuild/blob/e70a3159d64f9ed6ec3b60253ef863fa883a99b1/src/Tasks/ListOperators/FindUnderPath.cs#L89) in FindUnderPath. @Forgind were you looking into taking file path casing into account a few months ago? Should this be moved to MSBuild?

**Comment by Forgind** [comment]
That looks right to me. I'm assuming you tested whether the repro still works when that check uses a case-sensitive comparison? I'd be happy to approve a PR doing something like switching the check to a FileUtilities call that does something similar but takes the OS's casing into account, or I can make it if you'd prefer.

**Comment by sfoslund** [comment]
No I haven't tested a fix, I'll move it to MSBuild to let you all triage as appropriate.

**Comment by sfoslund** [comment]
This issue was moved to dotnet/msbuild#5768
