### ISSUE TITLE
Object.Equals (obj, obj) appears to perform reference equality rather than value equality

### ISSUE THREAD

**Issue by BHetrick** [dotnet/sdk#12783]
The Object.Equals method returns false when presented two StringBuilder objects with identical contents, although the StringBuilder.Equals method returns true. Object.Equals is documented as calling instance Equals on the first argument (modulo nulls). Alternatively, someone between Object and StringBuilder does "new Equals" instead of "override Equals."

The result of:

StringBuilder a = new StringBuilder ("a");
StringBuilder b = new StringBuilder ("a");
Console.WriteLine ("a == b: {0}.", a == b);
Console.WriteLine ("Equals (a, b): {0}.", Equals (a, b));
Console.WriteLine ("a.Equals (b): {0}.", a.Equals (b)

is:

a == b: False.
Equals (a, b): False.
a.Equals (b): True.

Dotnet Core 3.1.301, armv7l, Raspberry Pi 4, Raspbian current

[EqualsTest.zip](https://github.com/dotnet/sdk/files/5030964/EqualsTest.zip)

**Comment by SirUppyPancakes** [comment]
For whatever reason, `StringBuilder` does not override `object.Equals` or implement `IEquatable<StringBuilder>`. Instead, it simply defines its own equality methods (one for `StringBuilder` and one for `ReadOnlySpan<char>`):
https://source.dot.net/#System.Private.CoreLib/StringBuilder.cs,d667f7b9914a12ec

**Comment by BHetrick** [comment]
So StringBuilder breaks the Object contract. I suspect that might be regarded as a bug.

**Comment by SirUppyPancakes** [comment]
Slipped my mind when I commented, but the reason `StringBuilder` doesn't implement the normal equality stuff is because it is mutable. Generally, the best practice is to leave mutable objects with the default reference equality semantics (so that things that rely on hashing, like `Dictionary`, behave in an expected way), and only implement value equality (`object.Equals`, `GetHashCode`, `IEquatable`, etc) for immutable objects.

By providing their own `Equals` method that is separate from `object.Equals` and `IEquatable`, they give you a way to check for equality if you have two explicit `StringBuilder` instances, but without opening you up to accidentally getting weird behavior with hashing or when you have two `StringBuilder` instances behind some more general reference like `object` or `IEquatable`, or as the key to a `Dictionary` or similar.

Personally, I like to name my "Equals" method on mutable objects something else to avoid this kind of confusion, but the typical one I see implemented in official stuff is `Equals` which can definitely be confusing if you're not really familiar with the crazy world of .NET equality.

**Comment by BHetrick** [comment]
Ouch. Implementing value equality for immutable classes only is _significantly_ different than what I've been doing and recommending for the last 15 or so years. Either I greatly misunderstood the guidance available, or the guidance has changed. I suppose that's one way of handling hash code changes: don't let them. But then content addressable storage such as Dictionaries quit being content addressable, except by immutable types instead of objects that happen not to change. Yes it's a best practice, but... Since I'm currently writing a C# course (why I looked at this at all, it was an example), I'll have to research more. Thank you!

While I have the ear of an expert, can you point me at why the compiler refuses to let me compare two KeyValuePair <string, string> values with ==? == is well-defined on value types.

**Comment by sfoslund** [comment]
@BHetrick it sounds like your question has been answered, but if not feel free to open another issue. If you do, https://github.com/dotnet/runtime would likely be a better place to file it, thanks!
