### ISSUE TITLE
No error when Microsoft.NET.Sdk + net5.0 (without net5.0-windows)

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#12811]
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
</Project>
```

**Comment by wli3** [comment]
This is intention for preview 8 transition. But we need to remove it before GA

**Comment by wli3** [comment]
@sfoslund @dsplaisted this still works in RC1. Do we want to make it permanent? Or we just haven't got time to fix?

**Comment by sfoslund** [comment]
We error when -windows isn't set and UseWPF or UseWinForms is true, do we want to error when the output type is WinExe too?

**Comment by wli3** [comment]
> We error when -windows isn't set and UseWPF or UseWinForms is true

This is done? Or plan to do?

> do we want to error when the output type is WinExe too?

That's a bit risky. I think WPF and Winforms are not the only feature sets WinExe

**Comment by sfoslund** [comment]
> > We error when -windows isn't set and UseWPF or UseWinForms is true

>This is done? Or plan to do?

It's done, I believe it was in prev 8.

**Comment by wli3** [comment]
So that's the problem. I tried it on rc1, it does not error

**Comment by sfoslund** [comment]
Oh I just got a binlog and I know what's going on. It's not erroring [here](https://github.com/dotnet/sdk/blob/8deb8898af5029363784f2131148770b439a0cd9/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L366) because the TargetPlatformIdentifier is set to Windows because the target platform workaround is still in RC1. I just merged the change to remove the workaround so this should error in RC2: https://github.com/dotnet/sdk/pull/13168

**Comment by wli3** [comment]
So it is fixed in RC2. Closing
