### ISSUE TITLE
.NET core sdk is still SPYING it's users even after it's "disabled" by "DOTNET_CLI_TELEMETRY_OPTOUT=1" environment variable

### ISSUE THREAD

**Issue by rekaerst** [dotnet/sdk#12841]
My dotnet sdk is extremely slow on creating new projects, so I dug a little on this abnormal behavior, and then I found that dotnet is making a lot of network requests. I use Wireshark  captured those activities:

.NET core sdk sends requests to 
```
go.microsoft.com:443
nam06.safelinks.protection.outlook.com:443
webpifeed.blob.core.windows.net:443
blob.byaprdstr14a.store.core.windows.net:443
```
when "dotnet new" <project> runs.

Dotnet sdk won't return to the shell before those requests finished, and that's why it hangs after "Restore succeeded." message 

Not a new thing: #6145
But I already set DOTNET_CLI_TELEMETRY_OPTOUT=1 on my machine

**Comment by dagood** [comment]
This set of hosts looks like `dotnet new` checking for template updates, rather than telemetry. https://github.com/dotnet/sdk/issues/10564

Maybe you can set `DOTNET_NEW_LOCAL_SEARCH_FILE_ONLY=1` and try again to try to rule that out? I found it in https://github.com/dotnet/templating/issues/2093, which tracks fixing the slowdown.

**Comment by rekaerst** [comment]
Sorry, hit a wrong thing.
