### ISSUE TITLE
Cannot build C++/CLI 5.0 app 

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#12916]
https://github.com/nguerrera/NETCoreCppCliTest app and change TFM to net5.0 build will have error 

error MSB4184: The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation('', 10.0.18362.0)" cannot be evaluated. Parameter "targetPlatformIdentifier" cannot have zero length. [C:\Users\Administrator\Documen
ts\NETCoreCppCliTestWithNative\NETCoreCppCliTest\NETCoreCppCliTest.vcxproj]

**Comment by wli3** [comment]
@sfoslund I see this error in preview 8. However, did you fix it in master?

**Comment by sfoslund** [comment]
We're skipping this test in master (and I believe preview 8?) right now due to xcopy-msbuild (see https://github.com/dotnet/sdk/issues/3785). I don't remember explicitly fixing this bug, although this error looks familiar. It's possible I fixed it but I think relevant changes are all in prev 8 as well.

**Comment by marcpopMSFT** [comment]
@wli3 Can this be closed and marked complete on the RC1 tracking issue since the PR is merged?

**Comment by wli3** [comment]
I want to close it once i have an insertion and verify that

**Comment by wli3** [comment]
Verified. It works
