### ISSUE TITLE
Make conflict resolution read/understand the TargetFrameworkList XML file 

### ISSUE THREAD

**Issue by AlexGhiondea** [dotnet/sdk#1336]
This issue tracks the work required to make conflict resolution understand the targetframework list from the targeting pack on Desktop and passing that information to the conflict resolution target.

**Comment by dsplaisted** [comment]
@AlexGhiondea @ericstj What is conflict resolution supposed to do with the target framework list?  Is this still necessary?  The conflict resolution code checks for the presence of netstandard.dll in the targeting pack, so it will already turn itself off once that's part of the platform.

**Comment by ericstj** [comment]
> The conflict resolution code checks for the presence of netstandard.dll in the targeting pack, so it will already turn itself off once that's part of the platform.

Don't confuse conflict resolution with netstandard injection.  NETStandard injection is disabled when it is part of the platform, [conflict resolution *always* happens](https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.targets#L23-L24).

The reason it needs to happen is there are still plenty of packages out there trying to use the old System.* packages which provide an out-of-band implementation of many of the facades.  We found that RAR won't drop those when they are moved into the targeting pack, and even if it did it wouldn't touch the runtime items (ReferenceCopyLocalPaths).

Conflict resolution is really the best place to handle this.  It's designed to handle conflicts between multiple NuGet packages, or between NuGet packages and a framework.  In fact this is a very similar problem to the shared framework in NETCoreApp.  Since the shared framework never appears as runtime items in a shared framework application we needed a way for conflict resolution to "know" what was in the shared framework so that it could decide if a package had a newer version or not.  This was done through the [PlatformManifest](https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/src/Tasks/Common/src/ConflictResolution/ResolvePackageFileConflicts.cs#L24).  The FrameworkList is really the equivalent of this on desktop.

**Comment by dsplaisted** [comment]
@ericstj Can you point me to any examples of packages that have dependencies on the specific contract packages?  That would help me test this.

**Comment by ericstj** [comment]
How about NETStandard.Library: 1.6.1?  Or System.Net.Http: 4.3.3?

Most of the CoreFx packages reduce their dependencies on NETFx to nearly nothing so I don't have many good indirect examples, but direct references should be just as good.

**Comment by livarcocc** [comment]
This has now been fixed.
