### ISSUE TITLE
Microsoft.NET.Sdk.WindowsDesktop SDK should not be required for Windows Forms / WPF projects targeting .NET Core 3.x

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#13449]
For .NET 5, we use the base Microsoft.NET.Sdk for Windows Forms and WPF projects.  We should also support this for .NET Core 3.x projects.  This will reduce the pain in retargeting, as well as multi-targeting (see #13427).

It looks like we just need to change the condition checking the .NET Core version here: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L984-L990

@sfoslund

**Comment by wli3** [comment]
Also + @KathleenDollard 
This approach is ok for this specific issue. However this is a strategy change.

From 1.0 - 3.0, whenever there is a change required to edit the "default template"/the minimal project file. We don't provide a migration tool. And we just [ask the user to update TFM and edit the project file accordingly](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio). For example removing aspnet store package reference. At the same time, we try to separate the new logic from the older TFM, meaning, a lot of new feature in SDK is only applied when TFM is higher than x.

This works well for web projects which is majority of the case. However, people from desktop have different expectation. They expect a migration tool or the project stays the same. So far we don't have a good strategy yet. I don't think the approach we take here can apply to complex features.

1. Also not require Microsoft.NET.Sdk.WindowsDesktop to 3.1 means we "back port" the new feature to older TFM. That will increase the risk of breaking existing project at least. Again, this specific issue is fine, but it will not be safe for bigger features.

2. A weird, "I can compile my project in 5.0.xxx SDK targeting 3.1 TFM but cannot run on 3.x.xxx SDK" will happen. I don't know how important it is. But this is a new thing.

3. Not all new feature can be back ported to older TFM. At a certain point, maybe due to risk of the new feature or there is some hard dependency on the new TFM, we can no longer do this.

It is a hard problem, I don't think we have an obvious solution. I can see only 4 direction so far, 
1. a migration tool. Which we have never made a good one. 
2. Stop making "default template"/the minimal project file change. This would greatly restrict new features we can do.
3. Train the desktop user to accept "web project style migration".
4. relax the "minimalistic project" approach in desktop project. Full framework projects do not need migration due to everything is explicit in the project file.

**Comment by sfoslund** [comment]
Fixed by https://github.com/dotnet/sdk/pull/13441
