### ISSUE TITLE
Microsoft.DataSqlClient.dll is not copied to the bin folder when CopyLocalLockFileAssemblies is specified

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/sdk#1353]
1. Start Visual Studio
2. Create a new ASP.NET Core 1.1 Web Application with Individual Auth (this is required to created the dependency on sql client)
3. Save all
4. Switch to command line, and run dotnet build /p:CopyLocalLockFileAssemblies=true

Note that bin\Debug\netcoreapp1.1 does not contain this assembly.

When running the project under IIS, the entire closure needs to be in the bin folder as the application is running under the apppool identity which doesn't have a users folder, and hence no access to the .nuget path.

**Comment by nguerrera** [comment]
The issue here is that System.Data.SqlClient has a different implementation dll to deploy for windows and unix, but there is no RuntimeIdentifier set to allow the copy-local to know which one to use. The common case for CopyLocalLockFileAssemblies is for .NET Framework targeting in which case we default the RuntimeIdentiifer to an appropriate windows-specific value for you, but here it is being used with .NET Core targeting and that doesn't happen. 

A fix might involve defaulting the RID if the project hasn't already set it in the same place that IIS debugging is forcing CopyLocalLockFileAssemblies to true, but that is problematic because the RID must also be seen during package restore for it to be used during build.

**Comment by nguerrera** [comment]
I think a better approach will be to stop using CopyLocalLockFileAssemblies and instead use the publish resolution targets to resolve the publish assembly assets and copy those. This will produce a "fat" layout in bin that can work for multiple RIDs.

**Comment by nguerrera** [comment]
I played with that a bit and copying the publish layout is easy enough, but we also need to mimic the publish .deps file, which is quite problematic.

**Comment by nguerrera** [comment]
@BillHiebert Can you give me instructions to install IIS and test this end-to-end? I have another idea, but it will require a full repro to validate.

**Comment by nguerrera** [comment]
@BillHiebert Nevermind. I figured it out and have the full repro:

```
WebApplication12> Error: assembly specified in the dependencies manifest was not found -- package: 'system.data.sqlclient', version: '4.3.1', path: 'runtimes/win/lib/netstandard1.3/System.Data.SqlClient.dll'
```

**Comment by nguerrera** [comment]
OK, things work if I replace the target in Microsoft.Web.ISSSupport.targets with the following:

``` xml
<Target Name="ResolveAdditionalReferenceCopyLocalPathsForIIS" 
         Condition="'$(CopyCompilationRefAssemblies)' == 'true' and '$(CopyLocalLockFileAssemblies)' == 'true'" 
         AfterTargets="ResolveAssemblyReferences" 
         DependsOnTargets="RunResolvePublishAssemblies">

   <ItemGroup>
      <!--
        Copy reference assemblies that are not also runtime assemblies and therefore
        already included in ReferenceCopyLocalPaths via CopyLocalLockFileAssemblies=true.
      -->
      <ReferenceCopyLocalPaths Include="@(ReferencePath)" Exclude="@(ReferenceCopyLocalPaths)">
        <DestinationSubDirectory>$(RefAssembliesFolderName)\</DestinationSubDirectory>
      </ReferenceCopyLocalPaths>

      <!--
        Copy publish assemblies that not already included in ReferenceCopyLocalPaths
        via CopyLocalLockFileAssemblies=true. This will include RID-specific assets 
        that would be published in runtimes/*, but excluded from CopyLocalLockFileAssemblies
        when no RuntimeIdentifier is set.
      -->
      <ReferenceCopyLocalPaths Include="@(ResolvedAssembliesToPublish)" Exclude="@(ReferenceCopyLocalPaths)">
        <DestinationSubDirectory>$([System.IO.Path]::GetDirectoryName(%(ResolvedAssembliesToPublish.DestinationSubPath)))\</DestinationSubDirectory>
      </ReferenceCopyLocalPaths>
    </ItemGroup>
  </Target>
```

Notes:
* I've refactored the refs/ copying logic to simply add to ReferenceCopyLocalPaths. This made it easier to add the extra RID-specific publish assemblies and will also get you faster incremental builds (better Copy logic in common targets) and less code to maintain.

* We're actually copying too much (existing problem) because CopyLocalLockFileAssemblies also copies shared framework assets that are excluded from publish. However, when I tried to replace CopyLocalLockFileAssemblies with RunResolvePublishAssemblies to fix both issues, I ended up with a .deps file that includes assets that publish would exclude and the app would fail to start. So, instead, we only add to what is resolved by CopyLocalLockFileAssemblies and give up on trimming out unnecessary files for now.

* It's on our radar for vNext to have a proper "in-place publish" that can replace CopyLocalLockFileAssemblies. It would handle both of these concerns for you and you will be able to delete this target in favor of that option when available. That feature would also eliminate the extra files mentioned in the previous bullet.

I'm closing this because I think the best fix for the upcoming release is to amend the IIS support targets as described above.

**Comment by bhiitola2011-blip** [comment]
oitteko antaa minulle ohjeet IIS:n asentamiseen ja tämän testaamiseen päästä päähän? Minulla on toinenkin idea, mutta sen validointi vaatii täyden uudelleenasennuksen.
