### ISSUE TITLE
Missing System.Threading.Tasks

### ISSUE THREAD

**Issue by Jose-CF** [dotnet/sdk#1358]
To reproduce:

* Use a Windows 10 system with Visual Studio 2017, .NET Framework 4.6.2 SDK as well as .NET Core SDK installed.
* Create in Visual Studio 2017 a new project A targeting .NET Standard 1.3.
* Build project A using msbuild `Microsoft (R) Build Engine version 15.2.0.0`
* Create  in Visual Studio 2017 a new project B in a different solution targeting .NET Framework 4.6.2
* Import into B project A. (either the assembly or a nuget package, you name it)
* Build project B using msbuild `Microsoft (R) Build Engine version 15.2.0.0`
* Notice the output does not contain assembly `System.Threading.Tasks` (this should be ok, right? Should be in the GAC, right?)
* Copy your assemblies to a Linux machine with mono, run it with mono, works flawlessly.
* Try to run the software in Windows 10 machine, and get this result:
![image](https://user-images.githubusercontent.com/24405049/27315516-4676115e-55a4-11e7-957c-f7c973fba9c9.png)

Am I missing something too obvious in here?

**Comment by livarcocc** [comment]
I can't repro this.

I tried it with VS 15.6 and the 2.1.300-preview1 .NET Core SDK.

This scenario worked for me when I had the class library as a project reference or a package reference.

It did fail when just referencing the assembly, but I believe that happens because in that case we don't know this is netstandard and don't bring in the extra assemblies we need to make it work.

The failing case fails with this:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   --- End of inner exception stack trace ---
   at ConsoleApp3.Program.Main(String[] args)
```

@dsplaisted can on comment on the failure here? Is this supposed to work? netstandard1.3 being referenced by net462 app?

**Comment by livarcocc** [comment]
Thanks @dsplaisted, given that, I am going to close this issue now.

@Jose-CF, if the original issue still reproes for you, please comment and give us additional details, maybe provide a small repro on github and we can re-activate it.
