### ISSUE TITLE
global.json documentation

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1421]
Where can I find documentation on global.json? This is the only public documentation I could find:

https://docs.microsoft.com/en-us/dotnet/core/tools/global-json

Unfortunately it doesn't answer the questions I have about the `sdk.versions` property. In particular:

- What are the matching rules? Say I put 1.0 but 2.0 is available. Will 2.0 be chosen or will an error occur?
- Can I put in version ranges?
- Is there globbing support? 

Also of interest is the version of the SDK that comes installed with Visual Studio. Does that version change on every update, preview, etc ... of VS? Worried about how updates to VS will interact with restrictions that I add in this file.

**Comment by jaredpar** [comment]
CC @rainersigwald, @nguerrera, @dsplaisted

**Comment by livarcocc** [comment]
@mairaw can we work on documentation for this? We changed the policy in 2.0, it would be good to do an all up write up on this file.

**Comment by jaredpar** [comment]
@livarcocc can we get the details posted here while waiting for doc? Need to understand how this works before we can adopt in our repos.

**Comment by mairaw** [comment]
Sorry, I missed this mention earlier. Yes, we can improve the docs. Doc issues can be filed at https://github.com/dotnet/docs/issues. Can I have more info on what needs to be done @livarcocc @nguerrera? I don't know what the change was.

**Comment by nguerrera** [comment]
> What are the matching rules? Say I put 1.0 but 2.0 is available. Will 2.0 be chosen or will an error occur?

Prior to `dotnet 2.0`, the matching rule was that if no exact match was found, then latest would be used. https://github.com/dotnet/core-setup/issues/2334

In 2.0, the rules are described in this PR's description: https://github.com/dotnet/core-setup/pull/2621. However, in the desktop `msbuild`/VS case, the error cases listed there are actually currently fallbacks to the 1.1 SDK in the MSBuild folder due to the problem described in https://github.com/dotnet/sdk/issues/1470#issuecomment-322310484

> Can I put in version ranges?

No

> Is there globbing support?

No

> Also of interest is the version of the SDK that comes installed with Visual Studio. Does that version change on every update, preview, etc ... of VS? Worried about how updates to VS will interact with restrictions that I add in this file.

Yes, it does change.

**Comment by nguerrera** [comment]
This issue was moved to dotnet/docs#2902
