### ISSUE TITLE
Unable to attach debugger to .net core projects due to IPV6 restrictions

### ISSUE THREAD

**Issue by snhoxie** [dotnet/sdk#1437]
I work in an environment where IPV6 is blocked by IDS/IPS.
When I create a new core app in either VS2015 or 2017 (does not matter if it is a web or console app), I cannot debug it.  My IPS logs that it blocked IPV6 communications (loopback) and Visual Studio says it cannot attach the debugger - do I wish to proceed without debugging...   The app runs ok.  When the IPS/IDS is temporarily disabled, all is good.  Everything works.  Unfortunately that is not a permanent solution. 

Nothing in my app uses IPV6.  Even an empty console app, with no network code at all triggers the block.

Is there a setting somewhere that I can use to disable this?  I have not seen this anywhere else in any forum

**Comment by gregg-miskelly** [comment]
@snhoxie the debugger tries to figure out if IPv6 is disabled. But whatever your network has done to disable it isn't something that we can detect. Can you try going into your network adapter properties and removing IPv6?

**Comment by snhoxie** [comment]
I have gone to all of the adapters and disabled (unchecked) IPV6 - and it still fails and creates an entry in the IPS.  It appears that the IPS is below the actual network drivers and can detect and stop the call even if IPV6 is disabled.

**Comment by snhoxie** [comment]
Is there a configuration setting that would provide the framework with a directive not to use IPV6 at all?

**Comment by gregg-miskelly** [comment]
The framework isn't using IPv6 - it is Visual Studio that is using it. The problem is that from the several operating system calls that we make, IPv6 looks like it should work. VS checks if we can bind an IPv6 socket (via the `socket` and `bind` API), and it checks if the routing table table for the socket is non-empty (via 'WSAIoctl' with `SIO_ROUTING_INTERFACE_QUERY`). I think you will need to work with the vendor of whatever networking software you are using to find a way to either allow localhost IPv6, or to more fully disable IPv6.

**Comment by snhoxie** [comment]
Thank you for your response...  I do concur that Visual Studio is triggering the event during debugging of core projects.  It does not trigger the IPS when debugging standard .net 4.x applications.  So... only .net core variants trigger the block.  I am still puzzled why the core projects force IPV6 activity and .net standard do not.

I will work with our policy people on an exception but I will need to be very specific on what I am asking (e.g. allowing IPV6 loopback)

**Comment by gregg-miskelly** [comment]
.NET Core projects are 64-bit, desktop projects default to 32-bit (though they can run 64-bit). Anytime VS needs to debug a 64-bit process it needs to utilize a helper process (msvsmon.exe) which it communicates with over a localhost socket.

**Comment by snhoxie** [comment]
Wow!  Thanks.  That explains it....
I think this should be looked at again... My project is within the Department of Defense and may have a major impact on core usage there in our highly regulated environment.

I really appreciate the time spend on letting me know what is happening.

**Comment by snhoxie** [comment]
I have further investigated disabling IPV6 via netsh, registry, adapter settings.  Can a s

**Comment by snhoxie** [comment]
I have further investigated disabling IPV6 via netsh, registry, adapter settings.  Nothing works.  I understand need for a helper process to use the localhost socket but do you need to use both IPV4 and IPV6?  Cannot one be toggled off via a switch or debug setting?   This issue renders any dotnet core development within my, highly regulated, organization very difficult.  My security team has no authority to waiver on the block of IPV6 so I am no longer able to provide solutions leveraging all of the core features!  Please consider reviewing this in future updates.

**Comment by livarcocc** [comment]
@gregg-miskelly is there a repo that is more appropriate for this issue? This is not really something controlled on the SDK.

**Comment by gregg-miskelly** [comment]
In Visual Studio 2017 version 15.7 (preview 3 and later), the debugger team added a new mode so that local 64-bit debugging can be configured to communicate between processes using anonymous pipes instead of TCP/IP. 

To enable this today:
1. Install Visual Studio from the preview channel (https://www.visualstudio.com/vs/preview/). This step will go away once 15.7 enters the release channel.
2. Go to the Windows Start Menu and launch the “Developer Command Prompt for VS 2017 Preview”
3. Run: `"%DevEnvDir%vsregedit.exe" set "%VSINSTALLDIR:~0,-1%" HKCU Debugger UseAnonymousPipes dword 1`
4. Restart VS if it is already running

In a future version of VS, anonymous pipes will become the default transport.

**Comment by gregg-miskelly** [comment]
@livarcocc I would suggest closing this issue.

**Comment by livarcocc** [comment]
Thanks for letting us know.

**Comment by snhoxie** [comment]
ALL
Thank you for your responses and closing this out!

**Comment by radsolution** [comment]
This 'solution' (IPV6 thing) din't fix it for me. I can debug .NET 4.6.1. apps, but not .NET Core 2.0
Nothing is telling me why - I just get a silly error telling me to set my start-up project....
The browser-select bar doesn't say 'IIS Express (<browser-name>)' it just says 'Start'...
What is wrong, please? Version 15.7.2

**Comment by gregg-miskelly** [comment]
@radsolution your problem doesn't sound related to this issue. It sounds like your project somehow doesn't think that it can be launched. If you right click on your project in solution explorer, does 'Set as StartUp Project' appear in the context menu? Does setting that help? You might also try deleting your .suo file and .vs folder and then reloading your project in case that helps any.

If none of that helps: I would would recommend reporting this problem through the Visual Studio problem reporting tool (In Visual Studio: Help-\>Send Feedback-\>Report a problem) so that your issue can hopefully be redirected to the folks who might be able to help.

**Comment by radsolution** [comment]
Thanks Gregg.
Today I installed .Net Core 2.1 and re-started VS. created a new WebAPI project and got the same issue.
Clearly my install of VS doesn't like .NET Core for some reason. Will use the send feedback route you suggest.
Thanks,
Dave Radcliffe (RadSolution)
    On Thursday, 14 June 2018, 18:49:17 BST, Gregg Miskelly <notifications@github.com> wrote:  
 
 
@radsolution your problem doesn't sound related to this issue. It sounds like your project somehow doesn't think that it can be launched. If you right click on your project in solution explorer, does 'Set as StartUp Project' appear in the context menu? Does setting that help? You might also try deleting your .suo file and .vs folder and then reloading your project in case that helps any.

If none of that helps: I would would recommend reporting this problem through the Visual Studio problem reporting tool (In Visual Studio: Help->Send Feedback->Report a problem) so that your issue can hopefully be redirected to the folks who might be able to help.
