### ISSUE TITLE
Resolve publish file conflicts after _ResolvedCopyLocalPublishAssets has been merged into ResolvedFileToPublish

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#14422]
#14020 fixes an issue where we can have duplicate files copied to the publish output.

The reason this was happening is because we have two item types for files that will be published: `_ResolvedCopyLocalPublishAssets` and `ResolvedFileToPublish`.  We merge `_ResolvedCopyLocalPublishAssets` into `ResolvedFileToPublish` in the `ComputeResolvedFilesToPublishList` target, after we have already run conflict resolution on `_ResolvedCopyLocalPublishAssets`.

#14020 currently fixes this by adding another conflict resolution pass that looks at both time types.  However, it would probably be better to run conflict resolution just once, after the item types have been merged.

**Comment by sfoslund** [comment]
Closing this issue as I've looked into this logic a little bit more and I think we do need to keep the new task added in the original PR. Existing conflict resolution is performed on the `_ResolvedCopyLocalPublishAssets` itemgroup which needs to be kept because it's hooking into a target that is reused in store (which doesn't do any subsequent merging or conflict resolution) as well as publish, so I think for publish it makes sense to keep this second round of conflict resolution after the new publish content is introduced.
