### ISSUE TITLE
.Net 5 CLI  missing  `dotnet nuget search`

### ISSUE THREAD

**Issue by John0King** [dotnet/sdk#14549]
today, on Devbog https://devblogs.microsoft.com/nuget/getting-started-with-nuget-5-8/ , it saids that now nuget.exe support nuget search , but no `dotnet nuget search`.

also related to  https://github.com/NuGet/Home/issues/6060

**Comment by dsplaisted** [comment]
I think the issue in the NuGet repo is the place to track this.

**Comment by John0King** [comment]
I'm confused  about the nuget repo and dotnet sdk repo,    this issue is about missing the command in dotnet sdk  instead of nuget.exe ,  and it seems that there are no one interested in this issuce in  nuget repo  team,  maybe because they can not make chagnes on this repo , only the nuget repo.

**Comment by drewgillies** [comment]
Hi @dsplaisted -- the way command line NuGet functionality is surfaced in the dotnet sdk is via the NuGet.CommandLine.XPlat assembly, built from this project: https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.CommandLine.XPlat.
So, if we wish to see new NuGet functionality in the dotnet sdk, we add it there. NuGet's home repo is where we track all of our issues, so if you add it here: https://github.com/NuGet/Home/issues, our team can track it with you.

**Comment by drewgillies** [comment]
Hi @John0King -- the way command line NuGet functionality is surfaced in the dotnet sdk is via the NuGet.CommandLine.XPlat assembly, built from this project: https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.CommandLine.XPlat.
So, if we wish to see new NuGet functionality in the dotnet sdk, we add it there. NuGet's home repo is where we track all of our issues, so if you add it here: https://github.com/NuGet/Home/issues, our team can track it with you.

**Comment by drewgillies** [comment]
Hi @John0King -- the way command line NuGet functionality is surfaced in the dotnet sdk is via the NuGet.CommandLine.XPlat assembly, built from this project: https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.CommandLine.XPlat.
So, if we wish to see new NuGet functionality in the dotnet sdk, we add it there. NuGet's home repo is where we track all of our issues, so adding it here: https://github.com/NuGet/Home/issues, means our team can track it with you. I see that you've commented there and may be concerned that it's fallen off the radar. I would expect that this isn't the case as the issue is still open, but I'll defer to the NuGet Client team to respond to you there.
