### ISSUE TITLE
NETSDK error happening when adding Microsoft.Windows.SDK.Contracts in WPF App targeting net5.0-windows

### ISSUE THREAD

**Issue by ansarnisargill** [dotnet/sdk#14591]
Wpf apps targeting net5.0windows are crashing when adding Microsoft.Windows.SDK.Contracts version '10.0.19041.1' as a nuget dependency with the error message "**NETSDK1135 SupportedOSPlatformVersion 10.0.19041.0 cannot be higher than TargetPlatformVersion 7.0**" any idea for potential solution or why it is happening?

**Comment by smourier** [comment]
I had the same problem with Winforms, but here is a workaround.

My csproj was like this:
	
	<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	 ...
	  <PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net5.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
	  </PropertyGroup>
	  ...
	</Project>

One solution I found is to set this in the csproj:

    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    
Note the target Windows version appended. If you want to know what you can put here just put a bogus version like 11 and it will tell you this:

	error NETSDK1140: 11.0.0.0 is not a valid TargetPlatformVersion for Windows. Valid versions include:
	error NETSDK1140: 10.0.19041.0
	error NETSDK1140: 10.0.18362.0
	error NETSDK1140: 10.0.17763.0
	error NETSDK1140: 8.0
	error NETSDK1140: 7.0

Ok, now the build complains about 

	"warning NETSDK1137: It is no longer necessary to use the Microsoft.NET.Sdk.WindowsDesktop SDK. Consider changing the Sdk attribute of the root Project element to 'Microsoft.NET.Sdk'."
	
So, I changed to this:
	
	<Project Sdk="Microsoft.NET.Sdk">
	
No I get this (because I used an "old" Microsoft.Windows.SDK.Contracts nuget,  maybe you won't have this issue):
	
	"error NETSDK1130: Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target."
	
So I removed that nuget. Now it compiles fine. Addind a Windows version after the "windows" token in  the TargetFramework automatically  adds the WinRT projection.
