### ISSUE TITLE
Publish a .net core project with dependencies

### ISSUE THREAD

**Issue by juanan** [dotnet/sdk#14657]
Hi, 

I have a .net core 3.1 project (lets called A.proj) that has a dependency to other .net core 3.1 project (lets called B.proj).
The reference was added as a hint path

![image](https://user-images.githubusercontent.com/17723190/99962895-3b1a0180-2d91-11eb-8813-8a9fe60f0cb6.png)

The thing is that when I run "dotnet publish" over the A.proj I get the B.dll but I dont have any of the dependencies of B.dll (mostly other Nuget packages).

So can I get all the libraries from the B.proj when I publish A.proj?

Many thanks.

**Comment by juanan** [comment]
Any idea?

I would really appreciate some kind of help.

**Comment by sfoslund** [comment]
It looks like you're referencing the project's output dll instead of the project itself. If you use built in [project references](https://github.com/dotnet/msbuild/blob/main/documentation/ProjectReference-Protocol.md#projects-that-have-references) it should include its dependencies in the output. I expect this will fix your issue, but feel free to reopen if you have further questions, thanks!
