### ISSUE TITLE
global.json not enforcing SDK version

### ISSUE THREAD

**Issue by jaredpar** [dotnet/sdk#1470]
Attempting to move dotnet/roslyn to SDK 2.0. My first step was to use global.json to enforce that 2.0 was being used to prevent bad behavior when a developer accidentally build on an environment with only 1.X installed. 

I tried using global.json to achieve this by adding the following file to the root of my repo:

``` json
{
  "sdk": {
    "version": "2.0.0"
  }
}
```

I then built and everything succeeded. This is contrary to my expectations because I don't have the 2.0 SDK installed on this machine. I do have `dotnet` on the path and MSBuild 15.3 but no 2.0 build of the SDK. 

Why did this work? I really can't understand the function of global.json if it doesn't prevent this build from functioning.

**Comment by jaredpar** [comment]
CC @rainersigwald, @livarcocc

**Comment by dasMulli** [comment]
I think the error behaviour has only been added for 2.0.0+ https://github.com/dotnet/core-setup/pull/2621

**Comment by jaredpar** [comment]
Sounds like global.json is only useful then when:

- At least MSBuild 15.3 is installed
- dotnet 2.0.0 is installed

Lacking that it's just a file on disk that is ignored by the build? 

If that's the case then why does our only documentation of the file display it restricting to the 1.0.0 SDK? Doesn't seem very useful.

**Comment by jaredpar** [comment]
@dasMulli what I really want is a simple, declarative way to constrain my build to the components I need. At this point that requires constraining MSBuild, SDK and NuGet. Unfortunately there is no straight forward way to do this. Hence when customers approach our projects with the wrong versions of the tools they get cryptic errors vs. a nice declarative message like:

> Need MSBuild 15.1 to build this project 

Global.json solves only SDK for a subset of the available scenarios.

**Comment by nguerrera** [comment]
> Sounds like global.json is only useful then when:

> At least MSBuild 15.3 is installed
> dotnet 2.0.0 is installed

global.json is respected by `dotnet` all the way back to pre-1.0. What's new in 15.3 is wiring desktop msbuild to targets installed by dotnet via the resolver and the resolver looks at global.json the way that `dotnet` always did.

**Comment by nguerrera** [comment]
> Why did this work?

You would see it fail with `dotnet build`, but in the case of `msbuild` / VS, there is (unfortunately) still a copy of the SDK in `[msbuild dir]\sdks` path. When desktop `msbuild` invokes our resolver with global.json specifying 2.0.0 we return an error message saying that we could not locate that version. MSBuild, then proceeds to give the next resolver in the chain a chance and that one (the default resolver) ignores versions and finds the 1.1 copy in its own directory. If any resolver succeeds, then the errors from the earlier resolvers are suppressed.

To fix this, we'd either:

1. Need a new msbuild feature where we can force a hard-error to break the resolver change.
2. Remove the extra SDK copy from `[msbuild dir]\sdks` 

The primary reason for keeping that copy was workloads that support .NET Standard projects but do not install a `dotnet` (desktop, UWP). We are talking about how to shrink the required footprint of `dotnet` so that it can be installed in all .NET workloads, e.g. making the ASP.NET packages / runtime store optional. In that case, we could do (2), but it would break anyone using $(MSBuildSdksPath) directly instead of Import Sdk so we'd need to vet the breaking change implications.

@jaredpar , you, @dsplaisted and I had actually talked through this issue with @dsplaisted and the workaround we had established would be to add a target checking that `$(UsingMicrosoftNETSdk)` is true. That is only set by 2.0+ and 2.0+ can only be found by a resolver. So if it's false, then the problematic fallback to default 1.1 has happened.

**Comment by nguerrera** [comment]
> I think the error behaviour has only been added for 2.0.0+

Yes, that is another issue. :(

Summary:
`dotnet` < 2.0.0  -- error -> silently use latest version.
`dotnet`: >= 2.0.0 -- hard error
`msbuild`: < 15.3 -> does not read global.json, uses its own copy of the SDK
`msbuild` >= 15.3 -> error -> falls back to its own SDK.

**Comment by nguerrera** [comment]
I believe this was covered in the documentation added for https://github.com/dotnet/docs/issues/2902
