### ISSUE TITLE
.NET core 2.2 unable to run the tests with the following message Mising hostpolicy.dll

### ISSUE THREAD

**Issue by d-saravanan** [dotnet/sdk#1476]
Not able to run dotnet test due to the missing hostpolicy.dll file

Testhost process exited with error: A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'G:\DS\Security\test\Microsoft.AspNetCore.Authentication.Test\bin\Debug\netstandard2.0\'.

I have tried inside visual studio using Debug Tests, but nothing succeeds. When tried to use dotnet xunit, it says command not found. How are developers meant to run tests in this version?

**Comment by livarcocc** [comment]
Can you share repro steps or a repro project? This is happening because your test project is a library (netstandard2.0) instead of an app (netcoreapp2.0).

Changing your project's TFM should fix this. Another alternative is running `dotnet new mstest` or `dotnet new xunit` and seeing what is the project format in those cases and comparing to yours.

If this does not solve your problem, please comment and we can re-activate the issue.

**Comment by nohwnd** [comment]
A similar issue was solved recently in VSTest. Linking for visibility https://github.com/microsoft/vstest/issues/2427
