### ISSUE TITLE
Build of web project fails with .NET Core 2.0 preview 2 / VS 2017 (15.3.0 Preview 7.0)

### ISSUE THREAD

**Issue by markusschaber** [dotnet/sdk#1478]
We have a project which successfully builds with VS 2017 (15.2) and target framework .NetCoreApp 1.1.

When trying to build it with .NET Core 2.0 preview 2 or VS 2017 (15.3.0 preview 7.0), we get the following build error:
`C:\Program Files (x86)\dotnet\sdk\2.0.0-preview2-006497\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.DefaultItems.targets(285,5): error : Duplicate 'Content' items were included.
 The .NET SDK includes 'Content' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'wwwroot\swagger\custom.css'; 'wwwroot\swagger\index.html' [D:\AutomationServer\Source\DotNetCore\AutomationServer\AutomationServer\AutomationServer.csproj]`

No changes were made to the project or solution files, so I'd expect it to build fine.

Additional information: The project contains an explicit ItemGroup for the two files:
`
  <ItemGroup>
    <Content Include="wwwroot\swagger\custom.css" />
    <Content Include="wwwroot\swagger\index.html" />
  </ItemGroup>`

**Comment by markusschaber** [comment]
Attached the project file in question...
[AutomationServer.csproj.txt](https://github.com/dotnet/sdk/files/1205400/AutomationServer.csproj.txt)

**Comment by geomorillo** [comment]
i have this error with 1.1 cant compile im sure i dont have any duplicates

**Comment by livarcocc** [comment]
This happens because of these entries in your csproj:
```
<Content Include="wwwroot\swagger\custom.css" />
    <Content Include="wwwroot\swagger\index.html" />
```
The Web SDK already includes the contents of the wwwroot folder and that's why you are getting the duplicate content error message above. It should be safe for you to remove those entries completely.

I don't re-call if there were changes made to the Web SDK between the 1.0 time frame and the 2.0 time frame that involved the implicit contents or not. cc @vijayrkn in case he remembers something.

If this does not solve your problem, please, comment and we can re-activate the issue.

**Comment by vijayrkn** [comment]
The content globs were added before 1.0
