### ISSUE TITLE
VB.NET WinForms template vastly different from Visual Studio

### ISSUE THREAD

**Issue by adegeo** [dotnet/sdk#14937]
The `dotnet` template is missing the VB app framework and is also missing this critical project setting:

```xml
<PropertyGroup>
  ...
  <MyType>WindowsForms</MyType>
</PropertyGroup>
```

### File structure of each template

**dotnet template**

```
C:\code\Work\vbdotnet> dir -r | select fullname

FullName
--------
C:\code\Work\vbdotnet\Form1.Designer.vb
C:\code\Work\vbdotnet\Form1.vb
C:\code\Work\vbdotnet\Program.vb
C:\code\Work\vbdotnet\vbtest.vbproj
C:\code\Work\vbdotnet\vbtest.vbproj.user
```

**Visual Studio template**

```
C:\code\Work\vbvisualstudio> dir -r | select fullname

FullName
--------
C:\code\Work\vbvisualstudio\ApplicationEvents.vb
C:\code\Work\vbvisualstudio\Form1.Designer.vb
C:\code\Work\vbvisualstudio\Form1.resx
C:\code\Work\vbvisualstudio\Form1.vb
C:\code\Work\vbvisualstudio\WinFormsApp1.vbproj
C:\code\Work\vbvisualstudio\WinFormsApp1.vbproj.user
C:\code\Work\vbvisualstudio\My Project\app.manifest
C:\code\Work\vbvisualstudio\My Project\Application.Designer.HighDpi.vb
C:\code\Work\vbvisualstudio\My Project\Application.Designer.vb
C:\code\Work\vbvisualstudio\My Project\Application.myapp
```

**Comment by dsplaisted** [comment]
@KathleenDollard @merriemcgaw Is this expected?

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann can you check on this?

**Comment by KlausLoeffelmann** [comment]
I just tested it. It's working fine for me. Please note, that we don't support the Application Framework for .NET Core 3.1 Apps, since the required infrastructure is only present from .NET 5.0 on. So, if creating a new VB 3.1 VB App, it pretty much looks structured like C#. That is by design.

On top of that, at the command line, we can also have C# structured VB apps in .NET 5. The application framework needs to be dedicatedly enabled:

```
dotnet new winforms --language VB --framework:net5.0 --use-app-framework
```

Hope this helps!
