### ISSUE TITLE
For a non-admin (CI machine or local location), install an optional workload

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/sdk#14954]
- [ ] Need detection on whether the install is going to be admin vs. Non-admin 
- [ ] Read manifest to know the version and package id for missing workload 
- [ ] Run a restore with required workload 
- [ ] Read the asset.json for the restored workload files (half done by global tools) 
- [ ] Know where to move it by convention or manifest. 
- [ ] move it to the right place in transactional manner (done by global tools) 
- [ ] A command to detect if a workload is installed already (required by VSMac installer)
- [ ] A command to print out packages URL without installing them
  - [ ] an option should be available to print URL of highest SDK's manifest's workloads, even though this version of SDK may not support it
- [ ] A command To install previously cached download packages

**Comment by wli3** [comment]
@dsplaisted @KathleenDollard I added a line "A command to detect if a workload is installed already (required by VSMac installer)". VS for mac installer need to check if a component exists. Something like _dotnet workload exist android_. And note, the return need to be machine readable.
![image](https://user-images.githubusercontent.com/6993335/102674092-913c5380-4149-11eb-8682-399d7115b3ea.png)

**Comment by wli3** [comment]
> A command to download packages without installing them
>  an option should be available to download highest SDK's manifest's workloads, even though this version of SDK may not support it
>  A command To install previously cached download packages

This is a scenario required by VSMac updater. While the user is using VSMac, the updater could download packages in the background. And then later prompts the user to install them in bulk. .NET SDK need to fit in this case. When there is a new SDK available("suggest to update" every 4 month, "have to update" every year), the current SDK may not be able to work with the latest workload, but it should be able to download them. So that, during the install process, the new SDK (download by VSMac), will be installed first. The downloaded workload will be installed later. The install process do not need to hit the internet. There is a chance the older SDK cannot even process the higher version SDK's manifest. At this point we would do a best effort. We expect the manifest would be stable after the first year.

**Comment by wli3** [comment]
Prefer https://github.com/dotnet/sdk/issues/16483
