### ISSUE TITLE
Use Task.run execute method error

### ISSUE THREAD

**Issue by beetlex-io** [dotnet/sdk#15146]
Create console program executes the following code
``` csharp
    class Program
    {
        static User user = new User();

        static void Main(string[] args)
        {
            for (int i = 0; i < 50; i++)
            {
               Task.Run(() => user.Init());
            }
            System.Threading.Thread.Sleep(-1);
        }
    }

    public class User
    {

        private bool mIsInit = false;

        private void OnInit()
        {
            Console.WriteLine("User init");
            System.Threading.Thread.Sleep(1000);
        }
        public void Init()
        {
            lock (this)
            {
                if (mIsInit)
                    return;
                var task = Task.Run(() => this.OnInit());
                if (!task.Wait(1000 * 5))
                {
                    throw new TimeoutException("user init error!");
                }
                mIsInit = true;
            }
        }
    }
```
In debug mode program throw timeout exception

![image](https://user-images.githubusercontent.com/2564178/103440782-8b835980-4c83-11eb-86fe-c50e3e4e904f.png)

In release mode the `user.OnInit` method is called multiple times

![image](https://user-images.githubusercontent.com/2564178/103440852-f3d23b00-4c83-11eb-8994-fd44d894e5fa.png)

Test runtime .netcore 3.1 and  .net5

**Comment by beetlex-io** [comment]
This problem is thread pool has a minimum number of threads available at all times.

**Comment by zsybupt** [comment]
@beetlex-io I come here from your blog post, it is true there is no enough threads and cause timeout:
> In debug mode program throw timeout exception
> 
> ![image](https://user-images.githubusercontent.com/2564178/103440782-8b835980-4c83-11eb-86fe-c50e3e4e904f.png)
> 
This is because Task.Run will default queue work items into local queue of current thread, and Task.wait(timeout) blocks current thread. So if CLR can not create new threads quickly to steal OnInit work item from current thread local queue, it will cause timeout because there is a deadlock wait.
And If you use Task.Wait() instead of Task.Wait(timeout) in this case, no timeout will occur and all tasks finish quickly, because there is an optimization of [infinite wait](https://devblogs.microsoft.com/pfxteam/task-wait-and-inlining/), it will try to inline execute the task, so OnInit will be executed inline and no wait time increase to cause timeout.
> In release mode the `user.OnInit` method is called multiple times
> 
> ![image](https://user-images.githubusercontent.com/2564178/103440852-f3d23b00-4c83-11eb-8994-fd44d894e5fa.png)
> 
Actually, it throws TimeoutException also in Release mode, but because it runs background and does not interrupt the program (you can add Console.Writeline before throw statement to check this). So the first thread queues the OnInit to its local queue, then timeout and release the lock, another thread enter the lock section and mInit is false, so it queues another OnInit to its local queue and multiple OnInit is called, but mInit is always false (because TimeoutException throwed, no chance to set mInit to true), and after CLR create enough threads, when next thread  queues OnInit to its local queue and wait for timeout, this time there are available threads to steal the OnInit work item and finish it quickly, so there is no TimeoutException and mInit is true. This is why that you can see OnInit is executed several times at the beginning and recover to normal afterwards.
