### ISSUE TITLE
_CollectTargetFrameworkForTelemetry is taking 8% of a targets run time

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1535]
_CollectTargetFrameworkForTelemetry is adding 8% of total targets run time. This is way too high for a target/task that is just reporting telemetry.

See: https://github.com/dotnet/sdk/issues/1534.

**Comment by rainersigwald** [comment]
This is with a command-line build with msbuild.exe?

Target is trivial:

https://github.com/dotnet/sdk/blob/6274bb6a1e07c0e255fd1042cc47367f41dc8541/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.TargetFrameworkInference.targets#L105-L107

The `Telemetry` task should do nothing if no telemetry sink is defined. Would love to see a profile of the actual elapsed time inside it here.

Possibly not POGOed for this case because the training runs don't include a Telemetry run?

@jeffkl will probably be interested when he's back.

**Comment by davkean** [comment]
I'm having a real hard time seeing where most of the cost is coming from - I'm seeing extraordinarily large amounts of MSBuild's total CPU time (50%) being consumed by JITing - but unsure yet how to actually figure out what impact that actually has on run time. We get zero node reuse because it's a single project - wish MSBuild's node model included a server a la C#/VB that MSBuild entry point would just farm command-line args to to avoid this startup cost.

**Comment by jeffkl** [comment]
The telemetry task still does some work to send the event but if no listener is attached then the event goes nowhere.

**Comment by nguerrera** [comment]
@davkean Can you confirm this was with desktop msbuild.exe and not dotnet build. If so, I'll move to msbuild repo since our target is trivial and there would be no actual telemetry sent without a the CLI wiring up the listener.

**Comment by davkean** [comment]
This was MSBuild.

**Comment by nguerrera** [comment]
This issue was moved to Microsoft/msbuild#2487
