### ISSUE TITLE
Global Tool Update help script is not accurate

### ISSUE THREAD

**Issue by csharpfritz** [dotnet/sdk#15381]
`dotnet tool update --help` reports:

```cli
Usage: dotnet tool update [options] <PACKAGE_ID>

Arguments:
  <PACKAGE_ID>   The NuGet Package Id of the tool to update.
```

The argument for update is expecting not the NuGet package id, but rather the command name.

Instead of:

`dotnet tool update Microsoft.EntityFrameworkCore.Tools`

we should execute

`dotnet tool update dotnet-ef`

Recommendation:  change 

`<PACKAGE-ID>The NuGet Package Id of the tool to update` 

to 

`<COMMAND>  The dotnet command-name to update`

**Comment by dsplaisted** [comment]
@wli3 Can you look at this?  If it's accurate that the help text is wrong, it should be a quick fix.

**Comment by wli3** [comment]
It **is** the package ID. https://github.com/dotnet/sdk/blob/master/src/Cli/dotnet/commands/dotnet-tool/update/ToolUpdateGlobalOrToolPathCommand.cs#L51

I think the issue is, _Microsoft.EntityFrameworkCore.Tools_ is not a dotnet tool, while dotnet-ef(https://www.nuget.org/packages/dotnet-ef/) is both a package id and he command
