### ISSUE TITLE
Long bin paths even for single output type

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1547]
_From @davidmatson on August 28, 2017 20:44_

Compared to old-style .NET Framework csproj, bin output paths are more involved/nested than they used to be. For example, the default used to be just
bin\Debug
bin\Release

(folders per configuration only.)

For secondary platforms, they'd add one more level, such as:
bin\x64\Debug
bin\x86\Debug
bin\x64\Release
bin\x86\Release

With AnyCPU staying in the higher-level directory.

This organization was simple and nice.

With this csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
  </PropertyGroup>
</Project>
```

There's a minimum extra level of nesting:
bin\Debug\net47

And with this one:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
```

it gets even worse:
bin\Debug\net47\win-x64

In both cases, there's just one value in use (it's a single TargetFramework, not multiple TargetFramework**s** and a single RuntimeIdentifier, not multiple RuntimeIdentifier**s**). For these cases, could the extra levels of bin subdirectory nesting be removed?

Edit: I've been getting confused between Platform & Platform**s**. It gets even worse when using that property:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net47</TargetFramework>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
```
bin\x64\Debug\net47\win-x64
Yikes!

_Copied from original issue: dotnet/project-system#2749_

**Comment by livarcocc** [comment]
You can turn off appending the TFM to the path by setting AppendTargetFrameworkToOutputPath to false.

Similarly, you can turn off appending the RID to the path by setting AppendRuntimeIdentifierToOutputPath to the path.

I don't believe not setting these for single TFM projects is the right approach, because then folks will have to build this logic in their scripts/tests if they are figuring out the output paths for their projects.

Also, this would be a breaking change now, that we would only do in the 3.0 timeframe.

If this does not address your questions, just comment and we can re-activate this issue.

**Comment by davidmatson** [comment]
For 3.0, could we make the default of both Append* false if there's a single TFM and RI? That gets us back to path length parity with full .NET Framework for the simple case.

**Comment by tannergooding** [comment]
> For 3.0, could we make the default of both Append* false if there's a single TFM and RI

I don't believe so. That would be considered a breaking change for existing SDK consumers and would disrupt anyone dependent on the existing behavior.
