### ISSUE TITLE
TargetPlatformAttribute & SupportedOSPlatformAttribute while Multi-Targeting

### ISSUE THREAD

**Issue by knoopr** [dotnet/sdk#15596]
When generating a project targeting framework and net5.0-<platform> the automatically generated attributes `TargetPlatformAttribute` and `SupportedOSPlatformAttribute` are not for framework such that `<GenerateAssemblyInfo>true</GenerateAssemblyInfo>` can't be used.

A flag such as #14836 or another alternative while multi-targeting such that the other aspects of the automatically generated assembly info could be used would be nice.

**Comment by dsplaisted** [comment]
Hi @knoopr,

Could you provide more details about how these automatically generated attributes are causing problems?  A repro project or a [binlog](https://aka.ms/binlog) would be helpful.

**Comment by MrMikeJJ** [comment]
Hi @dsplaisted 
I have the same issue (found the defect with google). 
Since you haven't had any response from @knoopr , i can hopefully provide details of how the automatically generated attributes are causing problems.

In a Sdk style csproj file, i have targetframeworks set to 
`<TargetFrameworks>net48;net6.0-windows</TargetFrameworks>`

Which then results in the following error at compile time, in the generated AssemblyInfo.cs
![image](https://user-images.githubusercontent.com/5191401/187884600-db5e70a6-0f10-48d4-b167-35ecd81aca99.png)

![image](https://user-images.githubusercontent.com/5191401/187884659-618ec79e-129d-414c-85e7-a5ca5785d706.png)

I hope that helps
thanks
Mike

**Comment by knoopr** [comment]
Hi @dsplaisted,

Sorry I didn't get a notification via GH for your mention. The note that @MrMikeJJ was essentially the issues that it was causing for me. 

Rick

**Comment by dsplaisted** [comment]
Could one of you share a repro and/or a binlog?  I tried building a simple library project targeting `net48;net6.0-windows` and I don't get this error.  There should be a separate SupportedPlatformAttributes.AssemblyInfo.cs file generated for each target framework, and the `net48` one shouldn't have those attributes.

Are you overriding the output / intermediate paths?  If both target frameworks are trying to use the same intermediate output path then this could happen depending on the timing of the build.

**Comment by MrMikeJJ** [comment]
Hi @dsplaisted ,
> Are you overriding the output / intermediate paths?
After i updated this issue, i noticed that there was a setting in Directory.Build.Props which may have had this effect. 
AppendTargetFrameworkToOutputPath was set to true, which i removed when i saw it.

I will re-enable <GenerateAssemblyInfo> tomorrow to check and update this issue. 
(If this doesn't work, i'll create a repo & binlog, but from what you said, it probably was that setting)

thanks
Mike

**Comment by MrMikeJJ** [comment]
@dsplaisted - i can confirm that removing the line which set AppendTargetFrameworkToOutputPath to false resolved this issue for me,
@knoopr - it is worth checking your .csproj files and any Directory.Build.Props or Directory.Build.Targets for lines which manipulate the "bin" and"obj" directories.

thank you :)
Mike

**Comment by dsplaisted** [comment]
Great, glad we were able to figure this out!

**Comment by knoopr** [comment]
@MrMikeJJ Glad it worked! I left that position in late 2022 and don't multi target anymore so can't give it a go but trust it works
