### ISSUE TITLE
Possibility for chaining style API?

### ISSUE THREAD

**Issue by Thaina** [dotnet/sdk#1601]
After learning about faunadb API for sometimes I felt unfamiliar with the style of API

Such as

```C#
client.Query(
  Paginate(Match(Index("spells_by_element"), "fire")));
```

```C#
client.Query(
  Do(
    Create(
      Ref(Class("magical_creatures"), 1),
      Obj("data", Obj("name", "Hen Wen"))),
    Get(Ref(Class("magical_creatures"), 1))));
```

I felt that some functions that require expression should be extension method. And so we could like it like this

```C#
client.Query(Index("spells_by_element").Match("fire").Paginate());
```

```C#
client.Query(Do(Class("magical_creatures").Ref(1).Create(Obj("data", Obj("name", "Hen Wen")))
     ,Class("magical_creatures").Ref(1).Get()));

/// or

client.Query(Class("magical_creatures").Ref(1).Create(Obj("data", Obj("name", "Hen Wen")))
    .Then(Class("magical_creatures").Ref(1).Get()));
```

Could we have some this like a sub namespace for this style api? (FaunaFB.LINQ maybe?)

**Comment by livarcocc** [comment]
I am not sure what are these APIs that you are referring to, however, they are not produced at this repo. This repo contains MSBuild props/targets required to be able to build dotnet core projects.
However, because I don't know about these APIs, I can't redirect it either.

If they are in the framework, I would suggest dotnet/corefx. If they are entity framework APIs, I would suggest aspnet/entityframework.

**Comment by Thaina** [comment]
@livarcocc Oh sorry I post on the wrong repo thanks
