### ISSUE TITLE
.NET 6: The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found

### ISSUE THREAD

**Issue by dustinmoris** [dotnet/sdk#16427]
I have the .NET 6 SDK installed on my Apple M1 laptop.

I have `<TargetFramework>net5.0</TargetFramework>` projects which I can successfully restore (`dotnet restore`) and successfully build (`dotnet build`) without any errors or warnings, but when I run `dotnet run` I get the following error on my ASP.NET 5 project:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.
  - The following frameworks were found:
      6.0.0-preview.1.21103.6 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
      6.0.0-preview.2.21154.6 at [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0&arch=arm64&rid=osx.11.0-arm64
```

The URL in the error message doesn't work and redirects me to the default .NET download page:

```
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0&arch=arm64&rid=osx.11.0-arm64
```

When I change my `TargetFramework` to `6.0` then I can run my app, but I don't want to upgrade yet. I just want to develop on my new laptop and also it's illogical to me that I can build the binaries but then not run them when targeting .NET 5.

**Comment by vigu184** [comment]
Did you check the .NET runtime you have? I think it requires different a ASP.NET 5 runtime. 
According to this line:
The framework 'Microsoft.AspNetCore.App', version '5.0.0' was not found.

What does dotnet --info show?

**Comment by dustinmoris** [comment]
> Did you check the .NET runtime you have? I think it requires different a ASP.NET 5 runtime.

I didn't check because as I said I have .NET 6 SDK installed and nothing else since no other SDK + runtime has native M1 support yet.

Why can .NET 6 not run an ASP.NET Core 5 project on the .NET 6 runtime though? That can't be normal?

**Comment by dasMulli** [comment]
Can you try setting

```xml
<PropertyGroup>
  <RollForward>Major</RollForward>
</PropertyGroup>
```

in the csproj so the emitted runtimeconfig.json tells the host to execute the 5.* app on a 6.* framework? Major version roll-forward currently requires explicit opt in.

**Comment by dasMulli** [comment]
> also it's illogical to me that I can build the binaries but then not run them when targeting .NET 5.

In order to build the app, the SDK "only" needs to resolve and download the targeting packs necessary for the compilation via NuGet. Running apps is a different story. I suppose this will also be used to build (libraries) for net6.0-ios on windows machines but you won't be able to run anything.

**Comment by dustinmoris** [comment]
> Can you try setting
> 
> ```
> <PropertyGroup>
>   <RollForward>Major</RollForward>
> </PropertyGroup>
> ```
> 
> in the csproj so the emitted runtimeconfig.json tells the host to execute the 5.* app on a 6.* framework? Major version roll-forward currently requires explicit opt in.

This works!

So I understand that .NET is not self contained and I need to have the correct runtime installed, but what I don't understand is why my web project has a hard dependency on the ASP.NET 5 runtime. I have not specified that anywhere therefore I'd expect the roll forward to happen automatically. It's not like I've put `<MustUseRuntime>5.0</...>` somewhere. I have only specified `<TargetFramework>5.0</TargetFramework>` which to me sounds like specifying which assemblies to load into my app, but the final project can still be executed on the 6.0 runtime with the 5.0 assemblies loaded. Maybe I misunderstand something.

To be honest I don't even want to specify `<TargetFramework>5.0</...>`. Ideally it should always use the latest installed unless I explicitly specify it otherwise. It's really annoying that when I want to upgrade framework I cannot not just upgrade my Docker image but have to edit each project file manually as well.

**Comment by dasMulli** [comment]
>but the final project can still be executed on the 6.0 runtime with the 5.0 assemblies loaded

This might have worked with the 1.* versions.

I like to explain it like this: You are always targeting a runtime + version (excluding runtime specifics for a moment). However, there are actually multiple runtimes and you usually target only one of them. Until 3.* you could even only target one of them.
The runtime in your case is actually ASP.NET Core. For the App, it requests `Microsoft.AspNetCore.App` version `5.0.0` as a runtime. This is what the muxer looks for (and fails to find) on your local machine.

In theory, `Microsoft.AspNetCore.App` could ship with all dependencies needed to run a .NET App but in practice it internally depends on `Microsoft.NETCore.App` - but the host doesn't know that until it reads `/usr/local/shared/dotnet/shared/Microsoft.AspNetCore.App/5.0.4/Microsoft.AspNetCore.App.runtimeconfig.json` for example which tells it to also load the other framework. (you could try copying one over from an x86 installation and change the file to reference a 6.0.0 framework just for fun, no guarantees)

In 3.* onwards you can also target multiple runtimes, e.g. `Microsoft.AspNetCore.App` and `Microsoft.WindowsDesktop.App`.

For 6.0 I guess this hidden complexity is going to get more interesting as there are new frameworks like `Microsoft.iOS` and `Microsoft.Android`. These may or may not depend on `Microsoft.NETCore.App` and contain Mono bits instead of CoreCLR. (I have no idea as of yet, but just want to show the possibilities of this system).

**Comment by marcpopMSFT** [comment]
I think dasMulli has more or less covered things here. The SDK will let you target any runtime and by default that application will try to run on that runtime. You can enable [single file](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file) which wouldn't require the runtime to be installed as we should download the runtime pack from nuget during build.  That won't work for you as you are using apple M1 which support is in net6.0 so you need to use the rollforward option as he suggested. We don't automatically rollforward as customers wanted more predictability (as if that were the default, the moment you event installed a new runtime the application would roll forward even if the target  runtime were present).

**Comment by dustinmoris** [comment]
Why is it called `<TargetFramework>` and not `<TargetRuntime>` then? I think that is where my confusion comes. I am *NOT* targeting a specific runtime, unless that is literally what `TargetFramework` means?

**Comment by dasMulli** [comment]
I'd say this is mostly historic. "target framework" previously meant ".NET Framework", ".NET Client Profile", "Portable Class Library" (which then also need a TargetFrameworkProfile). And it's the most important one in determining "what" your project is.

Most english words that sort of mean "things you run on" already have an assigned meaning - framework, runtime, platform. I remember @DamianEdwards complaining about that years ago on a community standup..
There aren't may more names I guess. And with .NET 5 & 6 we're sseing more things just get into the TFM to make things simpler (e.g. `net5.0-ios`) instead of adding new names.

I guess .NET will be complete once all naming issues have been solved 🙃 Personally(!) I favor the options and possibilities allowed by this flexible system, knowing that it's nearly impossible to find proper names for things that people will agree upon.

**Comment by Dave9404** [comment]
<PropertyGroup>
  <RollForward>Major</RollForward>
</PropertyGroup>

It didn't wor for me, i solve this by downloading and installing dotnet sdk 5.0(in windows for me)...here:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-5.0.404-windows-x64-installer

**Comment by nagthgr8** [comment]
I have .NET 5 on the PC where I am working but I want to run the distributable which is built on .NET 5. Why can't I run .NET 5 on .NET 6 environment instead?
