### ISSUE TITLE
Repeating the build without changing the code cause few projects to rebuild

### ISSUE THREAD

**Issue by jaydeept** [dotnet/sdk#1646]
I have almost 22 projects in my solution based on .Net Core 2. When I repeat the build without changing the code, cause 19 projects to rebuild and only 3 are recognized as up-to-date. I believe, the second build should say 22 up-to-date.
Do I need to modify anything in `csproj` file to fix this issue?
JFYI: I have `postsharp`Nuget package installed in few projects but I don't think that will be causing this issue.

**Comment by livarcocc** [comment]
We had some issues with incremental checks that have since been addressed. I tried this out with a small two project solution and projects are showing as up-to-date as expected.

If this is still an issue for you, please, comment and give us some more details on how to repro this and we can re-activate.

Also notice, like you mentioned above, that some package references, or open package references (* version) may impact the incrementality check.
