### ISSUE TITLE
Add diagnostic message when trimming WinForms/WPF for .NET 6

### ISSUE THREAD

**Issue by agocke** [dotnet/sdk#16716]
This is certainly necessary for WinForms, it may also be necessary for WPF if it also uses COM.

We have determined that COM is not trim-safe and that WinForms requires it to function. Since the current plan of record is to add a COM feature switch and disable it by default when trimming, WinForms should have an error of the form:

> WinForms requires COM, which is not trim safe. COM is disabled by default when trimming. To enable COM and proceed with trimming, \<language around setting feature flag>. This configuration is not recommended."

 
For WPF, if it does not require COM, we should at least provide a top-level warning that WPF is not trim-safe for .NET 6 and is not recommended.

**Comment by AaronRobinsonMSFT** [comment]
>We have determined that COM is not trim-safe and that WinForms requires it to function.

@agocke Have we captured the list of concerns for this in a design doc or another issue? Recording this will help with future costing.

**Comment by agocke** [comment]
https://github.com/dotnet/runtime/issues/36659 tracks adding the feature flag. I agree that when we add the feature flag we should note that it's disabled by default in trimming because it's not trim safe, then describe why, and the proposed path forward for existing COM uses.

fyi @LakshanF

**Comment by vitek-karas** [comment]
I don't think we should talk about COM as being the only reason - there are other issues with WinForms.
I would work the message in general terms "WinForms is not compatible with trimming".

We should have a property which if used will override the message, something like "I Want WinForms Trimmed Anyway". If set I think it would make sense to also revert some of the default feature switches to ON, so that we don't break WinForms on-purpose. The COM feature switch is the obvious first choice.

**Comment by agocke** [comment]
Closed by #16892
