### ISSUE TITLE
ILLinkTasksAssembly is empty blocking C++/CLI 

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#16725]
"C:\work\NETCoreCppCliTest\NETCoreCppCliTest.sln" (Restore target) (1) ->
"C:\work\NETCoreCppCliTest\NETCoreCppCliTest\NETCoreCppCliTest.vcxproj" (_IsProjectRestoreSupported target) (2) ->
  C:\Program Files\dotnet\sdk\6.0.100-preview.4.21203.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(107,32): error MSB4022: The result "" of evaluating the value "$(ILLinkTasksAssem
bly)" of the "AssemblyFile" attribute in element <UsingTask> is not valid. [C:\work\NETCoreCppCliTest\NETCoreCppCliTest\NETCoreCppCliTest.vcxproj]

**Comment by wli3** [comment]
ILLinkTasksAssembly is in `Sdks\Microsoft.NET.ILLink.Tasks\Sdk\Sdk.props`

However, C++/CLI does not import this prop. See https://microsoft-my.sharepoint.com/:u:/p/wul/EWQCrYfAxd1KjBTyvGjF4MUBck444kEkh6iT0f808jBSZg?e=XKQd6q for binlog

How to test c++/CLI 

@sbomer please resolve this ASAP it is blocking

**Comment by wli3** [comment]
All the properties on the prop are problematic

**Comment by sbomer** [comment]
This looks like fallout from https://github.com/dotnet/sdk/pull/15801 which no longer imports the linker props from Microsoft.NET.ILLink.targets (instead they get imported by Microsoft.NET.ILLink.props). The problem is that the C++/CLI scenario imports the .NET SDK targets but not the .NET SDK props (which would pull in ILLink.props). It happens here in Microsoft.CppCommon.targets:

```xml
  <Import Sdk="Microsoft.NET.Sdk" Project="$(MicrosoftNETSdkAfterCommonTargets)"  Condition="'$(CLRSupport)' == 'NetCore'  and '$(ImportNETCoreSdkFromVCTargets)' != 'false'"/>
```

I assume the easiest fix would be to condition the ILLink.targets import on something like `CLRSupport` or `Language`, unless there is a better fix based on the layering of the targets (since I don't understand why C++/CLI imports the .NET targets but not props). What do you think @wli3?

/cc @ViktorHofer

**Comment by wli3** [comment]
I prefer condition on `Language` is `c++`, we did that for many places. C++ publish is blocked already so that should be fine.
