### ISSUE TITLE
How to config *.runtimeconfig.json file, to let the .net standard program work fine with multiple versions SDKs.

### ISSUE THREAD

**Issue by JoeLiu2015** [dotnet/sdk#1697]
I build a .net standard runnable program. The generated *.runtimeconfig.json file looks like follows:{
    "runtimeOptions": {
      "framework": {
        "name": "Microsoft.NETCore.App",
        "version": "1.0.4"
      }
    }
  }
It works fine with runtime 1.0.4. However, it couldn't work with runtime 2.0.0. If I modify above version "1.0.4" to "2.0.0", the issue is solved.

The question is how to config the file *.runtimeconfig.json, to let it work fine with any SDK version.

**Comment by livarcocc** [comment]
In order to do this, you need to Multi-target. Meaning, using the `<TargetFrameworks>` tag in your csproj and having netcoreapp1.0 and netcoreapp2.0 and values in there. Note that if you do this you will end up with two versions of your app. One for each TargetFramework you are targeting.

The runtime does not make any roll-forward compatibility in minor and major versions, which is why this does not work.

If it were a patch version difference, say, you target 1.0.0 and you have 1.0.4 installed, you will get automatically rolled forward, and we make servicing guarantees in that regard.
