### ISSUE TITLE
ResolvePackageDependencies is producing 6.5% of allocations in a build

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1711]
In a customer solution I'm looking at, I see that ResolvePackageDependencies is producing 6.5% of all allocations for an up-to-date build:

![image](https://user-images.githubusercontent.com/1103906/32355033-a01b264e-c080-11e7-8f3b-a29ddef61cdd.png)

Can we see if we can trim/remove unneeded allocations from this task.

**Comment by nguerrera** [comment]
Working on this.

**Comment by davkean** [comment]
👍

**Comment by nguerrera** [comment]
#2020 should bring this down to a bare minimum for the incremental (normal) build case. We now deserialize into ITaskItem[] with near zero waste when project.assets.json. However, I'm leaving this open after this goes in because we still use the old ResolvePackageDependencies for the dependencies node in the IDE. I will be working with project system folks to get that fixed next.

**Comment by nguerrera** [comment]
cc @abpiskunov @Pilchie

**Comment by nguerrera** [comment]
Fixed by #2020. Will use a separate issue for design-time build case.

**Comment by nguerrera** [comment]
#2100 tracks design-time build case now.
