### ISSUE TITLE
Update URL for dotnet-core-preview

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/sdk#17128]
When creating a project with a preview SDK, the following message is printed:
```
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
```

Given that we're no longer branding as ".NET Core", we should update that URL.

**Comment by marcpopMSFT** [comment]
@richlander You own that aka.ms link.  A) it takes me too the global.json documentation which doesn't seem right and b) did you want to create a dotnet-preview link for us to place in the code?

**Comment by richlander** [comment]
Great topic. I don't actually know where this should go. I think the intention is that it takes you to a doc that explains how to configure your environment to either use the preview or not. Is that fair? If not, we should just remove the link entirely.

For fairness, I've never liked the warning at all. I think it has low value.

**Comment by KathleenDollard** [comment]
@tdykstra @mairaw 

Can you help us with this? Do we already have a page on previews?

**Comment by richlander** [comment]
It would be good if we had a page on previews. I'm still wondering what our guidance would be that would be so important to have this warning.

**Comment by joeloff** [comment]
Off the top of my head... previews usually don't have go-live licenses, it's unsupported (e.g. no updates through MU), can have breaking API changes, needs additional settings to work with Visual Studio.

People sometimes forgot they installed a preview, especially if everything builds and works. It's good to have a reminder before you publish and distribute an application that depends on an unsupported release of .NET.

**Comment by richlander** [comment]
> People sometimes forgot they installed a preview, especially if everything builds and works. It's good to have a reminder before you publish and distribute an application that depends on an unsupported release of .NET.

This is true, but you can say almost all those same things about a stale copy of .NET Core 3.1. Also, if you use .NET 6 to publish a .NET 5 app, it is supported. The previews that people are likely to install are the RCs and they are supported.

> can have breaking API changes

I don't think we need a warning for that.

I'm not pushing back on having an article. My main point is that the situation is pretty nuanced. How about this. Let's rank order the concerns that people should have in using a preview. It would also be good to call out ones that would apply to using stale serviced GA bits (we may eventually offer a similar warning for that scenario) and that are Visual Studio specific. Fair?

**Comment by joeloff** [comment]
Agree. We already have checks in the SDK that would surface warnings if you are targeting something that's out of support, e.g. 2.0

Perhaps we should see if there was an issue that prompted adding this message in the first place?

**Comment by richlander** [comment]
I didn't know that. I rarely if ever target EOL versions. The difference in treatment between the two experiences is interesting, particularly how they compose together.

![image](https://user-images.githubusercontent.com/2608468/117339701-e48f1400-ae54-11eb-9346-adaab2aca5e6.png)

I was focused more on a potential warning for 6.0.1 after 6.0.2 goes out and same for the SDK.

If all of these experiences were actual warnings, people would manage them more easily. I've always wanted to disable the existing preview warning message. I cannot because it's not a real warning. Maybe that's a good test for this. If we're not willing to make it a real warning, we should remove it.

**Comment by tdykstra** [comment]
To answer Kathleen's question, we don't already have a page on previews. If we make it a real warning we'll have a good place to put such a page, with the other NETSDK error messages, such as https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1004

**Comment by terrajobst** [comment]
I agree with Rich, the warnings for SDK previews seem of low value to me. Also, the SDK is something that the developer of the machine controls which is different from the what the projects themselves are targeting because build can transparently acquire targeting packs.

Scenarios:

1. I install a support version of the .NET SDK (say, .NET 5 today). I then git clone some repo that happens to target .NET Core 3.0. I get a warning that .NET Core 3.0 is out of support that makes sense.
2. I install a preview version of .NET 6.0 SDK. I built my .NET 5 app. I get multiple warnings (one per project) that I'm using a preview version of the .NET SDK. Duh, I downloaded that one for a reason. This doesn't make sense to me.

**Comment by richlander** [comment]
@KathleenDollard -- this is really up to you. What's the customer guidance we need to communicate that is specific to previews? That's unclear to me.

If we cannot define this, we should remove the warning.

**Comment by baronfel** [comment]
Did some digging: https://github.com/dotnet/sdk/pull/1971 is the PR that added this message, almost 4 years ago. There's no linked issue, so we don't really have insight into why it was added initially. As far as having a page on previews, the link shown in @richlander's example (for the .NET support policy) does have a section on previews explicitly that I think does a good job covering the situation, and that can be found here: https://dotnet.microsoft.com/platform/support/policy/dotnet-core.  

This page lists explicit support timelines for previews with a go-live license.  I think we should:
* create a specific SDK warning for out of support previews, like we have already for out of support runtimes
* add a new target for warning when an out of support SDK preview is used, [like we have for runtimes](https://github.dev/dotnet/sdk/blob/d485e4593404ec6e5d79e44c484bcbef3e5d65ea/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.EolTargetFrameworks.targets#L1-L31), that encodes the data on this page. We should generally know this data ahead of time, though there is some danger of the embedded time spans going stale.

**Comment by baronfel** [comment]
Two units of work here:
* create a new aka.ms link with a better name that we can update the existing text for the message
* create/update the task with a specific SDK number id so that we can support NoWarn.

The link is easy, I'll do that shortly. The task work is more work, we might get to that as a follow-on.

**Comment by marcpopMSFT** [comment]
If we add an NETSDK number prefix, we'll want to modify this code and put a placeholder number: https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Tasks/Common/Logger.cs#L130

**Comment by baronfel** [comment]
@marcpopMSFT https://aka.ms/dotnet-support-policy has been created to serve as the target for this work.
