### ISSUE TITLE
An error dialog pops up when creating the .Net Core project with the latest .NET SDK 6.0

### ISSUE THREAD

**Issue by Zheng-Li01** [dotnet/sdk#17515]
**More info:**
1. This is a regression issue, can't reproduce on .NET SDK 6.0.100-preview.5.21255.24-win-x64.
2. The issue can reproduce more types core project, such as winforms, wpf. console etc.

**Version info:**
NET SDK 6.0.100-preview.5.21257.10-win-x64.

**Repro Steps:**
1. Install the latest .Net 6.0 from https://github.com/dotnet/core-sdk.
2. Try to  create .Net Core project.

**Actual Results:**
An error dialog pops up.
![image](https://user-images.githubusercontent.com/38325459/117532115-7e52ee80-b018-11eb-876f-fabb59d430b2.png)

**Expected Results:**
 Creating the .Net Core project with the latest .Net 6.0 successfully.

**Comment by Zheng-Li01** [comment]
**More info:**
The project can be create/built/run successfully by using Command.

**Comment by davidfowl** [comment]
+1 nothing works after I upgrade

**Comment by dsplaisted** [comment]
@Zheng-Li01 What version of Visual Studio is this happening with?

**Comment by benaadams** [comment]
I get it in 16.10.0 Preview 2.1

**Comment by dsplaisted** [comment]
Can you try setting `MSBuildEnableWorkloadResolver` to false and see if that fixes the problems?

(You don't want to leave this permanently on, as it will disable any workloads, which in .NET 6 will include ios, android, and Blazor AOT support.)

**Comment by benaadams** [comment]
Nope

![image](https://user-images.githubusercontent.com/1142958/117722806-6eced380-b1d9-11eb-9d01-91bd837af1cb.png)

**Comment by dsplaisted** [comment]
@dotnet/templating-engine-maintainers @wli3 @marcpopMSFT  This looks like it may be a separate issue from what #17536 is trying to fix.  It looks like maybe the workload template resolver hasn't been updated to handle the manifest schema change.  What's the process for updating that?  Is it supposed to happen with normal .NET SDK insertions or what?

**Comment by DavidKarlas** [comment]
@phenning Where is logic for VS sync with optional workload templates, sounds like it needs updating?

**Comment by dsplaisted** [comment]
Specifically, I think that the template engine needs to use a version of the workload manifest reader with this change: #17329

**Comment by davidfowl** [comment]
If this requires a VS change to function, what does that mean for using nightly builds?

**Comment by dsplaisted** [comment]
I think it may mean you need to create projects from the command line.

You could also try delete or rename the SDK manifests folder: `C:\Program Files\dotnet\sdk-manifests`.  That would break iOS, Android, and Blazor AoT though.

**Comment by davidfowl** [comment]
So nobody can update the sdk? Can we turn off the workload thing by default until there's a version of vs that works ?

**Comment by phenning** [comment]
@davidfowl this shouldn't require a template engine change unless there is something broken with the API surface. SDK needs to insert a new manifest reader. We just call the API.

**Comment by phenning** [comment]
FYI, the only thing we call on the locator are the following two methods:

       TemplateLocator.GetDotnetSdkTemplatePackages(sdkVersion, dotnetRootPath);
       TemplateLocator.TryGetDotnetSdkVersionUsedInVs(vsVersion, out sdkVersion);

**Comment by phenning** [comment]
OK, I see why this only seems to be happening on Create, - it actually is also happening on the enumeration of the templates as well, except NPD is handling the exception being thrown by the locator so that there isn't a problem with the template list. This is resulting in a fallback to the pre 16.9 behavior where we just see the vstemplate versions of the .net core templates - notice the (.NET Core) in the template name in the screenshot. Then when you try to create, we try to refresh the templates (since we failed earlier) and this time the exception is not caught by NPD.

Separate from a fix in the TemplateLocator, I think I (VS) needs to harden the where we call into the template locator in visual studio, catching any exceptions and logging them to the activity log. By doing this, at least we'd still have the core non-optional templates available and we'd only see the templates from the optional workload not be shown.

**Comment by dsplaisted** [comment]
OK, it turns out that the change in #17329 isn't in VS 16.10 yet, but it will be there before the GA release.  Until 16.10 GA, here are the workarounds you can use:

- Use .NET 6 Preview 4 instead of Preview 5
- Create projects using the command line (`dotnet new`) instead of from within Visual Studio
- Delete or rename the `C:\Program Files\dotnet\sdk-manifests` folder (note that this will break iOS, Android, and Blazor AOT)
- Build the `release/5.0.0xx` branch of the dotnet/sdk repo.  Copy the file `artifacts\bin\Microsoft.DotNet.TemplateLocator\Debug\net472\Microsoft.DotNet.SdkResolver.dll` to the Visual Studio PrivateAssemblies folder (with a path similar to `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\PrivateAssemblies`)

**Comment by Zheng-Li01** [comment]
Verified the issue with latest 6.0.100-preview.5.21263.57, for now the project can be created successfully. so closed it.
![image](https://user-images.githubusercontent.com/38325459/118209739-c4d29e00-b49b-11eb-9349-7ee5cd9e4368.png)

**Comment by benaadams** [comment]
Still broken in latest nightly `6.0.100-preview.5.21264.2`

![image](https://user-images.githubusercontent.com/1142958/118276990-30c6fd80-b4c0-11eb-9151-f6f254228765.png)

> OK, it turns out that the change in #17329 isn't in VS 16.10 yet, but it will be there before the GA release. Until 16.10 GA, here are the workarounds you can use:

Don't think VS 16.10 is a solution if installing the sdk breaks previous VS before even asking what version of .NET to use (e.g. this isn't trying to create a .NET6.0 app)

**Comment by davidfowl** [comment]
> Delete or rename the C:\Program Files\dotnet\sdk-manifests folder (note that this will break iOS, Android, and Blazor AOT)

Since this the only reasonable workaround, remember to undo this when you install a new version (if you did a rename), or the new installer won't remove it during the previous version uninstall.

**Comment by marcpopMSFT** [comment]
16.10 preview 4 will include the fix for this and the SDK will not load into 16.9 as we've updated the minimum required version for .NET 6 with preview 4 and newer.
