### ISSUE TITLE
When TargetName is specified dotnet run command fails

### ISSUE THREAD

**Issue by Vake93** [dotnet/sdk#17727]
I have created a console application and added the TargetName name property (See screen shot attached). Then `dotnet run` fails to execute the application. `dotnet build` works as excepted.

Tested on .NET 5 and .NET 6 preview SDKs.

![dotnet](https://user-images.githubusercontent.com/8337494/118913710-a19a6980-b947-11eb-837b-08de3423c9d5.PNG)

**Comment by dsplaisted** [comment]
Looks like `dotnet run` uses `AssemblyName`, while the `TargetName` is what determines the actual output file name.  @rainersigwald, do you know how well it's supported to have these properties be different?

**Comment by rainersigwald** [comment]
These have been separate for a very long time, but I don't know how often they're actually separated. It's surprising to me that this is even possible. I also note that `TargetName` isn't documented [but `AssemblyName` is](https://docs.microsoft.com/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019), though that's a pretty weak signal since our documentation isn't reliably great (no insult intended to our current doc writer!).

**Comment by Vake93** [comment]
Ok, using AssemblyName it works as expected. I assume TargetName isn't supported anymore.

**Comment by marcpopMSFT** [comment]
Sounds like you've found a solution and using TargetName is not supported at this time so closing this out.
