### ISSUE TITLE
Warning C4691 when building a C++/CLI executable

### ISSUE THREAD

**Issue by malachib** [dotnet/sdk#1781]
When using assemblies from NuGet, I am virtually guaranteed to encounter this warning

An easy example is when trying to use Microsoft.Extensions.Logger.  One can easily reproduce the issue with [this project](https://www.dropbox.com/s/9261ina8p4gyce1/SW-132v2.zip?dl=0)

We also [explored the issue on MSDN](https://social.msdn.microsoft.com/Forums/vstudio/en-US/fae48caa-7746-4c8f-9c44-839bd23ed128/warning-c4691-when-building-a-ccli-executable-referencing-microsoftextensionslogging-via-nuget?forum=vcgeneral)

Also this is a semi-cross-post from [here](https://github.com/aspnet/Logging/issues/734) but it seemed like the logging folks aren't the right ones to bug.  I felt this is a better spot to ask because the C4691 warning appears to be referring to a netstandard assembly.

If a) I am posting in the right place and b) you would like me to break it down more/provide more detail please let me know

**Comment by livarcocc** [comment]
cc @Petermarcu do you know how to make this work? I haven't tried it.

**Comment by Petermarcu** [comment]
@terrajobst as FYI, 

No, I haven't tried it either.

**Comment by livarcocc** [comment]
I don't believe this to be an SDK issue. I see in the feedback item you created by VS, it has been stated that this is not supported on the VS side. As such, I am going to close this issue.

**Comment by malachib** [comment]
I ended up opening an incident.  I think one could make an argument that SDK is strongly involved, but it's a combination of C++/CLI, VS and .NET Framework+.NET Standard interactions.  Specifically those shim libraries which map System.Runtime over mscorlib... reality seems to be though that C++/CLI demand is too low to really stir up concern.  Dang!

**Comment by pongba** [comment]
@malachib I'm having exactly the same issue when trying to use Roslyn in C++/CLI. Interesting how low C++/CLI demand is, AFAIK it's the best bridging language between native and .net.

**Comment by adaviding** [comment]
I am having this issue.  My C++/CLI project is pulling in a `netstandard2.0` project.  I am using VS 2017 and I have .net core sdk 2.2 (`dotnet --version` = 2.2.107).  This is difficult because the `netstandard2.0` project is the place where our constants are defined.  Now it looks like we'll need to define those constants in multiple places.

**Comment by malachib** [comment]
@pongba I agree
@adaviding probably is relatively unrelated to nuget, if it's the issue discussed here

Also, I don't think I can share that old incident link here.  Support request #118010217393556. 

But for the record, MS depressingly marked as "won't fix" with a "minimum" severity - though, many of those details appear to be lost due to a bug/archiving on their side.

**Comment by adaviding** [comment]
@malachib I wonder if this is fixed in .net core sdk 3.1.0 ... rumor is C++/CLI (mixed mode assemblies) might be supported on Windows now.  (I wish I had more time to investigate the rumor further.)

https://stackoverflow.com/questions/39140014/c-cli-support-in-net-core
https://github.com/dotnet/coreclr/issues/18013
