### ISSUE TITLE
dotnet-sdk installed with snap crashes on Ubuntu 21.04

### ISSUE THREAD

**Issue by sleeply4cat** [dotnet/sdk#18249]
> $ sudo snap install dotnet-sdk
> ...
> $ dotnet new
> Segmentation fault (core dumped)

tested with fresh Ubuntu installation. All the 3.1, 5.0, 6.0 versions are affected.

**Comment by tweing** [comment]
see https://youtrack.jetbrains.com/issue/RIDER-73736 for a workaround

**Comment by mochsner** [comment]
Same issue on 20.04 - @sleeply4cat can you update the scope of this to include more than just 21.04? Easy for Microsoft / .NET team to put this off if it's just labelled with a non-LTS version, but it seems to be a snap problem, not an Ubuntu problem.

**Comment by sleeply4cat** [comment]
@mochsner 
on Ubuntu 22.04
1. dotnet-sdk is not a normal snap anymore, installs only with --classic
2. so, everything* works pretty fine

**Comment by WhiteBlackGoose** [comment]
```
sudo snap install dotnet-sdk --classic --channel=6.0
sudo snap alias dotnet-sdk.dotnet dotnet
dotnet tool
```
gives
```
Segmentation fault (core dumped)
```

Ubuntu 22.04.

**Comment by WhiteBlackGoose** [comment]
For those stumbling upon it, this works:
https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install

**Comment by mochsner** [comment]
> For those stumbling upon it, this works:
> https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install

Correct, the install script doesn't break on updates, but that doesn't fix the snap problem. If it doesn't work or allow user to ever update the snap (without breaking), what's the point?

I'd rather just have snap discontinued / removed than half working.

**Comment by xorinzor** [comment]
Still happening on Ubuntu 22.10

**Comment by WhiteBlackGoose** [comment]
dotnet was added to ubuntu repositories, use `apt`

**Comment by xorinzor** [comment]
@WhiteBlackGoose that's not a solution. Snaps are offered and as such should be supported, otherwise they shouldn't be offered.

**Comment by xorinzor** [comment]
apt is a *workaround* for this specific issue, not a solution.

**Comment by WhiteBlackGoose** [comment]
How is it a workaround? It's an official package manager and core part of debian, ubuntu, and many more, unlike snap.

.net maintainers officially ship a deb package since recently.

I don't see how it's a "workaround"

**Comment by sleeply4cat** [comment]
dpkg is archaic format with _a lot_ of problems which should be avoided if possible.
What I see is literally a workaround.

**Comment by xorinzor** [comment]
@WhiteBlackGoose  Can we please stop cluttering this issue with a discussion?
This issue specifically is regarding dotnet using `snap`, not using `apt`.

**Comment by mochsner** [comment]
Hey @shanselman - sorry for the noise, I just follow you on Mastodon, and know you're a very responsive high-level resource for dotnet product development. 

As a Linux user, I find the handling of this issue disappointing - this issue has gotten 0 response or traction from anyone on the dotnet team. So, could we at minimum improve the documentation for time being, if this isn't going to be fixed near-term? I understand there are other priorities (like MAUI) that might keep that being a priority for early 2023, but this was an absolute horrible experience for me, and wasted quite a lot of effort that could've been more value adding doing .NET development.

**Issue**
Snap store has been _**reported**_ as broken for, from what it looks like, approaching 2 years.  Some folks seem to be running into it out of the box, but I ran into it when things were auto-upgraded from `6.0.300` to `6.0.301` (or, `6.0.5` -> `6.0.6`) on Ubuntu 20.04 ![image](https://user-images.githubusercontent.com/19310711/229863013-c8fcbd65-2388-4fec-9a6d-849e1a8a1191.png). It seems like it was occurring both before my instance, as well as after, but I think it's related to snap installations corrupting themselves somehow, maybe with bad pointers (since each version of an app installed by snap is installed in it's own location, and pointers change to them).

**Short-term Mitigation**
For the sake of Microsoft community, as a short-term mitigation for your Ubuntu audience, would it be possible to add a warning to the snap documentation [here](https://learn.microsoft.com/en-us/dotnet/core/install/linux-snap)? The current caution/warning is misleading, as it's more than just the "tooling" that's breaking. 

It's a very sneaky issue for Ubuntu users, and frustrating to troubleshoot or switch to other options, as dotnet on Linux isn't super common or well documented on forums. Needing to discover and clean dotnet remnants out (snap, aliases, ~/.dotnet folder, etc), and install another source of dotnet is wasted effort, which could be saved by better documentation and warnings, at minimum.

**Comment by richlander** [comment]
We're working with Canonical to get them to take over ownership of the Snap, given that they now have their own build of .NET. The Snap is effectively unmaintained at the moment. I'm sorry about that.
