### ISSUE TITLE
404 

### ISSUE THREAD

**Issue by sssseossss** [dotnet/sdk#18309]
wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb 
Resolving packages.microsoft.com (packages.microsoft.com)... 13.80.99.124                                               
Connecting to packages.microsoft.com (packages.microsoft.com)|13.80.99.124|:443... connected.                           
HTTP request sent, awaiting response... 404 Not Found                                                                  
2021-06-17 13:21:50 ERROR 404: Not Found.

**Comment by rbhanda** [comment]
Hello @sssseossss We are seeing all the files in the  https://packages.microsoft.com/config/ubuntu/20.10/ repo. The team that owns this had an outage some time back hence the reason you might have seen this issue. Please check again and confirm if this is working, otherwise let us know if you are still seeing this issue.
