### ISSUE TITLE
.NET 6 Preview 5 for Linux was built with PGO enabled, causing it to litter default.profraw files

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/sdk#18829]
On Ubuntu 20.04, using .NET 6 Preview 5 (or Preview 6) is causing `default.profraw` files to appear all over my project and bogus "LLVM Profile Error" messages to print to my console wherever I run `dotnet` commands. I don't normally run .NET Previews on Linux, but I assume this is not expected.

This seems to be occurring because the preview release of the SDK has PGO enabled via Clang's `-fcs-profile-generate` option. Ideally this would not be the case for the published preview builds.

--------------------

I unfortunately cannot inspect the actual contents of the profiles using `llvm-profdata show` due to a version mismatch. (Manually reading the file's header in a hex editor suggests they're from something built with LLVM 9 or older.) However I can infer it's caused by the .NET Preview because they don't appear if I disable previews in `global.json`:

![image](https://user-images.githubusercontent.com/278957/125116202-fb9aee00-e0b1-11eb-9d70-4595f93696ed.png)

In case it matters, I installed the .NET preview using [these instructions](https://github.com/dotnet/core/blob/123275423d786782b58ee4ae8a9233d6f97192db/release-notes/6.0/install-linux.md#install-using-debrpm-packages). Let me know if you need any further details from me!

**Comment by PathogenDavid** [comment]
As an aside, this actually happened to me in a mixed C#/C++ project where I'm building the native components with Clang. So I wasted quite a lot of time chasing a misconfiguration in my own build process. Assuming I haven't missed the mark, I'd really appreciate it if you all would consider [specifying a directory name](https://releases.llvm.org/10.0.0/tools/clang/docs/ClangCommandLineReference.html#cmdoption-clang1-fcs-profile-generate) for your PGO files to save people from the same fate.

**Comment by PathogenDavid** [comment]
Can confirm that this is still happening with Preview 6.

**Comment by marcpopMSFT** [comment]
@agocke Could this be related to your change here: https://github.com/dotnet/installer/pull/10229

**Comment by agocke** [comment]
Uh oh, looks like bits are getting crossed here -- PGO bits should never end up in the published packages

**Comment by agocke** [comment]
Trying to track this down now

**Comment by agocke** [comment]
OK, so it doesn't look like the .tar.gz files are affected... I just downloaded the same version and I don't think those are instrumented bits.

**Comment by agocke** [comment]
Found it: this is actually in the runtime build. It looks like packaging debs and rpms is at a separate post-step in publishing. 

https://github.com/dotnet/runtime/blob/f399076cb971fcfdab397d8b3786f321acb4b4d5/eng/pipelines/installer/jobs/base-job.yml#L429

The PGO builds disable building the installers, but these steps come along after and crack open the zip file created from earlier. Since this step is included in the PGO build, it's packaging up the PGO bits and publishing with the exact same name as the non-PGO bits.

When they get published, this creates a race condition where whoever publishes first wins.

Simple fix is to disable this step for PGO, but I'd like to also find some way to prevent the PGO build from building extra things by default.

**Comment by Redfoggg** [comment]
Happens to me too on ubuntu 21.04.

**Comment by agocke** [comment]
@Redfoggg If you use the tar.gz files instead of the deb/RPMs, those should contain the proper preview binaries.
