### ISSUE TITLE
Package version

### ISSUE THREAD

**Issue by dbarwikowski** [dotnet/sdk#1920]
https://github.com/dotnet/sdk/blob/94a3f2856cb09e66ee7472820b4e26fb576b4686/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.DefaultAssemblyInfo.targets#L18-L22

Shouldn't it be:
```
 <PropertyGroup Condition=" '$(Version)' == '' "> 
   <VersionPrefix Condition=" '$(VersionPrefix)' == '' ">1.0.0</VersionPrefix> 
   <Version Condition=" '$(VersionSuffix)' != '' ">$(VersionPrefix)-$(VersionSuffix)</Version>
   <Version Condition=" '$(VersionSuffix)' == '' ">$(VersionPrefix)</Version>
 </PropertyGroup> 
 
```

or even:
```
 <PropertyGroup>
   <Version>1.0.0</Version> 
   <Version Condition=" '$(VersionSuffix)' != '' ">$(Version)-$(VersionSuffix)</Version> 
 </PropertyGroup> 
```

**Comment by livarcocc** [comment]
No, this is by design.

If you don't specify version, we compose the version out of the prefix and suffix. 

This is what is happening in lines 20 and 21 above. If there is a suffix, compose the version from suffix-prefix. Otherwise, use only the prefix, which is guaranteed to be set, because we set it to a default if one is not provided.

**Comment by dbarwikowski** [comment]
Ok, I get it now, thanks
