### ISSUE TITLE
DocumentationFile being dropped at OutputPath instead of OutputPath/TFM

### ISSUE THREAD

**Issue by livarcocc** [dotnet/sdk#193]
Output for documentation file with the csproj below is ending up in the output path and then it gets copied to tfm. But this may cause problems where the documentation should actually be different per tfm.

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <VersionPrefix>1.0.0</VersionPrefix>
    <TargetFrameworks>netstandard1.5</TargetFrameworks>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <AssemblyName>TestLibraryWithConfiguration</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>$(OutputPath)\$(AssemblyName).xml</DocumentationFile>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <AutoUnify>true</AutoUnify>
    <DesignTimeAutoUnify>true</DesignTimeAutoUnify>
    <ProjectLockFile>$(MSBuildProjectDirectory)/project.lock.json</ProjectLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.Sdk">
      <Version>1.0.0-alpha-20160929-2</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <EmbeddedResource Include="**\*.resx" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <EmbeddedResource Include="compiler\resources\**\*" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
  </ItemGroup>

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by dsplaisted** [comment]
Here's what's going on:

- `GenerateDocumentationFile` is not used at all, except as metadata on `DependencyFileCompilerOptions` passed to the task used to preserve the compilation context.
- In VS 2015, if you check the box in project properties to create an XML documentation file, it defaults to setting the `DocumentationFile` to `bin\{Configuration}\{AssemblyName}.xml` in the PropertyGroup which corresponds to a given Configuration|Platform combination.
- In VS 15, checking the "XML documentation file" checkbox resulted in the following (however, with the latest build everything in the Build property page is disabled so it's not possible to check the box):

```xml
  <PropertyGroup Label="Configuration">
    <DocumentationFile>bin\Debug\.xml</DocumentationFile>
  </PropertyGroup>
```

- If the `DocumentationFile` property is set, it will always be copied to the output directory.  It works like this:
  - Microsoft.CSharp.CurrentVersion.targets [creates a `DocFileItem` based on `DocumentationFile`](https://github.com/Microsoft/msbuild/blob/fd25bc9c7deb56dbfe51621afb1021056f410241/src/XMakeTasks/Microsoft.CSharp.CurrentVersion.targets#L155), which is what is passed to the compiler in the CoreCompile target
  - Microsoft.Common.CurrentVersion.targets [creates a FinalDocFile item](https://github.com/Microsoft/msbuild/blob/fd25bc9c7deb56dbfe51621afb1021056f410241/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L350) with its path set to the output folder, and then [copies it to the output path](https://github.com/Microsoft/msbuild/blob/fd25bc9c7deb56dbfe51621afb1021056f410241/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L3979) in the CopyFilesToOutputDirectory target.
- The `OutputPath` property is set to `bin\Debug\` or `bin\Release` [in Microsoft.NET.Sdk.props](https://github.com/dotnet/sdk/blob/0f6ea54fac99d2dd14c451e12a8159ef388ebe93/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.props#L31), and then the `TargetFramework` is appended to it [in Microsoft.NET.TargetFrameworkInference.targets](https://github.com/dotnet/sdk/blob/0f6ea54fac99d2dd14c451e12a8159ef388ebe93/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.TargetFrameworkInference.targets#L86)

Here's what I suggest we do:
- In the Sdk targets, if `GenerateDocumentationFile` is true, then set `DocumentationFile` to `$(IntermediateOutputPath)\$(AssemblyName).xml`.  (Do this after Microsoft.Net.TargetFrameworkInference.targets so we get the final value for the intermediate output path).
- Update the "Build" property page so that you can check a box to generate an Xml documentation file without specifying the filename.  This should set `GenerateDocumentationFile` to true in the project file instead of setting the `DocumentationFile` property.  This should be based off of a capability so that projects that don't use the Sdk still get the old behavior.
- Figure out what the behavior should be if `GenerateDocumentationFile` and `DocumentationFile` are both set.  If `GenerateDocumentationFile` is true we can probably just use the specified value of `DocumentationFile`.  If `GenerateDocumentationFile` is false but `DocumentationFile` is set, perhaps we should make that an error, since the settings are in conflict.
- Don't set `OutputPath` in the props files.  If we're just going to be modifying it in the targets, then setting it to something in the props files can lead to unexpected behavior when the value is used in the project but doesn't represent the final value of the property.

Thoughts? @nguerrera @srivatsn

**Comment by nguerrera** [comment]
That all makes sense to me. Thanks for the thorough analysis.

**Comment by dsplaisted** [comment]
One more item to do: Update the compilation context preservation process to correctly handle the documentation file options (or ignore them entirely if we don't need them).

**Comment by nguerrera** [comment]
I have a change in progress that moves output path to before common targets. Had to refactor so that pack targets still see it.
