### ISSUE TITLE
BindingRedirect warning behaves inconsistently

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/sdk#19391]
### Issue Description
Visual Studio does not show a BindingRedirect warning when I use a class library targeting .NET Standard 2.0. It behaves differently and will show the following warning if I change the class library's target framework to .NET 4.8.

![binding redirect warning](https://user-images.githubusercontent.com/23503973/127386952-52eabdd6-2fa1-4411-a9c1-4b3af67f6b7c.png)

### Steps to Reproduce
I'm including 2 sample projects. I created a default ASP.NET full framework web app from VS2019 Preview and added a class library. Both examples perform the same task of authenticating to an Azure Key Vault using SDKs provided via NuGet package references. As such both examples will break until the appropriate binding redirects have been added to the `web.config` file of the ASP.NET sample project.

*WorkingExample*
1. The class library targets net48
[WorkingExample.zip](https://github.com/dotnet/sdk/files/6902857/WorkingExample.zip)
[WorkingConsoleExample.zip](https://github.com/dotnet/sdk/files/6947579/WorkingConsoleExample.zip)

*BrokenExample*
1. The class library targets netstandard2.0
[BrokenExample.zip](https://github.com/dotnet/sdk/files/6902858/BrokenExample.zip)
[BrokenConsoleExample.zip](https://github.com/dotnet/sdk/files/6947523/BrokenConsoleExample.zip)

### Expected Behavior
I expected the *BrokenExample* to produce the warning message shown from the *WorkingExample*.

### Actual Behavior
No warning is displayed.

### Versions & Configurations
* In a Visual Studio developer command prompt, run `msbuild -version` and paste the output here.
```
Microsoft (R) Build Engine version 16.11.0-preview-21351-03+1d7ed8e3d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.11.0.35103
```
* If applicable, include the version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):
```
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.11.0 Preview 3.0
```

**Comment by BenVillalobos** [comment]
MSBuild Team Triage: It looks like something in the SDK is disabling assembly resolution conflict errors when targeting netstandard. That makes sense for targeting a net core app but it's ambiguous for standard since it might run on framework where the binding redirects would be necessary. Is this something we should fix at the SDK level, or can we advise users to opt in with some property?

**Comment by ericstj** [comment]
Binding redirects aren't relevant for NETStandard projects since they aren't "runnable".  If a NETStandard project is consumed by a .NETCore project no bindingRedirects are needed as the binder will automatically allow the higher versions to load.  Even if you did emit bindingRedirects from the NETStandard application nothing would consume them automatically, the runtime only loads app.configs for the application.

I tried out your console sample and the problem is a little different.  In this case you have a project reference from an app (classic csproj) to a netstandard library, but the project has no package references.  As a result the project does not get the packages from the library.

To avoid this you can make sure that the application uses PackageReference.  This will ensure it resolves the nuget packages itself, and those will be analyzed by RAR for conflicts.

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#using-packagereference-for-a-project-with-no-packagereferences
Add the following to the project to get it working.
```xml
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
```
cc @joperezr

**Comment by KSchlobohm** [comment]
@marcpopMSFT  I'm closing this issue after identifying that the requested behavior is already available. The desired behavior is that the transitive references for PackageReference projects will be restored *AND* the packages.config references from the ASP.NET project will be restored.

> When using ```<RestoreProjectStyle>PackageReference</RestoreProjectStyle>``` you lose the restoration of NuGet references included by packages.config. Failing to restore references from packages.config causes runtime errors for the ASP.NET web app.

The better approach is to change the netstandard class library to multi-target netstandard, and net48 (where net48 is whatever target aligns with the ASP.NET web app). Using this approach causes the ASP.NET web app to include the class library as a net48 target which informs MSBUILD to behave differently. In this mode MSBUILD has awareness of the packages that are restored and will copy all transitive dependencies into the `\bin` folder when the ASP.NET web app is built. That awareness also extends into Visual Studio and causes the BindingRedirect warnings to appear.

I've updated the previously included BrokenExample to demonstrate this change.

[BrokenExampleFixed.zip](https://github.com/dotnet/sdk/files/7715022/BrokenExampleFixed.zip)

![BrokenExampleFixed](https://user-images.githubusercontent.com/23503973/146086005-6938ad8a-0d2a-4ad0-8733-924ea0af31d6.png)
