### ISSUE TITLE
Strange warning NU5132

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#19471]
When I build my project, I got `NU5132` warnings, could not understand what the warning exactly means, could someone please help.

![](https://user-images.githubusercontent.com/7604648/127960930-79436582-98ac-4c88-9d4e-14e5610fbe9b.png)

My project is here <https://github.com/WeihanLi/dotnet-httpie>

Thanks in advance.

**Comment by ryank425** [comment]
According to the source code (https://github.com/NuGet/NuGet.Client/blob/a5d5e3236e86f6c3c09097b723ce2b52852a1752/src/NuGet.Core/NuGet.Common/Errors/NuGetLogCode.cs), NU5132 refers to 
```

/// <summary>
/// File last write timestamp is out of range of what the zip format supports warning
/// </summary>
NU5132 = 5132,
```

You have files with last write timestamp going outside of range that Windows supports. NuGet is telling you those warnings to avoid any more problems. I would suggest that these files didn't lose timestamps from original source, and also make sure that your device OS time is in sync (Could be also due to dead CMOS Battery).

**Comment by WeihanLi** [comment]
Thanks for your answer @ryank425 , seemed the files are from  `Microsoft.Extensions.*` package

**Comment by KalleOlaviNiemitalo** [comment]
May be a duplicate of <https://github.com/dotnet/extensions/issues/2750>. Try a more recent version of the package.

**Comment by WeihanLi** [comment]
> May be a duplicate of [dotnet/extensions#2750](https://github.com/dotnet/extensions/issues/2750). Try a more recent version of the package.

Upgrade `Microsoft.Extensions.*` package from `3.1.0` to `3.1.17` saved me, great thank for your help @KalleOlaviNiemitalo
