### ISSUE TITLE
The console window displays garbled characters when type "dotnet --info"

### ISSUE THREAD

**Issue by quanljh** [dotnet/sdk#19996]
### Description

When type "dotnet --info" in console window, it displays garbled characters in the output information. My computer language is Japanese.

### Configuration

You can find my configuration in the attachment
![image](https://user-images.githubusercontent.com/38105306/130189697-7cf34b82-043c-4158-87d2-ed344593b4d4.png)

![image](https://user-images.githubusercontent.com/38105306/130189853-b7f8f02e-437e-4af7-8058-13528b9411c8.png)

And console program also displays ??. 

![image](https://user-images.githubusercontent.com/38105306/130307329-b4c27534-c5f8-45fb-88e8-5dd95d3f9742.png)

The code page is UTF-8 by default.
![image](https://user-images.githubusercontent.com/38105306/130307772-a963105a-b68b-436e-a5f5-7bca64b850a2.png)

**Comment by KalleOlaviNiemitalo** [comment]
I tried running `set DOTNET_CLI_UI_LANGUAGE=ja-JP` and `chcp 65001` and `dotnet --info`, in `cmd` on Windows 10 Version 21H1 (OS Build 19043.1165).

- In conhost, using "Consolas" font:
  Question marks in rectangles appear, but if I copy them to the clipboard and paste to WordPad, then Japanese characters appear in WordPad.
- In Windows Terminal Preview 1.10.1933.0, using "Consolas" font:
  Japanese characters appear.
- In OpenConsole.exe copied from Windows Terminal Preview 1.10.1933.0, using "Consolas" font:
  Japanese characters appear.

I think this is a conhost issue and will be fixed in some later version of Windows when the changes from OpenConsole have been merged in.

**Comment by quanljh** [comment]
@KalleOlaviNiemitalo  Thanks for helping to identify the root cause, if I copy the question mark characters to another editor then Japanese characters appear. Or If I change the font of conhost, the Japanese characters also display as normal. 
Since this is a conhost issue, I'll close this issue. Thanks.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/microsoft/terminal/pull/10478> may have fixed this in OpenConsole. I don't know which version of Windows will include a conhost with this change.
