### ISSUE TITLE
msbuild / dotnet build does not pass the property generated by nuget packagereference's GeneratePathProperty

### ISSUE THREAD

**Issue by sjmla** [dotnet/sdk#20160]
As a result of #20073, I am looking for a workaround to copy a nuget's native assets to my project's output directory.

What I am seeing is the property as a result of GeneratePathProperty is empty when I run either msbuild or dotnet build on a net48 project.
It works correctly via Visual Studio 2019 (v16.11.1), but not via msbuild tools.

I tried the setup in https://github.com/dotnet/sdk/issues/20073#issuecomment-905051300

I also tried, without success.
```
  <ItemGroup>
    <PackageReference Include="NativeLib" Version="1.2.3" GeneratePathProperty="true" />
    <None Include="$(PkgNativeLib)\runtimes\win-x64\native\*">
      <Link>%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

However, the below works ==> the ```$(PkgNativeLib)``` property generated as a result of ```GeneratePathProperty="true"``` is unavailable!
```
  <ItemGroup>
    <PackageReference Include="NativeLib" Version="1.2.3" GeneratePathProperty="true" />
    <None Include="$(NuGetPackageRoot)\NativeLib\1.2.3\runtimes\win-x64\native\*">
      <Link>%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

EDIT: the .nuget.g.props shows the property generated in all cases.

**Comment by marcpopMSFT** [comment]
The nuget targets are what generates that property. In order to use it, you have to put it in a target that runs after the Restore target. So the package reference itself has to be in a global scoped itemgroup and the use of the property within a target that runs after. @JonDouglas should we improve our documentation as the examples are after build?

https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#generatepathproperty
