### ISSUE TITLE
How to disable "preview version" warning message?

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#2033]
Currently, the SDK issues this high importance message when I build

> You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. 

I already have a global.json file and I explicitly set it a preview version, so the warning seems unnecessary. How can I disable this message altogether?

**Comment by nguerrera** [comment]
I'd be fine with a bool like $(SuppressNETCoreSdkPreviewMessage). 

cc @jaredpar @natemcmaster @KathleenDollard

**Comment by nguerrera** [comment]
cc @livarcocc

**Comment by natemcmaster** [comment]
A good first step. How hard would it be to do this?

```
bool SuppressNETCoreSdkPreviewMessage(string projectDirForCurrentBuild)
{
  var dir = new DirectoryInfo(projectDirForCurrentBuild);
  while (dir != null)
  {
    if (File.Exists(Path.Combine(dir.FullName, "global.json")) return true;
    dir = dir.Parent;
  }
  return false;
}
```

**Comment by nguerrera** [comment]
We shouldn't waste perf on it. We could know if there's a global.json at play without re probing once per msbuild node, but that requires plumbing it through.

**Comment by livarcocc** [comment]
Put it under discussion for now, so that we can agree on some good middle ground. I would like to have this fixed for 2.1.300 though.

**Comment by KathleenDollard** [comment]
If it were free, I'd agree with @natemcmaster 

Is there a way to have this automatic when global.json was used to specify the SDK without a file hit? 

If there isn't, would a switch on commands be too onerous? I assume this is most annoying in scripts?

An environmental variable seems easy to overlook, although it may turn out to be the best approach.

**Comment by nguerrera** [comment]
Complicating the command line doesn't seem worth it, and we need this to work in VS and `msbuild` too.

The msbuild variable I proposed would work as environment variable, but I imagine Directory.Build.props would be the most convenient way to leverage it.

There's no existing way to no if global.json is at play, but like I said, we could plumb it through. The main complexity is that we have to handle both `msbuild` sdk resolution and `dotnet` muxer dispatch.

My recommendation is that we start with the MSBuild variable I proposed because it's cheap and 90% good enough, but keep an open mind about plumbing global.json through. There are other use cases for that (improving dotnet --info) for one. I wouldn't do the plumbing nor workaround it with extra probing just to save one line in D.B. props...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by livarcocc** [comment]
I agree 100% with @nguerrera.

**Comment by KathleenDollard** [comment]
I don't think I understand how the MSBuild variable would work. Can you explain the user experience (when/how this variable is set, etc)?

**Comment by rainersigwald** [comment]
I think the property is reasonable, but plumbing knowledge of `global.json` through could also help with SDK restore . . .

cc @jeffkl

**Comment by natemcmaster** [comment]
@KathleenDollard the user experience is that users need to edit their project files to contain this:
```xml
<PropertyGroup>
  <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
</PropertyGroup>
```

If they are using an MSBuild file commonly imported to all projects, such as `Directory.Build.props`, they only need to set it once per repository. If not, they would need to add it to each .csproj/.vbproj file in their solution.

**Comment by jaredpar** [comment]
I think the MSBuild variable is fine. There is already an unofficial MSBuild variable you can use to suppress this message. It was pretty trivial to enable this in Roslyn.

**Comment by jeffkl** [comment]
In my opinion, it is not worth the overhead of reading `global.json` to suppress this message.  I would vote to not even log it personally.  But an MSBuild property is the next best thing because it can be set in a common import or an environment variable.

**Comment by dasMulli** [comment]
regarding `global.json`: this would be hard since the logic would need to check:

1. does it exist
2. did the version selected in it match the "preview-ness" of the currently running version, e.g. if the pinned non-preview version wasn't found and a preview version was used instead. Or if a different preview-version was pinned and not found.

=> probably way too complicated to be ""correct""

**Comment by natemcmaster** [comment]
Ok. Adding the MSBuild variable is pretty simple. I opened #2042
