### ISSUE TITLE
File scoped namespace is not generated anymore in .Net 6 RC1

### ISSUE THREAD

**Issue by Ponant** [dotnet/sdk#21016]
### Describe the bug
In .Net 6 Preview 7 a class generated with VS used the new file scoped namespace. In RC1 this is not the case anymore. It uses the block-scope namespace, which sounds like a step back.
Is there a flag to ensure file-scoped namepsaces are generated in VS?

### Further technical details
VS 2022 Preview 4

**Comment by AraHaan** [comment]
The reason is because ``<Imports Include="System" />`` was renamed to ``<Using Include="Systen" />`` which now has an xml attrib ute for setting if the Using should be generated as:

- an global static using.
- an global alias using.
- a normal global using.

While any other types of global using is invalid and will result in compile time errors.

As such I would say this should be closed as by design.

**Comment by Ponant** [comment]
@AraHaan , so how can you use file scoped namespace then?

**Comment by AraHaan** [comment]
Oh you mean file scoped namespaces, currently I see them generated for the rc.2 templates (I have rc.2 installed now) as for rc.1 I was manually doing it however that was because of the fact that I was moving pre-existing code to use file scoped namespaces.

Perhaps the reason for this is probably because something happened to the templates in rc.1 to not want to generate those file scoped namespaces.

**Comment by Ponant** [comment]
With dotnet new classlib, the `class1` that comes for free uses file-scoped namespace, but not in VS 2022. So I don't get it.

**Comment by Ponant** [comment]
And any new class added via VS will come with the block-scope namespace.

**Comment by AraHaan** [comment]
Perhaps this is a Visual Studio regression, you might have to file an issue for it using the "Report a Problem" option in Visual Studio (which might end up getting filed under the roslyn repository).

**Comment by Ponant** [comment]
OK will move it, thanks
