### ISSUE TITLE
First-chance ArgumentOutOfRangeException in NuGetUtils.cs line

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/sdk#2183]
https://github.com/dotnet/sdk/blob/1e286bdb0387033b8d0a7e3a2157010ea3855360/src/Tasks/Common/NuGetUtils.cs#L53

When debugging a design-time build on the line above I see `fullPath` =  `System.Xml` and `dir.FullName` = `J:\s\src\Tools\BuildUtil`. Calling substring with these arguments throws, obviously. 

It is being caught in the catch block below, but still causes dozens of annoying first-chance exceptions. 

Is there a check we could do to avoid the exception? Say, if the index is outside the string bounds, don't attempt to call Substring.

**Comment by nguerrera** [comment]
OMG, that catch. I have never seen this code. :(

**Comment by nguerrera** [comment]
We should fix the TODO that even caused this approach to exist: #1091. I moved it to 2.1.4xx as well.

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hi
Is this still available?

**Comment by KirillOsenkov** [comment]
Looks good I think, except I'd name the variable `fullNameLength`: we try to avoid using underscores in identifiers, and use camelCase for locals and parameters, and avoid abbreviations.

Would you send a Pull Request with this change?

**Comment by pedrowindisch** [comment]
Hey there @KirillOsenkov, is this still available? If so, I'd like to work on it if possible :)

I noticed that the method GetPackageIdFromSourcePath seems no longer in use. Searching through the git history, the last part of the code using it was removed/refactored in commit [#4cedcc](https://github.com/dotnet/sdk/commit/4cedccba5d5ebb37ef0763dc7bbf7c425736fd78). Given this, I wasn't sure if this issue is still relevant. 

Should I proceed and update the code based on the described solution (add a check to avoid the first-chance exception), or would you recommend some other approach to this dead code?

**Comment by KirillOsenkov** [comment]
I have no idea, perhaps send a PR that deletes it and see if the tests pass?
