### ISSUE TITLE
Explicitly downgrading packages when using shared framework

### ISSUE THREAD

**Issue by poke** [dotnet/sdk#2265]
I am trying to use the Microsoft.AspNetCore.App shared framework, which includes EntityFrameworkCore 2.1, but I want to explicitly downgrade to EF Core 2.0 (I have reasons :sweat:).

So my project looks like this:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.3" />
  </ItemGroup>
</Project>
```

However, when trying to build that, I get the following error message:

> Detected package downgrade: Microsoft.EntityFrameworkCore from 2.1.0-rc1-final to 2.0.3. Reference the package directly from the project to select a different version.

Now, I don’t know if this is even a supported situation, downgrading packages that are contained in a shared framework. However, if that’s the case, then the error message is misleading: After all, I _am_ referencing the package directly in the project.

Is downgrading individual packages from the shared framework supported? If it is not, can we do something about the error message there, so it would say that you cannot use the shared framework for this situation?

**Comment by livarcocc** [comment]
The Microsoft.AspNetCore.App package has a bunch of references, including Microsoft.EntityFrameworkCore.

Given that you are directly referencing a package in that closure with a lower version, you get the error message above. This is independent of Microsoft.AspNet.Core.App being a framework package or not.

We decided to make package downgrade an error back in 2.0 because these cause many hard to track down errors.

If you absolutely need to do this, you are at your own risk for it. You can do it by adding `<NoWarn>$(NoWarn);NU1605</NoWarn>` to your project. I would not say it is supported, but I also believe the error message is accurate regarding what is going on here. Like I said, this is an error regardless of the package being part of the framework or not.
