### ISSUE TITLE
`dotnet run` with invalid framework and `--` goes into infinite loop

### ISSUE THREAD

**Issue by zivkan** [dotnet/sdk#23034]
### Describe the bug

`dotnet run` allows us to use `--` to separate arguments that might be ambiguous to the app being run, or the `dotnet` CLI itself. For example, `dotnet run` has argument `-f`, but if I want my app to have an `-f` argument, I have to pass it using `dotnet run -- -f`.

When a project uses `<TargetFrameworks>` with more than one framework specified, it's also mandatory to tell `dotnet run` which framework to run, for example `dotnet run -f net6.0 -- my app arguments here` or `dotnet run -f net48`.

Normally if you tell `dotnet run` to use a framework that isn't specified in the project file, it generates an error message and the process exits. However, if the command line includes `--`, then `dotnet run` enters an infinite loop showing two errors over and over. If you press ctrl-c, then it starts repeating only one of those errors, and now it does so more quickly. The only way to break out is to kill the `dotnet` process, no amount of ctrl-c will stop it.

### To Reproduce

```text
dotnet new console
dotnet run -f net48 -- hello
```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

```text
.NET SDK (reflecting any global.json):
 Version:   6.0.200-preview.21573.3
 Commit:    a2bb0dde82

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200-preview.21573.3\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.209 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.200-preview.21573.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by baronfel** [comment]
You can get the infinite loop portion of this issue with a simpler repro: `dotnet run -- 1` in a random directory should show the same behavior around writing the error forever.

**Comment by baronfel** [comment]
The infinite loop seems to be because we have a custom exception helper assigned. This helper tries to show the help, which involves reparsing the arguments with the help token attached. This is not ideal because parsing the arguments is what has triggered the error message in the first place, causing the circular loop.

**Comment by baronfel** [comment]
A couple potential fixes:

* Alter the logic [here](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/ParseResultExtensions.cs#L18) to walk the tokens and insert the help at the best position (in order of precedence):
  * after the first Command token type seen
  * before the first `--` token type seen
  * before the first unparsed/unrecognized token
  * at the end of the token list
* instead of reparsing arguments, in the exception handler change the [call to ShowHelp()](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/Parser.cs#L141) to instead set the [invocation context's InvocationResult](https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs#L779) to something that shows the help, like [HelpResult](https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine/Help/HelpResult.cs). This is pretty easy to do and avoids the layering concerns.

**Comment by joeloff** [comment]
My vote would be for modifying ShowHelp. It seems pointless to reparse if we already know that the parsing would fail, though the command forwarding for NuGet/MSBUILD/VSTest might be what's complicating this

**Comment by baronfel** [comment]
The help forwarding for NuGet/MSBuild/VSTest is done explicitly in the HelpBuilder (which is invoked by this change), so we shouldn't run into any issues. That's all done [here](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/Parser.cs#L202-L239) if you want to take a look.

**Comment by marcpopMSFT** [comment]
A fix went into this.
