### ISSUE TITLE
`dotnet new console --help` doesn't work starting 6.0.2xx

### ISSUE THREAD

**Issue by vlada-shubina** [dotnet/sdk#23162]
`dotnet new console --help` doesn't work starting 6.0.2xx

### Describe the bug
Run: `dotnet new console --help` in 6.0.2xx branch.

Expected: help for console template is shown
Actual: `dotnet new --help` output is shown

### To Reproduce
Run `dotnet new console --help` in 6.0.2xx preview

**Comment by baronfel** [comment]
This bug is because we incorrect construct the array of arguments (including the --help token) to the new command (and several other commands). This is the same invalid positioning as shown in #23034.  To fix this, we need to determine the correct location for the help argument in the tokens array before forwarding those tokens to the forwarded command.  This can be seen [here](https://github.com/dotnet/sdk/blob/release/6.0.2xx/src/Cli/dotnet/Parser.cs#L205-L239)
