### ISSUE TITLE
Provide better experience when the dotnet version installed with VS and the available .NET MAUI version don't match

### ISSUE THREAD

**Issue by PureWeen** [dotnet/sdk#23295]
### Is your feature request related to a problem? Please describe.
Currently if you install Visual Studio 17.1 P2 it installs version `6.0.200` of the SDK

Right now .NET MAUI doesn't have any packages that are able to resolve to that version of the SDK so if a user runs

`dotnet workload install maui`

They will be met with the following exception

![image](https://user-images.githubusercontent.com/5375137/148422604-c5a4d89e-bbcd-4839-8d39-22513a58d8f5.png)

This also causes some difficulty with trying to install the correct workloads onto an iOS build host via the XMA tooling as well

@emaf has worked around this issue with the XMA installer by auto decrementing the nuget packages until a successful package is hit. 

### Describe the solution you'd like
Ideally there would be a solution baked into the SDK installer so that the .NET MAUI workload could easily be installed from the CLI if this type of mismatch occurs. Currently the only way I've found to workaround this is to run the installer from a directory pinned to `6.0.100`

**Comment by marcpopMSFT** [comment]
In VS, we recommend checking the box in VS setup to acquire the workloads. In this case, most likely there were not workloads available on the specific feeds you had configured since this was a preview. Checking nuget, this package wasn't published until Jan 19th so the package would have been on an internal feed at the time this was filed.
