### ISSUE TITLE
Should infer OutputType from NETStandard and NETCoreApp

### ISSUE THREAD

**Issue by eerhardt** [dotnet/sdk#235]
It isn't valid to have an OutputType of 'Exe' when you target NETStandard.  We should raise an error when these properties are configured that way.

/cc @nguerrera

**Comment by nguerrera** [comment]
Moving to RC. This is nice to have.

**Comment by dsplaisted** [comment]
Based on [discussion from](https://twitter.com/davkean/status/809623962464370688) @davkean and @terrajobst on Twitter, I think we shouldn't do this.  It is valid to have a class library targeting .NET Core, and it will be natural to do so as .NET Core will evolve ahead of .NET Standard.  It would be confusing to retarget a project from .NET Standard to .NET Core, and to get an error that it doesn't have an entry point because now the default output type is different.

**Comment by nguerrera** [comment]
OK.

**Comment by srivatsn** [comment]
Ok closing then.
