### ISSUE TITLE
Using target runtime win-x64 include runtime assets which should be excluded

### ISSUE THREAD

**Issue by adrianm64** [dotnet/sdk#23669]
### Describe the bug
I have a nuget package with a .targets file to exclude a dependency from runtime.
It works (i.e. dependency is not included) when publishing in Visual Studio with target runtime "portable" but dependency is included when target runtime is "win-x64"

The nuget package "NoRuntimeTest" (.nupkg not allowed, renamed to .zip [NoRuntimeTest.1.0.0.zip](https://github.com/dotnet/sdk/files/7966892/NoRuntimeTest.1.0.0.zip)) contain a `NoRuntimeTest.targets` file
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageReference Update="NoRuntimeTest">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```
When added to a new console app, Visual Studio shows it like this
![image](https://user-images.githubusercontent.com/15653488/151715376-bdf06744-86cd-412e-9468-cb9bfaaf8656.png)
i.e. the dll is correctly shown a compile time only dependency.
(the Colors.Net.dll is just an example)

When publishing with target runtime "portable" the `.deps.json` looks like: (no dependency on Colors.Net.dll)
```json
  "targets": {
    ".NETCoreApp,Version=v6.0": {
      "NoRuntimeTestApp/1.0.0": {
        "dependencies": {
          "NoRuntimeTest": "1.0.0"
        },
        "runtime": {
          "NoRuntimeTestApp.dll": {}
        }
      },
      "NoRuntimeTest/1.0.0": {}
    }
  },
```

but when publishing with target runtime "win-x64" the `.deps.json` file looks like: (a runtime dependency on Colors.Net.dll)
```json
    ".NETCoreApp,Version=v6.0/win-x64": {
      "NoRuntimeTestApp/1.0.0": {
        "dependencies": {
          "NoRuntimeTest": "1.0.0"
        },
        "runtime": {
          "NoRuntimeTestApp.dll": {}
        }
      },
      "NoRuntimeTest/1.0.0": {
        "runtime": {
          "lib/net6.0/Colors.Net.dll": {
            "assemblyVersion": "1.1.0.0",
            "fileVersion": "1.1.0.0"
          }
        }
      }
 ```
### To Reproduce
In Visual Studio:
1. Create a new net 6.0 console application
2. Add the attached "NoRuntimeTest" nuget package
3. Build and publish to a folder with target runtime "portable"
4. Build and publish to a folder with target runtime "win-x64"

I noted publishing from command line will always include the dependency!
* dotnet new console --name ...
* dotnet add package NoRuntimeTest --source ....
* dotnet publish --output Portable --framework net6.0
* dotnet publish --output Win64 --framework net6.0 --runtime win-x64 --no-self-contained

Also adding `<excludeAssets>runtime</excludeAssets>` to .csproj will always exclude the runtime dependency.

What is correct behavior?
And if correct behavior is to include the runtime dependency, what should I do to exclude it?
(I can't use the `developmentDependency` tag in .nuspec because it is transitive)

### Further technical details
`dotnet --info` [dotnetinfo.txt](https://github.com/dotnet/sdk/files/7966900/dotnetinfo.txt)
VS 2022 17.0.2 on windows 10

**Comment by dsplaisted** [comment]
Modifying `PackageReference` items in .targets files that are included in packages is not supported.  This is because the `PackageReferences` are an input to the NuGet restore process, and the .targets files from packages are not used until after NuGet restore is complete.

In Visual Studio, it can sometimes appear to work, but it is not recommended.

FYI @dotnet/nuget-team @nkolev92

**Comment by adrianm64** [comment]
@dsplaisted, thank you for your reply.

Didn't know it is not supported but that is ok.
But since I'm using .targets files for other tasks I like to understand a bit more so I don't do other not supported things.

Are you saying the "GenerateDepsJson" target (or whatever it is called) runs before the nuget restore target and will therefore not pick up msbuild properties, items etc in the nuget .target files?

**Comment by dsplaisted** [comment]
Anything that is an input to the restore operation shouldn't be set it .targets (or .props) in a package.  This is mainly `PackageReference` items, but would also include things like the NuGet feeds to use or other NuGet configuration.

The restore operation determines what packages are necessary for your project, downloads those packages, and determines what assets should be used from the packages.  The information about what packages are used and what assets should be used is recorded in the assets file (project.assets.json).

When the build runs after restore, it uses the information from the assets file, and pretty much ignores the `PackageReference` items.  So the `GenerateDepsJson` target does run after NuGet restore, but it uses the information from the assets file that was generated during restore.  So because the `<ExcludeAssets>runtime</ExcludeAssets>` was not part of the `PackageReference` metadata during the restore operation, the runtime assets were written to the assets file, and will be used during the build and flow into `GenerateDepsJson`.

Hopefully that helps explain things more!

**Comment by adrianm64** [comment]
@dsplaisted, thank you for the detailed explanation and sorry for the late reply. I understand a lot more.

To bad for me there is no way to include something in compile but not at runtime like the "Copy Local = false" feature in .NetFramework projects which I have used for a decade.

But I understand it is not a common case where the exact version of a 3rd party assembly is not available during build. For netsdk projects I will now solve it with a readme asking the users to manually exclude asset "runtime".

**Comment by adrianm64** [comment]
Wow, `ref` actually works. Thanks

"nuget pack" spit out warnings (including an undocumented one NU5131) but I just ignore them.

package.config projects does not work with `ref` (says there is no compatible assemblies or something) but there I can continue to use `lib` with a .targets file setting copylocal=false.

Just to be sure, according to the [documentation](https://docs.microsoft.com/en-us/nuget/reference/nuspec) `ref` is not a supported folder. "must begin with `lib`, `content`, `build`, or `tools`.". Is that just a documentation error?
 
My exact scenario is:
I'm working with a 3rd party product using their supplied assemblies (similar to com interop assemblies). It is important to use the assemblies matching the installed version of the 3rd party product.
Instead of building many different versions, applications are built against a generic version and then load the correct version at runtime via the LoadContext/AppDomain "Resolve" event. But this only works if the standard assembly load fails so the generic assemblies must not be part of the publish.

**Comment by KalleOlaviNiemitalo** [comment]
That seems a doc error. <https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory> includes `ref/{tfm}` though.

**Comment by zivkan** [comment]
The NU5131 warning is a known issue: https://github.com/NuGet/Home/issues/8684. It was created to ensure that packages that support packages.config also support PackageReference, but due to an oversight, it also tries to encourage package authors to make packages only compatible with PackageReference to also be compatible with packages.config, which we no longer consider important.

Hopefully we'll improve NU5131 in the next few months, but it's not currently a priority (not enough feedback/upvotes, so please add a 👍  reaction to the first comment in the NuGet/Home issue to help prioritization).

**Comment by adrianm64** [comment]
Thank you all for your input. I now know how to solve my problem.
