### ISSUE TITLE
Missing semi-colon in CoreCleanDependsOn

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#2387]
@nguerrera Saw this and it's missing a semi-colon

https://github.com/dotnet/sdk/blob/581f5371dac022ad2b3e5bcdbb2e576bd73b5c4a/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L96

**Comment by nguerrera** [comment]
Wow, not sure how that's working does CoreCleanDependsOn typically have a leading semi-colon?

**Comment by nguerrera** [comment]
Oh it's usually empty.

**Comment by onovotny** [comment]
I noticed it by inspection as I was trying to understand why https://github.com/onovotny/MSBuildSdkExtras/issues/89 was happening.

**Comment by nguerrera** [comment]
Thanks for that issue link. This would break anyone who sets CoreCleanDependsOn to non-empty without leading semicolon, which is a perfectly reasonable thing to do. Looks like we're breaking these targets: https://github.com/xamarin/XamarinVS/blob/433cfad03cfd00daf8737d248d3208c03806e677/src/MSBuild/Xamarin.Common.Targets/Xamarin.Common.targets#L12 based on a search for _CleanAllFiles across Github.

**Comment by nguerrera** [comment]
Fixed by #2388

**Comment by MichaelRumpler** [comment]
Where is that file on my harddisk with VS 15.8 pre4 installed?
I couldn't find the file where _SdkBeforeClean gets defined but I'm currently also running into https://github.com/onovotny/MSBuildSdkExtras/issues/89.

**Comment by nguerrera** [comment]
@onovotny Really? That's not expected. 

Run `msbuild /pp:preprocessed.txt`, then search `preprocessed.txt` for _SdkBeforeClean. You will see the file path as a comment.

**Comment by onovotny** [comment]
![image](https://user-images.githubusercontent.com/1427284/42959781-ed2a45e4-8b57-11e8-9bc8-ef4d2f233c2f.png)

**Comment by nguerrera** [comment]
Ah, I thought you were saying that Microsoft.NET.Sdk.targets was there. Wasn't that what @MichaelRumpler was asking or did I misunderstand.

**Comment by onovotny** [comment]
Oh, not sure :)

**Comment by MichaelRumpler** [comment]
I wanted to know, in which file I have to add that semicolon so that it works on my machine.

The file C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.Web.ImportAfter.targets only does one `<Import Project=... />`.

If I run `msbuild /pp:preprocessed.txt`, then that file is created in the current directory, but it is empty.

I searched the whole C:\Program Files (x86)\Microsoft Visual Studio for any *.targets file containing _SdkBeforeClean but didn't find anything.

However, I tried with VS 15.7 and this version could compile my project. So I'm fine with that.

**Comment by nguerrera** [comment]
Sorry, I meant run `msbuild /pp:preprocessed.txt` in the directory of your project file so that it preprocess your project file. Alternatively, you can do `msbuild /pp:preprocessed.txt path\to\project.csproj`.

Unless you've taken special install steps, the file will be in `C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets`. The version number might be slightly different (301 or 302) and it might be in Program Files (x86).
