### ISSUE TITLE
[API Compat] add rule to make sure that a member is not made more visible

### ISSUE THREAD

**Issue by safern** [dotnet/sdk#23904]
This rule should make sure that a member that is protected or protected internal in the implementation is the same in the contract and is not promoted to public.

**Comment by KalleOlaviNiemitalo** [comment]
Those compatibility rules are for "Modifications to the public contract", but the description of this issue is in terms of "contract" vs. "implementation". If the contract assembly defines a member as public but the implementation assembly defines it as protected, then a non-derived class in a project that references the contract can access the member at compile time, but the access will fail at run time when the implementation is used. So the description is correct although written as if the implementation comes before the contract.
