### ISSUE TITLE
Trailing \ or / will fail for path parameters for `dotnet test`

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/sdk#23970]
Failing sample
```cs
dotnet test C:\git\localPlayground\TestProject\ --results-directory:C:\git\localPlayground\TestProject\
...
The path 'C:\git\localPlayground\TestProject"' specified in the 'ResultsDirectory' is invalid. Error: The filename, directory name, or volume label syntax is incorrect. : 'C:\git\localPlayground\TestProject"'
```

**Comment by KalleOlaviNiemitalo** [comment]
ForwardingAppImplementation.GetProcessStartInfo() could perhaps set ProcessStartInfo.ArgumentList nowadays, instead of using ArgumentEscaper. Would that make a difference? <https://github.com/dotnet/sdk/blob/47281fb68e48ba18814cbb09981f608819ea7dd0/src/Cli/Microsoft.DotNet.Cli.Utils/ForwardingAppImplementation.cs#L76-L81>

**Comment by Evangelink** [comment]
@KalleOlaviNiemitalo I was looking at your suggestion and it seems we are stuck because of the `net472` compilation (where it wasn't introduced). I think that having two different paths could lead to more complex maintenance on our side (only my feeling, I could be wrong).
