### ISSUE TITLE
error CS8983: A 'struct' with field initializers must include an explicitly declared constructor. 

### ISSUE THREAD

**Issue by danielkon96** [dotnet/sdk#23971]
### Describe the bug
I have the following code that throws the error in the title when I try to build my project. It was not happening on build engine 17.0.0+c9eb9dd64 but now happens on 17.1.0+ae57d105c. The error code is no new there is no documentation around it. I first found it when building my project in GitHub Actions.

### To Reproduce
```
public struct AppManifestResult
{
    public bool Succeeded { get; set; } = false;
    public Exception? Exception { get; set; } = null;
    public AppManifest? AppManifest { get; set; } = null;
}
```

### Further technical details

> C:\Users\dakondra\source\repos\EasyAuthForK8s\src\EasyAuthForK8s.Web\Models\AppManifest.cs(118,19,118,36): error CS8983: A 'struct' with field initializers must include an explicitly declared constructor.
> 1>Done building project "EasyAuthForK8s.Web.csproj" -- FAILED.
- VS 2022 version 17.1

**Comment by KalleOlaviNiemitalo** [comment]
The change was discussed in <https://github.com/dotnet/csharplang/issues/5552>, and <https://github.com/dotnet/roslyn/pull/58581> added the error. It has been documented at <https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/parameterless-struct-constructors#definite-assignment>, but <https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#parameterless-constructors-and-field-initializers> still claims it's OK to have no explicit instance constructors if all fields have initializers.

I'm surprised that the change applies to C# 10 too, rather than just 10.1 or 11.
