### ISSUE TITLE
Installing workloads fails when using rollback files with workloads that only exist in a previous band

### ISSUE THREAD

**Issue by mattleibow** [dotnet/sdk#24368]
### Describe the bug
I get an exception if a workload only exists in an older band and I use a rollback file to install it for the new band. 

Unhandled exception: System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.sdk.android\WorkloadManifest.json'. 

### To Reproduce

1. Install the 200 and 300 sdk bands
2. Delete the workload manifest folders for the 300 bands. Not sure if it matters with the entire 300 folder of just a workload folder
3. Run a workload install for a workload that only exists in the 200 band (ie: one of the workloads you just deleted from the 300)

I know this is crazy to go in there and delete folders, but sometimes I have to do this to work around other bugs - notably the last one where you can't specify workload bands in rollback files. Also, this should work. I am using a rollback file so it should just plonk the new files there and not try read it. 

### Exceptions (if any)
System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\sdk-manifests\6.0.300\microsoft.net.sdk.android\WorkloadManifest.json'. 

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by marcpopMSFT** [comment]
I think you're just hitting another form of this bug: https://github.com/dotnet/sdk/issues/23402  Feel free to reopen if I'm wrong and this is a distinct scenario.

**Comment by mattleibow** [comment]
Maybe... I am doing terrible things. Once things get fixed I will re-evaluate.

**Comment by inforithmics** [comment]
I had a similar issue but with the 6.0.100 and 6.0.200 Band. Because it tried to remove old workload installs which wheren't availble because I removed the whole dotnet folder.
The only solution to make my machine working again, was to force deinstall all old workload installs with Windows Install Clean Up. 
Which made me sad because I thought the workloads are only copied in the right place and not fully fleged installers which  need to be uninstalled when removing them (Delete the folder is not sufficient).
