### ISSUE TITLE
SDK should add NETStandard.Library v2.x reference instead of the NETStandard.Library v1.6.1

### ISSUE THREAD

**Issue by LakshanF** [dotnet/sdk#24799]
### Describe the bug
SDK seems to be pulling in old version of a package like `"System.Private.Uri": "4.3.0"` when adding the package  Microsoft.DiaSymReader. The old version has component compliance concerns like, https://msrc.microsoft.com/update-guide/vulnerability/CVE-2019-0820. This seems to be happening since the SDK has a reference to netstandard like here, [1.6.1](https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L47-L55). The reference to old package version goes away if the latest NETStandard.Library (v2.x) is pulled in.

### To Reproduce

```
dotnet new console
dotnet add package Microsoft.DiaSymReader
dotnet publish -c Release -r win-x64

```

Observe: bin\Release\net6.0\win-x64\publish\test.deps.json contains references to vulnerable System.Private.Uri version that was brought in via NETStandard 1.6.1 package that is implicitly added by the SDK

The reference to the old System.Private.Uri goes away if the SDK adds the NETStandard.Library v2.x package instead of the old version

**Comment by teo-tsirpanis** [comment]
The issue of DiaSymReader will be fixed with dotnet/symreader#252. What I would recommend the SDK to do instead is to _warn_ if a library targets only .NET Standard 1.x and not 2.0.

**Comment by ViktorHofer** [comment]
> SDK seems to be pulling in old version of a package like "System.Private.Uri": "4.3.0" when adding the package Microsoft.DiaSymReader. The old version has component compliance concerns like, https://msrc.microsoft.com/update-guide/vulnerability/CVE-2019-0820. This seems to be happening since the SDK has a reference to netstandard like here, [1.6.1](https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets#L47-L55).

I would rephrase this slightly: This seems to be happening because Microsoft.DiaSymReader depends on NETStandard.Library/1.6.1 which brings in packages like System.Runtime/4.3.0 which depend on Microsoft.NETCore.Targets/1.1.0 which itself depends on System.Private.Uri/4.3.0 (via the package's runtime.json file).

By adding an explicit package reference to NETStandard.Library/2.0.*, the dependencies to old packages like System.Runtime disappear and hence System.Private.Uri isn't part of the dependency closure anymore.

Given that most packages in the ecosystem already target netstandard2.0 this issue will likely disappear in the future without any action taken by the SDK. That said, I'm not saying that it wouldn't make sense for the SDK to stop referencing the older version of NETStandard.Library.

FWIW nightly builds of the Microsoft.DiaSymReader package (available in the dotnet-tools feed) already contain a netstandard2.0 tfm that doesn't bring the problematic dependency closure in anymore.

**Comment by dsplaisted** [comment]
I think that just updating to the reference to version 2.0 of the NetStandard.Library package won't help projects that target .NET Standard 1.x.  They'll still get the same old references.

So I think the solution is for packages to target .NET Standard 2.0.
