### ISSUE TITLE
Share package fallback cache across SDKs

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#2516]
According to @chrisrpatterson in https://github.com/Microsoft/vsts-image-generation/issues/223#issuecomment-418936380, each version of the .NET Core SDK has its own copy of the package fallback cache. As a result, decompressing the package fallback cache with one SDK does nothing for the package restore performance of another SDK. Why is that?

Given the fallback cache is a bunch of packages, it seems harmless and beneficial to share the cache across all versions of the SDK:
1. Less hard disk space
1. Decompressing from one SDK makes those packages available for another version of the SDK to use if it doesn't decompress its own. And if it does decompress its own package versions, it's an incremental addition to the original cache and thus will still be faster.

What % of packages in the cache are unique in each SDK version? I'm guessing it's a small number.

**Comment by chrisrpatterson** [comment]
I am not quite sure I said that. 
What I think happens is each SDK install location seems to have one.  The other issue could be that each particular version of the SDK check to see if its first run has happened.

**Comment by AArnott** [comment]
Sorry for misquoting. What I think we can say though is the issue I linked to in this issue description describes a significant perf issue where an additional SDK version that is installed still takes 2 minutes to unpack a fallback cache even though that has already been done on the first SDK version.

**Comment by dasMulli** [comment]
Looks like the fallback cache approach is going away completely for 3.0: https://github.com/dotnet/cli/issues/9910

**Comment by livarcocc** [comment]
Besides what @dasMulli has said, each SDK has their own version of the cache, because that cache is comprised of different package versions based on the runtime versions the SDK ships with.

If there is an overlap of packages, said packages are not duplicated, since there is only one fallback folder. So, what ends up being duplicated effort is really going through the process of extracting the package, which on most cases happens once per SDK version.

We have a sentinel per SDK version for this.

Given that the big cost here is the cache expansion time and given that we won't be using the lzma on 3.0 anymore, I am going to close this issue.
