### ISSUE TITLE
Warning appears about not specifying self-contained when PublishAot are set

### ISSUE THREAD

**Issue by agocke** [dotnet/sdk#25808]
I think we should just set self-contained to true in these situations. FX-dependent is not supported, so this is just noise.

@richlander would you agree with this?

**Comment by agocke** [comment]
cc @MichalStrehovsky

**Comment by richlander** [comment]
Yes. Although, only for `dotnet publish`.

**Comment by agocke** [comment]
Agreed

**Comment by agocke** [comment]
I forgot that we might support trimming for FDD. In that case we can skip PublishTrimmed and just do this for PublishAot.

**Comment by richlander** [comment]
I'm wondering if we should give a different name to single file + fdd. I'm not convinced that pivoting in this way makes sense.

I'm happy to work on a short doc with some options if that would help.

**Comment by LakshanF** [comment]
Given the multiple scenarios for the 3 different form factors, I think its best if we restrict this issue to PublishAot and have a doc to describe the high level thinking

- Aot: We will assume SCD if its not specified since FDD does not make sense for this form factor. The target [here ](https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L1117-L1121)generates the warning.
- Trimming: Currently only supports SCD but there are customer requests for FDD. Ok to generate the warning if App type is is not specified
- SingleFile: Already supports both FDD and SCD

**Comment by LakshanF** [comment]
Fixed with #25927
