### ISSUE TITLE
source-build rid fails to publish: targeting runtime did not resolve any runtime-specific packages

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#2605]
[source-build](https://github.com/dotnet/source-build) automagically patches the known rid files when built on a new version of a distro.

The publish operation using that new rid fails with an error message: Project is targeting runtime 'xxx' but did not resolve any runtime-specific packages. This runtime may not be supported by the target framework.

This message comes from:

https://github.com/dotnet/sdk/blob/62632dd6369517e9a7a01dd68cbbdc126ca43a5f/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs#L823-L833

My expectation is this should work, because the dependencies were resolved using a 'higher' rid (e.g. linux-x64).

Maybe the severity of the message can be adjusted?

To force this to work, it is possible to specify the '/p:EnsureRuntimePackageDependencies=false`.

CC @nguerrera

**Comment by nguerrera** [comment]
That check wouldn’t disallow getting the assets from linux-x64 or another compatible RID. With EnsureRuntimePackageDependencies=false, does the resulting self-contained app actually have all the runtime files?

The rid graph used by nuget restore is obtained from the Microsoft.NETCore.Platforms package (not hard coded, another package could also supply runtime.json). If that's pulled from nuget.org, it wouldn't see any patches.

This is subject to change in 3.0 where we expect the sdk to carry the graph, which might help to make this work as you expect.

That said, if you expect all assets to come from linux-x64, then why publish for the new rid instead of linux-x64? 

If you actually want RID specific assets for the new RID, then those assets would need to have packages in the graph too.

**Comment by tmds** [comment]
> The rid graph used by nuget restore is obtained from the Microsoft.NETCore.Platforms package

Ah, based on the error message I had assumed the RID was known but there were no specific packages that matched the rid exactly.
For an unknown rid, you get the same error message.

>  does the resulting self-contained app actually have all the runtime files?

I published --self-contained=false which worked. --self-contained is missing the files.

> That said, if you expect all assets to come from linux-x64, then why publish for the new rid instead of linux-x64?

I knew source-build was doing some patching for the rid. So my expectation was the source-build sdk would be able to publish for that rid.

**Comment by nguerrera** [comment]
Note that --self-contained=false would not work in general either if there were rid-specific, non framework assets in the graph.

**Comment by tmds** [comment]
> This is subject to change in 3.0 where we expect the sdk to carry the graph, which might help to make this work as you expect.

That is a desired change. For source-build, we prefer the resulting sdk as much as possible to be self-sufficient.

I'll close this issue.

PS: Maybe the sdk should give a clear error message when trying to publish for an unknown rid. I did not realize this was the cause based on the message I got.
