### ISSUE TITLE
How can I install the Microsoft.WindowsDesktop.App version 6.0.0 framework in an azure app service?

### ISSUE THREAD

**Issue by Moeahmad94** [dotnet/sdk#26688]
Hi,

I have an api project targeting net6.0-windows10.0.22000.0 due to a windows dependency that I'm trying to run as an azure app service. It runs fine locally in VS 2022 but when I deploy and try to run it in azure, I get an error saying: "The framework 'Microsoft.WindowsDesktop.App', version '6.0.0' (x86) was not found."

Is there any way for me to install that framework to the app service? I don't see it available in the Extensions section in the azure portal and I can't install the Microsoft.WindowsDesktop.App.Runtime.win-x86 nuget package because its type is DotnetPlatform, which is incompatible with the project. Is there something else I could do to unblock this? I reached out to Azure Support and they suggested I reach out to the ASP.net dev team.

Please and thanks,
Moe

**Comment by RussKie** [comment]
Are you trying to deploy to a Windows box or a Linux box? Windows Desktop workload, as the name implies, is only available on Windows.

**Comment by NickCook-StruMIS** [comment]
Hi, i have exactly the same problem but trying to install Microsoft.WindowsDesktop.App 3.1x to an Azure App Service. The extensions does not cover it. I have a dotnet Asp core 3.1 app that unfortunately relies on Microsoft.WindowsDesktop.App 3.1x.
I can see the error message clearly in the cmd shell and browsing to C:\Program Files (x86)\dotnet\shared, i can see that it is not installed. So i have the same question above as Moeahmad94 and yes this is all Windows not Linux.

**Comment by Moeahmad94** [comment]
Hi Russ, apologies for the late reply. I am trying to deploy to a Windows box. Please let me know if there's any additional information I can provide to help with this. Feel free to contact me over Teams if that's easier, especially if screensharing may help - my alias is moahm.

**Comment by RussKie** [comment]
You need to install Windows Desktop runtime, you can get it from https://dotnet.microsoft.com/download/dotnet/6.0 and https://dotnet.microsoft.com/download/dotnet/3.1.

> Is it possible to upload the Microsoft.WindowsDesktop.App setup to the app service and run the install from the console shell?

You may need to contact the owners of that service and ask them.

**Comment by RussKie** [comment]
I had some internal discussions, and here are the outcomes:

a) this issue is outside of realms of .NET and within the realms of Azure AppService.
b) Azure AppService team will very unlikely provide any customisation out of the box given their sheer breadth of deployment. That's said you could try raising a feedback with the team. I don't have any contacts available, but you can probably find something from their website https://azure.github.io/AppService/.
c) If you're using a docker container you could install additional workloads yoruself.
d) if all else fails, you'd need to deploy your apps as ["self-contained"](https://docs.microsoft.com/dotnet/core/deploying/), but you'll have to assume responsiblity for patching the runtime.

Hope this helps.
