### ISSUE TITLE
Error meesage is unclear when trying to publish to an unsupported RID

### ISSUE THREAD

**Issue by ww898** [dotnet/sdk#26866]
The error always appears on Windows x64 with RuntimeIdentifier `osx-arm64`:
```
<path_net60>\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(99,5): error NETSDK1084: There is no application host available for the specified RuntimeIdentifier 'osx-arm64'.
```
Repro:
```
set _PkgDir=C:\1
set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
set DOTNET_MULTILEVEL_LOOKUP=0
if not exist "%_PkgDir%" mkdir "%_PkgDir%"
<path_net60>\dotnet.exe publish --packages "%_PkgDir%" --self-contained true -f net6.0 -r osx-arm64
```

nuget.config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget-org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
  </packageRestore>
</configuration>
```

**Comment by richlander** [comment]
I don't know what `--packages` does. I don't see it documented.

**Comment by marcpopMSFT** [comment]
Since arm64 is now supported, this message won't come up unless we end up with another combination of platforms where we haven't released apphosts for yet. While the error isn't great, I think it's unlikely to happen very frequently.

As for --packages, that will be passed to the nuget restore as the location to restore packages for. Maybe we should update our help CLI but we have a lot of commands we forward to other commands that we don't document.
