### ISSUE TITLE
SDK causes Segmentation Faults whenever I run essential cli commands.

### ISSUE THREAD

**Issue by LukeZerafaOffical** [dotnet/sdk#27174]
### Describe the bug
I am a Pop_Os user. I was using dotnet normally and everything was working well. All of sudden whenever I tried to use dotnet build or run. It says segmentation fault. I can still how ever use dotnet --version and displays the correct output of 6.0. I have been trying to figure out how to solve this for so long. I really do not want to reinstall the distro.

I have tried various methods of downloading the dotnet core, NONE have worked and I don't know what to do.

Please help.

**Comment by AraHaan** [comment]
Reinstall the .NET SDK, it might have been corrupted.

**Comment by LukeZerafaOffical** [comment]
I have done that multiple times using various methods. I used snap, used the script and even the manual installation. It didn't give me segmentation error but it would either not recognise the SDK or not even recognise the dotnet command.

I am all up to try again, just be aware that I have tried and none where successful

**Comment by AraHaan** [comment]
Perhaps a dependency of the .NET SDK is causing this?

**Comment by LukeZerafaOffical** [comment]
I will see what I can do and try and repair the OS

**Comment by LukeZerafaOffical** [comment]
> 

Yh i factory reset my OS, i have no clue why this is still happening.

**Comment by danmoseley** [comment]
I'm am not familiar with Pop!_Os. I see it is based on Ubuntu but we don't test on it so perhaps there's some difference in the OS or dependent packages that is relevant.

Do you have another machine with the same OS that you can test on? Although since you did a reset we can likely assume it would have the same result.

Can you get a stack backtrace at the point of the fault? LLDB or gdb which ever is easiest. That might give a hint.

**Comment by danmoseley** [comment]
https://github.com/dotnet/diagnostics/blob/main/documentation/lldb/linux-instructions.md 

To get symbols you need a tool that may not work on the system due to the problem you're debugging. You may find it easiest to create a core dump and move it to another machine. This may help

https://github.com/dotnet/diagnostics/blob/main/documentation/debugging-coredump.md

**Comment by marcpopMSFT** [comment]
I wonder if it's similar to this issue that is fixed in 7.0.100: https://github.com/dotnet/runtime/issues/72308

**Comment by marcpopMSFT** [comment]
closing as the linked runtime issue was resolved. Let us know if this is still happening.
