### ISSUE TITLE
RID publish as framework dependent app produces broken app on Linux

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/sdk#2722]
The simplest repro:

On Linux (I used Ubuntu 18)
install .NET Core SDK 2.2.100
run:
`mkdir webapp`
`cd webapp`
`dotnet new web`
`dotnet publish -c release -r linux-x64 --self-contained false`
`./bin/release/netcoreapp2.2/linux-x64/publish/webapp`

This will fail to find a usable framework to run on.

The root cause is that when we publish a RID specific (so with apphost) app as framework dependent, for some reason the SDK includes `hostfxr` and `hostpolicy` libraries in the published folder. The `apphost` searches for `hostfxr` first in the local folder, then in global locations. Since it finds it in the local folder it uses that. Then it tries to resolve a framework, but on Linux where there is no global location for frameworks, it looks only in the local folder... and fails.

On Windows to works "by luck", we still load the `hostfxr` from the app, but then since we do have global location for frameworks, we end up loading the framework from the global location.

Deleting the `hostfxr` and `hostpolicy` from the publish folder doesn't help, because for some reason they are listed as native runtime assets in the `.deps.json`. In fact there are native assets for `hostpolicy`, `hostfxr` and `apphost` which won't resolve at runtime either.

The SDK should not include `hostfxr`, `hostpolixy` in the publish folder and it should not include dependencies to the `Microsoft.NETCore.DotNetHostPolicy`, `Microsoft.NETCore.DotNetHostResolver` and `Microsoft.NETCore.DotNetAppHost` in the `.deps.json` since those bring wrong native assets.

**Comment by livarcocc** [comment]
adding @peterhuene here for FYI, even though he is OOF right now.

cc @nguerrera in case he can think of anything.

Does this happen even when you execute the app through dotnet or just if you use the apphost? Also, have you tried setting DOTNET_ROOT?

**Comment by nguerrera** [comment]
Does `<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies> change the behavior here?

**Comment by nguerrera** [comment]
Oh, this is 2.2.100. Then it must be something else that causes this.

**Comment by vitek-karas** [comment]
The original report is on 2.1 but the repro steps above are on 2.2.100.

**Comment by vitek-karas** [comment]
Running it through `dotnet path_to_dll` works - even on the published folder. Although in this case it does unnecessary work for the native assets. But it works.

**Comment by vitek-karas** [comment]
I tried the `CopyLocalLockFileAssemblies` set to false - but it made no difference.

**Comment by nguerrera** [comment]
(I did not expect it to, once I saw the repro was outside 3.x)

**Comment by nguerrera** [comment]
This appears to happen for `dotnet new webapp` but not `dotnet new console`

**Comment by vitek-karas** [comment]
Interesting - tried it on the Linux and I can confirm that console works just fine.
Given that difference I tried is this is related to `PreserveCompilationContext`, but no - still broken even with that set to false.

**Comment by nguerrera** [comment]
I think it might be due to the different PlatformLibrary. It seems to break at the point where we trim out things that come via that.

**Comment by peterhuene** [comment]
I'll look into this now that I'm back from vacation.

**Comment by peterhuene** [comment]
This appears to be behavior ever since ASP.NET Core moved to being a shared runtime (i.e. SDK 2.1.300).

The filtering done by the former `ResolvePublishAssemblies` task takes a singular `PlatformLibraryName`, which in 2.1 and 2.2 was `Microsoft.AspNetCore.App`.  This results in the `ResolvedAssembliesToPublish` item list containing the `Microsoft.NETCore.App` assemblies (including the two `host*` libraries), despite `SelfContained` being set to `false`. 

When we resolve conflicts for the publish, we filter out most of the `Microsoft.NETCore.App` assemblies because they conflict with assemblies from the platform manifest (which is only `Microsoft.NETCore.App.PlatformManifest.txt` 😕).  However, three files don't come from a package in the platform manifest: `apphost` (not renamed in 2.1, customized in 2.2), the `hostfxr` library, and the `hostpolicy` library.  As a result, these files get copied for publish of a framework-dependent application 😞.

For 3.0, we operate differently in multiple ways:

* The platform library is now `Microsoft.NETCore.App` and not `Microsoft.AspNetCore.App`; the latter is now an additional "runtime framework" resolved via framework references.
* By default, we use the output of `ResolvePackageAssets` for publishing, which can correctly determine the transitive closure of the dependencies from the platform library and runtime frameworks, thus marking anything from the `Microsoft.NETCore.DotNet*` packages as not be to be copied local when deploying as framework-dependent.  **As a result, the `host*` libraries are not copied for publish.**
* When falling back to 2.2 publish logic (for limited scenarios primarily involving the use of a 2.0-era runtime store), we now have the reverse: we output the `Microsoft.AspNetCore.App` assemblies instead of the `Microsoft.NETCore.App` assemblies from the `ResolveCopyLocalAssets` task (previously the `ResolvePublishAssemblies` task) because `PlatformLibraryName` is `Microsoft.NETCore.App`.  When conflicts are resolved, we filter the `Microsoft.AspNetCore.App` assemblies because `Microsoft.AspNetCore.App.PlatformManifest.txt` is used as an additional platform manifest.  **Unintentionally, this also results in the `host*` libraries not being published because they were never made a candidate for copying.**

I'm going to resolve this as fixed for 3.0.

If we desire to fix it for 2.1 or 2.2, I would suggest adding `apphost` and the `host*` libraries to `Microsoft.NETCore.App.PlatformManifest.txt` so they also get filtered during conflict resolution.

**Comment by nguerrera** [comment]
This was ultimately fixed for next 2.2 patch release. It was tracked by duplicate bug dotnet/cli#10602.
