### ISSUE TITLE
Add publish capabilities for SDK based ClassLibraries and ConsoleApps

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/sdk#2747]
Per our discussion with @nguerrera and @davkean we need to switch to new capabilities schema for publish (see below). To accomplish that one of the workitems is to add

- FolderPublish to SDK-based class libraries and console apps , along with WPF and WinForms (if it is not present yet)
- AppServicePublish to SDK-based class libraries and console apps 

This needs to happen in P2 and earlier rather than later since Publish would need to commit and test changes after all capabilities are added.

Capabilities 
 
•         "Publish": all projects that support any kind of publish should contain this capability
o    All .NET project types
•         "FolderPublish": if project supports publishing to folder
o    Class libraries  (classic and core). Note: we don't own Publish for classic class libraries and classic ConsoleApps, ClickOnce does. There should be separate work item tracking ClickOnce support for our publish framework. However we can add capability now and it would light up when ClickOnce adds apublish provider.
o    Console app (classic, core). 
o    WebSites, WAP, Web core
o    WPF (core and classic)
o    WinForms (classic and core)
•         "AppServicePublish": if project is publishable to any web related publish target: Web, AppService, etc 
o    Console apps (classic and core)
o    WebSites, WAP, Web core
 
Potential pending capabilities:
•         "ClickOnce"
o    Classic console apps
o    WPF (classic)
o    WinForms (classic)
•         "MSIX"
o    Console apps (classic and core)
o    WPF (classic and core)
o    WinForms (classic and core)
 
 
 
Providers 
 
•         FolderProvider: AppliesTo("Publish&FolderPublish")
•         AppServiceProvider: AppliesTo("Publish&AppServicePublish")
•         IISProvider: AppliesTo("Publish&Web")
•         AzureVMProvider: AppliesTo("Publish&Web")
•         AppServiceLinuxProvider: AppliesTo("Publish&DotNetCoreWeb")
•         ContainerRegistryProvider:AppliesTo(Publish&AppServicePublish&(Web|DotnetCoreWeb))
•         ClickOnceProvider:AppliesTo(Publish&ClickOnce)
•         MSIXProvider:AppliesTo(Publish&MSIX)
 
 
Workitems:
 
•	Add FolderPublish to WPF and WinForms (classic and core), Class Libraries and Console Apps (classic and core). Some of them already have it , just make sure all of them have. <- CSharp & SDK
•	Add AppServicePublish to Console apps (classic and core) <- CSharp and SDK
•	Add AppServicePublish to WebSites, WAP, and Core Web <- WAP and WebSdk
 
ClickOnce and MSIX I would leave to their owner to request/add when they are ready.

**Comment by nguerrera** [comment]
@davkean My understanding is you were still thinking about whether this should go in design-time targets or SDK targets. I am holding off on this until you signal that we should make the change in SDK targets.

**Comment by nguerrera** [comment]
Also, if this goes in SDK targets, we need to know if this is for the version of SDK in VS and up or 3.0 and up only. 

Before all of the above, the request started as specific to WinForms and WPF capabilities which would have been only supported in 3.0 and up.

**Comment by abpiskunov** [comment]
It should be in what VS ships and up. Originally we wanted to exclude WPF/WinForms in 3.0 yes, but now we switched to do a proper capabilities schema.

**Comment by nguerrera** [comment]
Ignoring "pending" and classic cases that don't go in targets, I think we're left with:

* "Publish" for all Microsoft.NET.Sdk projects
 * This is already here: https://github.com/dotnet/project-system/blob/0e77773302b329e1cbc71bb419b6f523a8a6b2b2/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L110

* "FolderPublish" for all  to Microsoft.NET.Sdk projects
  * This is already here: https://github.com/dotnet/sdk/blob/c93f4a14ebcff4a18840b06886c5dcf24ae64a0e/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L585-L588

(The fact that above are mixed between design-time targets and sdk seems arbitrary)

This leaves only the following AFAICT:

* "AppServicePublish" for all Microsoft.NET.Sdk Exe projects, except WPF and WinForms exes?
  * This does not exist yet
  * Similar case is "CrossPlatformExecutable": https://github.com/dotnet/sdk/blob/c93f4a14ebcff4a18840b06886c5dcf24ae64a0e/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L576
  * We can add it to the same spot in the code (if we're not deciding to use design-time targets for this)
  * Maybe instead of _IsExecutable (which is OutputType==exe or winexe), it should be Exe and only Exe here
  * That is probably right for "CrossPlatformExecutable" too. WinExes are not cross-platform.
  * Who uses CrossPlatformExecutable today.

**Comment by nguerrera** [comment]
> It should be in what VS ships and up

Set milestone accordingly.

**Comment by nguerrera** [comment]
Is Exe condition sufficient for "Core Web" case for AppServicePublish? I am guessing yes because web sdk sets the output type to exe.

**Comment by davkean** [comment]
VS spans SDKs versions, so this cannot be put into the SDK. I think we need to introduce a concept on our side of a file that is in sync with platforms and platform versions, but ships with VS to light them up.

**Comment by davkean** [comment]
Think like a targeting pack concept but contains capabilities/design-time stuff.

**Comment by abpiskunov** [comment]
@davkean What is the action item here? Christmas is close and i am oof after NY ...  ;)

**Comment by nguerrera** [comment]
This issue was moved to dotnet/project-system#4397
