### ISSUE TITLE
Dependent projects building to same output dir fail to Rebuild

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/sdk#28355]
### Describe the bug
When I have two projects, one which depends upon the other, that build to the same output directory, I can build both projects successfully but rebuilding them fails with an error.

### To Reproduce

1. Clone https://github.com/yaakov-h/dotnet-sdk-dependentprojrebuild
2. Open the solution file in VS2022
3. Select _Build > Build Solution_
4. Select _Build > Rebuild Solution_

### Exceptions (if any)
```text
2>------ Rebuild All started: Project: MyConsoleAppTests, Configuration: Debug Any CPU ------
2>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5097,5): error MSB3030: Could not copy the file "C:\Temp\sameoutputdir\bin\net6.0\MyConsoleApp.runtimeconfig.json" because it was not found.
2>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5097,5): error MSB3030: Could not copy the file "C:\Temp\sameoutputdir\bin\net6.0\MyConsoleApp.deps.json" because it was not found.
2>Done building project "MyConsoleAppTests.csproj" -- FAILED.
```

### Further technical details

`dotnet --info`:

<details>

```text
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  3.1.423 [C:\Program Files\dotnet\sdk]
  5.0.411 [C:\Program Files\dotnet\sdk]
  6.0.109 [C:\Program Files\dotnet\sdk]
  6.0.304 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

</details>

Microsoft Visual Studio Professional 2022 (64-bit) Version 17.3.3

**Comment by marcpopMSFT** [comment]
In general, we do not recommend compiling multiple projects to the same exact output directory specifically because there can be overwritten files. If they depend on each other, a post-build copy or publish step might make more sense.  @dsplaisted do we have any good guidance here?  I don't recall us having that.

**Comment by matman13** [comment]
Is there any update to this?  I'm seeing the same problem with Visual Studio 2022 Enterprise v17.4.4.

```
25>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): error MSB3030: Could not copy the file "C:\GitLab\MyProj\Source\bin\Debug\MyProj.Support.UnitTests.deps.json" because it was not found.
25>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5150,5): error MSB3030: Could not copy the file "C:\GitLab\MyProj\Source\bin\Debug\MyProj.Support.UnitTests.runtimeconfig.json" because it was not found.

```

**Comment by dsplaisted** [comment]
You can set the [`UseCommonOutputDirectory`](https://learn.microsoft.com/visualstudio/ide/how-to-change-the-build-output-directory#build-to-a-common-output-directory) property in your projects to true.  This fixed the rebuild issues for me.  I don't think we've used or tested this property much with the .NET SDK, so there may be other things that don't work.  If so, you can file a new bug here.

If you do want to use a common output directory, I'd recommend putting something like the following in a `Directory.Build.props` file in your solution root:

```xml
<Project>

  <PropertyGroup>
    <UseCommonOutputDirectory>true</UseCommonOutputDirectory>
    <OutputPath>$(MSBuildThisFileDirectory)\bin</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

</Project>
```

This will set all projects under that folder to use the same output path.  `AppendTargetFrameworkToOutputPath` is set to false so that the output goes directly in the folder specified instead of in a subfolder such as `net6.0`.  If any of your projects are multi-targeted, you shouldn't set this property to false, as then the builds for different TargetFrameworks of a project will conflict with each other.

@baronfel Can we add this information / guidance to the docs?  Probably this page: https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props

**Comment by matman13** [comment]
IIRC, the [UseCommonOutputDirectory](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-change-the-build-output-directory?view=vs-2022#build-to-a-common-output-directory) property does seem to fix this problem, but causes another problem that prevents the application from running.  I haven't had time to try to track it down.

**Comment by dsplaisted** [comment]
Using the repro project from the original post for this issue, the app seemed to run OK.  But it was a very simple console app.  If you can provide more info about how it's failing or ideally a repro I'd be interested in hearing.

**Comment by marcpopMSFT** [comment]
an alternative of routing to a shared artifacts path (though not the same exact directory) is coming out in .NET 8. Closing this issue as we haven't seen a response and going to the same exact output directory is known to have issues.
