### ISSUE TITLE
[NETSDKE2E]Error happens "Workload installation failed: Access to the path 'C:\ProgramData\dotnet\workloads\Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64\7.0.0-rtm.22507.1\msi.json' is denied." when installing workload using another account.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#28450]
1.Install RTM SDK(7.0.100-rtm.22510.12) and then install workload with below command in CLI
2.dotnet workload install wasm-tools --skip-manifest-update
3. **add another domain account as a admin into current machine**
![image](https://user-images.githubusercontent.com/65637796/195047911-8d10e027-602b-42a7-987b-ba5e5dc42cfc.png)

4. Login with anther domain account and then install workload with below command in CLI
dotnet workload install maccatalyst --skip-manifest-update
**Below error happens**
Workload installation failed: Access to the path 'C:\ProgramData\dotnet\workloads\Microsoft.NET.Runtime.MonoAOTCompiler.Task.Msi.x64\7.0.0-rtm.22507.1\msi.json' is denied.
![image](https://user-images.githubusercontent.com/65637796/195038813-26931c83-3f82-44ed-85dd-8ea53ce111ea.png)

Note:
1. Folder 7.0.0-rtm.22507.1 permission as below.
![image](https://user-images.githubusercontent.com/65637796/195039716-ba119937-fb2c-46b2-b439-5ace06cdaa09.png)

![image](https://user-images.githubusercontent.com/65637796/195039971-77202d7d-f69f-4802-b005-0d34483c1b0f.png)

2. Run cmd as an administrator and then install workload successfully without any issue.

**Comment by joeloff** [comment]
@vdanche did it not prompt you to elevate when you tried to install the workload as the second user. It should only write to the cache once successfully elevated.

Can you share the workload installation log from the second user? It should be in that user's %temp% folder.

**Comment by vdanche** [comment]
@joeloff  Only prompt UAC dialog when we tried to install the workload as the second user and no any other prompt during installation.
![image](https://user-images.githubusercontent.com/65637796/195489537-cd012de3-6a35-4aec-89e2-de74ef3e36be.png)


Log has been attached.
[Temp.zip](https://github.com/dotnet/sdk/files/9770069/Temp.zip)

**Comment by joeloff** [comment]
Think I understand the problem. When the first user runs the installs the workload, we first check the workload cache to see if we previously downloaded the MSI. If we have, we use the cached version, etc. If not, the MSI and its manifest is downloaded to a random folder where we do some preliminary checks before moving the file into the cache. The cache is created to inherit permissions, but because we're moving the files, it's not getting the read/execute for everyone and pulling the specific user ACE, When the second user performs a workload operation, we fail to check the cache, because the user has no read permissions on the file.

The fix is fairly simple. Once we move the file, we need to remove and then explicitly configure necessary ACEs on the files in the cache.

**Comment by vdanche** [comment]
@joeloff  This issue is not fixed on 7.0.100 SDK GA build, right?

**Comment by joeloff** [comment]
Correct, we're going to fix this in servicing because the fix for 7.0 will be slightly different and also because it did not meet the bar for fixes this late during GA.

**Comment by vdanche** [comment]
Checked on 7.0.200, this issue still repro.

**Comment by vdanche** [comment]
@joeloff 
We checked on NET 7.0.101, this issue not repro,  
But for NET 6.0.404, it still repro.

**Comment by vdanche** [comment]
@joeloff Today we checked on 6.0.405(January update) SDK, this issue still repro. Want to know which build we should pick up for 
 verifying this bug? thanks

**Comment by joeloff** [comment]
We haven't fixed this in 6.0 yet.
