### ISSUE TITLE
dotnet nuget push not working after GitHub packages changes (10/10/22)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/sdk#28545]
### Describe the bug

It seems the new "Consolidated owner and admin role" changes in GitHub packages are causing CI steps pushing to GitHub packages to fail, and I couldn't find a clear explanation on how to fix this through `dotnet nuget push`. See: https://github.com/Sergio0694/ComputeSharp/issues/403. I'm currently using this command:

```
dotnet nuget push "artifacts\*.nupkg" --source "https://nuget.pkg.github.com/ComputeSharp/index.json" --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
```

Which so far has always worked just fine. This broke a few days ago following those changes. Is there guidance on how to update scripts using `dotnet nuget push` to account for these recent GitHub changes? Not sure what additional params I should pass, if any.

### To Reproduce

See this CI run: https://github.com/Sergio0694/ComputeSharp/actions/runs/3242075036/jobs/5315478395.

### Exception

```
Pushing ComputeSharp.Pix.2.0.0-alpha.3242075036+6131b7f9b0d2ee95c98e5e76a5f5bafe62ef74ae.nupkg to 'https://nuget.pkg.github.com/ComputeSharp'...
  PUT https://nuget.pkg.github.com/ComputeSharp/
warn : Source owner 'ComputeSharp' does not match repo owner 'Sergio0694' in repository element.
  BadRequest https://nuget.pkg.github.com/ComputeSharp/ 380ms
error: Response status code does not indicate success: 400 (Bad Request).
```

### Further technical details

- Using the 6.0.402 .NET SDK

**Comment by DPatrickBoyd** [comment]
in case anyone is scratching their head trying to fix this, I tracked down @Sergio0694 's github, and saw that he changed the source to the org or user level index, instead of the index for the repo itself

in their case it was changing
https://nuget.pkg.github.com/ComputeSharp/index.json

to 

https://nuget.pkg.github.com/${{github.repository_owner}}/index.json

this also works for organizational level builds as well (at least for me), so if you replace repository_owner with your org name, it should work
