### ISSUE TITLE
Introduce `--aot` for simplify `PublishAot`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#28615]
### Is your feature request related to a problem? Please describe.

It's would be easier to publish for aot

### Describe the solution you'd like

``` sh
dotnet publish --aot
```

**Comment by MichalStrehovsky** [comment]
We explicitly advise people to place `<PublishAot>true</PublishAot>` into the project file. Then `dotnet publish` will just publish with AOT. The reason for this guidance is that PublishAot not only publishes the app as AOT on publish, but also enable a bunch of tools that make the experience better (source analyzers to generate warning for code that can be problematic at runtime with AOT, emulation of AOT behaviors at debug time, etc.).

An `--aot` argument to publish defeats this because we won't know at source code edit time, or debug time, that the user intends to publish with AOT later.
