### ISSUE TITLE
[release/7.0.2xx] Runtime fails to generate native System.Private.CoreLib in source-build bootstrap

### ISSUE THREAD

**Issue by lbussell** [dotnet/sdk#29177]
I have been looking at this issue for a little bit and can't seem to make any progress, so I'm hoping someone here can point me in the right direction.

The runtime-portable build is failing in the 7.0.2xx source build bootstrap scenario only with the following error:

```
      Generating native image of System.Private.CoreLib for Linux.x64.Release. Logging to 
      /tarball/src/runtime/artifacts/source-build/self/src/dotnet.sh /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/crossgen2/crossgen2.dll -o:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/System.Private.CoreLib.dll -r:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/*.dll --targetarch:x64 -O /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/System.Private.CoreLib.dll --perfmap-format-version:1 --perfmap --perfmap-path:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/
      Specify which project file to use because this '/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr' contains more than one project file.
    /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/crossgen-corelib.proj(104,5): error MSB3073: The command "/tarball/src/runtime/artifacts/source-build/self/src/dotnet.sh /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/crossgen2/crossgen2.dll -o:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/System.Private.CoreLib.dll -r:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/*.dll --targetarch:x64 -O /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/System.Private.CoreLib.dll --perfmap-format-version:1 --perfmap --perfmap-path:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/" exited with code 1.
    
    Build FAILED.
    
    /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/crossgen-corelib.proj(104,5): error MSB3073: The command "/tarball/src/runtime/artifacts/source-build/self/src/dotnet.sh /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/crossgen2/crossgen2.dll -o:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/System.Private.CoreLib.dll -r:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/*.dll --targetarch:x64 -O /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/System.Private.CoreLib.dll --perfmap-format-version:1 --perfmap --perfmap-path:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/" exited with code 1.
        0 Warning(s)
        1 Error(s)
```

Inside `src/coreclr` are multiple project files, `crossgen-corelib.proj`, `runtime.proj`, and `runtime-prereqs.proj`. I checked that these are also present in the runtime that's in .NET 7.0.1xx.
I also checked that the error from the .NET CLI isn't new to .NET 7.0.2xx. I'm not sure where else to look. Maybe @ViktorHofer knows who to tag?

**Comment by nagilson** [comment]
Thanks @jkotas for the ping and investigation. It was probably this PR: https://github.com/dotnet/sdk/pull/28484 

Before I can give a definitive answer, I need a bit more information ( see `Questions`). But if I understand the situation correctly, this is by design. We can certainly talk about if it should or shouldn't be by design if 'ya want. 

# Workarounds

First: @lbussell  as a work-around, setting `UseCurrentRuntimeIdentifier` = `false` should disable this behavior. Please let me know how that goes.

Another option may be: `AppendRuntimeIdentifierToOutputPath = false` which you can set, but that will just change the pathing; you'll still get the RID, so it's a hacky workaround.

# Explanation
I'm guessing this is caused by the following: There is a point in time in which `crossgen2` uses `RuntimeIdentifiers` but does not set a `RuntimeIdentifier`. If `crossgen2` depends on any of the following: `SelfContained`, or any `Publish*` property like `PublishSingleFile`, the SDK detects this and gives it a `RuntimeIdentifier`. Now it has a `RuntimeIdentifiers` and `RuntimeIdentifier`. 

# Questions

Is the above information correct, may someone from `crossgen` comment on the claim that it sets `RuntimeIdentifiers` but no `RuntimeIdentifier`? And do you use one of the following `SelfContained` or `Publish*` properties? If so, I'd imagine you had some special logic before to use them, because those properties require a `RuntimeIdentifier` to be set?

**Comment by jkotas** [comment]
> it sets RuntimeIdentifiers but no RuntimeIdentifier? And do you use one of the following SelfContained or Publish* properties? 

Yes, crossgen project does exactly that: https://github.com/dotnet/runtime/tree/main/src/coreclr/tools/aot/crossgen2

> Another option may be: AppendRuntimeIdentifierToOutputPath = false

This sounds like the most appropriate fix. Submitted https://github.com/dotnet/runtime/pull/78733 (verified locally that it fixes the build break)

**Comment by akoeplinger** [comment]
> it sets RuntimeIdentifiers but no RuntimeIdentifier? And do you use one of the following SelfContained or Publish* properties? 

This is also the default setup for Android/iOS builds, see e.g.:

https://github.com/xamarin/xamarin-android/blob/ac643dddb5e9ef968fa758a6bc77a084242780e7/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.DefaultProperties.targets#L71-L73
