### ISSUE TITLE
Get platform manifest and conflict resolution data from targeting packs or runtime packs if appropriate

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#2933]
For .NET Core 2.x, the `Microsoft.NETCore.App` package includes a platform manifest .txt file as well as `PackageConflictOverrides` MSBuild items for conflict resolution.  For .NET Core 3.0, these should come from the targeting pack for framework dependent apps, and from the runtime pack for self-contained apps.

This means that both targeting packs and runtime packs need to include this data, and the SDK needs to use the data from the appropriate type of pack depending on whether the app is self-contained or not.

**Comment by natemcmaster** [comment]
The platform manifest is meant to be used for trimming framework-dependent apps. I don't think runtime packs are the right place for this because those packs are mean for self-contained deployments and according to @nguerrera are deliberately not part of the offline experience. Also, I don't think the platform manifest should be necessary for self-contained -- isn't the idea that for self-contained you copy the whole folder from the runtime pack into the app output?

Targeting pack seems more appropriate for platform manifest.

**Comment by livarcocc** [comment]
@dsplaisted is this one still in progress?

**Comment by livarcocc** [comment]
Work is done for targeting packs. We still need to do the work for runtime packs but runtime packs don't have platform manifests yet.

**Comment by dsplaisted** [comment]
As to Nate's comment, the platform manifest is used for framework-dependent apps to trim dependencies that are already included in the shared framework.  For self-contained apps, if there is a dependency which is part of the Framework, we still need to decide which asset to use.  In either case, the platform manifest can provide the version information for conflict resolution to make these decisions.

**Comment by dsplaisted** [comment]
Closing this in favor of https://github.com/dotnet/cli/issues/10581 and https://github.com/dotnet/cli/issues/10442

**Comment by dsplaisted** [comment]
Looking back at this, I don't think we need the platform manifest for runtime packs, as the runtime list provides the same information.
