### ISSUE TITLE
"dotnet tool restore" failing when run concurrently in CI -- DotnetToolSettings.xml locked

### ISSUE THREAD

**Issue by SeanKilleen** [dotnet/sdk#29535]
### Describe the bug

Our client's CI process typically kicks off two builds in parallel - the branch without being merged in, and the branch after being merged in. (we're working to help modernize their process.)

But, this means that oftentimes in parallel, our build is running the following in a `bat` command in Jenkins:

`dotnet tool restore --tool-manifest code/src/REDACTED/.config/dotnet-tools.json`

Occasionally, the builds apparently run _too much in parallel_ 😄 and we see an error on both builds around a given tool (in this case, Swashbuckle, though we also use MinVer in our build and may see the error for that tool depending on the instance):

> Failed to retrieve tool configuration: The process cannot access the file 'C:\Users\REDACTED\.nuget\packages\swashbuckle.aspnetcore.cli\6.3.1\tools\net6.0\any\DotnetToolSettings.xml' because it is being used by another process

I've looked into the `--disable-parallel` flag but AFAICT that appears to be for parallel restores for a set of projects, not across invocations.

What is the recommendation for using dotnet tool restore in a CI setting, particularly where parallel builds are concerned?

(Side note: I'm happy to consider adding a PR to the code or the docs with a point in the right direction.)

### To Reproduce

* Create a tools file in a given project, e.g. `dotnet-tools.json`
* Create copies of the folder containing that tool setup
* In parallel, call `dotnet tool restore --tool-manifest path/folder1/to/dotnet-tools.json` and `dotnet tool restore --tool-manifest path/folder2/to/dotnet-tools.json`.

Expected behavior: the tools for both folders restore
Actual behavior: Error message about `DotnetToolSettings.xml` being locked.

## Backport PRs to create

* [x] 6.0.1xx #29579
* [x] 6.0.3xx #29583
* [x] 6.0.4xx: #29548
* [x] 7.0.1xx #29584
* [x] 7.0.2xx #29549

**Comment by SeanKilleen** [comment]
@baronfel FYI, all specified back-porting PRs have been created and are linked to this issue.

**Comment by baronfel** [comment]
Thanks @SeanKilleen  - I've applied the servicing template to each of them and will kick off the required internal emails (normally we'd cover these on twice-weekly meetings, but since it's near the holidays folks are already out). We'll take it from here :) Thanks again for raising the issue and contributing the main fix!

**Comment by baronfel** [comment]
I'm going to close this as the linked issues have all merged and should be in the February servicing releases. Thank you @SeanKilleen for your work here, and hanging with us to get it to all the relevant supported branches!

**Comment by ckrueger1979** [comment]
Problem seems to persist in:
dotnet version 6.0.421

Warning: tool package 'dotnet-ef' is invalid, contact tool author:
Failed to retrieve tool configuration: Access to the path 'C:\Users\<redacted>\.dotnet\tools\.store\dotnet-ef\7.0.18\dotnet-ef\7.0.18\tools\net6.0\any\DotnetToolSettings.xml' is denied.

From what we have found it only happens if the tool is installed globally -> bad practice.
