### ISSUE TITLE
Support publishing for a RuntimeIdentifier without building for that RuntimeIdentifier

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#2956]
This is similar to #2839, but also involves using the "No Build" option on publish.

So you have a project with:

```xml
<RuntimeIdentifiers>A;B;C</RuntimeIdentifiers>
```

And you do:

```
dotnet build
dotnet publish -r A --no-restore --no-build
```

After fixing #2839, the `--no-build` scenario is still failing.  It looks like this is because the RID-specific app-host isn't in the intermediate directory and it fails when trying to copy it to the publish directory.

**Comment by livarcocc** [comment]
@peterhuene can you take a look at this one?

**Comment by peterhuene** [comment]
Wait, how is the apphost the only thing preventing this feature for publish?  Where would it be sourcing the other build outputs from?  The RID-less obj directory?  That seems inherently wrong to me, even if the build output might be (semantically) identical between a RID-less and RID-specific build.

Conceptually I'm struggling with being 👍  on this.  A user of the .NET Core SDK expects to publish a built application.  They view a RID-less build as independent from a RID-specific build.  If they desire to publish a RID-specific version of their application, then I would expect them to also have built a RID-specific version of their application.  I think there will be quite a bit of confusion when you build as both RID-less and RID-specific and then publish as RID-specific; which of those two are we sourcing the outputs from?

Supporting this would also require us to always generate the deps file on publish rather than copying the one from the build output too (another place this is probably broken, but we don't notice because there are package references that are excluded from publish and thus we're always generating the deps on publish).  It's something I was hoping we would move away from and move towards copying the build output for publish.

**Comment by peterhuene** [comment]
@dsplaisted @livarcocc  I originally left a question to this issue which I later deleted because perhaps I wasn't seeing things correctly.

However, I now would like to ask that question again.  How is this supposed to work if we never build for the RID we're publishing for?

Currently `RuntimeIdentifiers` controls which RIDs we're restoring for, but not which we're targeting the build, which can currently only be a single RID specified via `RuntimeIdentifier`.  Thus, in the repro steps above, `dotnet build` builds RID-agnostic.

When we publish `--no-build` for a specified RID from a previous build being RID-agnostic, we have no RID-specific build outputs (either in `bin/` or `obj/`) to copy to the publish directory.

Are we proposing that the presence of `RuntimeIdentifiers` fans out the build the same way `TargetFrameworks` does?  That is a requested change from the community (I would have to dig up the issue), albeit a breaking change. 

If that's not the case, then I don't see how the above repro is expected to work.

**Comment by peterhuene** [comment]
Link to the other issue I mentioned https://github.com/dotnet/cli/issues/10087

**Comment by peterhuene** [comment]
@dsplaisted any thoughts on my comment above?

**Comment by dsplaisted** [comment]
@peterhuene I think you're right, it doesn't really make sense for this to work.  I thought that it was a scenario we supported or tried to support in earlier releases, but maybe I'm getting no-build confused with no-restore.

**Comment by peterhuene** [comment]
I'll close for now and we can reopen if it makes sense to do so.  Thanks!
