### ISSUE TITLE
Global tool shims: Store package version in Win32 version resource 

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#2966]
**Issue**

Currently the tool shim embeds a relative path to the target .dll in a `.data` section that includes package version:

For example:
```
.store\microsoft.dotnet.darc\1.1.0-beta.19081.1\microsoft.dotnet.darc\1.1.0-beta.19081.1\tools\netcoreapp2.1\any\Microsoft.DotNet.Darc.dll
```

This design makes it very difficult to change the version number in a post-build step. 
This approach is not compatible with some of our build tools and deterministic build tools that build artifacts without versions and stamp them with the version afterwards.

**Proposal**

Instead of embedding relative path, store the package version in a version resource, read the version and construct the path in the shim.

**Comment by wli3** [comment]
After we balancing the cost we decide to keep it the same way.

### Problem and work around

Global tools shim is tied to package version. One shim can only be used in one package. Since the relative path “/packageid/packageversion/packageid/packageversion/any/mytool.dll” is embedded in the apphost.

1. Arcade repack (one build, but pack to 2 nupkgs, one with suffix, one without, so it can be shipped anytime) does not work on global tools -- However, if we use the new “release-only” versioning for all global tool packages then we don’t need to rewrite the version.

2. One day we onboard cloudbuild, tools shim cannot be cached -- CloudBuild currently does not support stamping Linux binaries. Mac has versions in a separate file, which the OS knows about and is signed. Config files are not stamped since they are fast to rebuild and the stamping is only for optimization. They also currently rebuild all packages every time. If we don’t do anything the CloudBuild would regenerate the global tools loader binaries on every build. Since that should be fast it is probably not a problem. It would however cause any package or installer that contains global tool to be rebuilt as well.

### Proposal and downside

1. Instead of embedding the execute path in an arbitrary place. Embedded it in version [resource in PE files](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fwindows%2Fdesktop%2Fmenurc%2Fversioninfo-resource&data=01%7C01%7Cwul%40microsoft.com%7C8f8fc52dd1a94f4d236b08d6cf4cffdf%7C72f988bf86f141af91ab2d7cd011db47%7C1&sdata=LObAIVV37DFZFFvUyFgTGrmyJqrx88Y2lVbDeAhPjKc%3D&reserved=0). And use Win32 ProductVersion -- It is non trivial to move the field. Apphost has to read the PE resource first and then format it with “/packageid/PUTVERSIONHERE/packageid/PUTVERSIONHERE/any/mytool.dll” to get the actual dll. Apphost also does not have a servicing story.

2. Make re-stamping easier by having a guid to mark the start of the embdded path, or extract a library -- this will add special case for the re-stamping tool.
