### ISSUE TITLE
Whats the triage process here?

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/sdk#29960]
Whats the process here for issues to get viewed/discussed/fixed?

I see there are many issues on the pages wich are marked as "untriaged", and got additional no comments. Whats the way here to get things going?

I created a issue here too (https://github.com/dotnet/msbuild/issues/8319) (or it was moved here), and for me it's very urgent. What can I do to help?

**Comment by marcpopMSFT** [comment]
@baronfel , the SDK process is somewhat different than that as I have a query I run that filters out all non-SDK issues, then I assign out to members of the team to do triage. There's not one person on triage duty each week but rather everyone as we get 15-20 incoming a week. I usually do that assignment on Tuesdays.

The person assigned is supposed to as they have time either mark it for a release, raise it for discussion, reply with comments, or move it to backlog. For the particular issue this customer raised, that seems very much specific to their build rather than a bug so the person assigned would probably try to get some initial guidance on how to dig further and assign the milestone as discussion. We would normally treat it as lower priority as individual customer builds can be very expensive to diagnose and add up quickly.
