### ISSUE TITLE
Match Compile, EmbeddedResource project.json defaults

### ISSUE THREAD

**Issue by brthor** [dotnet/sdk#306]
There's been an ask to clean up the compile and embedded resource items post-migration. 

To do this safely (without risk of mangling someones project), SDK will need to update it's default excludes to match that of project.json. 

These are the full set of defaults for project.json

```
<Compile Include="**\*.cs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />

<EmbeddedResource Include="**\*.resx" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
<EmbeddedResource Include="compiler\resources\**\*" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
```

**Comment by nguerrera** [comment]
FWIW, this could be simplified a bit and it would be easier to contrast against current defaults.

1. There's no need to exclude *.xproj from lines where only *.cs or *.resx are included.

2. There's no need to exclude bin, obj, and packages where only compiler\resources are included.

**Comment by nguerrera** [comment]
So the xproj exclusion only matters for compiler/resources and xprojs are not going to stay sound as a concept, right? I think it would be strange to carry a default related to a file format that lived only during a pre-release. 

So I think this amounts to excluding packages/ in addition to bin/ and obj/ by default. I'm ok with that, but it's also a little strange because the defaults don't restore to a packages sub folder.

**Comment by dsplaisted** [comment]
What about `node_modules` or similar folders?  I thought one of the requirements for decent globbing perf was to avoid looking at those folders, but I don't see them ecxluded anywhere.

**Comment by nguerrera** [comment]
Let's go ahead and add node_modules. Do you have a list of "similar" folders?
