### ISSUE TITLE
Files generated before build (e.g. by NPM or Gulp) into the wwwroot folder might not be accessible

### ISSUE THREAD

**Issue by barthamark** [dotnet/sdk#3065]
I have a BeforeTargets="BeforeBuild" script defined in my csproj file that executes a Gulp task which generates a bunch of js files taking more than 4 seconds to finish. These files are not accessible by the web application only after rebuilding the solution. However, if the script finishes quickly (couple milliseconds) then it will be fine after the first build.

```
<Target Name="NpmInstall" BeforeTargets="BeforeBuild">
  <Exec Command="npm install" />
  <Exec Command="gulp" />
</Target>
```

This might be a duplicate by one of the following issues, however, none of the workarounds fixed this scenario where the goal is to access these files locally on my development environment and not after publishing the website.

https://github.com/aspnet/websdk/issues/114
https://github.com/dotnet/sdk/issues/1044

**Comment by livarcocc** [comment]
Which version of the .NET Core Sdk are you using?

What is your csproj like?

@rainersigwald what is the best target to use here? Is BeforeBuild target the ideal one? I remember there is some complication here.

cc @vijayrkn

**Comment by barthamark** [comment]
I am using SDK v2.2.104 currently. 

The content of the csproj is something like this:

```
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="node_modules\**" />
    <EmbeddedResource Remove="node_modules\**" />
    <None Remove="node_modules\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Gulpfile.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="OrchardCore.Module.Targets" Version="1.0.0-beta3-70939" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\My.Project\My.Project.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Gulpfile.js">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  
  <Target Name="NpmInstall" BeforeTargets="BeforeBuild">
    <Exec Command="npm install" />
    <Exec Command="gulp" />
  </Target>

</Project>
```

**Comment by rainersigwald** [comment]
Is the problem that the `NpmInstall` generates javascript files that you expect to be picked up by the build and deployed with your application?

I suspect that the problem is that you don't add the files to the appropriate item after generating them in `NpmInstall`. The default glob (wildcard) includes apply only to files that exist on disk _before the build starts_. If files are created during the build, they will be discovered for the _next_ build (so it'll work on rebuild) but not the current build. The solution is to explicitly create the items after creating the files on disk, perhaps something like

```xml
  <Target Name="NpmInstall" BeforeTargets="BeforeBuild">
    <Exec Command="npm install" />
    <Exec Command="gulp" />

    <ItemGroup>
      <None Include="path\to\generated\files\*.js" />
    </ItemGroup>
  </Target>
```

> what is the best target to use here? Is BeforeBuild target the ideal one? I remember there is some complication here.

`BeforeTargets="BeforeBuild"` is a very good place for this. @livarcocc I think you're thinking of `AfterTargets="Build"` which has some nasty edge cases.

@barthamark can you elaborate on

> However, if the script finishes quickly (couple milliseconds) then it will be fine after the first build.

? That surprises me.

**Comment by dasMulli** [comment]
The web SDK solved this for all web projects by re-evaluating some glob paths - see https://github.com/aspnet/websdk/blob/d6ba9de37748a12e7b8ea28bb7def3c954b1317f/src/Publish/Targets/ComputeTargets/Microsoft.NET.Sdk.Publish.ComputeFiles.targets#L48-L60

Since this project is using the Razor SDK, it doesn't get that behavior.

**Comment by barthamark** [comment]
In the meantime I found that this is caused by the modular framework I am using. It gathers all the resources found in the module's wwwroot folder (which is a .NET Standard project) and registers them as static resources.
I couldn't reproduce it in a simple ASP.NET Core project. The BeforeBuild task will block the project build until the NPM task is not finished which is the expected way so all the resources are accessible after the build meaning it can't be a .NET bug (or at least I can't reproduce it for now).
