### ISSUE TITLE
Error parsing dotnet publish parameters when using ReadyToRun 

### ISSUE THREAD

**Issue by raffaeler** [dotnet/sdk#3164]
Version:   3.0.100-preview5-011507
Commit:    fddc070d00

When running `dotnet publish` using both `-p:ReadyToRun` and `--self-contained` the message is misleading:

```
$ dotnet publish -c Release -r linux-arm --self-contained -p:ReadyToRun=true -o scd
Microsoft (R) Build Engine version 16.1.65-preview+gc86abee47b for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/opt/dotnet/sdk/3.0.100-preview5-011507/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.TargetingPackResolution.targets(85,33): error MSB4030: "-p:ReadyToRun=true" is an invalid value for the "SelfContained" parameter of the "ResolveFrameworkReferences" task.
The "SelfContained" parameter is of type "System.Boolean". [/home/pi/test3/test3.csproj]
```

If instead, I specify `=true` the command succeed:
```
 $ dotnet publish -c Release -r linux-arm --self-contained=true -p:ReadyToRun=true -o scd
Microsoft (R) Build Engine version 16.1.65-preview+gc86abee47b for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 372.72 ms for /home/pi/test3/test3.csproj.
/opt/dotnet/sdk/3.0.100-preview5-011507/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [/home/pi/test3/test3.csproj]
  test3 -> /home/pi/test3/bin/Release/netcoreapp3.0/linux-arm/test3.dll
  test3 -> /home/pi/test3/bin/Release/netcoreapp3.0/linux-arm/test3.Views.dll
  test3 -> /home/pi/test3/scd/
```
It looks like `-p:ReadyToRun` already forces `--self-contained=true` but I would like the command output to clearly states whether the produced output is self-contained or not.

By the way, the parameter `--self-contained` can be used alone (without `=true`) and it has been possible even in .NET Core 2.x. The following command is valid and succeeds:
```
dotnet publish -c Release -r linux-arm --self-contained -o abc
```

**Comment by livarcocc** [comment]
The problem here is how the parser works. The issue in particular is not about ReadyToRun, but also that you are passing a -p value after self-contained. Because that is not a special value to the parser, like -o, that we intercept and translate, the parser is seeing some value after --self-contained and assumes that it is the value being passed to self-contained.

In this case, I would recommend passing a value to self-contained <true|false> as a way around this. Meanwhile, @peterhuene anything we could do in the parser to improve this?

**Comment by peterhuene** [comment]
We could validate that the argument is a boolean in the CLI rather than passing MSBuild the value.

Still, this would only occur when the next token the command line parser encounters after `--self-contained` is *not* a recognized option (i.e. an option that we would automatically forward to MSBuild).

Thus, `... --self-contained --no-build` would work just fine, but `... --self-contained -p:Foo=bar` would error with "-p:Foo=bar" isn't a boolean 🤦‍♂ 

The best solution would be to hijack a time machine, travel back to 2016, and stop a boolean option like `--self-contained` from ever accepting a value (so very unPOSIX).

**Comment by raffaeler** [comment]
Thank you.
At this point, I'd prefer to have an error message if the boolean is not explicitly passed. At least I have a starting point instead of a big question mark in my head.

Also, since ReadyToRun is not able to work unless, self-contained is enabled, I would switch self-contained to true automatically.

Finally, I was said ReadyToRun changed to PublishReadToRun in P5, but the error messages still contain ReadyToRun.

**Comment by AntonLapounov** [comment]
This was fixed in .NET 6 according to the https://github.com/dotnet/sdk/issues/13196#issuecomment-732361316.

**Comment by raffaeler** [comment]
@AntonLapounov could you please explain or link the expected behavior after the fix?

**Comment by AntonLapounov** [comment]
I have tried your `publish` command on .NET 6 and `--self-contained -p:ReadyToRun=true` just works now.
