### ISSUE TITLE
Could not upgrade to .Net Core 2.2.4

### ISSUE THREAD

**Issue by Lemraj** [dotnet/sdk#3178]
Hi,

I am trying to upgrade my solution to the latest .net core version (2.2.4).

I have noticed that the test projects (xunit) are not updated automatically.

I could reproduce it by creating a new solution with a wen api project and xunit project.

![image](https://user-images.githubusercontent.com/10677560/56751833-39d4bd00-6787-11e9-9850-ae0f142a8e16.png)

I have installed the latest versions of the runtime & the SDK:
![image](https://user-images.githubusercontent.com/10677560/56752028-aea7f700-6787-11e9-8dc6-75478b861287.png)
![image](https://user-images.githubusercontent.com/10677560/56752052-bbc4e600-6787-11e9-9836-a9f68f444248.png)

Any idea why the xunit project is not upgraded?

**Comment by livarcocc** [comment]
You should not be referencing this package directly or even upgrading it.

The version for this package is managed implicitly for you. if you are a framework dependent app, your app will target the 2.2.0 version of the package and your app will be rolled forward to the latest version of the runtime installed on your box automatically.

if you are a selfc-contained app, when you publish the app, it will be published the latest version of the package that the SDK is aware of when publishing.

It is possible that you are seeing the situation above because for the web api you have an explicitly package reference to the package while for the test project it is implicit.
