### ISSUE TITLE
dotnet msbuild /t:Pack puts the nupkg in a TFM-specific directory

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#318]
#316 Repro:

csproj

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <TargetFramework>netstandard1.5</TargetFramework>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>$(OutputPath)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <EmbeddedResource Include="**\*.resx" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
    <EmbeddedResource Include="compiler\resources\**\*" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>1.0.0-alpha-20161019-1</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NETStandard.Library">
      <Version>1.6.0</Version>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard1.5' ">
    <DefineConstants>$(DefineConstants);NETSTANDARD1_5</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
  </PropertyGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

run `dotnet pack` or `dotnet msbuild /t:Pack`
# Expected

nupkg is generated in `bin/Debug/projectName.nupkg`
# Actual

nupkg is generated in `bin/Debug/netstandard1.5/projectName.nupkg`

**Comment by piotrpMSFT** [comment]
@nguerrera @srivatsn @eerhardt

**Comment by srivatsn** [comment]
@rohit21agrawal - I assume this is not expected? Can you take a look?

**Comment by eerhardt** [comment]
This is because `/t:Pack` uses the `$(OutputPath)` property to where to stick the packed nupkg.

When the project is multi-targeted, the `$(OutputPath)` property changes depending on whether it is building the "inner" or "outer" build.  During the "inner" build, `$(OutputPath)` == `bin\Debug\TFM`.  During the "outer" build, `$(OutputPath)` == `bin\Debug`.  Since pack runs in the outer build, the nupkg gets placed to `bin\Debug`.

However, the project above is not multi-targeted.  It only targets `<TargetFramework>netstandard1.5</TargetFramework>`.  Thus there is no "outer" build.  And when pack runs, the  `$(OutputPath)` == `bin\Debug\netstandard1.5`. 

If we feel we need to fix this, we could make a new property for `/t:Pack` to use called `$(PackOutputPath)` that would get defaulted to the `$(OutputPath)` before we appended the TFM to the end of it: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.TargetFrameworkInference.targets#L86

**Comment by srivatsn** [comment]
If we have a single TFM project, should we even append the TFM to outputpath? That's unnecessary directory depth isn't it?

**Comment by rohit21agrawal** [comment]
i like the idea of $(PackOutputPath)

**Comment by eerhardt** [comment]
> If we have a single TFM project, should we even append the TFM to outputpath? That's unnecessary directory depth isn't it?

Not saying this makes it "right", but this is what the CLI did as well.  Your output path was always consistent whether you targeted one or many TFMs.

**Comment by nguerrera** [comment]
> Not saying this makes it "right", but this is what the CLI did as well. Your output path was always consistent whether you targeted one or many TFMs.

I'm not saying it's right either, but it certainly makes the code simpler. Given that this is how it has always worked, I'd say let's keep it that way.

The nuget path does need to be consistent too, though. @eerhardt's approach of PackOutputPath defaulting to OutputPath before TFM change is elegant. +1 to that.
