### ISSUE TITLE
Build Issue with Latest SDK 7.0.302

### ISSUE THREAD

**Issue by Klunkles** [dotnet/sdk#32637]
### Describe the bug
We've a build pipeline in DevOps that was running as expected and deploying to Azure Web Apps up to 15/05/2023. Once deployed, we could navigate to our site without issue.

As of 17/05/2023 any deployments to Azure using this pipeline resulted in successful builds and deployments, but when testing the site, 404 errors were being received.

We've tested with current release branch, master and previous release versions as well, but all of them are returning a 404.

### To Reproduce
The application is Razor running on .Net 7.0
I've stripped out a few items, but the YAML for the build pipeline is as follows:

name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Phase_1
  displayName: Agent job 1
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Set Culture to GB
    inputs:
      targetType: inline
      script: Set-Culture -CultureInfo en-GB
  - task: UseDotNet@2
    displayName: Use .Net Core sdk 7.0.x
    inputs:
      version: 7.0.x
  - task: DotNetCoreCLI@2
    displayName: Restore NuGet packages for Solution
    inputs:
      command: restore
      projects: XXX.sln
      feedRestore: XXX
  - task: VSBuild@1
    displayName: Build ClarifiedBy Solution
    inputs:
      solution: XXX.sln
      msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
  - task: PublishBuildArtifacts@1
    displayName: Publish
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: XXX

Please let me know if you need any more information

### Further technical details
I've managed to get the site deploying again by changing the SDK version from "7.0.X" to 7.0.203 and can now navigate the site, however I'd prefer to use latest version when building.

**Comment by dre99gsx** [comment]
I'm also experiencing issues on deployment with Azure and 7.0.302, except for me, web applications are throwing 

> System.InvalidOperationException: The view ‘Index’ was not found. The following locations were searched…

For every single page. Once I switch back to 7.0.203 in the DotNetCli SDK build step, all works fine. 

I had posted this on Microsoft's Devops community-----

C# ASP.Net web application using RazorPages, server on latest 7.0.5 hosting bundle for x64, running IIS Server on a Windows machine (and/or Azure VMs). Build pipeline uses Windows 2022 agent and Visual Studio 2022 as the Build VS version (although I can’t confirm if Azure is already on 17.6 as this may be required for 7.0.302 to build correctly?)

Devops Build pipeline is set to pull the latest SDK before executing msbuild, then releasing to various IIS servers. No issues for months, but suddenly receiving errors when visiting a site such as:

System.InvalidOperationException: The view ‘Index’ was not found. The following locations were searched…

No pages at all are found as I try to navigate to any basic page.

I can confirm on my local development environment, this issue doesn’t exist even though I am on 7.0.5 and latest SDK 7.0.302.

Did some investigating and found one change: Devops build log shows SDK 7.0.203 was used the day before, deployed and worked fine. Today, build log shows SDK 7.0.302 was now being used. I was able to force a new build but with 7.0.203 explicitly in my build configuration, deployed, and the issue is gone. This definitely caused the issue.

Any breaking changes in the new version with regards to Devops parameters or .net C# code in Program/Startup?

**Comment by dre99gsx** [comment]
Unable to provider binary log file since it is littered with secrets and other proprietary parameters we use for building, but I can confirm what @MrBildo  sees in the regular text build log of 

`2023-05-16T23:58:32.4437681Z ##[warning]CSC(0,0): Warning CS9057: The analyzer assembly 'C:\hostedtoolcache\windows\dotnet\sdk\7.0.302\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll' references version '4.6.0.0' of the compiler, which is newer than the currently running version '4.5.0.0'.
2023-05-16T23:58:32.4441479Z CSC : warning CS9057: The analyzer assembly 'C:\hostedtoolcache\windows\dotnet\sdk\7.0.302\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll' references version '4.6.0.0' of the compiler, which is newer than the currently running version '4.5.0.0'. [D:\a\1\s\RCL_project.csproj]`

which shows up for every razor class library project I use in the solution. This warning does not exist when using 7.0.203

**Comment by jaredpar** [comment]
That text unfortunately doesn't help. It tells us what is wrong, not why it is wrong. There are a number of customer successfully using 7.0.302 so it's likely to be specific to your environment somehow. 

Can you grab the binlog locally, find the `<Csc>` task that is failing, expand it out such that we can see where the assembly is loading from, screen shot that and post it here? Effectively this view

<img width="690" alt="image" src="https://github.com/dotnet/sdk/assets/146967/e60bb119-ce9b-4d3e-9394-f9df2adfb383">

Also if you could post the full command line arguments that would help

<img width="419" alt="image" src="https://github.com/dotnet/sdk/assets/146967/d520363b-c5df-4796-b832-44ad67ae8628">

**Comment by MrBildo** [comment]
Is there a way to get that info from Aazure DevOps? All I have is the raw build log from pipeline. Locally I'm just building with Visual Studio and there is no issue there.

**Comment by jaredpar** [comment]
If you add the argument `-bl` to build will produce a msbuild.binlog file.

**Comment by jaredpar** [comment]
@dre99gsx how do you build in DevOps? Can you show me the YML snippet or code you use?

**Comment by dre99gsx** [comment]
`steps:
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(Parameters.solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:EnvironmentName=Staging /p:PackageLocation="$(build.artifactstagingdirectory)\$(BuildConfiguration)" /bl:binarylogfilename.binlog'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    createLogFile: true
    logFileVerbosity: diagnostic`

**Comment by jaredpar** [comment]
Can you all check to see what version of MSBuild you are running here? I strongly suspect it's 17.5 or earlier. That explains all the symptoms we're seeing in this thraed, as well as why other people are not seeing it.

**Comment by dre99gsx** [comment]
I'm looking into how to grab the version, but I do have Visual Studio 2022 as the selected version in the pipeline:

> "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" "D:\a\1\s\WebApp.sln" /nologo /nr:false /fl /flp:"logfile=D:\a\1\s\WebApp.sln.log;verbosity=diagnostic" /dl:CentralLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.214.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=eea1f187-676a-45fc-9515-95d31239c0b2|SolutionDir=D:\a\1\s|enableOrphanedProjectsLogs=true"*ForwardingLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.214.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:EnvironmentName=Staging /p:PackageLocation="D:\a\1\a\Release" /bl:binarylogfilename.binlog /p:platform="any cpu" /p:configuration="Release" /p:VisualStudioVersion="17.0" /p:_MSDeployUserAgent="VSTS_47eb312b-ea9c-4258-a4ec-4e39de0a1c94_build_37_0"

**Comment by jaredpar** [comment]
Generally the first line of the build output will have the version number of msbuild attached to it. If you can paste in the first few lines I can decihper back to the real version.

**Comment by gpai-pv** [comment]
I noticed this same issue in some build pipelines today. The commonality appears to be the VSBuild task. The dotnet build and dotnet restore tasks appear to be using the correct version of msbuild but I don't think VSBuild is.

**Comment by jaredpar** [comment]
I'm fairly certain the problem here is that customers hitting this: 
1. Are using the 7.0.3xx SDK
2. Are using the 17.5 MSBuild 
3. Using `msbuild` to build in DevOps instead of `dotnet build`. 

That explains all the symptoms here. This is essentially by design though, you can't mix SDK and MSBuild versions this way for 17.5 and 7.0.3xx. The solution is to do one of the following: 

1. Pin back to 7.0.2xx
2. Use `dotnet build`

**Comment by MrBildo** [comment]
```
pool:
  vmImage: "windows-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
  - task: UseDotNet@2
    displayName: Use .NET 7.0
    inputs:
      packageType: "sdk"
      version: "7.0.x"

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: "$(solution)"

[....]
 

  - task: VSBuild@1
    inputs:
      solution: "$(solution)"
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
      platform: "$(buildPlatform)"
      configuration: "$(buildConfiguration)"
```

Here is the the UseDotNet log:

```
Starting: Use .NET 7.0
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.219.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 7.0.x.
Found version 7.0.302 in channel 7.0 for user specified version spec: 7.0.x
Version 7.0.302 was not found in cache.
Getting URL to download .NET Core sdk version: 7.0.302.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.219.0\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/c973fb82-ecba-4bcc-b1cc-443d817b9472/f4426b15af724f4baf31a50d204d1ca7/dotnet-sdk-7.0.302-win-x64.zip
Extracting downloaded package D:\a\_temp\de5d4608-cfcf-42b6-878b-adbaeecc6bd0.
Extracting archive
C:\Windows\system32\chcp.com 65001
Active code page: 65001
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\de5d4608-cfcf-42b6-878b-adbaeecc6bd0', 'D:\a\_temp\9db7')"
Successfully installed .NET Core sdk version 7.0.302.
Creating global tool path and pre-pending to PATH.
Finishing: Use .NET 7.0
```

Start of VSBuild:

```
Starting: VSBuild
==============================================================================
Task         : Visual Studio build
Description  : Build with MSBuild and set the Visual Studio version property
Version      : 1.214.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/visual-studio-build
==============================================================================
"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.214.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [17.0,18.0) -latest -format json
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" "D:\a\1\s\src\[##].sln" /nologo /nr:false /dl:CentralLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.214.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=9b46f27d-c8de-4978-8cd2-f8f95e9a4dad|SolutionDir=D:\a\1\s\src|enableOrphanedProjectsLogs=true"*ForwardingLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.214.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="D:\a\1\a" /p:platform="Any CPU" /p:configuration="Release" /p:VisualStudioVersion="17.0" /p:_MSDeployUserAgent="VSTS_15e42b62-20a4-473f-b7e9-551e7e88d529_build_24_0"
```
We're not specify any particular version in DevOps. This is pretty barebones.

**Comment by MrBildo** [comment]
I want to be clear, for me at least, this is only an issue in Azure DevOps. I don't have any issues locally using Visual Studio or `dotnet run.`

**Comment by baronfel** [comment]
@MrBildo the telltale sign is that the VSBuild task is using `msbuild.exe` from the VS install. This is the cause of the mismatch. I would encourage you to use the `DotNetCoreCLI` task for building .NET SDK projects/solutions if possible to reduce the incidence of this kind of mismatch, both for the build portions of your AzDO pipeline as well as the restore portions.

**Comment by MrBildo** [comment]
@baronfel - considering the rug can apparently just be pulled out with versioning, exactly what is the use case for VSBuild? Also, asking for a friend who sucks at devops, is there a quick link on how to properly set up my.. err.. their pipeline? It seems they referenced the wrong thing.

**Comment by baronfel** [comment]
The use case for VSBuild is "Build a solution or project the exact way that VS would build it", but the actual problem here is that the VS installs on the AzDO and GitHub images are still on 17.5 and so only include tools that are expecting 7.0.2xx. Soon those images should be bumped to include the VS 17.6 install. Generally, the only reason I would use VSBuild with an SDK-style project is if that SDK-style project actually made use of props/targets that are delivered via VS components and not part of the .NET SDK itself (or NuGet MSBuild SDKs, etc). For most 'standard' .NET projects I would wholesale recommend moving away from the VSBuild and MSBuild tasks for this mismatch reason.

**Comment by dre99gsx** [comment]
I can confirm that this was indeed the issue. I switched over from VSBuild type of task to a dotnet build / dotnet publish set of tasks, and I no longer have issues on the deployment. Moving over is a bit tricky since documentation is muddy. Interestingly, they both use msbuild, but on dotnet build log, I can see the actual version of msbuild specified.

Thanks everyone for the quick advice and help!

**Comment by muhlisatac** [comment]
Same issue here. I manualy published my apps for like 3 days and its was really a mess. My build pipeline is below. It's not acceptable behavior for pipelines to suddenly stop working, right? Whats the recommended way then should we avoid using VSBuild@1 tasks?

``
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: CmdLine@2
  inputs:
    script: 'dotnet tool install -g Volo.Abp.Cli' 

- task: CmdLine@2
  inputs:
    script: 'abp install-libs'
    workingDirectory: 'src/XXX.Web'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop' 
    publishLocation: 'Container'
``

**Comment by gavazquez** [comment]
As a workaround do not use the latest sdk.

```
- task: UseDotNet@2
  displayName: 'Get dotnet version'
  inputs:
    **version: '7.0.203'**
    includePreviewVersions: true
```

**Comment by Klunkles** [comment]
> 

Thanks for checking this out and confirming it works. 

I'll look to update our pipeline to use the DotNetCoreCLI instead of VSBuild as per the recommendation.

**Comment by muhlisatac** [comment]
I have changed my pipeline and tested it. It works now. 

`
# removed
# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# added
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'

# removed
# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
#     clean: true

# added
- task: DotNetCoreCLI@2
  inputs: 
   command: build
   arguments: '--configuration $(buildConfiguration)'
   projects: '**/XXX.Web.csproj'
  
# added
- task: DotNetCoreCLI@2
  inputs:
    command: publish
   # Choose the spesific project. Couse there is more then one web project in the folder.
    projects: '**/XXX.Web.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
`

**Comment by luisabreu** [comment]
Hello guys.

Does this means you can't build a vs solution with net core (in the latest version) and regular net projects in azure devops?

**Comment by Klunkles** [comment]
You can still build your solutions in the DevOps pipeline, you just need to be careful on which SDK you're using if you use the VSBuild1 task. 

If you want/need to use VSBuild@1, I suggest using the 7.0.203 SDK

If you use DotNetCoreCLI@2, then you can use the latest SDK without issue

**Comment by dalton-baker** [comment]
Why is this closed, this issue is NOT fixed. 7.0.302 has broken Blazor in a big way and that should be noted in the release notes at the very least. 

The entire update should be replaced and obsoleted. What are you guys doing?!

**Comment by xrkolovos** [comment]
I have the same issue with Blazor Project

**Comment by americanslon** [comment]
Same issue with Blazor projects.

**Comment by robertmclaws** [comment]
This issue is still happening in 7.0.400.

**Comment by baronfel** [comment]
@robertmclaws can you check and comment what your SDK and VS versions are? I expect that you're still on VS 17.6 if you're building in AzDO or GitHub actions, because their inventory [says so](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022). I bet you're trying to build with .NET SDK 7.0.400 and VS has advanced. You can't really fix VS in this environment, so your only outlet will be to pin to 7.0.3xx in some way until the VS images are updated. Another alternative would be to stop using VSBuild in favor of just dotnet build.
