### ISSUE TITLE
[NETSDKE2E][Loc]With .NET8 preview 5 installed on Loc OS, the options for artifacts-path are unlocalized after running "dotnet build --help" in CLI .

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#32955]
Steps:
1.install it on locale OS Version 17.7.0 Preview 2.0 [33731.450.main] with .net 8 preview sdk checked from https://vsdrop.microsoft.com/file/v1/Products/DevDiv/VS/7d871550f1ba0a46faa22a9e9f2d51429f378d00/0d822b1b-8807-1c8e-0114-6a879fb10967%3bchannels/internal/Preview/bootstrappers/fixed/Enterprise/vs_Enterprise.exe

2.Run “dotnet build --help” in CLI.
3.Check if output contents are localized well.

Expected result:
Options are localized.

Actual Result:
The options for artifacts-path are not localized.

e.g
EN:
![MicrosoftTeams-image (18)](https://github.com/dotnet/sdk/assets/106054229/4f6c2b8c-6143-4de2-b137-1404244f59cf)

SC:
![1](https://github.com/dotnet/sdk/assets/106054229/c1f67283-cf4a-432b-af60-2d3788dba456)

TK:
![MicrosoftTeams-image (19)](https://github.com/dotnet/sdk/assets/106054229/58bd457f-647c-4704-8b69-692dc421d2f8)

dotnet --info
![2](https://github.com/dotnet/sdk/assets/106054229/07c8891b-7995-4055-85b5-b72799411d86)

**Comment by marcpopMSFT** [comment]
This is new in .net 8 and will be localized when we switch to the 8.0.1xx branch in August

**Comment by vdanche** [comment]
below strings also unlocalized, we'll keep tracking
![image](https://github.com/dotnet/sdk/assets/65637796/7383b9bc-ab70-47d5-8156-e5f30251b560)

**Comment by vdanche** [comment]
The issue has been fixed in 8.0.100-rc.2.23456.6(runtime- 8.0.0-rc.2.23431.9)
Chinese
![image](https://github.com/dotnet/sdk/assets/65637796/59841a40-b3ad-47f1-bf43-7ac95d2dfacd)
![image](https://github.com/dotnet/sdk/assets/65637796/864c47c9-0372-4e8b-960d-5a67de5fe2dd)
German
![image](https://github.com/dotnet/sdk/assets/65637796/3b32b8a5-da2a-48ba-b4eb-74264df632ad)
![image](https://github.com/dotnet/sdk/assets/65637796/11bbefdc-3219-4f5c-bd66-269f869665a9)
