### ISSUE TITLE
Define InternalsVisibleTo "attributes" in the csproj file

### ISSUE THREAD

**Issue by petroemil** [dotnet/sdk#3299]
Many of the AssemblyInfo.cs file's content are already generated from the project file, meaning in many (or more like most) cases we don't need to have an AssemblyInfo.cs file in our projects. 

There is one quite frequently used assembly level attribute though that still has to be defined as a traditional attribute - the `InternalsVisibleToAttribute`.

It would be nice if this could also be defined from the project file, which would also mean we could easily define it in a solution level props file, enabling all projects implicitly to see their `internal`s from the test project(s).

**Comment by davkean** [comment]
Moved this to the SDK repro, this would build driven.

**Comment by DanVicarel** [comment]
I would also love to see an `InternalsVisibleTo` MSBuild property out of the box.  The [`AssemblyAttribute` technique](https://stackoverflow.com/questions/42810705/visual-studio-2017-and-the-new-csproj-internalsvisibleto/49978185#49978185) that @ggirard07 mentioned is pretty slick, but it quickly becomes clumsy if internals need to be visible to multiple projects. Likewise, the [`targets` file](https://github.com/dotnet/arcade/blob/cdd5d318667c5af1740d69c8a7755e23e7964aeb/src/Microsoft.DotNet.Arcade.Sdk/tools/GenerateInternalsVisibleTo.targets#L27) that @Pilchie mentioned looks powerful, but I'm scared to copy-pasta because I don't fully understand how it works and I'd rather not add unnecessary properties to my project if I can avoid it. Seems like that property could be made part of the vanilla SDK, and then we could have full peace of mind using it. 🙂

**Comment by WeihanLi** [comment]
any plan for this feature?

**Comment by sfoslund** [comment]
Fixed by #3439
