### ISSUE TITLE
Should APICompat PackageValidation's EnableStrictModeForCompatibleTfms default to true?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#33011]
Follow-up on https://github.com/dotnet/sdk/pull/32964#discussion_r1214609786

https://github.com/dotnet/sdk/blob/0991d35e4e52d25816a9656a1f471e2fa7438de7/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets#L48

APICompat PackageValidation's `EnableStrictModeForCompatibleTfms` msbuild property currently defaults to true in the MSBuild frontend. We should discuss if we actually want that.

It was introduced with https://github.com/dotnet/sdk/pull/18714#discussion_r663448216

**Comment by ericstj** [comment]
I'm surprised that the default was true before, and also surprised that we don't notice this default.  I'm pretty sure we have some cases in dotnet/runtime today where we add more API in later TFMs.  If this were set to true - wouldn't that mean that we'd flag that added API as problematic?

To me it makes sense to have this as an option.  Some people may want to have identical API across all compatible frameworks in their package.  Since it's not a requirement for compatibility I think the default should be false.

CC @joperezr

**Comment by joperezr** [comment]
mmm this is weird to me as well, as we have this scenario in dotnet/iot where we use package validation and I haven't seen issues logged. Basically we ship two packages from that repo that cross target different TFMs, and TFMs like net8.0 have a superset of APIs from netstandard2.0 so not sure why we are not getting issues if this is the default.

**Comment by ViktorHofer** [comment]
So here's the reason why this works today. The `EnableStrictModeForCompatibleTfms` switch determines whether the `CompatibleTFMValidator` package validator runs in strict mode or not. That validator does the following:

> Validates that there are compile time and runtime assets for all the compatible frameworks. Queues APICompat work items for the applicable compile and runtime assemblies for these frameworks.

The behavior that @ericstj and @joperezr mention above is the one from the `CompatibleFrameworkInPackageValidator` package validator. Strict mode for that validator is determined by the `EnableStrictModeForCompatibleFrameworksInPackage` switch which defaults to false. The validator is described as:

> Validates the api surface between compatible frameworks.
