### ISSUE TITLE
"Application host will not be customised" - meaning?

### ISSUE THREAD

**Issue by vadi2** [dotnet/sdk#3309]
I've built an application[1] on .NET Core that runs on Windows, macOS, and Linux and I'd like to reduce the friction involved in getting it running - that is, having to install the runtime separately. I've read the [single-publish](https://github.com/dotnet/designs/blob/master/accepted/single-file/design.md) and [tried out the command](https://travis-ci.com/vadi2/Hammer/builds/114541271#L323) - but I get this warning:

> The application host executable will not be customized because adding resources requires that the build be performed on Windows (excluding Nano Server).

What does it actually mean? I'm new to the .NET world so I'm not sure what customisations is it actually talking about.

[1] https://github.com/vadi2/Hammer

**Comment by livarcocc** [comment]
It won't set the icon on the generated exe and it won't set the activation host on the exe either. That is, if the exe should be launched as a console app or a gui app.

@peterhuene anything else that I might have missed?

**Comment by peterhuene** [comment]
Currently this warning is produced when not building on Windows, but targeting Windows.

Perhaps we should limit the warning for `WinExe` projects since that's where there will be non-default resources?  Although, for console apphosts, it wouldn't customize the version information.

**Comment by peterhuene** [comment]
@vadi2 to answer your question:

The application host is the native executable (.exe for Windows, no extension for Linux and macOS) that is responsible for resolving and loading the .NET Core runtime and then running your application dll.

For Windows, the apphost can be customized to include the same Windows resources that your application dll contains: version information, icons, manifests, etc.  Unfortunately the customization currently relies on the Windows API to work, so it means that it can only take place on Windows.

Rather than silently produce an uncustomized application host, we emit this warning.

**Comment by vadi2** [comment]
Makes sense. Thank you!
