### ISSUE TITLE
App host not published correctly after a previous PublishSingleFile

### ISSUE THREAD

**Issue by fadimounir** [dotnet/sdk#3337]
To repro:
1) dotnet new console
2) dotnet publish -r win-x64 /p:PublishSingleFile
3) dotnet publish -r win-x64

After step 2, there will be a single app.exe (+pdb) file in the publish folder. Approx size is ~70 MB.
Step 3 correctly copies all dlls and other files to the publish folder, but fails to overwrite app.exe with the non-bundled version of the file (should be around ~150 KB). The large single-file bundle is still there in the publish folder.

Not sure if we can do something about it. This falls in the "clean publish" category of bugs, but I thing at least we should overwrite the app.exe in the publish folder with the correct one.

**Comment by fadimounir** [comment]
cc @swaroop-sridhar @nguerrera

**Comment by livarcocc** [comment]
@peterhuene

**Comment by nguerrera** [comment]
Yes, I would separate anything that involves *extra* files from a previous publish from anything that causes an incorrect file from a previous publish to be retained.

**Comment by peterhuene** [comment]
The cause is likely having the apphost `<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>` and the timestamp of the single-file exe is newer than the intermediate apphost from the previous publish.

This was written under the assumption that the executable in the publish output would always be the apphost.  As that's no longer the case, the fix would be to always copy the apphost.

**Comment by rainersigwald** [comment]
It's not exposed through metadata on the standard items, but the `Copy` task does support the desired operation via `SkipUnchangedFiles="true"`. As an implementation detail, that compares modification time and file size, so you can skip most incremental-build copies but still catch this case.

**Comment by peterhuene** [comment]
The apphost gets added as a `None`, so the `Copy` is in the common targets :/

**Comment by peterhuene** [comment]
Erm wait, I was thinking for the build output directory, not publish.  I think your solution is best.

**Comment by swaroop-sridhar** [comment]
@peterhuene  If the Copy task checks both modification time and file size -- I don't understand the concern expressed is in the above comment about skipping unchanged files.

**Comment by peterhuene** [comment]
I think the intent of the comment in the publish targets was likely due to a customer scenario where they post-processed the published files and didn't want another incremental publish to overwrite the post-processed files without the source file changing.

**Comment by nguerrera** [comment]
Reviewing #3373 now and coming back to the discussion here, I still don't understand why we can't use SkipUnchangedFiles

The comment looks to be copied from https://github.com/microsoft/msbuild/blob/0cd0e92a7243088977d31b56626b56d6116de016/src/Tasks/Microsoft.Common.CurrentVersion.targets#L4590-L4593

So, there are two cases:

PreserveNewest: Copy file if newer than destination
Always: Copy file always

It seems to me that PreserveNewest is compatible with "application may want to change one of these files and not have an incremental build replace it" while always is not. 

SkipUnchangedFiles, if it does what is described above just means that the physical copy won't happen unless the timestamp or size are different, right? So it seems totally separate from the concern in the comment, but I'm sure I'm missing something.

**Comment by peterhuene** [comment]
I think the intention of not using `SkipUnchangedFiles` on the *PreserveNewest* target is that we *don't* want to copy on size difference alone, as that might overwrite post-processed files on an otherwise incremental, up-to-date build.  Only if the timestamp of the input is newer should the file be copied.

I agree that the comment on the *Always* target seems to be entirely unnecessary (and likely copied from the *PreserveNewest* target) since we wouldn't use it *anyway* given that the user requested to copy the file regardless of it being up-to-date (i.e. it doesn't matter if the timestamps *and* file sizes match, we copy).

As I commented in the PR, the problem with changing the apphost to be *Always* is that we had a previous issue that expected the `FileWrites` item group to be empty upon incremental publish when nothing has changed.  We have a test that confirms that behavior which currently does not target `netcoreapp3.0` and hence isn't checking this behavior for the 3.0 default apphost.

**Comment by nguerrera** [comment]
Even in the PreserveNewest case, won't the Inputs/Outputs take priority? So if the output is newer than the input ("modified by application" according to that comment) it will be preserved, then failing that if we were to say SkipUchangedFiles="$(SkipCopyUnchangedFiles)" like everywhere else, then it wouldn't break that, but I guess it wouldn't do anything because if the Copy task is running the timestamps are different? Still feels like it would be easier to just follow the pattern everywhere else and not bother with this comment. Maybe I am still misunderstanding?

How about this:
1. Remove the comment from the Always path.
2. Set SkipCopyUnchangedFiles="$(SkipCopyUnchangedFiles)" in Always path.
3. Add netcoreapp3.0 coverage to the test in question now.

**Comment by peterhuene** [comment]
Right, the inputs/outputs would take priority for the `PreserveNewest` target.  My understanding of not using `SkipUnchangedFiles` *in lieu of* the inputs/outputs would be that copies would take place when the file size *alone* differs.  I think that's why the comment exists there.

I think adding `SkipUnchangedFiles="$(SkipUnchangedFiles)" ` to the `Always` target makes sense; by default this will remain false and not change the current behavior.

However, my concern remains that, by default, the apphost would be always copied and thus would no longer be incremental on publish.  If we target the test I mentioned to `netcoreapp3.0` with the PR's current changes, it will fail.  The only reason it passes now is that it *doesn't* target `netcoreapp3.0`.

**Comment by nguerrera** [comment]
If we add skip copy unchanged flag, won’t it only actually be copied if the previous publish was using a different app host (uncommon case but the one we are trying to fix here)?

It looks to me like the test would pass if we used it and retargeted to 3.0? Can we try that?

**Comment by peterhuene** [comment]
I need to step back a second, I think.

I don't see how we can keep any item (including the apphost) in the `PreserveNewest` group and keep the existing behavior of copying *only* when the timestamp of the source is "newer".  That is, if only the file sizes differ, we don't copy.  To me, that's why we're using input/output items for that target instead of `SkipUnchangedFiles`.

Likewise, I don't see how we can put the apphost in the `Always` group (the fix proposed in the PR) and *not* have it end up always copied, thus regressing #2573 and breaking the test designed to ensure no files get copied on incremental publish when nothing has changed.  If it's in the `Always` group, that implies it get copied every publish.

If we add `SkipUnchangedFiles="true"` to the `Copy` task responsible for copying the `Always` items, then that sort of breaks the semantic behavior of "always copy this file please", doesn't it?  It really becomes `PreserveNewestWithSizeCheck` rather than `Always`.

**Comment by nguerrera** [comment]
I understood from @rainersigwald's comment above that SkipUnchangedFiles means same timestamp AND same size, then don't copy, otherwise copy.  So Always would become
"AlwaysUnlessNeitherTimestampNorSizeHasChanged" with the change, right? If so, the only time you could observe a difference would be if you changed the input file to different content of the same length yet identical timestamp. I think a lot of things assume this case can be ignored in common targets. Well, they assume it if $(SkipCopyUnchangedFiles) is not overridden to false. You can set it to true if you are paranoid. However, the reality of incremental builds in msbuild is that they are not provably correct. There are other heuristic such as counting $(MSBuildAllProjects) as an input being good enough to detect various changes that might also be caused by a global property, etc. Paranoid mode is really `git clean -fdx`. I always tell people never to ship incremental builds, always have official builds start from a clean working directory.




Looking

**Comment by nguerrera** [comment]
For the PreserveNewest case, I think SkipCopyUnchangedFiles would not have any impact. MSBuild is only going to pass the files that are out of date to Copy so they will never have the same timestamp and therefore never be skippable irrespective of the flag.

**Comment by peterhuene** [comment]
My point is that `Always` currently means just that: no timestamp check and no size check; just copy the file to the publish directory every time the application is published.  Introducing `SkipUnchangedFiles` on its `Copy` task fundamentally changes the behavior to what one *might* expect `PreserveNewest` to mean, except `PreserveNewest` ignores size differences *on purpose* according to the comment.

I don't like changing the behavior of `Always` to mean a conditional copy just to prevent the apphost from always being copied on a no-op incremental publish. 

It seems like there should be three enum values for `CopyToPublishDirectory`: `Always` (i.e. always copy  - "just doing what we're told...user knows best"), `PreserveNewest` (i.e. copy if source has a newer timestamp), and something like `PreserveUnchanged` (i.e. copy if source has a newer timestamp or differs in file size).

**Comment by nguerrera** [comment]
I still have no idea what the comment accomplishes in PreserveNewest if skip unchanged checks time stamp. By the time it gets to the copy, we know the timestamp is different. So the flag wouldn't change anything. If that's right, I think the comment should be removed from PreserveNewest. It's not the lack of the flag that makes it so you can edit output and not get replaced, it's that the timestamp pf output will be newer. I still think making that cooy look like the 100 others would be better than a false alert that the flag would do something harmful. I could also live with changing the cimment to say there's no point to skip unchanged in PreserveNewest case. Am I still missing something here?

For always, the comment also makes no sense to me. It's always copied so you can't edit. 

I'd be ok with a new PreserveUnchanged and changing the always comment to something like "always really means always, therefore no  inputs/outputs and no skip unchanged. The one wrinkle is that this is currently 1:1 with the output options and those are in common targets. And we default copy to publish from copy to output whuch suggests they should have the same options.

I was thinking about the two user scenarios as follows:

1. let me make post build/publish edits and preserve them on incremental builds ->. PreserveNewest

2. Revert any post build/publish edits on incremental build to source of truth -> Always


Separately, there's a cross cutting feature of all the targets that if $(SkipCopyUnchangedFiles) is true, which it is by default, then assume that same timestamp AND same size means identical content and optimize all cooies accordingly. If this assumption holds there's no genuinely observable distinction between Always and PreseeveUnchanged. There seem to be like 20 places where this assumption is made. I'm not sure why in build case, it's allowed for so many other things but not content that is set to always. If you have a genuine case where you manage to modify files without changing timestamp and size, then you'd have to set SkipCopyUnchangedFiles to false, which you'd be free to do for Always here if we went with my plan.

So I'm not really convinced we need more knobs. I think all the scenarios are covered between Always/PreserveNewest/SkipCopyUnchangedFiles. Strictly speaking Always would be a lie but the rest of the build lies when SkipCopyUnchangedFiles is true too.

**Comment by peterhuene** [comment]
Ah, I didn't realize that `SkipCopyUnchangedFiles` was true by default.  The name sounds very "false by default" to me for some reason, probably the "skip" in the name.

I agree that the comment makes no sense on the `Always` target completely.

With respect to the `PreserveNewest` case, the comment makes sense to me as a warning against refactoring the code such that the target does not have inputs/outputs and instead use `SkipUnchangedFiles="$(SkipCopyUnchangedFiles)"` which has the potential to overwrite changes made to the published files due to the file size check.

Anyways, if that's the way the common targets do it for build (`Always` really meaning "always" only when `SkipCopyUnchangedFiles` is `false`), then I'm convinced we can copy that behavior for publish `Always`.

Let's implement the [three steps](https://github.com/dotnet/sdk/issues/3337#issuecomment-512033709) you outlined above then. :shipit:

**Comment by nguerrera** [comment]
Ah! I didn't read the comment in PreserveNewest that way because it's above where Skip would be passed, after inputs/outputs have already been passed, and makes no mention of inputs/outputs. 

I suggest changing it to: "Inputs/Outputs are used instead of SkipUnchangedFiles so that [...]"

So common targets have the same incorrect comment where content files with always are copied. We must have copied it from there. We should fix it there too.

They also do not use skip unchanged in always case, but I'm arguing they could since all of the other files that are copied in the build do.

I'd like to get one more vote before proceeding with my 3 steps because this was all very confusing and I want to make sure I haven't missed something. @rainersigwald do you think it makes sense to honour SkipCopyUnchangedFiles for Always or should we handle this semantic for apphost as a one-off or add a new PreserveUnchanged?
