### ISSUE TITLE
Roll-forward enabled with `PackAsTool`

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#33704]
I hadn't heard that we made that change. Was this intentional? If so, what do folks think about this change increasing our compat burden?

```bash
$ cat dotnet-runtimeinfo.csproj | grep Forward
    <RollForward>LatestMajor</RollForward>
$ dotnet build
$ cat bin/Debug/netcoreapp3.1/dotnet-runtimeinfo.runtimeconfig.json | grep Forward
    "rollForward": "LatestMajor",
$ cat dotnet-runtimeinfo.csproj | grep Forward
    <!--    <RollForward>LatestMajor</RollForward> -->
$ dotnet build
$ cat bin/Debug/netcoreapp3.1/dotnet-runtimeinfo.runtimeconfig.json | grep Forward
    "rollForward": "Major",
$ cat dotnet-runtimeinfo.csproj | grep PackAs
    <!-- <PackAsTool>true</PackAsTool> -->
$ dotnet build
$ cat bin/Debug/netcoreapp3.1/dotnet-runtimeinfo.runtimeconfig.json | grep Forward
```

**Comment by marcpopMSFT** [comment]
Yes, this was an intentional change per the linked proposal as otherwise, customers can't use any tools on release day. We could discuss alternatives where if the target runtime is present, we use that and otherwise we roll forward but I don't think that option exists within the current rollforward behavior.
https://github.com/dotnet/sdk/issues/30336
https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/tool-rollforward

Closing and continued discussion can happen on the linked issue.
