### ISSUE TITLE
File used by another process

### ISSUE THREAD

**Issue by lewing** [dotnet/sdk#33956]
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=336802
Build error leg or test failing: Microsoft.DotNet.Cli.New.IntegrationTests.TemplateDiscoveryTests.CanRunDiscoveryTool
Pull request: https://github.com/dotnet/sdk/pull/33949

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "error : The process cannot access the file",
  "ErrorPattern": "",
  "BuildRetry": true,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=336802
**Error message validated:** `error : The process cannot access the file`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/12/2023 4:34:24 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[370415](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370415)|dotnet/sdk|[Microsoft.DotNet.Cli.New.IntegrationTests.TemplateDiscoveryTests.CanRunDiscoveryTool](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370415&view=ms.vss-test-web.build-test-results-tab&runId=7860172&resultId=100044)|dotnet/sdk#34522|
|[365401](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365401)|dotnet/sdk|[Microsoft.DotNet.Cli.New.IntegrationTests.DotnetNewDetailsTest.CanDisplayDetails_LocalPackage](https://dev.azure.com/dnceng-public/public/_build/results?buildId=365401&view=ms.vss-test-web.build-test-results-tab&runId=7729826&resultId=100130)|dotnet/sdk#34476|
|[361227](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361227)|dotnet/sdk|[Microsoft.DotNet.Cli.New.IntegrationTests.TemplateDiscoveryTests.CanRunDiscoveryTool](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361227&view=ms.vss-test-web.build-test-results-tab&runId=7626714&resultId=100000)|dotnet/sdk#34412|
|[344492](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344492)|dotnet/sdk|[Microsoft.NET.Restore.Tests.dll.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344492&view=ms.vss-test-web.build-test-results-tab&runId=7199884&resultId=103650)|dotnet/sdk#34076|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|4|

**Comment by marcpopMSFT** [comment]
https://dev.azure.com/dnceng-public/public/_test/analytics?definitionId=101&contextType=build
The test failed 5 times in the last month with this failure.  Poking through the file lock, it appears because multiple tests build the same project but output to a different pack location. It's the obj folder that stays locked between different test runs.

@joeloff @MiYanni as template owners. I see a few options for fixing this:

1. shut down dotnet in between tests (not sure what side effect this would have)
2. Set the BaseIntermediateOutputPath for each build of the shared project (only fixes 10 tests and doesn't affect locking of the build output, only the obj)
3. Copy the test project to a unique folder before building (this is what the other sdk tests do but there isn't existing infrastructure for this in the templating tests).

Opinions?

**Comment by MiYanni** [comment]
If the output for each is in the different location, I'd just do the same for the intermediary files too. So, option 2 in this case.
