### ISSUE TITLE
Add a way to customize the path imprinted into apphost.exe

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/sdk#3405]
Currently there's no supported public way to customize the path to the app which is imprinted into the apphost.exe (to get the native executable). For normal apps it's always the name of the main application dll.

There are scenarios where it would be handy to be able to customize the path by redirecting it to a subfolder relative the native exe. See for example https://github.com/dotnet/core-setup/issues/5120 and https://github.com/dotnet/cli/issues/11713. It would not provide a full solution to the issue described there, but it would make it significantly easier to implement a custom solution.

**Comment by vitek-karas** [comment]
Note that using a relative path as the imprinted path is already supported as it's used by the global tools executables. The path is relative to the executable itself (current directory is not considered).

**Comment by Symbai** [comment]
I'm the owner of the issue https://github.com/dotnet/core-setup/issues/5120 and I would like to explain questions vitek-karas gave me to make it easier for readers to understand this issue.

### what's the problem I'm facing now

At the moment publishing self contained applications simply throws the whole .NET Core libraries into the output folder which are >260 and growing, which is a mess. Why is this a mess? Consider that many developers don't rely on using installers which places desktop shortcuts for the end user. Instead releasing their software as a portable application. The end user opens a directory with more than >260 files, which has a huge negative impression for most end users (remember they're mostly not technicians). But there are other scenarios as well. Imaging a portable application creates a setting.xml file within the main directory. Opening the folder and having to locate this file by first searching for it, doesn't feel right.

The .NET Core team seems to get aware of this issue by introducing single-file publishing and trimming. But why both of them aren't completely solving this issue I'm trying to explain below.

### why single-file doesn't work for me

Single file is great for portable applications reducing the "messy look". Sadly it has some downside aspects in some scenarios I would like to explain:

1. Single file reduces the startup time. For first run by "a lot" for other runs by "a bit". It some cases it's okay in other cases it's not. But in both cases it's a downside at first.
2. Many portable application developers placing the setting file into the same directory of the executable. For a single-file it will be a random temp folder, which may get vanished after a reboot. It's not persistent.
3. A benefit of a portable application is that it can be run from an external device and that it can also avoid leaving file traces on the computer. A single file application is fixed to get extracted into the temporarily directory the SDK has chosen itself. If we have to use single file publishing to avoid our problem, we can no longer say our application can be run from an external device without leaving traces.

### why trimming doesn't work for me

Trimming is a good way to get rid of unused code and perhaps some libraries but this targets the size aspect more than everything else. A larger application still has >200 .NET Core libraries in the output directory after trimming. While it helps for reducing the size, it doesn't help for this problem.

### Why do I want this

In short to get rid of the mess. To take the superb feature of .NET Core letting us publish our application self contained but avoid having the .NET Core files laying into the same folder as the application.exe, its setting file and perhaps its third party dependencies. To get a cleaner folder structure that separates the .NET Core from the application.

In my opinion there are two ways to achieve this, an easy and an advanced one.

## Easy:
Let us simply define the relative path of the Apphost is looking for. There is a short hack made by 0xd4d https://github.com/0xd4d/dnSpy/blob/master/Build/AppHostPatcher/Program.cs demonstrating it, which works very well but requires patching the executable and nobody knows if this is going to work in the future. For end users they will see the executable first and don't have to look into the real folder mess. In this case the folder structure can become:

```
Program.exe
bin\Program.dll
bin\Settings.xml
bin\System.dll
bin\...
```

## Advance:
Let us define the relative path of the Apphost is looking for **and** the relative path of the .NET Core libraries which, unlike the easy solution, separates the .NET Core files strictly from the rest of the application which is an even cleaner folder structure. For end users they will see the executable first and don't have to look into the real folder mess. For advanced users they can navigate into the bin folder and see only the application files but don't have to bother with .NET Core files. Which is great because it now doesn't matter how many .NET Core files there will be, because we don't have to see them at all.

```
Program.exe
bin\Program.dll
bin\Settings.xml
bin\core\System.dll
bin\core\...
```

**Comment by Kinematics** [comment]
I created issue https://github.com/dotnet/cli/issues/11713, and have similar issues as @Symbai. I'm kind of repeating a lot of what he said, but still wanted to explain my perspective.

## Scenarios

This is a combination of issues with portable and self-contained programs.  If I provide a program that someone wants to run on a library computer (bringing it with them on a flash drive), they can't depend on being able to store config information on the computer (eg: if extracted to a temp directory).  The computer also may or may not have .NET Core installed on it (which wasn't as much of a concern when creating a .NET Framework-based program), which means the user might need a self-contained version of the program.

Either way, the more noise in the root directory, the more difficult it is to run the program, and the more aggravating it is for the end user.  It might be a minor aggravation, but it's one that shows up every time they want to use the program, prompting questions of why I moved to a less usable and more annoying framework.

.NET Core is moving more and more towards the use of NuGet packages to expand functionality, which means more and more support libraries are are being included in the build.  That means that the more we move towards .NET Core, the messier this gets, and it expands exponentially if you need a self-contained version of the program, since that includes all the .NET Core libraries as well.

Single-exe is not a solution because the program is extracted to a temporary location, which will be lost when the user leaves.  Not only are config files lost, but if you need to provide a self-contained version of the program (because the library computer doesn't have .NET Core installed), it's having to extract 60 MB of files every time you go to the library.  That's a different type of aggravation, but one that will nonetheless still persist on every use.

## Specifying the output subfolder

Whether from CLI or Visual Studio's GUI, you can specify the output directory, the configuration, the target framework, and the target runtime of a project during publish.  Adding another option for the target library path (relative to the .exe) should be trivial, since that's already possible within the build tools, and just hasn't been exposed by the SDK.

It can default to the current empty field, which just drops everything in the root directory, or allow the user to specify an alternate directory.  Note that I can't think of any reason to allow anything other than a single child directory to be used for this purpose, but I also don't think anything special needs to be done to filter what's placed here, so just accept a single relative directory entry here.

Given that relative directory, all build output other than the .exe should be placed there. 

Aside: I'm not sure whether the .json config files need to be next to the myapp.exe or the myapp.dll output, so adjust accordingly.  I'm also not sure which directory would be considered the 'root' directory, for the purpose of running the program, saving config files, etc.  If the bin directory is the new root, then `additionalProbingPaths` doesn't need to be modified. 

It would probably be preferable for the 'root' to remain the original directory, though, because that's a good location to put config files or log files that you want the user to be able to easily find, and there's reasons for other subdirectories for the program to want access to (eg: resource images, language packs, etc).

## Structuring the output

Subdirectories under the bin directory have further use.  @Symbai already mentioned a core directory to hold all the .NET Core files, in the case of a self-contained build.  In addition, I believe it would be beneficial to place all nuget packages in appropriate relative paths (eg: `HtmlAgilityPack/1.11.8/lib/netstandard2.0`) within the bin directory.  This is related to https://github.com/dotnet/core-setup/issues/5645, where the locally specified relative paths are not searched on their own.  With this, 5645 would basically be a non-bug because, while the `bin` directory would be ignored when trying to resolve dependencies, `bin/HtmlAgilityPack/1.11.8/lib/netstandard2.0` would be searched, which is all we need.  It's a huge hassle to do that manually, but wouldn't be an issue if automated.

This is not strictly necessary for cleaning up the root directory, since all the output will have already been moved if Part One is implemented, and, from what I understand, said root directory would be fully searched for assembly resolution purposes.  However it provides relative easy options for loading specific versions of a given NuGet package, or possibly even multiple versions in the event of dependency problems (eg: depending on Library A and Library B.1, while Library A itself depends on Library B.2).

That's obviously a future issue, but having a proper framework for how the dlls get stored means that's not a stumbling block if/when that ever gets tackled, and it's relatively easy to make use of on the dev side even without that.

Since the relative paths are already stored in the `deps.json` file, nothing else is necessary on the runtime side, only the build side.  Since the full directory to each dependency is clearly already known, given that it's necessary to find the files and build the `deps.json` file, creating the directories in the build directory shouldn't be an issue.

Note: I don't think we need user-controlled specification of these deeper folders.  The NuGet folder structure, and 'core' (if used) for the .NET Core files of a self-contained build, should be sufficient and stable.

## Summary

In general:
- Self-contained is sometimes useful, but exacerbates the noisy root directory problem.  It is not itself a fix for the issues at hand.
- Single-exe hides the mess, but introduces new problems with how it uses temp directories, and is not suitable for a portable program unless you can get it to extract to a temp directory within the current directory itself (which feels like it would be more annoying to get right, and redundant with just having a decent zip archive that could be unzipped there). Single-exe+Self-contained is especially troublesome.
- Cleaning up the root directory means both moving the immediate output, and making sure the dlls can be found, which means making use of the full NuGet relative paths (which has the potential for other benefits later).

**Comment by livarcocc** [comment]
We don't need two issues (One in the cli and one in the SDK for this). Given that the CLI issues is older, I am going to close this one.

For reference, this is the CLI issue: dotnet/cli#11713,
