### ISSUE TITLE
App manifest needed to specify maxTestedVersion for hosting xaml but .NETCore 3 doesn't pick up the manifest

### ISSUE THREAD

**Issue by asklar** [dotnet/sdk#3462]
I have a .netcore3 [console] app in the form of a DLL, which uses the uap xaml APIs that allow creating xaml objects, etc (Windows.UI.Xaml.Hosting, etc.). 

When I run the app, I get an exception:
Unhandled Exception: System.Exception: Catastrophic failure

WindowsXamlManager and DesktopWindowXamlSource are supported for apps targeting Windows version 10.0.18226.0 and later.  Please check either the application manifest or package manifest and ensure the MaxTestedVersion property is updated.

Since the hosting feature requires an app manifest, I wrote one, but nothing in the build process is picking it up (I just put garbage into the manifest and nothing complained). I figured that since my app is a DLL and not an exe, maybe the manifest thing doesn't work.

I found this issue talking about app.manifest in dotnetcore3 but not clear what the fix is for the **MaxTestedVersion** issue I'm seeing is.
https://github.com/dotnet/sdk/issues/1899

**Comment by livarcocc** [comment]
cc @nguerrera

**Comment by nguerrera** [comment]
cc @jeffschwMSFT @vitek-karas @peterhuene 

> I have a .netcore3 [console] app in the form of a DLL

Are you setting UseAppHost=false? The manifest will be copied to the apphost EXE otherwise. It is not possible to honor a manifest if the app is activated using `dotnet app.dll`, you will need to use the apphost exe to launch the app.

If that's not it, can you supply a small project that reproduces the issue?

**Comment by asklar** [comment]
I'm not able to find any msdn docs on UseAppHost but I was not setting it in my csproj file.
I tried setting it, rebuilt, and it's still building a dll…

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="3.1.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.1.0" />
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.18362.2002-preview" />
    <PackageReference Include="System.CodeDom" Version="4.5.0" />
  </ItemGroup>

</Project>

```

**Comment by jeffschwMSFT** [comment]
@asklar <UseAppHost>true</UseAppHost> is what you are looking for to enable this scenario (the default in 3 is true).  What are the contents of your output directory when this is set to true?

**Comment by asklar** [comment]
interesting. When I set it to true, dotnet build says it built a DLL but the build directory shows both a DLL and an EXE.
Running the EXE displays this message:
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

**Comment by jeffschwMSFT** [comment]
I feel this means we are heading in a good direction.  Can you verify if the side-by-side manigest in the apphost is valid?  It is possible that it was merged incorrectly.

**Comment by asklar** [comment]
d'oh, I was missing a closing > in my </application> close tag.
It seems like there's no XML/manifest validation that gets run as part of dotnet build, I'd expect it to do so though.

**Comment by jeffschwMSFT** [comment]
I am happy to hear that things are going well.  I'll loop @nguerrera back in on thoughts on if this could be validated in some way.

**Comment by nguerrera** [comment]
We don't really know anything about manifest, roslyn embeds it as a win32 resource and then we copy all the win32 resources to apphost. I think the validation here is exactly the same as you would get in a .NET Framework project. If we wanted to validate, I think the analysis would go in the compiler so that it applied to all projects, not just .NET Core.

Also just want to reiterate that UseAppHost=true is the default for .NET Core 3+ so you can simply remove that from the csproj. Just make sure to run the exe and not dotnet the dll.
