### ISSUE TITLE
Investigate APICompat errors caused by assembly references re-used from the right-hand side during package validation

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/sdk#35214]
I.e. winforms when dropping net6.0 and net7.0 from their System.Drawing.Common package:

> D:\winforms\.dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ApiCompat.ValidatePackage.targets(39,5): error : API compatibility errors between 'lib/net6.0/System.Drawing.Common.dll' (d:\Nuget\system.drawing.common\7.0.0\system.drawing.common.7.0.0.nupkg) and 'lib/netstandard2.0/System.Drawing.Common.dll' (D:\winforms\artifacts\packages\Debug\Shipping\System.Drawing.Common.9.0.0-dev.nupkg):
1>D:\winforms\.dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ApiCompat.ValidatePackage.targets(39,5): error CP1002: Could not find matching assembly: 'System.Runtime.dll' in any of the search directories.
1>D:\winforms\.dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ApiCompat.ValidatePackage.targets(39,5): error CP0008: Type 'System.Drawing.CharacterRange' does not implement interface 'System.IEquatable<System.Drawing.CharacterRange>' on lib/netstandard2.0/System.Drawing.Common.dll but it does on [Baseline] lib/net6.0/System.Drawing.Common.dll

**Comment by ericstj** [comment]
I think this is related the discussion we were having here: https://github.com/dotnet/sdk/pull/32930#issuecomment-1570559651

We can only use "newer" references.  So we need to make sure we check the framework we're applying the references to and make sure those references are equal or newer to the framework they're being applied to. 

Looks like there's a special case here with our packages, where we're introducing holes in the support which causes this problem for us.  If we wanted to handle that special case, we could consider _all_ right side reference groups when deciding which to use for the left assembly - however I'm not sure that's really going to matter since in our cases of support holes we just want to skip all the compat checks for these support holes.

Another case of this might be for a project to reduce it's multi-targeting (without creating a support hole) - for instance intentionally reducing from `netstandard2.0;net6.0` to `netstandard2.0`.

In practice I don't think it's going to be too common for users to reduce their multi-targeting in newer versions, so I think in the default case we can just skip using references when we see that they'd be older than the framework of the asset we're loading.  Optionally - we could look at the entire set of frameworks to see if we could find any newer framework references to use - though this would only work in the cases where the project still targeted those newer frameworks.  If we wanted to create a pathway for folks to be 100% correct, they'd need another restore (eg from a generated project) to collect references for the old frameworks.
