### ISSUE TITLE
dotnet pack fails due to bad paths returned by BuiltProjectOutputGroup target

### ISSUE THREAD

**Issue by rrelyea** [dotnet/sdk#356]
See https://github.com/NuGet/Home/issues/3865 for repro instructions.
we were seeing this with: cli: 1.0.0-preview3-004007
Works fine for migrated projects (TargetFrameworks), broken for new projects (TargetFramework).
We'd love to see fixed for RC if possible.

@nguerrera @piotrpMSFT @srivatsn @livarcocc

**Comment by srivatsn** [comment]
@nguerrera can you take a look at this?

**Comment by nguerrera** [comment]
@srivatsn @rrelyea I took a look and the problem appears to be due to an error in the batching MSBuild calls made by the pack target:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack/Pack.targets#L135

I don't know why %(_MSBuildProjectReferenceExistent) is involved here, seems like cut and paste from other invocations that are actually building the project references, but here we're building the the root project. This is causing duplicate invocations: we're asking for all the project reference (# of project reference) times. Worse, and I don't understand why (cc @rainersigwald), some of the invocations get global property TargetFramework=[blank], which is why the wrong output path is calculated.

**Comment by rainersigwald** [comment]
The reason that some invocations get an empty TargetFramework is that the rules for batching over multiple metadata are so complicated that my advice is "never do it".

**Comment by tommed** [comment]
For reference, you can also build both projects then `pack` with the `--no-build` option.
