### ISSUE TITLE
CopyLocalLockFileAssemblies not respected in 8.0.100-rc.1.23463.5

### ISSUE THREAD

**Issue by petertiedemann** [dotnet/sdk#35817]
### Describe the bug
* Use this simple sample app
 [TestApp.zip](https://github.com/dotnet/sdk/files/12791994/TestApp.zip)
* Note that TestApp.csproj specifies `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`
* Run dotnet build TestApp.csproj - o foo
* cd foo and note that the System.Text.Json.dll is not in the folder as expected.

Bonus info:
* If you add System.IO.Pipelines, it *will* get copied, as will e.g. Newtonsoft.Json.
* If you replace the target framework with net6.0 or net7.0, then System.Text.Json.dll **is** copied.

### Further technical details
.NET SDK:
 Version:   8.0.100-rc.1.23463.5
 Commit:    e7f4de8816

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-rc.1.23463.5\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.1.23419.4
  Architecture: x64
  Commit:       92959931a3
  RID:          win-x64

.NET SDKs installed:
  2.1.818 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.414 [C:\Program Files\dotnet\sdk]
  7.0.401 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23463.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.1.23420.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by MiYanni** [comment]
I tested this against `8.0.100-rc.2.23477.19` and could repro the issue where `System.Text.Json.dll` is not copied to the output path when `CopyLocalLockFileAssemblies` is set to `true`.

@dsplaisted I took a look at this and I didn't see anything obvious causing this to change on our side by looking for the use of `CopyLocalLockFileAssemblies` in our codebase. Any chance that the portable RID changes could have affected this?

@jeffhandley This issue is related to `System.Text.Json` for the 8.0.0 versions. Do you know if something would have changed to no longer nominate this for being copied when `CopyLocalLockFileAssemblies` is set `true`?

**Comment by dsplaisted** [comment]
@MiYanni This isn't really related to `CopyLocalLockFileAssemblies`.  When that is set to true, then dependencies will be copied to the output (ie so that the app can run, as opposed to a library where dependencies won't be copied).

However, for assemblies that are part of the shared framework, they will not be copied (unless the version from the NuGet package is newer).  This is called conflict resolution.  See my comment here also: https://github.com/dotnet/sdk/issues/35816#issuecomment-1755919590

**Comment by marcpopMSFT** [comment]
Resolved per Daniel's comments
