### ISSUE TITLE
Net 8.0 RC During build System.Text.Json NuGet isn't copied to bin folder (in net 7.0 its still copied) 

### ISSUE THREAD

**Issue by GC-Configit** [dotnet/sdk#35816]
### Describe the bug
When I'm using net 8.0 RC during build I don't get `System` NuGet dlls in the bin folder. For net 7.0 I would get it, thats why I'm assuming it's a bug.

### To Reproduce
Simply create a new console application. Change `<TargetFramework>net8.0</TargetFramework>` to `<TargetFrameworks>net8.0;net7.0</TargetFrameworks>` Add `System.Text.Json` package. Build the project and then compare bin folders:
- in net7.0 folder there would be `System.Text.Encodings.Web.dll` and `System.Text.Json.dll`
- in net8.0 folder there won't be those dlls

![image](https://github.com/dotnet/sdk/assets/106981486/0c781b4e-f6e6-4f85-8549-fa704ba29b21)

**Comment by marcpopMSFT** [comment]
I believe this is by design since those components come from the runtime. I recall seeing a change for this but can't find it at the moment where we changed the behavior to no longer copy binaries we didn't need since for a framework-dependent application, we can load that file from the shared framework directly. @baronfel @dsplaisted do ya'll recall that change?

**Comment by petertiedemann** [comment]
@marcpopMSFT This should be the same issue btw: https://github.com/dotnet/sdk/issues/35817

**Comment by marcpopMSFT** [comment]
Resolved per Daniel's comments

**Comment by GC-Configit** [comment]
Thank you guys for the information :)
