### ISSUE TITLE
Containers: detection of port config should prefer ASPNETCORE_URLS

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#35845]
For backwards compat, HTTP_PORTS and HTTPS_PORTS get ignored when URLS is set:

https://github.com/dotnet/aspnetcore/blob/f49c1c7f7467c184ffb630086afac447772096c6/src/Hosting/Hosting/src/GenericHost/GenericWebHostService.cs#L81-L83

The sdk doesn't implement this, and exposes ports for all the envvars.

cc @baronfel

**Comment by baronfel** [comment]
Good catch - since the only result of this is more ports being declared, and since very little tooling uses the exposed port information (mostly local dev inner loop tooling like 'docker run -P' and things like the VSCode Docker tooling run and attach capability), I think we should fix this in 8.0.200 instead of trying to get approval to take the fix to 8.0.100.

**Comment by baronfel** [comment]
This should be released in 8.0.200 next month!
