### ISSUE TITLE
[NETSDKE2E]With NET8 RC2 SDK installed, The message "Manifest package for microsoft.net.sdk.aspire doesn't exist" displays during installing workload.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#35921]
1. install net 8 RC 2 SDK: 8.0.100-rc.2.23502.2 from [https://dev.azure.com/dnceng/internal/_build/results?buildId=2281595&view=artifacts&pathAsName=false&type=publishedArtifacts](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D2281595%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=05%7C01%7Cv-danche%40microsoft.com%7C94a7f101b158405aa43b08dbc5e75fa4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638321370006213947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1T9GHI7Bjhi06TduvDuxbbWk1%2FpeWDml9UOzRmA9y28%3D&reserved=0)
2. Run "dotnet workload install wasm-tools" in CLI

Expected Result:
wasm-tools workload can be installed successfully

Actual Result:
wasm-tools workload is  installed successfully, but the message "Advertising manifest not updated. Manifest package for microsoft.net.sdk.aspire doesn't exist" displays during installing workload.

![image](https://github.com/dotnet/sdk/assets/65637796/bdac9715-5c69-42e9-9c1c-0e25be17f737)

dotnet --info:
![image](https://github.com/dotnet/sdk/assets/65637796/34a1f0ee-9d6a-4470-a554-291c353cd9f8)

**Comment by vdanche** [comment]
This issue not repro now after applying feed https://devdiv.pkgs.visualstudio.com/_packaging/8.0.0-rc.2.9373-shipping%40Local/nuget/v3/index.json
![image](https://github.com/dotnet/sdk/assets/65637796/4657289c-9a38-4079-81b4-1d0b72ec5d0b)

**Comment by TheFanatr** [comment]
Hi! For people outside of Microsoft, it seems that access to both [`https://dev.azure.com/dnceng/internal/_build/results?buildId=2281595&view=artifacts&pathAsName=false&type=publishedArtifacts`](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D2281595%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=05%7C01%7Cv-danche%40microsoft.com%7C94a7f101b158405aa43b08dbc5e75fa4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638321370006213947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1T9GHI7Bjhi06TduvDuxbbWk1%2FpeWDml9UOzRmA9y28%3D&reserved=0) and [`https://devdiv.pkgs.visualstudio.com/_packaging/8.0.0-rc.2.9373-shipping%40Local/nuget/v3/index.json`](https://devdiv.pkgs.visualstudio.com/_packaging/8.0.0-rc.2.9373-shipping%40Local/nuget/v3/index.json) is forbidden; the issue of `Advertising manifest not updated. Manifest package for microsoft.net.sdk.aspire doesn't exist.` can be fixed with the package source [`https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json`](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json), which, when used in `sudo dotnet workload update --include-previews --from-previous-sdk --ignore-failed-sources --advertising-manifests-only --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json` on macOS Sonoma 14.1 Beta, results in `Updated advertising manifest microsoft.net.sdk.aspire.`.

Is there some other, more official, equivalent to the internal build archive listing and feed? Thanks!
