### ISSUE TITLE
Flexibility of installation on Linux is more trouble than it is worth.

### ISSUE THREAD

**Issue by glennsills** [dotnet/sdk#36046]
### Is your feature request related to a problem? Please describe.
People face recurring issues often described as "dotnet SDK installed on Linux but not recognized". This seems to be due to multiple conflicting ways of installing Dotnet on Linux.  If a developer, after using a version of the SDK for a year or so needs to upgrade, it is understandable if he forgets how he did it the last time. Also, the changing package manager situation vis a vi Microsoft and Ubuntu is problematic.

### Describe the solution you'd like
I would suggest you create **one** installation methodology and follow the pattern illustrated by the Go installation procedures here:  
[Download and Install - The Go Programming Language ](https://go.dev/doc/install). Select Linux from the instructions. You'll see that after downloading the gzipped tar file, there are three easy command lines needed to accomplish both an install **or** an upgrade.

In understand the attraction of package management, but unless it works perfectly, including handling uninstalls of installations made by other methods (almost impossible) it seems to be more trouble than it is worth.

### Additional context
I ended up fixing this particular problem myself with a judicious "sudo cp" of one installation into another. This would not be necessary if you just simplified. In this case, less is more.

**Comment by glennsills** [comment]
I think it should be label:Area-NetSDK, but I am unable to set it.

**Comment by richlander** [comment]
FYI: This is the intended link.

https://go.dev/doc/install

**Comment by richlander** [comment]
The point on complexity is fair, particularly on how the Microsoft and Canonical feeds relate. That bit is particularly unfortunate. We're working with Canonical to avoid this problem by encouraging them to ship their (new major version) packages on the same day as us. They are working towards that goal and want to do the best for the .NET community.

This point-of-view is an uncommon one (please only ship `.tar.gz` files) and we know that users (collectively) enthusiastically use the full set of download options we offer. I use all of the options regularly, depending on what I'm doing. Also, the packages experience has a lot of benefit, while `.tar.gz` files put more update burden on the user.

There would be a lot of (legit) criticism if we removed the other options. In reality, we're no longer in a position to do that. .NET packages are baked into [several Linux distros](https://github.com/dotnet/core/blob/main/linux.md). Those projects take and build .NET source on their own because their users want it. Naturally, we support them (figuratively and literally) doing that.

It takes perhaps a minute to determine how a given component was installed on a system. It doesn't need to be a mystery.

All that said, I'd love for there to be better support for installing and update .NET from the CLI and for it to report if a given action is going to lead to the problems you are raising. That'd be real nice, particularly for nightly builds.

**Comment by glennsills** [comment]
A mechanism to update .NET from the CLI would be great, but it would need to accommodate the different places that the installation mechanisms are putting things.

**Comment by MichaelSimons** [comment]
> This point-of-view is an uncommon one (please only ship .tar.gz files) and we know that users (collectively) enthusiastically use the full set of download options we offer.

Having .NET absent from native package feeds can be an adoption blocker for some.  It is common for enterprises to have policies which prevent (or require an approval process) usage of components that are not in the native package feeds.  The basis for these policies is based on security/serviceability amongst others.

**Comment by baronfel** [comment]
I'm going to close this as we have generally stopped pushing .NET to package.microsoft.com for Ubuntu and Fedora in favor of the distro feeds. If users want newer SDKs than the distros provide, they can request that from the distro maintainers and/or use the dontet-install scripts to install and manage local installations.
