### ISSUE TITLE
The Container test failed due to no available .NET9 images

### ISSUE THREAD

**Issue by v-wuzhai** [dotnet/sdk#36160]
### Pull Request
https://github.com/dotnet/sdk/pull/34996

### Failed leg
dotnet-sdk-public-ci (Build Ubuntu_22_04 Build_Release)

### Describe the bug
Container tests is hitting the exception below while running in pipeline. Build link: https://dev.azure.com/dnceng-public/public/_build/results?buildId=437466&view=results

`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

**Comment by v-wuzhai** [comment]
As @baronfel said, these tests are based on. NET 9 images, but there aren't currently any SDK Container tooling features that are reliant on .NET 9, so we could probably just keep these tests pinned to .Net 8 (where we do have usable base images) and bump them to 9 at a later time, once we begin creating usable .NET 9 images from dotnet/dotnet-docker.

**Comment by baronfel** [comment]
We should be able to light this one up shortly after the first preview of .NET 9. When the 9 preview images become available, we can:
* change the TFM in the test to net9.0
* use the RuntimeFrameworkVersion MSBuild property to force the test app to use that runtime framework so that the app will actually _run_
