### ISSUE TITLE
New csproj re-generates files forever when Visual Studio is open

### ISSUE THREAD

**Issue by Jmales** [dotnet/sdk#3627]
I'm generating some .cs files using **node.exe** before the compilation, which I then include in my project.

I call **node.exe** and define the steps for the generation via CSProj. After migrating the CSProj to the new format `<Project Sdk="Microsoft.NET.Sdk">` the files are constantly being generated, erased and generated again while Visual Studio is open (tested with VS2017 and VS2019). This doesn't happen if Visual Studio is closed.

This is my targets file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    ...
  </PropertyGroup>

   <Target Name="SetVariables">
    <ItemGroup>
      <_NodeJsExe Include="$(MSBuildThisFileDirectory)..\..\..\Node.js.redist\*\tools\win-x64\node.exe"/>
    </ItemGroup>
    <PropertyGroup>
      <__NodeJsExe>@(_NodeJsExe);</__NodeJsExe>
      <NodeJsExe>$(__NodeJsExe.Substring(0, $(__NodeJsExe.IndexOf(';'))))</NodeJsExe>
    </PropertyGroup>
  </Target>

   <Target Name="ProblemHere" BeforeTargets="TransformDuringBuild;PrepareForBuild;CoreCompile" DependsOnTargets="SetVariables;CleanFilesBeforeBuild">
    <Exec Command="&quot;$(NodeJsExe)&quot..." />
  </Target>

  <Target Name="CleanFilesBeforeBuild">
    <ItemGroup>
      <Ts2LangFiles Include="$(GeneratedFolder)\**\*.cs" />
    </ItemGroup>
    <Delete Files="@(Ts2LangFiles)"/>
  </Target>
  </Project>
```

Anyone knows what the problem is?

**Comment by Jmales** [comment]
https://github.com/Microsoft/msbuild/issues/3342

**Comment by Jmales** [comment]
#https://github.com/Microsoft/msbuild/issues/3342

**Comment by rainersigwald** [comment]
This is related to Visual Studio's [design time builds](https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md), which run builds in the background to collect information about the project. That link has more information, including how to detect that a design-time build is currently running and avoid doing work. The only thing I'd add is that it's important to make sure that every target that runs in a design-time build context either completes quickly, or has good [incremental behavior](https://docs.microsoft.com/en-us/visualstudio/msbuild/incremental-builds) so that it doesn't unnecessarily regenerate its outputs. It sounds like the latter is the case here:  this target is running in each design-time build (that's good, because it generates source files and it's important to have the right set of source files passed to the compiler at design time), but it also deletes and recreates the files for every design-time build, instead of just completing as up to date.
