### ISSUE TITLE
Can you try setting when you have minor .net runtime 

### ISSUE THREAD

**Issue by iliya-fatahi** [dotnet/sdk#36498]
You can  try setting

```xml
<PropertyGroup>
  <RollForward>Major</RollForward>
</PropertyGroup>
```

in the csproj so the emitted runtimeconfig.json tells the host to execute the 5.* app on a 6.* framework? Major version roll-forward currently requires explicit opt in.

_Originally posted by @dasMulli in https://github.com/dotnet/sdk/issues/16427#issuecomment-803971194_

**Comment by vitek-karas** [comment]
Could you please describe what is the ask here?

It is by design that apps are by default not going to run on higher major version of runtime. Major versions introduce breaking changes and thus allow it would potentially break apps. That's why by default the app will require a matching major version runtime (it will roll forward on minor versions by default). If you want your app to run on any version of the runtime and you accept the risk that new major versions of the runtime may break your app, then use the `RollForward=Major`.

**Comment by iliya-fatahi** [comment]
Thanks for share you're tips
it was just spelling mistake I wanted to share this with other friends
