### ISSUE TITLE
Provide an option to prevent trim from removing unused constructors

### ISSUE THREAD

**Issue by NeilMacMullen** [dotnet/sdk#36835]
### Is your feature request related to a problem? Please describe.

Many serializers expect types to contain parameterless constructors so that they can "new up" an empty object then fill in the properties. Unfortunately when publishing a self-contained  exe with "trim unused code" implicit parameterless constructors which are only referenced via reflection are removed since there's no visible use.

### Describe the solution you'd like
This seems like a common enough scenario that a special trim option could be provided to prevent trimming of unused constructors as long as some use is made of the object type within the code.  The alternative would presumably be to explicitly declare the constructors and decorate with the no-trim attribute but that's a bit tedious and it's not obvious it would work for cases where the object is included from a library

**Comment by NeilMacMullen** [comment]
Thanks - that's a good suggestion.   https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming?pivots=dotnet-8-0 contains some info along with this message...  
![image](https://github.com/dotnet/sdk/assets/9131337/032717f2-0cbf-4136-8b58-5d2d7b1f411e)

I guess my suggestion was that since reflection-based serializers are a pretty common thing (maybe less so in the future...) it would be helpful to have a "global" method for avoiding falling into the trap of turning on "trim" and having all your serialization code fail ;-)

**Comment by vitek-karas** [comment]
What type of application do you work on? If this is a console app or ASP.NET app you should get a warning for each of these "broken" cases. Did you get a warning like that?

Note that just preserving constructors would not be enough - what about the properties the serializer would fill in later on? And what about additional members the serializer might need to call, and so on. This is a very difficult problem to solve, and so far we didn't come up with a solution which would work in general for "serializers". Source generators are the best approach we have right now - System.Text.Json supports it, but many other serializers don't and it makes them trim incompatible right now.

**Comment by vitek-karas** [comment]
I have to apologize, apparently there's still a bug in VS publish experience. The `just a few generic "library X has trim warnings` should be reported as real warnings, but somehow they're not. If you run the publish from command line they will be reported correctly.

What this warning (once it's recognized as such) is saying that the library is not compatible with trimming and that your app may not work correctly. 

Unfortunately this doesn't have a simple answer. I understand that your case might be "simple" as it's obvious to you what needs to be kept in order for the app to work, but it's not obvious to the tools. You could use the annotations mentioned above and maybe it will work, but there are no guarantees, unless you get 0 warnings on publish.

You can read some more details here: https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/fixing-warnings

The problem is that reflection usage is "global" - meaning if the tooling can't completely figure out what it's doing, there's no way to tell if the "Deserializer" in your command line parser will only touch types from your code, or if it will also use reflection on stuff from the framework, or really any other assembly in the app.

As for the "partial" mode mentioned above - it's a possibility and it's more likely to work without additional work, but there are no guarantees. In that mode you won't get any warnings, but things might still break. It also makes the app larger typically.

**Comment by NeilMacMullen** [comment]
No worries.  I think that on reflection my suggestion is probably not the best one.  Perhaps the real problem here is that the placement of the option in the VS UI makes it appear that "trimming unused code" is simply a straightforward way of removing unreferenced bits of the net framework.
