### ISSUE TITLE
dotnet 8 SDK uninstalls dotnet 7

### ISSUE THREAD

**Issue by jods4** [dotnet/sdk#36990]
After upgrading VS to 17.8, which installs the dotnet 8.0.100 SDK, I noticed my v7 SDK is gone.
This is easily verified with `dotnet --list-sdks`.

I knew SDK automatically uninstalls previous patch releases to keep the number of installed SDKs reasonable, and that is fine (we use `rollForward: feature` in `global.json` to account for that).
Uninstalling a major version is a bigger deal and I think it's a bad idea, here's why:

We use `global.json` to force the local use of a specific (major) SDK release.
This ensures that until the CI has been upgraded, no developer inadvertently uses new features (e.g. C#12 syntax) that breaks the build.

Suddenly after a seemingly minor VS patch upgrade, devs are faced with lots of errors (because the SDK is gone):
![image](https://github.com/dotnet/sdk/assets/3832820/a49bad79-3253-4c7d-ab6c-a27f695db82a)

I assume you're doing this because 7 is STS and 8 LTS, but please reconsider.

**Comment by adegeo** [comment]
@jods4 This sounds like a Visual Studio problem. You can use **Help** > **Send Feedback...** menu item to report a problem. The Visual Studio installer has options to install different versions of .NET.

I think if you run `dotnet --list-sdks` you'll see what's installed on your system, not necessarily what Visual Studio has. If I remember correctly, VS has its own copies of .NET.

**Comment by jods4** [comment]
@adegeo Obviously, I'm only observing the situation after the fact. I have no way of knowing for sure which process has actually uninstalled .net 7.

I'd be surprised that VS itself, in a minor upgrade, decided to remove a dotnet SDK; whereas on the other hand the dotnet SDK is already known to remove previous (minor) SDK releases. But this is something that you can check internally at MS?

> I think if you run dotnet --list-sdks you'll see what's installed on your system, not necessarily what Visual Studio has. If I remember correctly, VS has its own copies of .NET.

Well, that sounds like a dotnet problem them. Because I definitely had the 7.0 SDK installed on my system before (as reported by `--list-sdks`) and then it was gone.

Please don't focus on the VS screenshot too much though: I also had similar "missing SDK" issues reported in VS Code, and they all (VS + VS Code) went away after I manually re-installed the 7.0 SDK (so it's back in `--list-sdks`).

**Comment by ivaylo5ev** [comment]
I've experienced the same issue. Indeed one of the last things I did was to update Visual Studio before I noticed the missing SDK. I use Rider for most of my .NET development, and I was surprise to see it fail to load one of my projects that uses the .NET 7 SDK (a couple of hours after the VS update). 

Manually installing the .NET 7 SDK resolved the problem, but created some confusion. I am certain now that during the VS installation process is where it all happened, but I am not sure if this was done intentionally by the VS installer, or by the .NET 8 SDK installer itself, which was started by VS Installer. If the .NET 8 SDK installer has such an option, and if VS Installer issued that option for whatever purpose, then I think it should be addressed with the VS team because this behavior does not play nice with other tools relying on the 7.0 SDK.

**Comment by adegeo** [comment]
The only thing I can really do is just ping people :D I wouldn't know where to look at to determine if there was some uninstall logic. However, I can test what happens on my machine as I'm out of date. I have VS from Sept-ish, .NET 8 RC, and 2x .NET 7 versions installed. `dotnet --info`:

```
.NET SDKs installed:
  6.0.417 [C:\Program Files\dotnet\sdk]
  7.0.311 [C:\Program Files\dotnet\sdk]
  7.0.403 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23463.5 [C:\Program Files\dotnet\sdk]
```

After upgrading, I have this!

```
.NET SDKs installed:
  6.0.417 [C:\Program Files\dotnet\sdk]
  7.0.311 [C:\Program Files\dotnet\sdk]
  8.0.100-rc.1.23463.5 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]
```

The RC wasn't removed (as expected, AFAIK previews are never removed) but I find it odd that 7.0.403 was removed had 7.0.311 remains! I also noted that the corresponding runtimes were removed too. I looked at my "Uninstall Programs" list and I see this:

![image](https://github.com/dotnet/sdk/assets/67293991/7539927f-6e05-4f21-b21c-d1a7599a13c3)

I wonder if my 7.0.403 (the latest 7.x) was also installed via Visual Studio and sure enough, upgrading to the latest installed .NET 8 and removed .NET 7. However, versions of .NET installed outside of VS remained.

I believe the .NET SDKs support the older versions, for example, I removed .NET 6 SDK and I was able to continue to target .NET 6 in Visual Studio and compile no problem. The output log indicated that it used a .NET 6 runtime though.

If you're going to pin a specific SDK/Runtime, I think that you need to manually install them so that they're not managed by Visual Studio. Looking at the Visual Studio installer in the **Individual Components** section, there is only an option for a single SDK, just named **.NET SDK**. But, every runtime is listed **.NET Core 2.1** through **.NET 8**.

**Comment by ivaylo5ev** [comment]
@adegeo Thank you for the detailed findings! It is useful to know that I need a manual install if I intend to keep the SDK for longer, and I am almost certain the removed .NET 7.0 SDK was installed by VS. Maybe it is not OK for the Rider IDE to rely on the VS stuff, so my comment for "playing nice" does not seem that appropriate now.

**Comment by marcpopMSFT** [comment]
This is the intended design. See the last item in [the global.json documentation](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#troubleshoot-build-warnings) for the details. It includes the workaround which you have already found which is to install the stand-alone SDK separately from Visual Studio and Visual Studio will not remove that version on upgrade. Note that most customers should not need to use an older SDK as the latest SDK can target all older runtimes.

**Comment by jods4** [comment]
> Note that most customers should not need to use an older SDK as the latest SDK can target all older runtimes.

As you're working for MS on build tools, I'd like to share the feedback that this might not be true.
Why can we even lock the SDK in `global.json` if you think that's not needed?

Yes, the latest SDK actually works fine (most of the time), but we lock the SDK in global.json to align with what our CI servers actually support.
Not everyone in a team, not every CI server, and not every static analysis tool gets to upgrade to a newer SDK at the same time.
Most of the time it causes no problem, but we've had issues in the past: someone merged something that was working fine locally, and the CI build was then broken for everyone until we figured it out. That's when we decided to use `global.json` to lock the SDK used by our projects, which we upgrade regularly after testing and ensuring that everyone has the SDK installed.

For my team personally, the question of installing VS 17.8 is past us so I don't care.
I think it'd be nice in future updates to have one screen in the installer wizard with a checkbox list of SDK that will be uninstalled. So that we're aware of what's happening and so that we can choose to keep them.

The biggest issue is that this is vastly unexpected from what the user perceives as a minor VS version update, and in some contexts (...VS Code) the resulting errors are confusing and a big loss of time to figure out what happened.
