### ISSUE TITLE
Build Order Bug with app.config/BeforeBuild

### ISSUE THREAD

**Issue by christophwille** [dotnet/sdk#3708]
Please see https://github.com/icsharpcode/ILSpy/issues/1731

Effectively, only Visual Studio gets the build order wrong, but both of our build servers don't (msbuild). The cause seems that app.config for ILSpy.csproj is built from a template.

**Comment by dasMulli** [comment]
the current pipeline determins if the project has a valid app.config during PrepareForBuild, at which point it is failing because there is a `<None Include="app.config" />` in the csproj but the file doesn't exist on disk. New build logic to work with that file now doesn't work.

Changing the custom target that runs a powershell script to run run before `PrepareForBuild` instead of before `BeforeBuild` fixes this issue and also fixes design-time builds that fail (somewhat invisible to the user) while projects are loaded and Nuget packages restored.

**Comment by dasMulli** [comment]
Looks like https://github.com/dotnet/sdk/pull/2447 breaks some VS builds for projects that generate the app.config file in BeforeForBuild and aren't prepared that the file is actually required for some design time builds now.

**Comment by livarcocc** [comment]
@wli3 can you take a look?

**Comment by wli3** [comment]
@christophwille Will setting `GenerateSupportedRuntime` to false help in this case? My understanding is ILSpy is generating an app.config during the build but we did not successfully detect that.

I don't think there is an "precise" way to do so, since it is a state on the disk, it could in theory appear anytime during the build. Moving the detection more close to copy files might help, but due to MSBuild scheduling task, it could still miss the disk state.

**Comment by christophwille** [comment]
@wli3 We are generating the app.config for ILSpy.csproj in a project that is a reference for it (icsharpcode.decompiler.csproj). Where would I put that property? ILSpy.csproj I presume.

Note that thanks to @dasMulli we tried another approach (see linked issue), but that means it is invoked multiple times (not desireable either).

**Comment by wli3** [comment]
Yes, ILSpy.csproj should work

**Comment by christophwille** [comment]
That worked, thanks.

**Comment by livarcocc** [comment]
Seems like the issue has been addressed. Closing.
