### ISSUE TITLE
minimumExpectedTests for dotnet test

### ISSUE THREAD

**Issue by rgroenewoudt** [dotnet/sdk#37101]
I would like a additional option for `dotnet test`: minimumExpectedTests.

It is possible that dotnet test runs less tests than expected and without this check it will happen without anyone noticing.

VsTest.exe aldy supports this functionality, which I'm missing now when migrating from VsTest to dotnet test.

**Comment by nohwnd** [comment]
This is functionality of the vstest azdo task that builds above the vstest platform. Which testing framework are you using to run tests?

**Comment by rgroenewoudt** [comment]
NUnit.

Perhaps something that returns an exitcode != 0 if dotnet test doesn't find so many tests to execute?

**Comment by pavlexander** [comment]
I also struggle because of this missing parameter... If you set up the azure devops pipeline (Linux agent) to execute the tests, and, due to misconfiguration of the pipeline - no tests are run - you will have no way to find it out..

Currently if the tests (or rather - the test project) are not found you get the **warning** message:

> ##[warning]Project file(s) matching the specified pattern were not found.

I would like to force the task to fail if no tests are executed at all.

Therefore the parameter `minimumExpectedTests` would be a solution to my problem as well..

**Comment by nohwnd** [comment]
We have this feature in the new testing platform https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli, which is available for mstest (in stable), xunit and nunit (in preview).

We do not yet have a full integration with dotnet test, but previews will be coming soon in net10

**Comment by Frulfump** [comment]
> We have this feature in the new testing platform https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-platform-intro?tabs=dotnetcli, which is available for mstest (in stable), xunit and nunit (in preview).
> 
> We do not yet have a full integration with dotnet test, but previews will be coming soon in net10

@nohwnd MTP doesn't work with projects like Stryker https://github.com/stryker-mutator/stryker-net/issues/3094, why not just add this super simple flag to the existing `dotnet test` command and .NET 8 will be supported until November 10:th 2026 https://dotnet.microsoft.com/en-us/platform/support/policy so we are far away from everyone moving on to .NET 10.

How will this work when it's integrated with `dotnet test` we just supply `--minimum-expected-tests 1`?

From the docs https://learn.microsoft.com/en-us/dotnet/core/testing/microsoft-testing-platform-intro?tabs=dotnetcli#options (can't anchor link to each option sadly so you will have to scroll a bit)

>--minimum-expected-tests
Specifies the minimum number of tests that are expected to run. By default, at least one test is expected to run.

So we can expect the command to fail by default if no tests are found? That would be ideal but it's not clear from the docs it just says what's expected but not what will happen if that expectation is not met.

Since we are a bit further into the .NET 10 previews what's the current state and is the integration on track to be integrated in .NET 10 GA in November?
