### ISSUE TITLE
Add-Migration not recognized after install of Microsoft.EntityFrameworkCore.Tools

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/sdk#37205]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Add-Migration-not-recognized-after-insta/10521987)._

---
[severity:It's more difficult to complete my work]
After installing Microsoft.EntityFrameworkCore.Tools I cannot use Add-Migration. It only reports
>Add-Migration : The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
>and try again.
>At line:1 char:1
>+ Add-Migration Net8
>+ ~~~~~~~~~~~~~
>    + CategoryInfo          : ObjectNotFound: (Add-Migration:String) [], CommandNotFoundException
>    + FullyQualifiedErrorId : CommandNotFoundException

When I try with dotnet, I get the following:
>dotnet ef migrations add Net8
>Failed to read environment variable [DOTNET_STARTUP_HOOKS], HRESULT: 0x80070002
>Build started...
>Build failed.

Thesse errors were there before VS 17.8 but I thought that it might be solved by 17.8 but unfortunately.... 

---
#### Feedback Bot on 11/22/2023, 01:50 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by erikthysell** [comment]
Sorry to have bothered. My mistakes... 
1. I tried to use Add-Migration in Developer PowerShell. In Package Manager Console it works just fine. (for me, these to consoles are a bit non-intuitive when it comes to usage)
2. Even if building the project that contains the dbcontext/migraitons and the startup project worked just fine, other projects in the same solution did not build (which was not obvious at first).  After fixing these. Add-Migration succeeded without issues.

Take away: When Add-Migration build fails -> instead of just "Build failed" message - "Build failed for one or more projects - see Output Build window" would be nice.

**Comment by marcpopMSFT** [comment]
Closing per above comment.
