### ISSUE TITLE
Extension point for languages

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#373]
To have an awesome language agnostic experience it's nice if the sdk (like previous `preview2`) has a clean extension point to add additional languages

Atm works ( ref f# [examples](https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview3) and [tests suite](https://github.com/dotnet/netcorecli-fsc/tree/master/test-msbuild) ), but can be improved a bit

An example the [fsharp with preview3](https://github.com/dotnet/netcorecli-fsc/blob/99e22f5413fa0dc7ea16bf92a35fb0048fa99207/examples/preview3/console/ExampleConsoleApp.fsproj#L26-L28)

So:

1. Add a `PackageReference`  to a lang sdk package who contains msbuild target files (example [FSharp.NET.Sdk](https://github.com/dotnet/netcorecli-fsc/tree/master/src/FSharp.NET.Sdk) ) who are auto imported
     - The targets file contains a:
          - `CoreCompile` task => ok, thats usually invoke the compiler to compile
          - `CreateManifestResourceNames` task => why?
2. Import at the end `$(MSBuildToolsPath)\Microsoft.Common.targets` (instead of `Microsoft.CSharp.targets`)

That's ok and works, but with some issues:

- I cannot directly include `Microsoft.Common.targets` inside my target files, because at the first `dotnet restore` doesnt exists, so restore doesnt work (`Common` imports nuget restore target somewhere).
- I think is important to be able to import `Microsoft.Common.targets` inside custom language targets, for example to be able to replicate the .net framework build script (so wildcard include before and after `.Common` import). If i put `.Common` inside the target file is an authoring error because is included two times (on `dotnet restore` is ok, but after that is included two times)
- I can specify to import the target inside nugetpackage at the end of project file, but is annoying atm because i need to do that starting from $NugetPackageCacheRoot directory, so that's going to include version of package. Also doesnt work at first `dotnet restore`, because doesnt exists yet, so i need to conditionally include `Common` anyway

Best experience from project:

- Just include a `PackageReference` with custom targets like `CoreCompile` (compiler can be a dotnet sdk tool :love:)
- No need to include `Microsoft.Common.targets` target at the end, maybe another target who will invoke the auto-imported lang target.

@nguerrera you have some ideas about how to do the extensibility changes?

/cc @piotrpMSFT @livarcocc @blackdwarf 
/cc @cartermp @KevinRansom @cloudRoutine for F#

Moved from https://github.com/dotnet/cli/issues/4669 on behalf of @enricosada

**Comment by enricosada** [comment]
@nguerrera got time to think about that? the extensibility with `dotnet-compile-{compilerName}` was nice in `preview2`.

The only blocking issue i think is split nuget `Restore` target functionality (invoked by `dotnet restore`) from `$(MSBuildToolsPath)\Microsoft.Common.targets` into another target. So:

- `dotnet restore` in a project with or without lang sdk works.
- the **empty** project file **doesnt include Microsoft.Common.targets** at end, just the extracted nuget target
- the lang specific extension can be added with a normal `PackageReference` (like f# does), and the auto included language target can include `Microsoft.Common.targets` because is not already included.
- for c# doesnt change anything, because can continue to have `<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />` at end, and that target include new nuget target before anything.

Using `f#` as example of an external language, the

```xml
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>1.0.0-alpha-20161102-2</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FSharp.NET.Sdk">
      <Version>1.0.0-alpha-20161102-2</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  
  <Import Project="$(MSBuildToolsPath)\Microsoft.DotnetRestore.targets" />
</Project>
```

maybe `Microsoft.DotnetRestore.targets` is not a good name, but that's what does

**Comment by nguerrera** [comment]
@enricosada I have not had much time. Adding @dsplaisted. There is some talk about changing how an SDK package is installed and referenced and how that implies customizable props and targets specified by the SDK. I think that direction has the potential to solve this problem.

With that said, there is already a separate file for the restore targets.  Does <Import Project="$(MBuildExtensionsPath)\NuGet.targets" /> work?

**Comment by rainersigwald** [comment]
I think the big question is how much that NuGet targets file depends on properties that are only set in common.targets, and I think the answer is quite a bit. @rohit21agrawal may have thoughts on this, but I think is out of the office.

**Comment by enricosada** [comment]
@nguerrera @rainersigwald nuget.target alone doesnt work.

- I used https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview3/console
- imported only `<Import Project="$(MBuildExtensionsPath)\NuGet.targets" />` at end (no Common)
- `dotnet restore`, fails because `$(MBuildExtensionsPath)` was empty, so joined path was invalid path
- changed to `<Import Project="$(MSBuildToolsPath)\NuGet.targets" />` , another `dotnet restore`
- fails too, but now i get `target "_SplitProjectReferencesByFileExistence doesnt exists`

    ```
    c:\dotnetcli\dotnet-dev-win-x64.1.0.0-preview3-004056\sdk\1.0.0-preview3-004056\NuGet.targets(538,5): error MSB4057: The target "_SplitProjectReferencesByFileExistence" does not exist in the project. [e:\github\netcorecli-fsc\examples\preview3\console\ExampleConsoleApp.fsproj]
    ```

So yes, depends on some bit elsewhere 😄 .

@nguerrera @rainersigwald to try you can also use `https://github.com/dotnet/netcorecli-fsc/tree/master/examples/preview3/console` as example if you want. The downloaded f# sdk targets are inside the `FSharp.NET.Sdk` package,, so you can mess with local .fsproj and the msbuild targets in nuget cache (a bonus of sdk packages, remove it from cache fix mistakes next restore)


As a note: I think having a clean language extension point help everyone, c#, VB, f#.
In `preview2` the `dotnet-compile-csc`  (for c#) was embedded in sdk, but the extension point was `dotnet-compile-{compilerName}` so worked really well.
That can help also c# if they want to move sdk integration as packageref (has lots of benefits 😄 ), just sayin

**Comment by enricosada** [comment]
@rainersigwald as an update about language extension point. i think current `LanguageTargets` is enough maybe.
If sdk imports will continue works in sequence, it's possibile already to do like dotnet/cli#4922, just improving it by fixing the behaviour at `dotnet restore` step (target restore is not defined if i dont import common)
I populate the `LanguageTargets` property inside a props auto-imported by `FSharp.NET.Sdk` after restore, so will work like c# does without hardcoded and embedded target files like `Microsoft.Csharp.Common.target`

**Comment by enricosada** [comment]
@nguerrera @rainersigwald I think the following can a solution (already used in preview4 for f#)

The language target file is choosen with `LanguageTargets` property. If not set, build/restore fails. That's ok.

In `preview4` i set the current `LanguageTargets` property, using props file inside an sdk added as PackageReference, to inject F# templates (more info https://github.com/dotnet/cli/pull/4922#issue-193554603). 
the preview4 doesnt support remote sdk, are just embedded and simulated, so there an hack to use a packagereference too (ref https://github.com/dotnet/cli/pull/4940#discussion_r91133859 )

The trick is adding the language sdk before the .net sdk, so like `Sdk="FSharp.Sdk;Microsoft.NET.Sdk"`.

Like that it's possibile to valorize the `LanguageTargets` property, and there is no need to multiply sdk for .net/web (so web is just `Sdk="FSharp.Sdk;Web.sdk"`), at least now

Can be a good solution long term?
