### ISSUE TITLE
Mistake in Spanish localization for the CLI

### ISSUE THREAD

**Issue by nataliaschlebinger** [dotnet/sdk#37537]
### The issue
The first time I ran `dotnet new mvc -o <NAME>` on my new  Spanish language Windows laptop, as part of the output, I got this phrase: `Notificar problemas y encontrar el origen en GitHub: https://github.com/dotnet/core`, which looks like it's translating "the source", as "the origin", when it actually means the source code.

### To Reproduce
Freshly install the .NET 8.0 SDK on a Windows 11 Home Single Language installation that uses Spanish as the system language, and run `dotnet new mvc -o MvcMovie`.

**Comment by Forgind** [comment]
I turned this into a bug on our localization team with a proposed translation identical to the current one but with 'origen' replaced by código fuente', which I think is a better translation.

Thanks for bringing this up!

**Comment by nataliaschlebinger** [comment]
No prob, thanks to you!
One thing, I can't find the bug, is it public? Also, should the `untriaged` label be removed, should I close the issue, or maybe I can make a pull request?

**Comment by Forgind** [comment]
It's internal. It's also been closed as fixed now, so hopefully it'll come to us soon.

Localizations _look_ like they're in this repo, but they're actually stored in a database somewhere that I don't have direct access to, and we just get PRs every once in a while that refresh our translations. If we try to change a translation here, it's overwritten with the next loc update, unfortunately. But since they fixed it on their side, it should be fixed properly next time we get loc changes.

Since they closed their bug, we can probably close this one, too.

**Comment by Forgind** [comment]
Looks like it was fixed in https://github.com/dotnet/sdk/pull/37856/files#diff-cc90feed7bc4467978aa4d917233547e93bec980f232c9966aebf67a3c117954R42

**Comment by nataliaschlebinger** [comment]
Ahh, I understand, fantastic that it was fixed! Thank you for your kind response!
