### ISSUE TITLE
Add `--source` for `dotnet tool install` - for specifying the package source url

### ISSUE THREAD

**Issue by 304NotModified** [dotnet/sdk#37716]
`dotnet add package` and `dotnet restore` has the [`--source`](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package#options) option:

> The URI of the NuGet package source to use during the restore operation.

`dotnet tool install` is missing that option. It has the [`--configfile`](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#options) option, but that is more work in the CI/CD (sometimes you don't have a file). Note the `--configfile` option is also available with  `dotnet restore` but not with `dotnet add package`

Please add the `--source` for `dotnet tool install`

**Comment by WeihanLi** [comment]
Since we had already `--add-source` option, would it help? 
Though they do have different semantic meaning

**Comment by JL03-Yue** [comment]
@304NotModified 

`dotnet tool install` has a `--add-source` option that adds an additional NuGet package source to use during installation(referred in this [documentation](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#:~:text=win%2Dx86.-,%2D%2Dadd%2Dsource%20%3CSOURCE%3E,information%2C%20see%20What%20happens%20when%20a%20NuGet%20package%20is%20installed%3F.,-%2D%2Dconfigfile%20%3CFILE%3E)). I wonder if this help with your request? For more information, see [What happens when a NuGet package is installed?](https://learn.microsoft.com/en-us/nuget/concepts/package-installation-process).

**Comment by 304NotModified** [comment]
Thanks!

Im afraid it won't solve my issue. There are multiple feeds configured already and some need authentication. But unfortunately that wont work on our CI. 

So I need a way to only use the non-authenticated feed. For now we do write a config file with powershell (because its a template and we cant force a configfile from our users)

**Comment by hayer** [comment]
I have tried doing this
```
dotnet tool install --tool-path . --add-source 'https://api.nuget.org/v3/index.json' --ignore-failed-sources --version 5.3.6 dotnet-reportgenerator-globaltool
```

But it still fails since the `Nuget.config` has a private feed.. even though `ignore-faileds-sources` is set.
Seems to be related to https://github.com/dotnet/sdk/issues/24140 ?
