### ISSUE TITLE
Unable to install .NET 8 SDK on Alpine following official instructions

### ISSUE THREAD

**Issue by bdovaz** [dotnet/sdk#37790]
### Describe the bug

I try to install the .NET 8 SDK following the official instructions: https://learn.microsoft.com/en-us/dotnet/core/install/linux-alpine#install-net-8

The result is that it does not exist.

https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz

Related: https://github.com/dotnet/docs/issues/38904

### To Reproduce

Run: `apk search dotnet`

You will see that there are no results for dotnet8.

**Comment by bdovaz** [comment]
I see that although it has not been communicated here or in the other issue I mention, the documentation has been changed and now says that this installation method is not available yet.

When will it be available @marcpopMSFT? .NET 8 came out in November and we are in February....

Thanks.

**Comment by marcpopMSFT** [comment]
@rbhanda and @MichaelSimons who may know the answer to that question.

**Comment by MichaelSimons** [comment]
Alpine does not backport newer .NET releases to older versions.  Because of the timing of the .NET 8.0 release and Alpine 3.19 (they were very close to each other), .NET 8.0 was not included in Alpine 3.19.  Expect to see it with 3.20.  It is [available in edge](https://pkgs.alpinelinux.org/packages?name=dotnet8*&branch=edge&repo=&arch=x86_64&maintainer=) today to try out.

**Comment by DrMarkDunne** [comment]
@MichaelSimons did .net 8 make into 3.20?

**Comment by MichaelSimons** [comment]
> @MichaelSimons did .net 8 make into 3.20?

It appears so - https://pkgs.alpinelinux.org/packages?name=dotnet8*&branch=v3.20&repo=&arch=x86_64&maintainer=

**Comment by adegeo** [comment]
This issue could be closed.
