### ISSUE TITLE
UX when specifying a PublishProfile that does not exist.

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#37822]
When specifying a PublishProfile that does not exist, the SDK prints a warning and exits with a success exit code.

```
$ dotnet publish /p:PublishProfile=DefaultContainer
MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  console -> /tmp/console/bin/Release/net8.0/console.dll
/usr/lib64/dotnet/sdk/8.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(204,5): warning NETSDK1198: A publish profile with the name 'DefaultContainer' was not found in the project. Set the PublishProfile property to a valid file name. [/tmp/console/console.csproj]
  console -> /tmp/console/bin/Release/net8.0/publish/
```

Since the publish profile was not found, it's likely that the command isn't publishing the right thing.

Would it make sense to change this to an error?

cc @baronfel

**Comment by baronfel** [comment]
cc @vijayrkn since PublishProfiles are mostly in his remit.

The problem with making this an error is that a solution-level publishprofile becomes impossible to provide. Currently projects that a) aren't publishable, or b) don't support that specific profile will just warn, which is recoverable. I'd rather lean into `/t: PublishContainer` instead, which has clearer 'this project doesn't support this target' semantics.

**Comment by tmds** [comment]
> The problem with making this an error is that a solution-level publishprofile becomes impossible to provide. Currently projects that a) aren't publishable, or b) don't support that specific profile will just warn, which is recoverable

I'm going to close this, as it would be undesirable to change the warning into an error

> I'd rather lean into /t: PublishContainer instead, which has clearer 'this project doesn't support this target' semantics.

That's a good alternative.
