### ISSUE TITLE
'dotnet workload list' CLI command should not download and install workloads without a user permission

### ISSUE THREAD

**Issue by devhls** [dotnet/sdk#38026]
I guess there were problems with workloads after the upgrade to dotnet 8 and in order to fix it I used Redth.Net.Maui.Check utility and updated the visual studio using its installer which can cause that some workloads were missing.

Once I run the command: `dotnet workload list` and get this: 
![image](https://github.com/dotnet/sdk/assets/85612581/24507391-7e62-468f-9658-585299aad1ed)

Actual behavior: 
the command 'dotnet workload list'  downloads and installs all missing workloads.

Expected behavior: 
the command 'dotnet workload list'  provides the list of workloads and marks missing or corrupted and the prompt to the user to fix listed problems with 'Yes\No' options.

**Comment by Forgind** [comment]
Interesting! So this doesn't actually have to do with dotnet workload list—in fact, if you'd run any other dotnet command, you would have gotten the same result. This has to do with our first run experience. If you haven't used dotnet before, we (by default) "ConfigureDotNetForFirstTimeUse", and that includes a WorkloadIntegrityChecker.RunFirstUseCheck. The latter looks at what workloads you have installed and tries to install them again before it starts the operation to make sure everything is in working order for your new version of dotnet.

I'll admit that can be surprising, and you can disable that behavior if you'd like by setting the environment variable DOTNET_SKIP_WORKLOAD_INTEGRITY_CHECK to 1.

This looks like an intentional change (issue https://github.com/dotnet/sdk/issues/31872; PR https://github.com/dotnet/sdk/pull/34322). I can't think of a reason off-hand that someone would want to update .NET and have non-functional workloads; was there a scenario you had in mind in which someone would be likely to reject the workload update we recommended?
