### ISSUE TITLE
binding redirects do not get generated

### ISSUE THREAD

**Issue by krwq** [dotnet/sdk#384]
Project: https://gist.github.com/krwq/32e6b8727408ffb94b15ecc802b7b03b

dotnet build -f net451
Expected binding redirects with Newtonsoft.Json 4.5, none found

**Comment by dsplaisted** [comment]
`NuGet.Protocol.Core.v3.dll` depends on `Newtonsoft.Json` version `6.0.0.0`.  The `PackageReference` in the project file is bringing in a lower version (`4.5.0.0`).  I think automatic binding redirects will only get generated to redirect a reference to a lower version of a DLL to a higher version, not from a higher to a lower version.  If you change the version of the `PackageReference` to `Newtonsoft.Json` to be to version 9.0.1, then the build will generate the binding redirects.

So I think this is working as intended.

**Comment by krwq** [comment]
When I was using the old dotnet-build the lowering binding redirects were happening and that what the test was expecting

**Comment by dsplaisted** [comment]
Our binding policy for new platforms is that references to lower versions of assemblies can be satisfied by higher versions of assemblies- ie you can roll forward to newer versions.  We added the automatic binding redirection for .NET Framework projects to help get this "roll-forward" binding behavior instead of you having to write binding redirects explicitly.

I tested what the behavior is on .NET Core when you try to downgrade a reference.  If you share types from the downgraded assembly at compile-time, you'll get a compile error:

> error CS1705: Assembly 'NetStandardLibrary' with identity 'NetStandardLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' which has a higher version than referenced assembly 'Newtonsoft.Json' with identity 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

If you don't share them at compile-time, you'll get a runtime error when it tries to load the assembly:

> System.IO.FileLoadException: 'Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Since downgrading the assembly version isn't supported on .NET Core, I don't think we should automatically do it when targeting .NET Framework.  If you need to preserve the behavior when migrating projects, then you could have the migration tool add the required binding redirects.  But I doubt that is even necessary, as even if you make the binding work there are likely to be missing APIs or other functionality that makes the lower version incompatible.

**Comment by krwq** [comment]
@dsplaisted - this is true for our framework but anyone except us doesn't necessarily have roll-forward policies

**Comment by dsplaisted** [comment]
> this is true for our framework but anyone except us doesn't necessarily have roll-forward policies

I'm not sure what you're saying.  The desktop .NET Framework is the only one that needs binding redirects.  All other current versions of .NET will allow a reference to roll forward.  The automatic binding redirection helps make it easier to roll forward when targeting .NET Framework.
