### ISSUE TITLE
Can't install maui workload on Mac

### ISSUE THREAD

**Issue by adriansuhov** [dotnet/sdk#38653]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/install
Operating System: macos

Hello! I can't install maui on a Mac. Error message is `Workload installation failed: microsoft.ios.sdk::16.4.7133 is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json"`.
Command run:  `sudo dotnet workload install maui`

System info:
Os version: 13.6.3 (22G436) (x86_64)
dotnet version: 8.0.101
Xcode: 15.2
brew version: 4.2.7

I did post about this a few weeks ago on the developer community, the issue was solved for a few days (I was able to install the workloads) but after a week or so the problem reappeared

**Comment by KieranFoot** [comment]
I'm not sure that making this an MAUI specific issue is the correct course of action as this is more a question of how dependant packages are pushed for any and all workloads. This is an issue facing mane users of .NET as nuget dependencies are not currently pushed in a reverse dependant order, resulting in missing dependencies at install.

Possibly you could look at suggesting a tool to automate pushing packages in the correct order instead of just a `dotnet nuget push *.nupkg` as most, including yourselves at Microsoft currently do.

**Comment by marcpopMSFT** [comment]
Triage: Looks like that pack ended up getting uploaded to nuget.org after this was filed. Not sure how you got an unreleased manifest as patch Tuesday in Feb was on Feb 13th when the pack eventually shipped. We'll keep an eye out for nuget publish ordering issues.
