### ISSUE TITLE
dotnet build copies appsettings.json from referenced project.

### ISSUE THREAD

**Issue by msgorgo** [dotnet/sdk#3871]
Since .NET Core 3.0, the command dotnet build now builds a framework-dependent executable by default.  This has the following side effect, that if for example project A references project B through a project reference, the build command now copies also the appsettings.json (and environment variants of the appsettings.json) from project B into the bin folder of project A which will potentially overwrite the appsettings from project A. If you would have more than one project reference, lets say project A would reference projects B and C, which appsettings.json would end up in the bin folder of project A?

From my point of view, dotnet build **should not copy** the appsettings.json files from the project references. 

[ProblemSample.zip](https://github.com/dotnet/sdk/files/3818973/ProblemSample.zip)

**Comment by peterwurzinger** [comment]
I'll second the content of this issue.

But in my opinion not copying the appsettings.json-files isn't enough. There are also the /Properties/launchsettings.json and the whole /runtimes-folder ending up in the build output of the referencing project. So besides the config files you end up with a load of files that you probably don't need (or maybe even don't want).

**Comment by dsplaisted** [comment]
@sfoslund Can you take a look at this?

Note that I think there are cases when you do want these types of files to flow.  For example some people reference one Exe from another Exe and want them to both end up in the same folder.  So we'll have to figure out what the right behavior is, and maybe add a flag to control this.

**Comment by michha** [comment]
This issue hit us when we migrated from 2.1. We have a test project for testing a MVC project that is referenced. In the test project is an appsettings.json with some configuration settings. After migrating to 3.0 our tests on the build server suddenly used some production settings because on the build server the ASPNETCORE_ENVIRONMENT variable was not set and therefore the appsettings.Production.json copied from the MVC project was used.

How about adding a parameter to the ProjectReference tag that gives the consuming project the control about the copied items?
```
<ItemGroup>
  <ProjectReference Include="..\someMvcProject\someMvcProject.csproj" />
</ItemGroup>
```

No matter how it is solved, the changed behavior concerning project references should probably be mentioned in the [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30) guide as it possibly breaks test projects with web project references.

**Comment by JosephGarrone** [comment]
Would this not be resolved by assigning some form of precedence to files during copying? I would expect in almost all situations that the files in the project being build should overwrite files copied in as dependencies/resources/etc from dependency projects. i.e. A depends on B, therefore all files from B should be copied into output, then all files from A should be copied into output.

**Comment by peterwurzinger** [comment]
Precendence resolves the issue of config files getting overwritten. It doesn't prevent publish artifacts of referenced projects getting copied into the build output though.

**Comment by dsplaisted** [comment]
@peterwurzinger Aren't a lot of the "extra" copied files needed for the app to run, and in that case would be needed by referencing projects?

Right now I'm thinking the best way to fix this is probably to have a file from the referencing project "win" over a file that would be copied to the same location from a referenced project.  Thoughts @nguerrera @rainersigwald?

**Comment by michha** [comment]
How does this fix my usecase with the test project? I have just a single appsettings.json in the test project and still get the appsettings.production from the mvc project copied and executed when running my tests - that meant the tests tried to touch the production database when the builds were executed the first time after migrating to 3.0.
I could prevent it by making lots of dummy json files, but this will still
1. gets some people surprise, because its unexpected, undocumented behavior
1. breaks how the projects (or tests) were running since the beginning of .NET Core

**Comment by peterwurzinger** [comment]
@dsplaisted Absolutely, yes. But it's not deterministic *which* files getting copied, since it's apparently dependent on the combination of the target framework and the SDK.

I just did some experiments referencing an ASP.NET Core 2.2 web app  from a XUnit test project, that targets `netcoreapp2.2` and `netcoreapp3.0`. So when building the test project you can choose between with various valid permutations of target framework and SDK:
* `netcoreapp2.2` built with SDK 2.2(.105)
* `netcoreapp2.2` built with SDK 3.0(.100)
* `netcoreapp3.0` built with SDK 3.0(.100)

Each permutation ended up with a unique set of files in the output folder.

In my opinion just referencing an executable project doesn't express a clear intent of wanting to actually execute it. So the question of which files are needed is quite a subjective one, and, to be honest, I don't feel chosen enough to make a claim on the single irrefutable truth. I see arguments for both strategies, and to me it would be great being able to configure the behavior.

**Comment by seanamosw** [comment]
I just lost at least an hour to this.

I had:
Project A with `script.sh` file copying to output directory 
Project B, which references Project A, also with a `script.sh`

Which script.sh Project B would have in its final output was random, so the behaviour is unexpected and racy.

**Comment by MgSam** [comment]
Am I to assume based on the PR that this is being fixed in .NET 5?

**Comment by sfoslund** [comment]
Yes, this fix should be in .NET 5 preview 5 and later.
