### ISSUE TITLE
C++/CLI projects do not generate .runtimeconfig.json

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/sdk#3889]
When building a C++/CLI library, a .runtimeconfig.json file is not generated. As a result, these libraries cannot be used from native applications or through p/invokes from managed applications.

**Repro:**
VS 2019 16.4 Preview 4
.NET Core 3.1.0-preview2

1. Create a C++/CLI library in Visual Studio
2. Create either a:
    - native application that calls into the library from (1)
    - managed application that uses DllImport to p/invoke into the library from (1)
3. Run the application from (2)
    - Failure on using the library because there is no .runtimeconfig.json present

cc @wli3 @nguerrera

**Comment by wli3** [comment]
Per Nick:

- [ ] Decide if we want to enable generating runtimeconfig by default for C++ library?
- [ ] Fix when asset file missing, generating runtimeconfig also get disabled
- [ ] Fix output $(TargetDir) mismatch in C++ project

**Comment by wli3** [comment]
Lucky ProjectRuntimeConfigFilePath is based on $(TagetDir) https://github.com/dotnet/sdk/blob/be128d0ba81f0971ddbd5bb5a1039dd2c7768edf/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L64

There is mismatch in C++ I believe. Due to the following issue, I can only test in a single library. And the output location is correct there.

However, looks like creating a runtime config is much harder since existing code is highly coupled with asset file. I am not sure a short cut of the following is enough.

```c#
                RuntimeConfig config = new RuntimeConfig();
                config.RuntimeOptions = new RuntimeOptions();

                    config.RuntimeOptions.Framework = new RuntimeConfigFramework();
                    config.RuntimeOptions.Framework.Name = RuntimeFrameworks[0].GetMetadata("FrameworkName");
                    config.RuntimeOptions.Framework.Version = RuntimeFrameworks[0].GetMetadata("Version");
                    config.RuntimeOptions.Tfm = TargetFramework;
                    config.RuntimeOptions.RollForward = RollForward;
```

Also, even today, if a C# console app referencing a C# library with `EnableDynamicLoading=true`, the result output folder will not have the library’s runtimeconfig.json. Is it still useful? @elinor-fung  @olgaark

**Comment by elinor-fung** [comment]
>  C# console app referencing a C# library with `EnableDynamicLoading=true`, the result output folder will not have the library’s runtimeconfig.json. 

The direct reference like that wouldn't need the .runtimeconfig.json (since it wouldn't be using the referenced library as a 'component'). However, I could imagine something like using project references for build order/copying to output (without the direct reference) and expecting everything be copied for use as a separate component. That said, I'm not sure how much doing something like that is supported in general - trying something like that won't work for console apps either, since .runtimeconfig.json and .deps.json don't get copied.
