### ISSUE TITLE
Downgrading transitive PackageReferences

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/sdk#3918]
We have a DLL that contains downgrade instructions, so despite being built in the project containing the latest version, it must inherently be loadable on the oldest version we ever shipped. In order to do so, we used PackageReference Update= to pin reference of dlls when building that version.

Unfortunately this doesn't really work for some reason we don't know. The Update= version force is ignored and the higher version in the dependent dll is used instead. This actually causes the dynamic load to fail whenever we need to update the packages. For some reason, despite the same artifact being present in the dll refrenced by PackageVersion, the dynamic load succeeds there (or we would have noticed the very first time we tried this).

Don't let netstandard2.0 fool you; we are building with the 3.0 toolchain and the executable (omitted from the sample) is linked against netcoreapp3.0. You can check the dependencies of DynamicLoaded.dll with ildasm. It should reference Demo.dll version 1.0.0 but it references Demo.dll version 2.0.0

The real If.dll is not an interface-only dll. It contains quite a bit of code for upgrade and downgrade, and the current version of If.dll used during upgrade can't function with the older version of Demo.dll.

This issue is newly discovered a few days ago, thankfully not by a customer.

[downgradedemo.zip](https://github.com/dotnet/sdk/files/3852941/downgradedemo.zip)

**Comment by rainersigwald** [comment]
Can you point to any docs or issues you used to develop your understanding of what `Update` does in this context? It seems we have something misleading, because it doesn't work the way you expect.

`Update` is an MSBuild language feature that will update items matching the pattern with the specified metadata.
From your example you have

```xml
<PackageReference Update="Demo" Version="1.0.0.0" allowedVersions="[1.0.0.0]" />
```

 It's not applying in this case because your project does not have any Demo items, for example

```xml
<PackageReference Include="Demo" Version="xxx" />
```

`DynamicLoaded.csproj` gets a reference to `Demo` from its `ProjectReference` to `..\If\If.csproj`. NuGet sees that and promotes it to a reference to `Demo` with a matching version in `DynamicLoaded`--but it's not a direct reference, and thus doesn't have an entry in `@(PackageReference)` to update.

I think this is a NuGet feature request; I'll move this issue to the NuGet bug tracker.

**Comment by rainersigwald** [comment]
This issue was moved to NuGet/Home#8833

**Comment by jhudsoncedaron** [comment]
@rainersigwald : https://stackoverflow.com/questions/43860379/how-do-i-replace-a-dependency-of-a-third-party-nuget-package

Also https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NU1605)%26rd%3Dtrue (F1 from NU1605) seems to suggest the Update= line is for fixing these problems.

Note that if I throw an Include= line the build error immediately with NU1605.
