### ISSUE TITLE
Does /p:OutputType=WinExe propagate to dependencies?

### ISSUE THREAD

**Issue by TheBuzzSaw** [dotnet/sdk#3920]
I am attempting to build a project with overridden properties.

    dotnet publish MyProject.csproj -f netcoreapp3.0 -c Release -r win-x86 /p:CopyOutputSymbolsToPublishDirectory=false /p:OutputType=WinExe

However, it results in a build error in a classlib dependency.

    error CS5001: Program does not contain a static 'Main' method suitable for an entry point

I can only assume that the `/p:OutputType=WinExe` is propagating down and overriding their properties too. Is there way to stop that? Can I have that override only apply to the target project?

Oddly enough, if I build without `/p:OutputType=WinExe` and then immediately build _with_ `/p:OutputType=WinExe`, it succeeds. (The dependencies are built and cached, I guess.)

**Comment by rainersigwald** [comment]
Specifying a property at the command line causes it to be set as a [global property](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-properties?view=vs-2019#global-properties); global properties are by default inherited by projects built as `ProjectReference`s (or otherwise using the `MSBuild` task inside MSBuild).

There's no trivial way to disable this but there are some options:

1. Use a different property (maybe `MyProjectOutputType`) that isn't used by other projects and set `OutputType` based on that in `MyProject.csproj`.
1. Tell `MyProject.csproj` to avoid passing `OutputType` metadata to its references by setting the metadata `UndefineProperties="OutputType"` on all `ProjectReferences` it has (probably via an [item definition](https://docs.microsoft.com/en-us/visualstudio/msbuild/item-definitions?view=vs-2019) rather than on every `ProjectReference` XML node)

**Comment by TheBuzzSaw** [comment]
Using a variable ended up being an excellent workaround.
