### ISSUE TITLE
Where is .NET SDK 5.0.416? The latest download is 5.0.408.

### ISSUE THREAD

**Issue by daiplusplus** [dotnet/sdk#39409]
My desktop has the .NET 5 SDK version 5.0.416, which was/is the version specified in my project's `global.json`:

```
{
  "sdk": {
    "version": "5.0.416",
    "rollForward": "latestFeature"
  }
}
```

The `5.0.416` SDK appears in Add/Remove Programs as "_Microsoft .NET SDK 5.0.416 (x64) from Visual Studio_" - the "_from Visual Studio_" suffix is interesting, as none of the other SDKs (except `8.0.102`) have it... but I don't know what it means, exactly.

My `dotnet sdk check` lists:

```
C:\git>dotnet sdk check
.NET SDKs:
Version                        Status
---------------------------------------------------------------------
2.1.818                        .NET 2.1 is out of support.
3.1.426                        .NET 3.1 is out of support.
5.0.201                        .NET 5.0 is out of support.
5.0.214                        .NET 5.0 is out of support.
5.0.416                        .NET 5.0 is out of support.
6.0.419                        Up to date.
7.0.406                        .NET 7.0 is going out of support soon.
8.0.102                        Up to date.
9.0.100-preview.1.24101.2      Up to date.
```

However my build script fails on other machines that only have `5.0.408` installed - my initial response to them was "well, update to 5.0.416" - but it turns out [that `5.0.408` is actually the latest .NET 5 SDK you can download today](https://dotnet.microsoft.com/en-us/download/visual-studio-sdks).

* ...so how did my machine get `5.0.416`?
* Should I be using 416 at all in `global.json` - or should I restrict reference to 408?
* If I should be using 416 as it's more recent, then where/how do I obtain it and how can I make it available on other machines?

**Comment by joeloff** [comment]
The later 5.0.4xx and 5.0.2xx SDKs we special releases that shipped with Visual Studio. They were never released as standalone copies.

5.0 was an STS release. At the time when 5.0 was going out of support, the Visual Studio versions in which the SDKs shipped, needed to support creating/running .NET Core 3.1 (LTS) apps. Since 6.0 was targeting newer versions of VS and because of how SDKs are tied to some features in VS, we could not migrate 6.0 back, nor could we introduce a new 3.1 SDK band. Subsequently we provided Visual Studio with a copy of the last released 5.0 SDKs (basically 5.0.408) that was built to run on top of .NET 6. This way users could continue to work in VS with .NET Core 3.1 projects using the 5.0 SDK.

You should upgrade your Visual Studio to move to an LTSC version of VS like 17.8 that includes the .NET 8.0 SDK. You can still target, build, and run lower versioned applications using the newer 8.0 SDK, though there were some changes around features like publishing in .NET 8
