### ISSUE TITLE
SDK 3.0.101 is not delivered via Visual Studio

### ISSUE THREAD

**Issue by DerAlbertCom** [dotnet/sdk#3951]
A promise of the SDK 3.0 was that a new version of an patch level SDK will uninstall the the previous Version. Great, less hassle keeping the machine cleaner.

So I downloaded the SDK (main download page), installed it and, of course SDK 3.0.100 still present on the machine.
![image](https://user-images.githubusercontent.com/136992/69367812-42e42900-0c99-11ea-9f18-caa18c4c47d1.png)

So there is a Visual Studio Version of the SDK and an "other" Version of the SDK. Or what is happening here? 

And why is Visual Studio (Released 2019/10/20) not updating the SDK (Released 2019/10/19). 

The SDK Update mess is really confusing.

**Comment by nguerrera** [comment]
> So there is a Visual Studio Version of the SDK and an "other" Version of the SDK. Or what is happening here?

VS and the standalone installer "ref count" the same components. The standalone installer will not uninstall something VS installed and VS won't uninstall standalone installs. This is important for some scenarios.

> And why is Visual Studio (Released 2019/10/20) not updating the SDK (Released 2019/10/19).

Generally this would have happened. It's not necessarily coordinated to happen on the same day in the case where the update is not a critical security vulnerability fix. That's the case for this update. Also, logistically, it just so happened that the process for getting into a 16.3 update was going to end up very close to 16.4 release, so we have opted not to push these updates to 16.3 and will advise upgrade to 16.4 to get them.

I am going to close this since it is expected at this time. The timing issue that led to this short window of lag in 16.3.x should not be the general case.
