### ISSUE TITLE
'dotnet test' sometimes causes terminal to stop echoing after completion (ubuntu)

### ISSUE THREAD

**Issue by beevik** [dotnet/sdk#4090]
When running `dotnet test` on ubuntu, the terminal often stops echoing input after the command completes. It's not 100%. Sometimes echoing remains on.  I'm using the xunit testing framework.

Here are the results of typing `stty -a` after the terminal stops echoing:
```text
speed 38400 baud; rows 40; columns 132; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S;
susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig -icanon -iexten -echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```
As you can see, echo is off (`-echo`).

This does not appear to be a bug in xunit, as someone has reported a [similar issue](https://github.com/haf/expecto/issues/327) when using expecto instead.

Ubuntu 18.04.3
.NET Core 3.1
xunit 2.4.1

**Comment by rmunn** [comment]
I'm the one who reported that issue with Expecto. I also have a vague memory of seeing this pop up with other `dotnet foo` commands such as `dotnet build`, but I don't have a solid example since I'm away from my desk for the holidays. Once I get a solid example I'll mention it here.

BTW, for anyone else who experiences this, you can restore your terminal to normal functionality after this issue triggers by typing `stty echo` followed by Enter.

**Comment by beevik** [comment]
An additional data point.  I encountered the same bug running `dotnet test` on MacOS.

**Comment by livarcocc** [comment]
This issue was moved to microsoft/vstest#2282
