### ISSUE TITLE
ResourceManager can't find parent culture resources when built using csproj/msbuild

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#410]
Moving https://github.com/dotnet/cli/issues/4781 on behalf of @ryanbrandenburg

----

## Steps to reproduce
1. Clone [this](https://github.com/ryanbrandenburg/ResourceManagerMsbuild) repo
2. Run the project.

## Expected  behavior
Finds the parent culture of "en" and outputs "key1 en" (this is confirmed to work with ".NET Command Line Tools (1.0.0-preview3-003770)" which still used project.json)

## Actual behavior
Unable to find parent culture, so A MissingManifest exception is thrown.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

**Comment by hishamco** [comment]
@ryanbrandenburg seems the localization fallback into `en` even a default culture is specified. Try to add another cultures and resources for those cultures, all they should give you the expected result except 'en` one

**Comment by nguerrera** [comment]
The issue here is with the default generated `[NeutralResourcesLanguage("en")]`, which tells the resource manager that it can find English resources in the main assembly and does not need to probe for satellites to find English resources.

Workarounds:

1. Rename strings.en.resx to strings.resx and let it build in to the main assembly.
2. Add `<GenerateNeutralResourcesLanguageAttribute>false</GenerateNeutralResourcesLanguageAttribute>`

**Comment by nguerrera** [comment]
@davkean Thoughts here? My inclination is to stop defaulting $(NeutralLangauge) to 'en'. Leave it empty and no attribute will be generated, and the user can set it as needed if it's actually appropriate.

**Comment by hishamco** [comment]
@nguerrera I already blogged about `NeutralResourcesLanguageAttribute` issue few weeks ago, it doesn't respect the localization. http://www.hishambinateya.com/neutralresourceslanguageattribute-doesn't-respect-localization-in-asp.net-core

**Comment by davkean** [comment]
@hishamco I read your blog post, and I don't understand the issue. If you could fire up a repo for me that demonstrates the issue, that would be great.

@nguerrera Trying to understand the issue - is it that the default is unexpected?

**Comment by davkean** [comment]
What I mean, is that If you'd set the appropriate property to the same value in project.json, you'd see the same behavior.

**Comment by nguerrera** [comment]
The default is unexpected as exemplified by this case. The user has all of their strings in satellite assemblies, there are no neutral resources in the main assembly, but we go ahead and slap NeutralResourcesLanguageAttribute("en"), which is wrong in this case. It would also be wrong if there were neutral resources in the main assembly, but they weren't English.

My recommendation is that we require the user to specify NeutralLanguage if they want/need the attribute, but we don't default to en. I'm prepping that change now.

**Comment by davkean** [comment]
It means that you pay for an extra probe for English.

**Comment by nguerrera** [comment]
I understand that. But you can eliminate the probe by saying `<NeutralLanguage>en</NeutralLanguage>`.

**Comment by davkean** [comment]
Ha, the same can be said about MissingManifestException. :)

**Comment by nguerrera** [comment]
I favor correct in all cases as default.

We're guessing here by defaulting to en.

If we guess right -> performance boost.
If we guess wrong -> MissingManifestException or displaying text in wrong language.

**Comment by hishamco** [comment]
@davkean in nutshell setting the `NeutralResourcesLanguageAttribute` lets the Localization APIs doesn't figure out the proper resx file, so if you have
```csharp
[assembly:NeutralResourcesLanguage("fr-FR")]
```
The localization APIs will look for `Resource.resx` instead of 'Resource.fr-FR.resx`, so setting this attribute in the assembly level or in `project.json` is confusing.

**Comment by davkean** [comment]
@hishamco That's entirely by-design and behaving exactly how it's supposed to. By applying NeutralResourceLanguage, your telling ResourceManager, my neutral resources live in my main assembly (hence "Resource.resx") and avoid the extra attempts assembly loads. ie It's basically a performance boost for cases where you store a particular language's resources in the main assembly.

**Comment by hishamco** [comment]
I see, but the main issue is when you set it in the `project.json`, I see many of folks did that before, they don't know that setting the language in the `project.json` will set this attribute behind the scene and break the expected behavior. Hope we mention in that in the docs to avoid such issue accidentally
