### ISSUE TITLE
[NETSDKE2E][intermittent]7.0.120 SDK installation failed with error "A DLL required for this install to complete could not be run..." after allowEnforceSignCI policy enabled.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#41078]
1.Install VS 17.4.19 on windows11-x64
2.Copy the CIP file to a folder
[allowEnforceSignCI.zip](https://github.com/dotnet/sdk/files/15399980/allowEnforceSignCI.zip)
3.Open an admin prompt and run citool --update-policy allowEnforceSignCI.cip in above folder
3.Restart the machine
4.Try to run the 7.0.120 SDK, check If it was properly signed the install should succeed.

Expected Result:
SDK can be installed without any issue

Actual Result:
installation failed with below error
![image](https://github.com/dotnet/sdk/assets/65637796/37bb8d9d-66a3-4be3-9bad-a04b4f5fc7af)
![image](https://github.com/dotnet/sdk/assets/65637796/5334f0ed-ec4b-45f4-8a8f-da418ad3efe8)

[Microsoft_.NET_SDK_7.0.120_(x64)_20240522070357.log](https://github.com/dotnet/sdk/files/15400094/Microsoft_.NET_SDK_7.0.120_.x64._20240522070357.log)

**Comment by vdanche** [comment]
It's intermittent issue. this issue not repro on another VM with the same build.

**Comment by joeloff** [comment]
This is expected and by design.

The .NET host MSI that comes from the runtime always upgrades. The host MSI that VS installed would get removed when the 7.0.20 host MSI is executed. The host MSI has a custom action that always runs and the older MSI's custom action isn't properly signed, so it triggers the CI failure when it's removed.

```
[04E8:046C][2024-05-22T07:04:09]i301: Applying execute package: dotnet_host_7.0.20_win_x64.msi, action: Install, path: C:\ProgramData\Package Cache\{EE5EB03B-D65C-4991-848E-2C6E024326DB}v56.80.15184\dotnet-host-7.0.20-win-x64.msi, arguments: ' ARPSYSTEMCOMPONENT="1" DOTNETHOME="C:\Program Files\dotnet\"'
[04E8:046C][2024-05-22T07:07:06]e000: Error 0x80070643: Failed to install MSI package.
[04E8:046C][2024-05-22T07:07:06]e000: Error 0x80070643: Failed to execute MSI package.
[2900:1408][2024-05-22T07:07:06]e000: Error 0x80070643: Failed to configure per-machine MSI package.
[2900:1408][2024-05-22T07:07:06]w348: Application requested retry of package: dotnet_host_7.0.20_win_x64.msi, encountered error: 0x80070643. Retrying..
```

You need to look at the MSI log to see the actual error: Microsoft_.NET_SDK_7.0.120_(x64)_20240522070357_001_dotnet_hostfxr_7.0.20_win_x64.msi.log 

If the host was already updated, installing 7.0.20 may not modify the host. For example, if you installed 6.0.5, then installed 8.0.4 and then 7.0.20, the 8.0.4 install would have updated the host. When 7.0.20 is installed, it will detect that a newer host is present and decide to skip that package.

I'd need to see the machine and all the logs, but I can repro this using mix of older unsigned runtimes, enabling CI and running newer installs that trigger upgrades.

The detection in your case reports the host as absent and is planned for install. I'd need to see the machine to give a more conclusive answer
