### ISSUE TITLE
`slnx` wildcard support

### ISSUE THREAD

**Issue by adambajguz** [dotnet/sdk#41465]
Hi,
I'm not sure where to write about this, hopefully it's the right place.

Do you plan to add wildcard support in the new `slnx` file format?

### Is your feature request related to a problem? Please describe.
Yes, maintaing a solution file with a lot of projects (e.g. 200) will be less painful.

### Describe the solution you'd like
It will be nice if `slnx` supports wildcards for paths. Example:

``` xml
<Solution>
  <Folder Name="/Modules/Payments">
    <Project Path="Modules\Payments\*\*.csproj" />
  </Folder>
  <Folder Name="/Application/">
    <Project Path="**\*.csproj" />
  </Folder>
</Solution>
```

**Comment by baronfel** [comment]
Hi @adambajguz - the .NET SDK doesn't control the new Visual Studio slnx file format, can you please raise this feedback at https://developercommunity.visualstudio.com? The VS team will see it and be able to respond if you do.

**Comment by thomaslevesque** [comment]
A few questions:
- Is there a home for the new slnx format on Github? Because let's be honest, searching for anything on developercommunity.visualstudio.com is a terrible experience. Is there a Github issue I can track for the wildcard feature?
- I can't seem to find any documentation of the format anywhere. Does this documentation exist?
- Now that the .NET CLI supports the slnx format, doesn't it make it part of the .NET SDK?

**Comment by baronfel** [comment]
Hey, some quick answers:

* The place you should go for issue/feature requests for the SLN/SLNX file formats is now https://github.com/microsoft/vs-solutionpersistence.
* There is no public documentation on the format that I know of at this time - though the parser is OSS and available at ^that repo. For a public spec I would suggest raising an issue there.
* The parser is included in the .NET SDK, but we only use it to read and do our own logic on the SLNX file - we in no way control the format. Because of how the SDK ships, all of our dependencies must also be OSS, and so this library is now available to help us parse SLNX and solution files. That's all!

**Comment by thomaslevesque** [comment]
@baronfel thanks for the quick reply. I'll check it out. Since it's now out of preview, I hope an official documentation will be published soon!

**Comment by Rekkonnect** [comment]
Just linking that this issue is open in the proper repo that was mentioned: https://github.com/microsoft/vs-solutionpersistence/issues/61

Since I could not find any other links from this thread
