### ISSUE TITLE
dotnet build causes InitialTargets to run multiple times

### ISSUE THREAD

**Issue by alanwest** [dotnet/sdk#4148]
Steps to reproduce:

1. Run
```
mkdir test && cd test && dotnet new classlib
```

2. Replace contents of `test.csproj` with:
```xml
<Project Sdk="Microsoft.NET.Sdk" InitialTargets="HelloWorld">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <Target Name="HelloWorld">
    <Message Importance="high" Text="Hello World" />
  </Target>

</Project>
```

3. Run
```
dotnet build
```

Output:
```
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Hello World
  Hello World
  Restore completed in 25.71 ms for /Users/awest/test/test.csproj.
  Hello World
  test -> /Users/awest/test/bin/Debug/netstandard2.0/test.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.87
```

I would expect "Hello World" to be printed once.

---

dotnet --info
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.802 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by dasMulli** [comment]
`dotnet build` triggers 2 (sort of) independent MSBuild runs: one that runs the `Restore` target and one that runs the `Build` or `Rebuild` target (these cannot be run in the same MSBuild run since the files have to be re-evaluated b/c of NuGet generated MSBuild files that may contribute to evaluation). 
`InitialTargets` are run on every MSbuild run, regardless of what target was requested by the command line / wrapping program, so that behavior is intended. So `dotnet restore` will run, `dotnet build --no-restore`  will only run it once, but also `dotnet publish --no-restore --no-build` will run it.

If you only want to contribute logic to the "acutal" build process - as in "when the Build target is run" - i suggest hooking the target into that process with `<Target Name="Foo" BeforeTargets="BeforeBuild">`.

Also note that if you would use multi-targeting by specifying multiple target frameworks (`<TargetFrameworks>netstandard1.6;netstandard2.0;...`), the target would be run even more times: On restore, On the "outer build" and then for each target framework because the "Build" target will dispatch additional MSBuild "inner build" runs for each target framework.

**Comment by alanwest** [comment]
Thank you very much for your detailed reply!

**Comment by jeremyjee** [comment]
In case you are having this issue because of needing to have some external build process run e.g. npx webpack, working consistently even from fully clean and without interfering with incremental builds, and you are now have this issue because you wanted to force it to run via use of InitialTargets, well the droid you are looking for is <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>. You can now go back to using BeforeTargets="BeforeBuild" so that e.g. npx webpack isn't being invoked when running targets other than build e.g. restore.
