### ISSUE TITLE
[NETSDKE2E]With NET9 p7 zip installed, the prompt message "update are available for the..." should not be displayed after installing wasm-tools.

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#42170]
**Build info:**
 .net9.0.100-preview.7.24365.17(runtime-9.0.0-preview.7.24365.1) sdk

**Repro steps:**
1.Download the NET9 preview 7 SDK zip package.
2.Modify environment variables
3.Install workload with commands.
`dotnet workload install wasm-tools`
4. Check the workload list
`dotnet workload list`

**Expected:**
The workload list should display normally and will not prompt for updates.

**Actual Result:**
After installing wasm-tools, a prompt message "Update available for..." is displayed.
![image](https://github.com/user-attachments/assets/29493fd2-4ffd-4930-81c5-2eedeb0ecf69)

**dotnet --info**
![image](https://github.com/user-attachments/assets/1ef50631-86b1-4c5a-aacd-0e643d171d35)

**Comment by vdanche** [comment]
This issue also happens for maui workload
repro steps:
dotnet workload install maui
dotnet workload list
![image](https://github.com/user-attachments/assets/f64476df-e290-4de8-9dc6-86817de117c5)
dotnet workload update, the manifest version still not change.
note:
This issue should be caused by incorrect manifest version, the manifest version(preview.7) as below on yesterday's build:
![image](https://github.com/user-attachments/assets/fa8bad97-f7ab-44a1-8d8f-2e164f819060)

**Comment by v-ainigao** [comment]
This issue does not repro with net9preview7.exe installed.

**Comment by marcpopMSFT** [comment]
So we think there are available updates even after installing new workloads and it only repros in the file-based install? I wonder if one of our recent refactors lead to this.

**Comment by v-ainigao** [comment]
This issue has been fixed on latest .net9.0.100-preview.7.24379.15sdk.
![image](https://github.com/user-attachments/assets/b06656a6-d457-415f-977c-b970bc9fb8b0)
![image](https://github.com/user-attachments/assets/46f6d070-d137-4c7b-8b11-bc322e52ced3)
