### ISSUE TITLE
Implicit restore in `pack` and `publish` should not restore projects with IsPackable=false and IsPublishable=false

### ISSUE THREAD

**Issue by alrz** [dotnet/sdk#42476]
### Describe the bug

Implicit restore in `pack` and `publish` should not restore projects with IsPackable=false and IsPublishable=false

### To Reproduce

1. Run dotnet pack or dotnet publish
1. Observe that unpackable and unpublishable projects are being restored.

**Comment by yugabe** [comment]
Yes, this! This makes debugging/testing NuGet packages even more painful than they should be. I have to execute `dotnet pack` on the solution first so that the packable projects are packed. Then, the test projects (which are `IsPackable=false`) are set to pick up the packed NuGet package from the `artifacts/package` directory set in `AdditionalRestoreSources`. However, in CI/CD, the artifacts folder doesn't exist yet and breaks the build. Even if the folder did exist, the packages couldn't be located yet.

**Comment by marcpopMSFT** [comment]
Triage: The implicit restore during pack/publish are trying to restore the full transitive graph as you may need them for the build even if they are not packable or publishable. We don't currently have a good method of identifying which projects you don't want to restore (independent of pack/publish) so this is really not possible with the current design.
