### ISSUE TITLE
[NETSDKE2E][Workload Sets] Running `dotnet workload restore` should install the workload set when using global.json

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/sdk#42582]
### Describe the bug
Running dotnet workload restore` should install the workload set when using global.json

### To Reproduce
1. Install .NET 8.0.400 SDK
2. Install workload within manifest mode. eg. aspire workload
![image](https://github.com/user-attachments/assets/d163673c-b305-42e0-a644-7937323761a2)

4. New global.json and add workloadverison
`     dotnet new global.json`
```
    {
      "sdk": {
        "version": "8.0.400",
        "workloadVersion": "8.0.400"
      }
    }
```
5. Try to run` dotnet workload restore` to install the workload set.

### Expected Result
Run `dotnet workload restore` should install the workload set eg. 'dotnet workload list'
![image](https://github.com/user-attachments/assets/914046e8-e3dc-4f1b-8b85-2d7fb5f7f04f)

### Actual Result
Unhandled exception:
![image](https://github.com/user-attachments/assets/903a3fb5-65e5-4b1e-87e8-cf69b63fdc4d)

**Comment by Forgind** [comment]
Thanks for the bug! This is an interesting chicken-and-egg type problem in that the workload restore command creates and executes a WorkloadInstallCommand that would install the correct workload set, but before it has a chance to do that, we need to know which workloads to install, so we create a new ProjectInstance and execute a special target that hunts for any workloads we might need, but as part of that, it creates a workload resolver and searches for the manifests it needs, which triggered this error. In other words, we need to run Install before we'll have the right workload set, but we can't run Install until we know which workloads to install. We can't figure out the workloads to install without creating a project, and to do that, we have to already have the workload set installed.

I should be able to make a fix to this soon 🙂

**Comment by vdanche** [comment]
@Forgind checked on 9.0.100-rtm.24514.22 
workload can be updated via dotnet workload restore when using globaljson even though there is no project. but there is an error message. is it expected?
![Image](https://github.com/user-attachments/assets/14873833-f3fc-4fa6-aa3b-311a064fefc3)

**Comment by Forgind** [comment]
@vdanche, I think that's right. The global.json can tell you the version (of the workload set and hence all workloads) that we should use, but we still need to know which workloads the user should have. We can't just use what the user currently has because they might not have the set of workloads they need installed yet. So we do need a project for restore to work properly.

We do _not_ need a project for update to work properly. The way restore now works is that it updates then looks for projects. I do think it would be good to have that error message before the update, so perhaps we should change the ordering of that to look for projects, then update, then install the updates. All we would have to do to implement that would be switching the order of these two lines:
https://github.com/dotnet/sdk/blob/eb416236bb8769bfe8b01df39a3c36d9b3c61bb4/src/Cli/dotnet/commands/dotnet-workload/restore/WorkloadRestoreCommand.cs#L54-L56

I'd be in favor of making that change. I think the error with the workload set not being installed came from running the target, not from discovering projects, but it's been a bit since I've thought about it; is that correct @dsplaisted? If so, then switching those two lines should be safe.

**Comment by dsplaisted** [comment]
It looks like technically we could switch those two lines.  I'm not really sure what the best user experience would be.
