### ISSUE TITLE
-bl is not working with dotnet run

### ISSUE THREAD

**Issue by mariam-abdulla** [dotnet/sdk#43310]
### Describe the bug
In command line, when we run
` dotnet run -bl --project .\ConsoleApp\ConsoleApp.csproj`

it returns: Unknown option '--bl' and doesn't succeed.

![image](https://github.com/user-attachments/assets/7f4a68b0-882d-4e00-8a90-da7509f74a59)

.NET SDK:
 Version:           9.0.100-dev
 Commit:            a7cc732588
 Workload version:  9.0.100-manifests.e3b0c442
 MSBuild version:   17.10.0-preview-24127-03+6f44380e4

**Comment by baronfel** [comment]
After some digging by @mariam-abdulla this is because the `-bl` argument isn't recognized by the parser and so it's being passed as 'restoreargs' - instead it's being forwarded to the application directly. The most straightforward way to handle this is to create a new Option for the bl flag so that everything Just Works ™️as we expect it to.

**Comment by baronfel** [comment]
Closing as we've merged a fix for this case.
