### ISSUE TITLE
Use simple names for SDK specifiers

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/sdk#436]
Related to #415 and Microsoft/MSBuild#1392

In the interest of having clean project files, we should consider making the names used to specify which SDK is used as simple as possible.  I'd suggest the following:

**.NET SDK**
```xml
<Project Sdk=".NET">
  ...
</Project>
```

**Web SDK**
```xml
<Project Sdk="ASP.NET">
  ...
</Project>
```

For the next preview, this is simply a matter of updating the templates and laying out the files in the `MSBuildSDKsPath` under the appropriate folder names.

When we have an acquisition story for SDKs, it will probably involve downloading them as NuGet packages.  We wouldn't want to publish our Sdks as NuGet packages with the names `.NET` and `ASP.NET`.  One way to solve this would be to automatically prepend something like `MSBuildSDK` to the name specified in the `Sdk` attribute (and to add a period if the `Sdk` attribute value didn't start with one).  Thus, the NuGet package names would be `MSBuildSDK.NET` and `MSBuildSDK.ASP.NET`.  We could also consider replacing a `#` with `Sharp` so that, for example, `Sdk="F#"` would map to an Sdk NuGet package with an ID of `MSBuildSDK.FSharp`.

@srivatsn @AndyGerlicher @piotrpMSFT @yishaigalatzer

**Comment by davidfowl** [comment]
I'd like to see how multiple SDKs compose before we try to "fix" the names. Right now that isn't very clear to me.

**Comment by dsplaisted** [comment]
@davidfowl What are your concerns?  Are you talking about when one SDK has a dependency on another, or when a project file specifies more than one SDK?

**Comment by davidfowl** [comment]
> @davidfowl What are your concerns? 

I'm generally worried about having to reinvent semantics where they already work and exist today. E.g. 
- dependency conflict resolution
- dependency version unification (if any)
- asset resolution
- (insert thing nuget solves here)...

I also think that "SDK" is just another word for "development dependency" or most recently "build time" dependencies with the added feature that it can be "pre-installed". I think we're glossing over acquisition but we'll immediately hit it, as soon as we need to ship something outside of the set of pre-installed things that come with the .NET SDK. 

> Are you talking about when one SDK has a dependency on another, or when a project file specifies more than one SDK?

- SDKs depending on other SDKs
- SDKs that want to bring in packages 
- packages that would like to bring in SDKs

BTW I'm using SDK to mean, props and targets, because that's all it really is.

**Comment by cdmihai** [comment]
> I also think that "SDK" is just another word for "development dependency" or most recently "build time" 

I'd be in favor for separating the population of packages into 2:
- build augmentor packages: packages that extend the meaning of what it means to build a project. At the low level you'd have core SDKs, that bring in the language and general flavor of the project. These are the things that ship with the CLI / VS (e.g. a UWP, F#, .net core application :) ). At the higher level you have cute tools that print your dependency graph, test executors, linters, fancy cloud deployment things, etc
MSBuild understands the layout and contents of these packages, and knows how to integrate a build augmentor's assets (props, targets, tasks) in the build.
- runtime packages: packages that provide extra code (usually binary) that the runtime application that is being built depends on. MSbuild does not understand the contents of these packages. The application runtime (CLR, CoreCLR, Mono) knows how to find and load these dependencies. The low level build augmentors know how to unpack them such that the runtime for the specific project flavor (Full Framework dependency resolution / layout vs .net core dependency resolution / layout) can find and load them. Runtime packages usually consist of binary code packaged in that language's de facto binary package format (dlls, jars, etc)

The separation between these two package types could be made via the new [package type qualifier](https://docs.nuget.org/ndocs/create-packages/creating-a-package#setting-a-package-type) that nuget now supports. And the types are exclusive: a package either augments the build, either adds a runtime dependency.

This means that current packages that both augment the build and bring in runtime dependencies will have to be split up. Junit for example, which both provide a runtime package (test specific types and utilities) and a build augmentor package (that drops in a test executor wrapped task, targets, VS test discoverer, etc). This kinda makes sense, since there could be third party providers that want to provide their own, fancier test executors but reuse the Junit types.

Backwards compatibility wise, it's going to be interesting on what to do with the current population of hybrid population: suddenly break them, have nuget issue errors (tool and / or hosting sites), etc

**Comment by cdmihai** [comment]
> SDKs that want to bring in packages

If SDKs can bring in tasks, it means that they can bring in runtime dependencies for those tasks. This means that the SDK graph needs to be separate from the runtime graph :)
There is absolutely no connection between the fact that my fancy build linter needs Newtonsoft/3.2 and my runtime app needs Newtonsoft/9.9. The tasks and the runtime app execute under different VM instances either way.

**Comment by cdmihai** [comment]
Caveat: the SDK dependency graph needs to have an extra rule saying "MSbuild's dependencies always win". This is because tasks are loaded into MSBuild's runtime and share its dependencies. Since MSbuild runs first, it picks the dlls that get loaded.

**Comment by davidfowl** [comment]
> At the low level you'd have core SDKs, that bring in the language and general flavor of the project. These are the things that ship with the CLI / VS (e.g. a UWP, F#, .net core application :) ). At the higher level you have cute tools that print your dependency graph, test executors, linters, fancy cloud deployment things, etc. MSBuild understands the layout and contents of these packages, and knows how to integrate a build augmentor's assets (props, targets, tasks) into the build.

I'd like to understand the rules of separating these things. Is the Web SDK an SDK or a nuget package? What's the breaking point that turns your "tool" into a full blown SDK? Isn't an SDK just a suite of these tools strung together? At that point, am I am MSI vs being a nuget package? Right now F# isn't baked into the CLI SDK, neither is the CoreRT toolchain. Are those SDKs or are they build time dependencies?

> The separation between these two package types could be made via the new package type qualifier that nuget now supports. And the types are exclusive: a package either augments the build, either adds a runtime dependency. This hard requirement avoids us doing multiple phase builds to stabilize the build logic closure.

@cdmihai YES, exactly! 

> This means that current packages that both augment the build and bring in runtime dependencies will have to be split up. Junit for example, which both provide a runtime package (test specific types and utilities) and a build augmentor package (that drops in a test executor wrapped task, targets, VS test discoverer, etc). This kinda makes sense, since there could be third party providers that want to provide their own, fancier test executors but reuse the Junit types.

That's fine but it should be possible to define a meta package that brings in both. In this world, edges need to be labeled as build time or not. I also think we need to go further here. I have a diagram I want to post.

**Comment by cdmihai** [comment]
> I'd like to understand the rules of separating these things. Is the Web SDK an SDK or a nuget package? What's the breaking point that turns your "tool" into a full blown SDK? Isn't an SDK just a suite of these tools strung together? At that point, am I am MSI vs being a nuget package? Right now F# isn't baked into the CLI SDK, neither is the CoreRT toolchain. Are those SDKs or are they build time dependencies?

An SDK is a nuget package of types `Build Augmentor` and `MSBuild`. It brings in assets that MSBuild uses to extend the build logic closure. The Web SDK would specify the logic of what it means to build a web project. And nothing more. Of course, the Web SDK employs a set of tools to accomplish its job.

This leads the conversation into Tool packages, which I omitted on purpose up until now, since they feel like an orthogonal issue. And therefore maybe a different nuget package type. Tool packages define a `ready to execute tool`, with all its dependencies. The tool's VM type and instance is separate from MSBuild's type and instance (SDKs that bring in tasks run inside the same VM type and instance as MSBuild). They essentially represent a process. This means that each tool package would have its own separate dependency graph,

The compiler in this sense would be a tool package, that when restored, it's ready to have its executable called. SDKs would then have references to multiple tool packages. An SDK could choose to invoke a compiler programmatically, and if so, it would depend on the runtime package of the compiler and not the tool package of the compiler.

> it should be possible to define a meta package that brings in both

I wouldn't put together meta packages that define both the runtime application's dependencies and the extra build augmentation logic. This opens up a lot of issues that are quite hard to resolve:
- multi phase build. The build logic closure needs multiple iterations to stabilize, since each new build instruction might change the logic around it. In programming languages analogy, it's the equivalent of having an instruction that changes the AST around it. Meta packages don't completely resolve this problem, but make it much worse.
- MSBuild's evaluation is done in steps, and `PackageReference` items are executed after the build logic closure has been stitched together. That's why we went for the separate attribute on the `Project` element, to make SDKs visible in the build logic closure construction phase.

**Comment by gulshan** [comment]
In my opinion,
- Build time dependencies SDKs or tools can use same nuget mechanism, but use a separate myget-like repository maintained by MSBuild.
- The difference between SDKs and tools need not to be explicit.
- All build time dependencies should be installed globally.
- Dotnet cli tools can merge with MSBuild tools in future, given similar API support in MSBuild.

We should take a look at other successful ecosystems and build frameworks for ideas and inspiration. In particular, I have some reservation for gradle.

**Comment by davidfowl** [comment]
> Build time dependencies SDKs or tools can use same nuget mechanism, but use a separate myget-like repository maintained by MSBuild.

Where tools are doesn't matter. What matters is how they manifest themselves in the project file and what the system that pulls them down does. I think using nuget would be fine if we had a way to:
- Use pre-installed nuget packages
- Restore a separate graph per logical exe (one for msbuild, one per tool, one for csc loading analyzers)

> All build time dependencies should be installed globally.

Nah, it should be possible to acquire it without installing it globally.

> Dotnet cli tools can merge with MSBuild tools in future, given similar API support in MSBuild.

That doesn't make any sense. Tools are separate from msbuild targets/tasks/sdks. SDK is not an exe launcher.

**Comment by cdmihai** [comment]
> >All build time dependencies should be installed globally.

> Nah, it should be possible to acquire it without installing it globally.

It would be nice to have a "per workspace" way of setting up things (an msbuild workspace would be similar to a VS solution). When users have workspaces with more than a few projects, it would be nice to set versions in one place rather than doing a recursive search and replace and hope that unification works right.

Doubling back to the original issue, maybe shorthand SDK aliases would work well with such a "per workspace" build config file. The build config file defines the alias (`core` => `Microsoft.Net.Core/1.2.3.4`), and the projects use the aliases. Maybe the build config file could also alis groups of SDKs under a single name, like:

```
`core` => `Microsoft.Net.Core/1.2.3.4`
`web` => `Microsoft.Asp.Net/2.3.4.5`
`Android` =>`Foo.Mobile.Android/3.4.5.6`
`MyProjectFlavor` => `core;web;Android`
```

Then, the actual projects could use `<Project SDK="MyProjectFlavor">`
