### ISSUE TITLE
Question: Is the 9.0.100 daily build the final SDK?

### ISSUE THREAD

**Issue by jnm2** [dotnet/sdk#44512]
The 9.0.1xx download link in <https://github.com/dotnet/sdk/blob/main/documentation/package-table.md> downloads the SDK at version 9.0.100. This is not a prerelease version. Does that mean this is the final 9.0.100, or is it really a prerelease?

The 9.0.2xx link lists a prerelease version.

**Comment by baronfel** [comment]
It's not really the final release version. Starting with the RCs we take producing the product to internal pipelines, so while these links still work they don't represent artifacts that will be published. I would strongly recommend not installing them because it will make installation management difficult.
