### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by nathanboktae** [dotnet/sdk#4600]
I would love to install .NET via homebrew. Any plans to maintain a brew formula? I think the majority of Mac developers work this way.

**Comment by asbjornu** [comment]
I would just like to add my vote to getting a `dotnet` formula into Homebrew "proper". As @cglong writes in https://github.com/dotnet/sdk/issues/4600#issuecomment-378855545:

> The primary difference between a Caskroom version of .NET Core and a Homebrew version is that the latter is built from source, which would allow other open-source packages that depend on Core to also be eligible for Homebrew. As it is now, any apps written that take a dependency on Core (e.g. PowerShell) can never be in Homebrew proper :(

This is precisely the situation we're in with [GitVersion](https://github.com/GitTools/GitVersion). We already have a `gitversion` formula, but it is currently dependent on Mono, which keeps us from updating it, since such an update would require us to declare a dependency on `dotnet` which does not exist. We do not want to move our formula to a Cask.

So an important part of solving GitTools/GitVersion#2374 for us would be to solve this issue first by getting a source-built `dotnet` formula into Homebrew. Effort was made in Homebrew/homebrew-core#3691, but .NET Core was at such an early stage back then that it eventually was rejected.

We should be in a much better state with .NET Core now, though I'm having tremendous problems getting .NET Core to build on macOS. [I have tried to build on](https://github.com/asbjornu/homebrew-core/blob/feature/dotnet/Formula/dotnet.rb) @haf's work in Homebrew/homebrew-core#3691, but running `build.sh` just yields NuGet errors for a [private `darc-int-dotnet-core-setup` feed](https://pkgs.dev.azure.com/dnceng/_packaging/darc-int-dotnet-core-setup-3acd9b0c/nuget/v3/index.json) which seems to be required for whatever mysterious reason. Documentation on how to actually build .NET Core from source seems to be mostly non-existent.

Lastly, I'd like to echo what @bsiegel writes in https://github.com/dotnet/sdk/issues/4600#issuecomment-387492022:

> HOWEVER, the above is really tangential to what we're talking about here, which is getting .NET Core into Homebrew. We don't have to solve the version management problem to make that happen. If people need a specific point release of .NET Core in order to build their production-ready apps, they can do that today by following the official installation steps and downloading the appropriate .pkg installer directly from Microsoft. I don't think there's an expectation that people should be able to install a .NET Core package from homebrew and -not- have it upgraded for them.

💯 to this. Homebrew is a simple, low barrier to entry way to install packages. Hard-core .NET developers won't rely on Homebrew to manage their SDK's anymore than hard-core Ruby developers depend on Homebrew (directly) to manage their Ruby versions.

Getting a build-from-source version of .NET Core into Homebrew is not only or primarily about getting .NET Core itself installed on a system. For that, a Cask formula is good enough. The main point is that through the availability of a `dotnet` formula in proper Homebrew, other formulae can declare their dependence on `dotnet` and still be available in proper Homebrew. When other tools depending on .NET Core can be built from source, it's a huge let-down that .NET Core itself can't be. That needs to be fixed so `dotnet` can finally become a proper Homebrew formula once and for all.

**Comment by asbjornu** [comment]
Homebrew/homebrew-core#60929 is merged and `brew install dotnet` now works. 🎉

**Comment by jkone27** [comment]
I had an issue with the formula dotnet-sdk (not sure who is the mantainer)

https://github.com/dotnet/sdk/issues/28947. --> reported as last in the closed issue.

the issue specifically is the formula using a preview .NET version instead of a stable one, NET 7.0.100 instead of NET 7.0.0 and this causes manifest issues on top of other installations...
