### ISSUE TITLE
Discussion: How to help users with colliding Environment Variables?

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#481]
The manufacturer of my PC, HP, adds a `Platform` Environment Variable as part of configuration for their in-box support software. The value of this variable, `BWS`, in my environment overrides the `Platform` property in the SDK and causes my builds to fail. 

What's the right fix here? I know SDK is doing the right thin [listening to what's configured in the environment] but as an end-user it was pretty frustrating to track this down and now the fix is not clear.

How should we be approaching this class of problem? Is there a fix to make in SDK? In CLI?

**Comment by rainersigwald** [comment]
We've struggled with this exact variable in MSBuild and haven't been able to come up with a better solution than "do nothing and let the user struggle" which is definitely not something I'm proud of!

We dismissed:
* Changing the variable name internally (it's a good name and one that users already expect).
* Erroring or warning when not set (but how do we distinguish between intentional and not?).

I don't think we thought about adding an explicit check for `BWS` on that variable, but that would only solve this one hyper-specific problem and would involve building a scary amount of Windows OEM default-software-install knowledge into an awkward layer of the software stack.

**Comment by piotrpMSFT** [comment]
@rainersigwald is it possible to determine the list of properties that were set via env vars within the context of MSBuild? Can we send a message to the user that says "These properties are overridden by the environment"?

**Comment by rainersigwald** [comment]
@piotrpMSFT we do log "Environment at start of build": https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeBuildEngine/Logging/BaseConsoleLogger.cs#L619-L641

if opted in (either because you're at Diagnostic verbosity or explicitly opted in for this thing).

You could do similar with a logger listening for `BuildStartedEventArgs`, which has a `BuildEnvironment` field.
