### ISSUE TITLE
P2P refs choose first tfm in multi-targting reference, not closest one

### ISSUE THREAD

**Issue by onovotny** [dotnet/sdk#535]
In my solution, I have a multi-targeting project creating the following outputs: `netstandard1.2;netstandard1.3;net45;win81;wpa81;MonoAndroid70;Xamarin.iOS10`

When I do a P2P reference from an iOS app, a NET 4.5 unit test project, etc, they all pick `netstandard1.2` as shown on the properties path of the reference:
![ref](https://cloud.githubusercontent.com/assets/1427284/21328651/047d1b2a-c603-11e6-90bf-6fb63aa627dd.png)

You can repro this by loading the following https://github.com/onovotny/microsoft-authentication-library-for-dotnet/commit/d41e237f3fd1f9b6da06064b6d31046b9c19fbd2.

Build src\Microsoft.Identity.Client and then look at the properties of the test project below (and of the other sample projects.

**Comment by nguerrera** [comment]
@onovotny What I am seeing is that build actually selects the correct TFM, (change output level to detailed and see /reference arg to compiler) but the property pane does incorrectly show the path of the first target framework. 

I presume that you have worse symptoms than a bad path in the properties pane by the description of "so unit tests run for now" in your workaround commit. However, when I make a unit test from the net45 app that asserts that a method which returns the TFM does what I expect, it works fine. Do you have a (hopefully simple) repro for this causing unit tests to fail?

One thing I'm now noticing on top of the property pane being incorrect is that IntelliSense is showing me completions based on the surface are of the first TFM and not the one that a real build would use. I presume that has the same root cause as the bad property pane value. 

Based on these obeservations, I think this is better tracked on https://github.com/dotnet/roslyn-project-system. @mavasani, @davkean What do you think?

**Comment by srivatsn** [comment]
This issue was moved to dotnet/roslyn-project-system#1162
