### ISSUE TITLE
Changing the output path causes it's contents to be added to your project 

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#627]
1. File -> New Console Application (.NET Core)
2. Right project and choose Properties
3. Choose Build tab, in Output Path enter "Bar
4. Build

Expected: The project tree not to change
Actual: The output is shown in the tree:

![image](https://cloud.githubusercontent.com/assets/1103906/21834787/212fafe2-d80c-11e6-866a-e1340ead7789.png)

**Comment by dsplaisted** [comment]
I think this is by design.  We decided that 'None' items would be used to show all files in your project folder that weren't in the output, intermediate, or other special folders. How would you exist this to change?

**Comment by davkean** [comment]
> We decided that 'None' items would be used to show all files in your project folder that weren't in the output,

This is *my output*, why you are you showing it?

**Comment by dsplaisted** [comment]
Oh, I misunderstood.  In that case I think it's probably CPS not realizing that the includes should change.  Does it still show the output folder if you close and reopen the solution?

**Comment by davkean** [comment]
Yes it still shows.

**Comment by dsplaisted** [comment]
Turns out this is because the default items are based on `BaseOutputPath`, and VS is setting the `OutputPath` property.  So your `BaseOutputPath` is "bin\" but your `OutputPath` is "Bar".

I'm thinking of fixing this by excluding both `BaseOutputPath` and `OutputPath` (as well as `BaseIntermediateOutputPath` and `IntermediateOutputPath`) from the default items.  This will mean excluding folders that aren't necessarily used as the output paths in cases like yours, but I'm not sure if there's a better option.

**Comment by rainersigwald** [comment]
@dsplaisted That sounds reasonable to me (even though it's redundant in the default case).
