### ISSUE TITLE
Wrong behavior for a project with no CS files

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/sdk#638]
## Repro 1

1. Create a new console app project using `dotnet new`
2. Remove the `Program.cs` file
3. Run `dotnet restore`
4. Run `dotnet build`

### Expected result
A message stating that there are no source file to compile or similar.

### Observed

```shell
CoreCompile target) ->
         CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [F:\Experiments\repros\3133\3133.csproj]
```

## Repro 2

1. Create a new class lib using `dotnet new -t lib`
2. Remove the CS files in the directory
3. Run `dotnet restore`
4. Run `dotnet build`

### Expected result
As above, some info on the fact that I don't have any files in there.

### Observed
Build passing happily. 

The culprit is the `AssemblyInfo.cs` file that gets auto generated and then built. 

/cc @nguerrera @dsplaisted

**Comment by atanasa** [comment]
As far as I know, Visual Studio requires that msbuild projects meet certain requirements (kind of duck typing in terms of targets/properties/items). The easies way currently to create a generic msbuild project that plays with Visual Studio is to use a C# project with no code in it and ignore the produced "empty" assembly. 

So please don't break this use case. A warning could be ok, but not an error.

**Comment by dasMulli** [comment]
`<OutputType>Library</OutputType>` (default) would not require a main method. If you want a "generic" project, you could try the deploy projects from the SDK's build test assets: https://github.com/dotnet/sdk/blob/master/TestAssets/TestProjects/DeployProjectReferencingSdkProject/DeployProj/Deploy.proj
But that can't produce a NuGet package. For that there's a few other switches needed to be set (see [a sample](https://github.com/dasMulli/SimpleGitVersion/blob/master/DasMulli.SimpleGitVersion/DasMulli.SimpleGitVersion.csproj)).
It would be good to know what the exact use case is and what the expected behaviour should be.

**Comment by dsplaisted** [comment]
Taking a look at this, the behavior for SDK-style projects is the same as the behavior for "legacy" projects.  Given that the error message for app projects makes sense, and that for library projects there might be valid reasons to create an empty library, I'm going to close this as "won't fix".
