### ISSUE TITLE
AssemblyInfo.cs should not be generated on package restore

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#651]
The MSBuild restore target should _not_ generate version attribute files. The fact that it does makes packages like Nerdbank.GitVersioning that customize project versioning fail on build unless the generated assemblyinfo.cs file is deleted (which must be done manually to workaround #650).

```
git clone https://github.com/microsoft/vs-validation.git
cd vs-validation
git checkout 114f31640
cd src\Microsoft.VisualStudio.Validation
msbuild /t:restore
msbuild

:: build fails

del obj\Debug\netstandard1.0\Microsoft.VisualStudio.Validation.AssemblyInfo.cs
del obj\Debug\net45\Microsoft.VisualStudio.Validation.AssemblyInfo.cs
msbuild

:: build succeeds
```

IMO in addition to not creating these version files during package restore, incremental build should consider that the file would be changed due to the change in imported NuGet packages that influence the build and rebuild the file.

In fact, there is a pattern that all MSBuild files should contribute their own full path to `$(MSBuildAllProjects)` with the idea that if from one build to the next, the value of that property were to change, incremental build would deactivate and all files would be regenerated since such as in this case, they can't be assumed to have not changed since the last build.

**Comment by nguerrera** [comment]
@AArnott I'm not seeing what you describe.

> The MSBuild restore target should not generate version attribute files

It does not. The files are created on line 6 of your repro (`msbuild`), not line 5 (`msbuild /t:restore`).

> :: build fails

It succeeds for me the first time.

> :: build succeeds

It succeeds *again* for me and recreates the files as you expect.

> In fact, there is a pattern that all MSBuild files should contribute their own full path to $(MSBuildAllProjects) ...

We do use $(MSBuildAllProjects) as the inputs: https://github.com/dotnet/sdk/blob/c1468af16d9f59b4b4116e9fd854a5cda9e56418/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.GenerateAssemblyInfo.targets#L53-L54)

This will cause the file to be regenerated on incremental build if any conforming imported project is newer than the assemblyinfo file. However, just to clarify, it won't detect if a file was added to the property since last invocation.

Nevertheless, nuget does emit  `<MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>` to the .g.props and .g.targets that are imported, so if any targets are props are added there via restore, it would trigger a regeneration of the file.

**Comment by nguerrera** [comment]
This may have been what fixed it: https://github.com/dotnet/sdk/pull/276

Does it still repro for you on latest bits?

**Comment by AArnott** [comment]
It no longer repros for me. Thank you.
