### ISSUE TITLE
Multi framework targetting not working with VS2017 RC

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/sdk#700]
[ Moving from dotnet/cli#4996 ]

## Steps to reproduce
- Install Visual Studio 2017 RC with .NET Core support.
- Create a new .NET Core project. Type seemingly does not matter, tested with Web MVC and Console application.
- Right click on project in Solution Explorer and select "*Edit name.csproj*"
- Find the line with the `TargetFramework` element.
- Replace `netcoreapp1.0` with `netcoreapp1.0;net452`, as demonstrated in [this .NET Blog post](https://blogs.msdn.microsoft.com/dotnet/2016/10/19/net-core-tooling-in-visual-studio-15/) under the section **Cross-targeting**.

## Expected  behavior
- Project compiles for both `netcoreapp1.0` and `net452` as previously with the *project.json* format.

## Actual behavior
Error occurs:

```
MSB4115 The "HasTrailingSlash" function only accepts a scalar value, but its argument "$(OutputPath)" evaluates to "bin\Debug\netcoreapp1.0;net452\" which is not a scalar value.
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

From @MartinJohns

**Comment by nguerrera** [comment]
This is because TargetFramework was used to specify two framerworks instead of TargetFrameworks plural.

dotnet/sdk#385 already tracks getting a better error message for that.

There was some further discussion to have just one term, but that is not reflected at all in the bug description copied here. It would be better served by a new bug. FWIW, I also don't see how that can work: https://github.com/dotnet/cli/issues/4996#issuecomment-273992292

**Comment by npbenjohnson** [comment]
I hope this is intended usage (or netstandard2.0 will make this uneccesary) because I can justify, and have been using both tags, I've only been using it since VS RC4, but:

``` xml
    <NetStandardImplicitPackageVersion>1.6.1</NetStandardImplicitPackageVersion>
    <TargetFramework>net4.6.2</TargetFramework>
    <TargetFrameworks>netstandard1.5;net4.6.2</TargetFrameworks>
```

Allows you to use netstandard1.5 nuget packages without having to build netstandard1.5, which will barf on things like trying to use AppDomain or DbAdapter

**Comment by nguerrera** [comment]
That should work equally well without the TargetFrameworks.

**Comment by npbenjohnson** [comment]
Packages targeting netstandard don't show up in the nuget UI without it. I didn't check if there was any issue with manually installing packages outside of the UI, so it may be a minor issue.

**Comment by metadings** [comment]
man... I somewhat hate your version problems... I'm trying .NET 1.0.x, trying to do .NET 1.1.x, while I do want .NET Standard 1.0... 2.0... oh hey, I meant .NET Framework 4.5.x...

Just to run [github.com/zeromq/clrzmq4](https://github.com/zeromq/clrzmq4)...

Can't you create and post some example csproj, to get this library running **somehow**?
