### ISSUE TITLE
MSBuild\Sdks\Microsoft.NET.Sdk folder has a `buildCrossTargeting` subfolder

### ISSUE THREAD

**Issue by tannergooding** [dotnet/sdk#794]
This seems like a bug since the actual `build` folder has CrossTargeting subfiles (such as `Microsoft.NET.Sdk.BeforeCommonCrossTargeting.targets`).

I would expect the folder to actually be `build\CrossTargeting` or for the single file contained in it to be under the build folder and named `Microsoft.NET.SdkCrossTargeting.targets (based on the existing structure/layout).

**Comment by tannergooding** [comment]
@jinujoseph, @333fred

**Comment by 333fred** [comment]
For reference:
![image](https://cloud.githubusercontent.com/assets/2371880/22569495/96b264b6-e94c-11e6-9e0a-1f9c5de008d6.png)

**Comment by rainersigwald** [comment]
This is intentional. `buildCrossTargeting` is a new NuGet feature--files within it are automatically included in the "outer" build, where files within the `build` folder are included in the single-TargetFramework builds. This allows the Sdk to define the magic that allows a) identifying the right TFM to build for a given reference and b) allowing a build of the main project to build all TFMs within the project.

Having the crosstargeting directory just be a stub that points to targets under `build/` is odd but mostly harmless.

**Comment by srivatsn** [comment]
This is by design as @rainersigwald explains.
