### ISSUE TITLE
Quiet option to only print to console in case of error

### ISSUE THREAD

**Issue by lutzroeder** [dotnet/sdk#7986]
## Steps to reproduce
Run `dotnet restore --v:q` or `dotnet build --v:q`.

## Expected  behavior
Do not print to console unless there are errors.

## Actual behavior
Prints to console:
```
Restoring packages for /xxx/app.csproj...
Generating MSBuild file /xxx/
Generating MSBuild file /xxx/
Writing lock file to disk. Path: /xxx/
Restore completed in 998.62 ms for /xxx/
  
NuGet Config files used:
    /Users/lutzroeder/.nuget/NuGet/NuGet.Config
  
Feeds used:
    https://api.nuget.org/v3/index.json
```

## Environment data
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1

**Comment by 0xced** [comment]
@btecu 
> Still an issue in current version:
>
>  ```
> Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> ```

Since .NET Core 3.0 SDK you can use the `--nologo` argument in order to hide the startup banner and the copyright message, see https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#arguments

**Comment by rainersigwald** [comment]
@0xced fyi, that particular message is emitted by MSBuild and suppressible by `-nologo` since .NET Core SDK 1.0.

You can also disable the summary with `-consoleLoggerParameters:NoSummary`.

I'm going to close this issue. It's not the default behavior (MSBuild on Windows was designed to be super chatty, not really following the UNIXy output-only-on-error philosophy), but it's accomplishable:

```sh-session
$ dotnet build -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet

$ echo $?
0

$ echo "syntax error">> Class1.cs

$ dotnet build -nologo -consoleLoggerParameters:NoSummary -verbosity:quiet
Class1.cs(9,13): error CS1002: ; expected [/Users/raines/src/quiet/quiet.csproj]

$ echo $?
1
```

You can use a [`Directory.Build.rsp`](https://docs.microsoft.com/visualstudio/msbuild/msbuild-response-files?view=vs-2019#directorybuildrsp) to make that the default for your repo if you like.

**Comment by ewrogers** [comment]
It may not be the default behavior but still quite strange that `--verbosity quiet` has no effect even in .NET 8.0, nearly 5 years later.

For those wondering how:

```shell
dotnet build -clp:ErrorsOnly
```

Will do what you want.
