### ISSUE TITLE
dotnet publish doesn't include CopyToOutputDirectory/CopyToPublishDirectory files

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/sdk#854]
Moved from dotnet/cli#5649 on behalf of @timmydo.

-----

## Steps to reproduce

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <WarningsAsErrors>true</WarningsAsErrors>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Platform</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>Platform</PackageId>
    <RuntimeIdentifiers>win7-x64</RuntimeIdentifiers>
    <PackageTargetFallback>$(PackageTargetFallback);dnxcore50;portable-net451+win8</PackageTargetFallback>
  </PropertyGroup>
  <Import Project="..\Global.props" />
  <ItemGroup>
    <Content Update="wwwroot\**\*;web.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\**\*;web.config;start.bat;Platform.ini;serviceConfig.ini">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.EventSource" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.HttpOverrides" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.WebListener" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OAuth" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Ini" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Net.Http" Version="2.2.29" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="1.1.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="1.0.2" />
    <PackageReference Include="Swashbuckle" Version="6.0.0-beta902" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.0.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="npm --silent install" />
    <Exec Command="gulp --silent --no-color" />
  </Target>
</Project>

C:\Users\timmydo\AppData\Local\Temp\dotnet\dotnet.exe publish Platform -r win7-x64 -c release -f netcoreapp1.1 -o ..\test\platform
```

## Expected  behavior

expected platform.ini, wwwroot, etc. to exist in publish directory

## Actual behavior

files not found

## Environment data
`dotnet --info` output:

```
C:\Users\timmydo\AppData\Local\Temp\dotnet\dotnet.exe --info
.NET Command Line Tools (1.0.0-rc4-004777)

Product Information:
 Version:            1.0.0-rc4-004777
 Commit SHA-1 hash:  18c01886cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Users\timmydo\AppData\Local\Temp\dotnet\sdk\1.0.0-rc4-004777
```

**Comment by GuardRex** [comment]
Switch to `Sdk="Microsoft.NET.Sdk.Web`?

**Comment by timmydo** [comment]
I don't think .Sdk.Web is what I want for my console apps. Looks like that just has some extra target logic for commonly formatted web projects...

it seems dotnet migrate (I migrated through VS) created Content Update rules for the ini files, but now in the csproj, the ini/bat files are type None, so I just need to change all the update rules from Content to None.

**Comment by GuardRex** [comment]
> I don't think .Sdk.Web is what I want for my console apps.

I mentioned it because it looked like a web app (e.g., `wwwroot`, `web.config`, `Microsoft.AspNetCore.Mvc`, etc.).

I've had some luck with `Content Include="xxx" CopyToPublishDirectory="PreserveNewest" />` for files and folders that the `Sdk.Web` package doesn't automatically handle. For an empty folder that I want to create in the published output, I've had to resort to `MakeDir`:
```xml
<Target Name="CreateLogsFolder" AfterTargets="AfterPublish">
  <MakeDir Directories="$(PublishDir)Logs" Condition="!Exists('$(PublishDir)Logs')" />
</Target>
```

**Comment by timmydo** [comment]
It works for me when I use None instead of Content:

```
  <ItemGroup>
    <None Update="start.bat;CertInstaller.ini">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>
```

**Comment by srivatsn** [comment]
@dsplaisted what's the expected behavior here?

**Comment by dsplaisted** [comment]
@timmydo Did `dotnet migrate` set the Sdk attribute to `Microsoft.NET.Sdk` or to `Microsoft.NET.Sdk.Web`?

I think you probably want to use the Web SDK for this.

The reason it's not working is because doing an `Update` on a path that hasn't already been included in an item doesn't have any effect.  By default the `None` item includes most files in your project folder that aren't in another item, so that's why `Update` works with it.  You could also use `<Content Include="start.bat;CertInstaller.ini" />.

**Comment by timmydo** [comment]
I think `dotnet migrate` turned every project.json project into a Sdk.Web project. But most of them were console apps. For the one project that could have been a Sdk.Web project, I wanted it to behave like a console app (it uses web listener and I don't want VS trying to launch IIS express with some launch settings file). For the console apps, I'm not sure how it decided to turn them into Sdk.Web csprojs...

I got an understanding of how None/Content and Include/Update work when I tried fixing this issue, but the process could be more friendly to users who just want to include files in the build/publish output directory. I think VS2017 threw an error when I tried modifying it through the file properties window so I had to edit the csproj directly. Being able to edit the csproj through VS might be one of my favorite new features so far for VS2017 :)

**Comment by dsplaisted** [comment]
@timmydo `dotnet migrate` will use the Web SDK if you have any references to any AspNetCore packages.

You can still run a project using the Web SDK as a console app.  By default Visual Studio creates debug profiles for IIS Express and for launching as a console app.  The one to launch as a console app has the same name as your project:

![image](https://cloud.githubusercontent.com/assets/145043/22945417/08fbffea-f2a9-11e6-9689-3754ab26ab96.png)

You can also delete the IIS Express debug profile in the project properties if you never want to use it.

If VS is throwing an error when you try to change the file properties, please file a bug in https://github.com/dotnet/roslyn-project-system.  It is supposed to work.

We generate an error if you add an `Include` for a file that is already included by default.  That's supposed to help people who are editing the files manually discover how this works.  It doesn't help when you specify `Update` instead of `Include` instead of the other way around, though.

**Comment by livarcocc** [comment]
If you want changes to migrate based on this, please file an issue at dotnet/cli, though most people who use aspnetcore packages are web apps and that coupled with emitEntryPoint are the best heuristics we have to identify a web app. I don't see this changing.

As for the Content None, etc, this was slightly for 1.0.1. Give it a try there and see if it fixed your problem.

If you are still running into issues, please re-activate.
