### ISSUE TITLE
Request, able to config the location of ~/.dotnet and ~/.templateengine

### ISSUE THREAD

**Issue by ariellourenco** [dotnet/sdk#8678]
Hi @livarcocc ,

May you can help me with this simple question. Is there anyway to re-locate the dotnet user profile folder (.dotnet)?

**Comment by rkm** [comment]
Has there been any progress towards this, or would you be open to someone submitting a PR?

**Comment by wli3** [comment]
Also will setting `dotnet_cli_home` satisfy the requirement?

**Comment by rkm** [comment]
Just tried setting `DOTNET_CLI_HOME`, removing my current `~/.dotnet` directory, and re-building one of my projects. The result was that the `~/.dotnet` directory was partially repopulated:

```bash
$ dotnet --help
.NET Core SDK (3.1.103)
$ export DOTNET_CLI_HOME=~/tmp
$ rm -r ~/.dotnet
$ dotnet build ...
$ ls ~/.dotnet
corefx  optimizationdata
$ ls -a ~/tmp
.  ..  .dotnet  .nuget
```

**Comment by wli3** [comment]
I see. This is not ideal. Different component of .NET core stack have different code paths to decide the persistent storage. It is not an easy fix. I don't think this is something community can easily contribute since it requires coordination between runtime, templates engine, CLI and nuget.

It would also require a large amount of testing to ensure there is no regression.

So far there is no roadmap for this issue.

**Comment by dlagg** [comment]
> I see. This is not ideal. Different component of .NET core stack have different code paths to decide the persistent storage. It is not an easy fix. I don't think this is something community can easily contribute since it requires coordination between runtime, templates engine, CLI and nuget.
> 
> It would also require a large amount of testing to ensure there is no regression.
> 
> So far there is no roadmap for this issue.

[Nuget it's configurable](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders):
```bash
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
```

**Comment by SaphireLattice** [comment]
There's also `.templateengine` from https://github.com/dotnet/templating/blob/47e96dd1af9b63888da37b632f299b7c9e86879a/src/Microsoft.TemplateEngine.Edge/DefaultPathInfo.cs - not sure if slapping an actual directory existence check (so that it can work with legacy `$HOME/.templateengine` when present) would be good though? Kinda introduces a bit of a side effect, but dunno, it already checks up the env variable

And of course tests for that, too.

Now for `.dotnet` itself... well, there's *a lot*.

Various scripts, of course a ton of tests, and there's a [`.target` file](https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L75-L80) referencing `$([System.IO.Path]::Combine($(_DefaultUserProfileRuntimeStorePath), '.dotnet', 'store'))` so that would need to be handled too, if we want to avoid any breaking changes and have no intervention required when upgrading...

...and that's before we touch on any user tools, on interaction *between* SDK versions and their tooling. So yeah, this thing is very hardcoded basically, across different tools and non-C# files (definitions, scripts).

**Comment by bartekpacia** [comment]
So annoying!

**Comment by roadkell** [comment]
The more the devs postpone it, the larger their technical debt will be (as this will have to be implemented, sooner or later).

**Comment by baronfel** [comment]
@dotnet/templating-engine-maintainers we did some work recently on the directory of the template engine cache, didn't we? Is this still an issue for the template engine?

**Comment by vlada-shubina** [comment]
Dotnet new now respects DOTNET_CLI_HOME environment variable to define the location of settings. It is also possible to override location of settings with --debug:custom-hive option with path for the settings.

Tagged item to provide more details on triage.

**Comment by YuliiaKovalova** [comment]
The fix for DOTNET_CLI_HOME was introduced in the scope of:
https://github.com/dotnet/templating/issues/1650
After introducing this environment variable, the location on .templateengine will be changed.

Or you can use `--debug:custom-hive` oprion for defining a custom location for settings.

**Comment by Neme12** [comment]
https://learn.microsoft.com/en-us/windows/dev-drive/ recommends moving all package and other caches, e.g. the .nuget folder, to a dev drive. I did so for NuGet and moved all NuGet cache directories there, and I assumed the .dotnet folder would be configurable as well, but it's not? :(

**Comment by Neme12** [comment]
> This may not be 100% what you want, you can change the environment variable USERPROFILE on windows

I don't think changing that is supported at all. I won't even dare try changing that or I'll probably completely screw up my Windows installation.

**Comment by Neme12** [comment]
I'd like to change my DOTNET_CLI_HOME but I don't know what the default of that folder is, so I can know which folder I should move into that new location when I change it. And I can't seem to be able to find anything about that environment variable when googling, apart from GitHub issues. It doesn't seem to be documented anywhere. It's not even mentioned here: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables

Is DOTNET_CLI_HOME equivalent to the default %userprofile%\.dotnet? Meaning when I change the environment variable to a custom directory, I should move my current content of .dotnet there? Or does DOTNET_CLI_HOME represent a subdirectory within that? Or a parent directory, so that .dotnet will be created as a subfolder?

**Comment by Neme12** [comment]
> Edit: Splitting the user config from any cached data would be useful e.g. as specified [here](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

I agree. It's not great that cache files (that can be repopulated at any time) and config files are both in the same directory tree. Cache files should be stored either in %LOCALAPPDATA% (user\AppData\Local) or in %TEMP% by default, whereas config files should be stored in %APPDATA% (user\AppData\Roaming) by default.

**Comment by Neme12** [comment]
> In Windows, configuration files should not be stored in %USERPORFILE%. They should be in %APPDATA%. Please respect Windows standards. Moreover, you should consider XDG user directories in Linux. https://wiki.archlinux.org/index.php/XDG_user_directories

This is still not fixed as the default location afaict.

**Comment by bartekpacia** [comment]
Forgive a slight off-topic, but what did you set `DOTNET_CLI_HOME` to? `$XDG_DATA_HOME`, `$XDG_CACHE_HOME`, or `$XDG_STATE_HOME`? I'm just curious and a bit confused.

**Comment by ariellourenco** [comment]
@bartekpacia, 

Just for sake of curiosity I have set my `DOTNET_CLI_HOME` to `$XDG_DATA_HOME/`. Although, it's not clear to me what data in that folder is pure cache data or settings.

**Comment by pm4rcin** [comment]
I have set 3 env variables in `.bashrc`:
```bash
export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export OMNISHARPHOME="$XDG_CONFIG_HOME"/omnisharp
```
 but it still creates `.dotnet/corefx/cryptography/crls/` and `.dotnet/corefx/cryptography/x509stores/my/` while all the rest seems fine at least when compiling. So certs should be moved too.

**Comment by baronfel** [comment]
@terrajobst do you know if we have any runtime level config knobs for where private data should be saved?

**Comment by terrajobst** [comment]
@richlander or @jkotas might know.

**Comment by jkotas** [comment]
`Environment.GetFolderPath` API that returns locations for different types of private data respects the OS-specific conventions like `XDG_...` variables on Linux. There are no overrides.

Some libraries use their own schemes. `$(HOME)/.dotnet/corefx/cryptography...` used by System.Security.Cryptography to store per-user data is an example.

- https://github.com/dotnet/runtime/blob/73bffafa95247cef39d3f200d67be72c92e6e449/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslDirectoryBasedStoreProvider.cs#L322
- https://github.com/dotnet/runtime/blob/73bffafa95247cef39d3f200d67be72c92e6e449/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/OpenSslCrlCache.cs#L16-L24

**Comment by mmathau** [comment]
is there any update on this? would be really nice to get rid of that `.dotnet` folder thats cluttering up the `$HOME`

**Comment by Baerbeisser** [comment]
Same.
```
.dotnet
└── corefx
    └── cryptography
        ├── crls
        │   ├── 1633879b.7b7dc74c.crl
        │   ├── 244b5494.0f69abe2.crl
        │   ├── 24871c76.e8d7ba5a.crl
        │   ├── 75d1b2ed.de05bb98.crl
        │   ├── 779a33e6.28d8ec97.crl
        │   ├── b1159c4c.cbda5887.crl
        │   ├── bd6662f5.8ba5d856.crl
        │   ├── bf4f5bec.6f48407f.crl
        │   ├── c01cdfa2.d9aa0990.crl
        │   └── d16da424.cbeb964c.crl
        └── x509stores
            └── my
                └── CDE7FC609B4DB8DBA21CBD8CF041DEAE1D90F0F4.pfx
```
after compiling Pinta from AUR.  `DOTNET_CLI_HOME` is set.

**Comment by jkotas** [comment]
> is there any update on this?

This issue has been closed. It is not going to move forward or receive updates.

If you would like to see `.dotnet/corefx/cryptography` to be configurable or not exist, open a new issue on it in dotnet/runtime repo that describes the problem you are trying to solve. The code that creates this directory lives there.
