### ISSUE TITLE
System.IO.FileNotFoundException when using PrivateAssets = "All"

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/sdk#8789]
@KshitizGIT commented on [Sun Sep 03 2017](https://github.com/dotnet/core/issues/933)

I have a project layout like this.

Assembly A -> Assembly B -> Assembly C.

Program lives in Assembly A.
ClassB lives in Assembly B.
ClassC lives in Assembly C.

I don't want AssemblyC to be directly accessible in AssemblyA. So I added   PrivateAssets = "All" in the ProjectReference element in the AssemblyB.csproj file 

ClassB creates a instance of ClassC.

Program creates a instance of ClassB.

But this is causing a System.IO.FileNotFoundException : Couldnot load file or assembly 'C'.

I have attached the project. Please look into it.

[Dependency.zip](https://github.com/dotnet/core/files/1272843/Dependency.zip)

**Comment by mpawelski** [comment]
Is this issue outdated?

I've been doing tests similar to the project the author described (ConsoleApp -> ClassLib1 -> ClassLib2) and normally `<ProjectReference>` is transitive so ClassLib2 is available in ConsoleApp when I project reference only ClassLib1. 

But When I use `<ProjectReference Include="..\ClassLib2\ClassLib2.csproj" PrivateAssets="All" />`  in `ClassLib1` project then ClassLib2 is not available in ConsoleApp (compiler error). 

Similar when I put `<DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>` (learned bout it [here](https://github.com/microsoft/msbuild/issues/4717)) in ConsoleApp .

But in all cases my application works, ClassLib2 is copied to bin folder of my ConsoleApp, even though the compiler doesn't see it (this is good and what I expect).

So I downloaded the sample project the autor uploaded in 2017 (Dependency.zip) and checked it.
And it also works! No FileNotFoundException. 😮😑

![image](https://user-images.githubusercontent.com/2056282/75581454-c916c500-5a69-11ea-8317-930288e53cd6.png)


So was it changed in some release of .Net Core (or.Net Core SDK, I'm using old net48 with new SDK-csproj)? 

If so when was it changed and why this issue is still open and have been added to 2.2.1xx milestone?

**Comment by marcpopMSFT** [comment]
Closing an old issue based on last comment mentioning it working now.

**Comment by ChristoWolf** [comment]
I am still observing this in .NET 5 based solution.
Is there any work around for this?

**Comment by mpawelski** [comment]
Yes, this issue was closed prematurely I think.  I remember when I wrote previous comment then it was working but much later when I experimented again with `PrivateAssets="All"` on transitive dependencies it didn't copy it to parent project. But I think this issue should be closed anyway because this apparently is expected behavior. You should use `PrivateAssets="compile"` instead.

Microsoft really should add something like [`DisableTransitiveProjectReferences`](https://github.com/dotnet/sdk/issues/11803) to avoid confusion. 

@ChristoWolf try using `<PrivateAssets>compile</PrivateAssets>` as described [here](https://github.com/dotnet/sdk/issues/11803#issuecomment-907673210) I think it worked for me a year ago when I was testing different options for `PrivateAssets`.

**Comment by ChristoWolf** [comment]
@mpawelski: Setting the property to `compile` resolved the issue, thanks!
I am still not sure however what that option means/implies.

**Comment by mpawelski** [comment]
@ChristoWolf I'm glad it helped. 

Yep, this situation with transitive dependencies and their behavior is strange for me too, or at least it's heavily underdocumented. We don't have official documentation explaining what `DisableTransitiveProjectReferences` does. We have some vague and IMO not clear [documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets) for `PrivateAssets` metadata for `PackageReference` and that there is `compile` option. `PackageReference` doesn't have `PrivateAssets` metada in [documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2022#projectreference) even though it [appears to work](https://curia.me/net-core-transitive-references-and-how-to-block-them/).

I'm baffled that such important topis (transitive dependencies, their behavior and behavior configurability) is not treated by Microsoft more serious.
