### ISSUE TITLE
Enable `dotnet sln` to add SLN-level files

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#9112]
I wasn't able to add SLN-level files to a `.sln` file with the commandline tools. VS enables me to do this.

**Comment by rlove** [comment]
Today I wanted to add YAML files to the Solution as part of Microservice Solution generation script.      This feature would make that possible.

**Comment by tmay57** [comment]
In addition, you should be able to added such a file to a solution folder. It is very common to see a solution folder called something like "SolutionItems" with "config and readme" type files grouped into it. If you can do it in Visual Studio you should be able to do it in dotnet cli or you build in a feature gap that makes it hard for folks to move existing workflow from Visual Studio into a dotnet cli workflow.

**Comment by LordMike** [comment]
One of my contributions to `dotnet sln` was the ability to control the solution folder on add.. So it should be covered.

```
>dotnet sln add --help
Usage: dotnet sln <SLN_FILE> add [options] <PROJECT_PATH>

Arguments:
  <SLN_FILE>       The solution file to operate on. If not specified, the command will search the current directory for one.
  <PROJECT_PATH>   The paths to the projects to add to the solution.

Options:
  --in-root               Place project in root of the solution, rather than creating a solution folder.
  -s, --solution-folder   The destination solution folder path to add the projects to. <----- Here.
  -h, --help              Show command line help.
```

**Comment by tmay57** [comment]
Thank you for the contribution and this works for **projects** just fine. However, it doesn't allow for a file to be added. It would be sweet if it did. 
FWIW, we are building a project/code generation tool and because of the limitations of the CLI we decided to just bring a copy of the Cli.Sln.Internal project into our app so we can do everything we need without using the Process class.

**Comment by samsmithnz** [comment]
Another vote for this. Having the ability to add files would be very useful. Even something a call for each separate file would work for me:

`dotnet sln add --file 'README.MD'` 
`dotnet sln add --file '.github/workflows/workflow.yml'`

**Comment by baronfel** [comment]
I'm going to close this one as a duplicate of #9611 because I've sketched out a spec for the functionality we'd want over there. The issue is marked up-for-grabs, but we may take another look at this later in the summer as we look at integrating the slnx file format support into the CLI's solution-management commands.
