### ISSUE TITLE
Use Capitals for Release names

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#9319]
Just installed an RC1 build ... see:

![image](https://user-images.githubusercontent.com/2608468/39259304-f5fa33e4-486a-11e8-8743-bf31109b5106.png)

Branding should follow this form:

- "Preview 1"
- "RC1"

**Comment by sfoslund** [comment]
@dsplaisted is there any downside to just updating [this line](https://github.com/dotnet/installer/blob/release/3.1.3xx/src/redist/targets/Versions.targets#L7) to be capitalized in necessary branches? 

It looks like we're not following this pattern at all for 5.0: 
<img width="438" alt="DotnetInstallerPrev" src="https://user-images.githubusercontent.com/16010855/79800192-a3db6000-8310-11ea-8366-de78a34b889e.PNG">

**Comment by rainersigwald** [comment]
I don't think we'd want to capitalize that; it controls the semver prerelease part which is almost always lower-case. I think it's ok in the 5.0 screenshot you're sharing because that's a full semver version. Rich's string looks like it comes from a localized resource somewhere--maybe what gets displayed has changed since 2.1.3xx?
