### ISSUE TITLE
Issues with old CSproj project structure over new project.json

### ISSUE THREAD

**Issue by ChuckkNorris** [dotnet/sdk#982]
Problems with csproj
1.	Package Install Auto-Complete is Broken in csproj file (which was amazing in project.json)
2.	Quick Action Package Install no longer works (e.g. quick action to install missing package on method provided by an external lib available via NuGet)
3.	Much less human readable than Project.Json
4.	Folder-based editors (e.g, VS Code) do not correctly emulate file structure of CSProj (e.g. files excluded fromt the project)
5.	Csproj was added in SOLELY to support older existing build processes. Rather than adding support for them via project.json, a decision was made to force everyone to adapt to an ancient build process rather than continuing the innovation of simpler C# development
6.	DotNet Tools Watcher no longer works with .NET Core 1.1
7. Packages are much more modular than .NET Framework, but that means basic packages need to be manually installed and discovered. In .NET Core 1.0, this wasn't an issue, you could type a method and use CTRL+. to automatically install the package, but now, I have to scour the web to figure out which package provides what functionality. This wasn't as much of an issue in .NET Framework because most basic packages were already provided.

Due to a massive step backwards in the ease of development due to the transition from project.json to .csproj, I must ask the question: Will any of these issues be addressed? Are there plans to support project.json and the msbuild process built on top of the project.json?

**Comment by gulbanana** [comment]
Points 1, 2, 6 and 7 will be addressed. There's an (official) extension for VS2017 which starts adding the version intellisense back; this will later be built in to VS.

3 and 5 aren't really actionable, just statements of opinion. I personally disagree, because having element names helps me to read complex project files.

I don't know whether there are any plans for VSCode to start understanding excludes, but project.json had the same issue there.

project.json is not coming back in any official form.

**Comment by ChuckkNorris** [comment]
@gulbanana Thanks for the response.

I'm glad to hear the package auto-complete and install-package quick action will be re-added eventually.
Since the other issues are opinion-based, I will close this issue.
